In [1]:
import os

# import from cmu-tare-model package
from config import PROJECT_ROOT

# Measure Package 0: Baseline
menu_mp = 0
input_mp = 'baseline'

print(f"PROJECT_ROOT (from config.py): {PROJECT_ROOT}")

# Construct the absolute path to the .py file
relative_path = os.path.join("cmu_tare_model", "model_scenarios", "tare_baseline_v2_1.ipynb")
file_path = os.path.join(PROJECT_ROOT, relative_path)

# On Windows, to avoid any path-escape quirks, convert backslashes to forward slashes
file_path = file_path.replace("\\", "/")

print(f"Running file: {file_path}")

# %run magic command to run a .py file and import variables into the current IPython session
# # If your path has spaces, wrap it in quotes:
%run -i {file_path} # If your path has NO spaces, no quotes needed.

print("Baseline Scenario - Model Run Complete")

# Flag to prevent excessive output in other scenario files
individual_scenario_run = True

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
PROJECT_ROOT (from config.py): c:\users\jorda\desktop\projects\cmu-tare-model
Running file: c:/users/jorda/desktop/projects/cmu-tare-model/cmu_tare_model/model_scenarios/tare_baseline_v2_1.ipynb

=========================================================================================================
Welcome to the Trade-off Analysis of residential Retrofits for energy Equity Tool (TARE Model)
Let's start by reading the data from the NREL EUSS Database.

Make sure that the zipped folders stay organized as they are once unzipped.
If changes are made to the file path, then the program will not run properly.
==========================================================================================================

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
Result outputs will be exported here: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\output_results



====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO: MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
Load data from the NREL EUSS Database for the baseline scenario and apply various filters.

DATA: NREL EUSS Database
HOUSING FILTERS: Occupied units and Single Family Homes
GEOGRAPHIC FILTERS: National, State, or City

Additional details data can be found in the official End-Use Load Profiles/Savings Shapes documentation.
Our methodology is detailed in the process_euss_data.py file and its associated imports.

RESULTS OUTPUT:

Retrieved data for filename: baseline_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\resstock_amy2018_release_1.1_processed_data\baseline_metadata_and_annual_results.csv
Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 259)
You chose to filter for: PA
Location ID is: PA

To accurately characterize load profile, it is recommended to select subsets of data with >= 1000 models (~240,000 representative dwelling units).

The following cities (number of models also shown) are available for this state:

in.city
Not in a census Place      7975
In another census Place    6648
PA, Philadelphia           1962
PA, Pittsburgh              412
PA, Erie                    146
PA, Allentown               136
PA, Reading                 110
PA, Scranton                109
PA, Bethlehem                98
PA, Harrisburg               74
PA, Altoona                  70
PA, Lancaster                69
PA, York                     64
PA, Levittown                61
PA, Wilkes-Barre             56
Name: count, dtype: int64
You chose to analyze all of state: PA
Location ID is: PA

====================================================================================================================================================================
DATAFRAME: df_euss_am_baseline

         upgrade      weight  applicability  in.sqft  \
bldg_id
15             0  242.131013           True    333.0
79             0  242.131013           True   1220.0
119            0  242.131013           True   2152.0
122            0  242.131013           True   2176.0
150            0  242.131013           True   1690.0
...          ...         ...            ...      ...
549882         0  242.131013           True   1202.0
549915         0  242.131013           True   2176.0
549937         0  242.131013           True    885.0
549963         0  242.131013           True   1690.0
549989         0  242.131013           True   1220.0

                                            in.ahs_region  \
bldg_id
15       CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
79                               Non-CBSA Middle Atlantic
119      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
122      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
150                              Non-CBSA Middle Atlantic
...                                                   ...
549882                           Non-CBSA Middle Atlantic
549915                           Non-CBSA Middle Atlantic
549937                           Non-CBSA Middle Atlantic
549963                           Non-CBSA Middle Atlantic
549989                           Non-CBSA Middle Atlantic

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
15                                    4A
79                                    5A
119                                   4A
122                                   4A
150                                   5A
...                                  ...
549882                                5A
549915                                5A
549937                                5A
549963                                5A
549989                                5A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
15                                              4A                      Hour2
79                                              5A                     Hour10
119                                             4A                      Hour1
122                                             4A                     Hour18
150                                             5A                      Hour2
...                                            ...                        ...
549882                                          5A                      Hour5
549915                                          5A                      Hour0
549937                                          5A                     Hour20
549963                                          5A                     Hour13
549989                                          5A                     Hour22

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
15                 2                      Mixed-Humid  ...
79                 3                             Cold  ...
119                4                      Mixed-Humid  ...
122                4                      Mixed-Humid  ...
150                4                             Cold  ...
...              ...                              ...  ...
549882             2                             Cold  ...
549915             5                             Cold  ...
549937             4                             Cold  ...
549963             3                             Cold  ...
549989             3                             Cold  ...

        out.emissions.natural_gas.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                             1176.320144
79                                              625.962460
119                                            5540.594966
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                         6675.629132
549915                                            0.000000
549937                                         7002.945922
549963                                         8277.210267
549989                                            0.000000

        out.emissions.propane.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                                0.000000
119                                               0.000000
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                          223.856453

        out.emissions.electricity.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                             3520.864715
79                                             3334.140695
119                                            4179.118870
122                                            3794.589113
150                                           11378.222173
...                                                    ...
549882                                         2916.093184
549915                                        16728.421288
549937                                         3823.559604
549963                                         3992.118611
549989                                         2136.040859

        out.emissions.fuel_oil.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                            11194.437431
119                                               0.000000
122                                           13038.928166
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                         6042.544365

        out.emissions.natural_gas.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                             1176.320144
79                                              625.962460
119                                            5540.594966
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                         6675.629132
549915                                            0.000000
549937                                         7002.945922
549963                                         8277.210267
549989                                            0.000000

        out.emissions.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                                0.000000
119                                               0.000000
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                          223.856453

        out.emissions.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
15                                             2676.537445
79                                            13266.125327
119                                            7380.371515
122                                           14675.825549
150                                            4530.910597
...                                                    ...
549882                                         7916.182492
549915                                         6870.847124
549937                                         8577.560537
549963                                         9951.214681
549989                                         7176.439561

        out.emissions.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
15                                             4531.425424
79                                            14949.893770
119                                            9495.197860
122                                           16590.276103
150                                           10702.844907
...                                                    ...
549882                                         9422.157695
549915                                        15814.400458
549937                                        10516.078249
549963                                        11921.778240
549989                                         8281.270372

        out.emissions.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                             4127.883797
79                                            14585.037676
119                                            9035.427108
122                                           16204.985672
150                                            9290.264827
...                                                    ...
549882                                         9095.470037
549915                                        13772.445542
549937                                        10222.759114
549963                                        11608.667963
549989                                         8040.946248

        out.emissions.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg
bldg_id
15                                             4697.184859
79                                            15154.540586
119                                            9719.713836
122                                           16833.517280
150                                           11378.222173
...                                                    ...
549882                                         9591.722316
549915                                        16728.421288
549937                                        10826.505527
549963                                        12269.328878
549989                                         8402.441677

[17990 rows x 259 columns]


====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO: MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
In addition to the housing type and occupancy filters, the data has been filtered for fuel and technology
Please see the energy_consumption_and_metadata folder for more details on data processing.

We employ the df_enduse_refactored function to process the data and create a new dataframe, which is part of the 5-step data validation process:
1. Mask Initialization with initialize_validation_tracking()
2. Series Initialization with create_retrofit_only_series()
3. Valid-Only Calculation for qualifying homes
4. Valid-Only Updates using list-based collection
5. Final Masking with apply_final_masking()

Documentation for df_enduse_refactored function:
Creates a standardized energy usage DataFrame and applies data quality filters.

    This function creates a new DataFrame with standardized column names and structure,
    calculates total consumption by fuel type, creates data quality flags for analysis,
    and sets invalid consumption values to NaN.

    Args:
        df_baseline: The baseline DataFrame containing raw EUSS/ResStock data.

    Returns:
        A standardized DataFrame with processed consumption data and data quality flags.

    Raises:
        ValueError: If required columns are missing from the input DataFrame.

----------------------------------------------------------------

RESULTS OUTPUT (BASELINE):

Processing column: in.clothes_dryer
Initial data types: object
Data types after processing: object
Processing column: in.cooking_range
Initial data types: object
Data types after processing: object
Calculated total heating consumption
Calculated total waterHeating consumption
Calculated total clothesDrying consumption
Calculated total cooking consumption

Creating data quality flags for all categories

--- Processing heating ---
Values in base_heating_fuel (top 5):
base_heating_fuel
Natural Gas    9704
Electricity    3374
Fuel Oil       3302
Other Fuel      820
Propane         781
Name: count, dtype: int64
  heating: Found 829 homes (4.6%) with invalid fuel types
  Invalid fuel types (top 5):
base_heating_fuel
Other Fuel    820
Name: count, dtype: int64
Values in heating_type (top 5):
heating_type
Natural Gas Fuel Furnace               6269
Fuel Oil Fuel Furnace                  2113
Natural Gas Fuel Wall/Floor Furnace    1551
Natural Gas Fuel Boiler                1436
Electricity Baseboard                  1364
Name: count, dtype: int64
Allowed values for heating:
['Electricity Baseboard', 'Electricity Electric Boiler', 'Electricity Electric Furnace', 'Fuel Oil Fuel Boiler', 'Fuel Oil Fuel Furnace', 'Natural Gas Fuel Boiler', 'Natural Gas Fuel Furnace', 'Propane Fuel Boiler', 'Propane Fuel Furnace']
  heating: Found 4141 homes (23.0%) with invalid technology types
  Invalid technology types (top 5):
heating_type
Natural Gas Fuel Wall/Floor Furnace    1551
Electricity ASHP                        786
Natural Gas Shared Heating              448
Electricity Shared Heating              194
Propane Fuel Wall/Floor Furnace         148
Name: count, dtype: int64
  heating: Total 4141 homes (23.0%) excluded from analysis

--- Processing waterHeating ---
Values in base_waterHeating_fuel (top 5):
base_waterHeating_fuel
Natural Gas    9866
Electricity    5429
Fuel Oil       1977
Propane         693
Other Fuel       25
Name: count, dtype: int64
  waterHeating: Found 25 homes (0.1%) with invalid fuel types
  Invalid fuel types (top 5):
base_waterHeating_fuel
Other Fuel    25
Name: count, dtype: int64
Values in waterHeating_type (top 5):
waterHeating_type
Natural Gas Standard    8877
Electric Standard       4329
Fuel Oil Standard       1316
Electric Premium         949
Natural Gas Premium      756
Name: count, dtype: int64
Allowed values for waterHeating:
['Electric Premium', 'Electric Standard', 'Fuel Oil Premium', 'Fuel Oil Standard', 'Natural Gas Premium', 'Natural Gas Standard', 'Propane Premium', 'Propane Standard']
  waterHeating: Found 735 homes (4.1%) with invalid technology types
  Invalid technology types (top 5):
waterHeating_type
FIXME Fuel Oil Indirect       293
Natural Gas Tankless          233
Electric Tankless             118
Propane Tankless               33
Electric Heat Pump, 80 gal     33
Name: count, dtype: int64
  waterHeating: Total 735 homes (4.1%) excluded from analysis

--- Processing clothesDrying ---
Values in base_clothesDrying_fuel (top 5):
base_clothesDrying_fuel
Electricity    11769
Natural Gas     4163
Propane          306
Name: count, dtype: int64
  clothesDrying: Found 1752 homes (9.7%) with invalid fuel types
  Invalid fuel types (top 5):
Series([], Name: count, dtype: int64)
  clothesDrying: Technology validation not applicable (no technology type column)
  clothesDrying: Total 1752 homes (9.7%) excluded from analysis

--- Processing cooking ---
Values in base_cooking_fuel (top 5):
base_cooking_fuel
Electricity    8838
Natural Gas    7575
Propane        1399
Name: count, dtype: int64
  cooking: Found 9016 homes (50.1%) with invalid fuel types
  Invalid fuel types (top 5):
base_cooking_fuel
Electricity    8838
Name: count, dtype: int64
  cooking: Technology validation not applicable (no technology type column)
  cooking: Total 9016 homes (50.1%) excluded from analysis

Total 11857 homes (65.9%) excluded from all categories

Applying data validation (baseline only):
Baseline calculation for heating:

# LOAD EUSS DATA: Annual Energy Consumption and Metadata
## MEASURE PACKAGE 7 (MP7): Data for Electric Resistance Cooking

In [2]:
print(f"""
====================================================================================================================================================================
We assume the use of Electric Resistance (MP7) rather than Induction (MP8).
Electric Resistance is significantly cheaper and only slightly less efficient than Induction.
====================================================================================================================================================================
""")
# from cmu_tare_model.constants import ALLOWED_HOUSING_TYPES

# Measure Package 7
menu_mp = 7
input_mp = 'upgrade07'

filename = "upgrade07_metadata_and_annual_results.csv"
relative_path = os.path.join("cmu_tare_model", "data", "euss_data", "resstock_amy2018_release_1.1", "resstock_amy2018_release_1.1_processed_data", filename)
file_path = os.path.join(PROJECT_ROOT, relative_path)

print(f"Retrieved data for filename: {filename}")
print(f"Located at filepath: {file_path}")
print("\n")

# Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
columns_to_string = {11: str, 61: str, 121: str, 103: str, 128: str, 129: str}
df_euss_am_mp7 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
print(f"DATAFRAME SIZE before applying any filters: {df_euss_am_mp7.shape}")


# Filter for occupied homes
occupancy_filter = df_euss_am_mp7['in.vacancy_status'] == 'Occupied'
df_euss_am_mp7 = df_euss_am_mp7.loc[occupancy_filter]
print(f"DATAFRAME SIZE after filtering for 'Occupied' homes: {df_euss_am_mp7.shape}")

# Filter for allowed housing types
house_type_filter = df_euss_am_mp7['in.geometry_building_type_recs'].isin(ALLOWED_HOUSING_TYPES)
df_euss_am_mp7 = df_euss_am_mp7.loc[house_type_filter]
print(f"Allowed housing types: {ALLOWED_HOUSING_TYPES}")
print(f"DATAFRAME SIZE after filtering for allowed housing types: {df_euss_am_mp7.shape}")

# National Level 
if menu_state == 'N':
    print("You chose to analyze all of the United States.")
    input_state = 'National'

# Filter down to state or city
else:
    print(f"You chose to filter for: {input_state}")
    state_filter = df_euss_am_mp7['in.state'].eq(input_state)
    df_euss_am_mp7 = df_euss_am_mp7.loc[state_filter]

    # Filter for the entire selected state
    if menu_city == 'N':
        print(f"You chose to analyze all of state: {input_state}")
        
    # Filter to a city within the selected state
    else:
        print(f"You chose to filter for: {input_state}, {input_cityFilter}")
        city_filter = df_euss_am_mp7['in.city'].eq(f"{input_state}, {input_cityFilter}")
        df_euss_am_mp7 = df_euss_am_mp7.loc[city_filter]

# Display the filtered dataframe
print(f"DATAFRAME SIZE after applying geographic filter: {df_euss_am_mp7.shape}")
print(df_euss_am_mp7)

====================================================================================================================================================================
We assume the use of Electric Resistance (MP7) rather than Induction (MP8).
Electric Resistance is significantly cheaper and only slightly less efficient than Induction.
====================================================================================================================================================================

Retrieved data for filename: upgrade07_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\resstock_amy2018_release_1.1_processed_data\upgrade07_metadata_and_annual_results.csv


DATAFRAME SIZE before applying any filters: (548916, 346)
DATAFRAME SIZE after filtering for 'Occupied' homes: (482597, 346)
Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 346)
You chose to filter for: PA
You chose to analyze all of state: PA
DATAFRAME SIZE after applying geographic filter: (17990, 346)
         upgrade      weight  applicability  in.sqft  \
bldg_id
15             7  242.131013           True    333.0
79             7  242.131013           True   1220.0
119            7  242.131013           True   2152.0
122            7  242.131013           True   2176.0
150            7  242.131013          False   1690.0
...          ...         ...            ...      ...
549882         7  242.131013           True   1202.0
549915         7  242.131013          False   2176.0
549937         7  242.131013           True    885.0
549963         7  242.131013           True   1690.0
549989         7  242.131013           True   1220.0

                                            in.ahs_region  \
bldg_id
15       CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
79                               Non-CBSA Middle Atlantic
119      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
122      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
150                              Non-CBSA Middle Atlantic
...                                                   ...
549882                           Non-CBSA Middle Atlantic
549915                           Non-CBSA Middle Atlantic
549937                           Non-CBSA Middle Atlantic
549963                           Non-CBSA Middle Atlantic
549989                           Non-CBSA Middle Atlantic

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
15                                    4A
79                                    5A
119                                   4A
122                                   4A
150                                   5A
...                                  ...
549882                                5A
549915                                5A
549937                                5A
549963                                5A
549989                                5A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
15                                              4A                      Hour2
79                                              5A                     Hour10
119                                             4A                      Hour1
122                                             4A                     Hour18
150                                             5A                      Hour2
...                                            ...                        ...
549882                                          5A                      Hour5
549915                                          5A                      Hour0
549937                                          5A                     Hour20
549963                                          5A                     Hour13
549989                                          5A                     Hour22

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
15                 2                      Mixed-Humid  ...
79                 3                             Cold  ...
119                4                      Mixed-Humid  ...
122                4                      Mixed-Humid  ...
150                4                             Cold  ...
...              ...                              ...  ...
549882             2                             Cold  ...
549915             5                             Cold  ...
549937             4                             Cold  ...
549963             3                             Cold  ...
549989             3                             Cold  ...

        out.emissions_reduction.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                                0.000000
119                                               0.000000
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                          223.856453

        out.emissions_reduction.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
15                                              957.807463
79                                             9040.450190
119                                            4367.397352
122                                           10479.768179
150                                               0.000000
...                                                    ...
549882                                         5212.871757
549915                                            0.000000
549937                                         4636.242910
549963                                         4903.857419
549989                                         4686.866540

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
15                                              641.971549
79                                             4958.847783
119                                            2552.828291
122                                            6954.371623
150                                               0.000000
...                                                    ...
549882                                         3310.560695
549915                                            0.000000
549937                                         1673.632015
549963                                          609.743358
549989                                         2436.617472

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                              716.435541
79                                             5903.692936
119                                            2985.641141
122                                            7797.415226
150                                               0.000000
...                                                    ...
549882                                         3739.637305
549915                                            0.000000
549937                                         2257.364571
549963                                         1488.137683
549989                                         2959.741017

        out.emissions_reduction.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                              600.809402
79                                             4547.664485
119                                            2356.289439
122                                            6648.492515
150                                               0.000000
...                                                    ...
549882                                         3185.908976
549915                                            0.000000
549937                                         1154.203887
549963                                          -84.117798
549989                                         2177.081897

        upgrade.clothes_dryer upgrade.cooking_range  \
bldg_id
15                        NaN                   NaN
79                        NaN                   NaN
119      Electric, 100% Usage  Electric, 100% Usage
122                       NaN                   NaN
150                       NaN                   NaN
...                       ...                   ...
549882                    NaN                   NaN
549915                    NaN                   NaN
549937   Electric, 120% Usage  Electric, 120% Usage
549963                    NaN                   NaN
549989                    NaN  Electric, 100% Usage

        upgrade.hvac_cooling_efficiency    upgrade.hvac_heating_efficiency  \
bldg_id
15                                  NaN                                NaN
79                            Heat Pump            ASHP, SEER 15, 9.0 HSPF
119                           Heat Pump            ASHP, SEER 15, 9.0 HSPF
122                           Heat Pump            ASHP, SEER 15, 9.0 HSPF
150                                 NaN                                NaN
...                                 ...                                ...
549882                        Heat Pump  MSHP, SEER 15, 9.0 HSPF, Max Load
549915                              NaN                                NaN
549937                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549963                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549989                        Heat Pump            ASHP, SEER 15, 9.0 HSPF

              upgrade.water_heater_efficiency
bldg_id
15       Electric Heat Pump, 50 gal, 3.45 UEF
79       Electric Heat Pump, 50 gal, 3.45 UEF
119      Electric Heat Pump, 66 gal, 3.35 UEF
122      Electric Heat Pump, 66 gal, 3.35 UEF
150                                       NaN
...                                       ...
549882   Electric Heat Pump, 50 gal, 3.45 UEF
549915                                    NaN
549937   Electric Heat Pump, 66 gal, 3.35 UEF
549963   Electric Heat Pump, 50 gal, 3.45 UEF
549989   Electric Heat Pump, 50 gal, 3.45 UEF

[17990 rows x 346 columns]

## MEASURE PACKAGE 8 (MP8): Metadata, Space Heating, Water Heating, and Clothes Drying

In [43]:
# Print debugging information
# print_debug = False
print_debug = True

if print_debug:
    from cmu_tare_model.utils.create_sample_df import create_sample_df

In [4]:
# Measure Package 8
menu_mp = 8
input_mp = 'upgrade08'
scenario_name = 'Basic-BAU'
cost_scenario = 'BAU Costs'
grid_scenario = 'Current Electricity Grid'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

filename = "upgrade08_metadata_and_annual_results.csv"
relative_path = os.path.join("cmu_tare_model", "data", "euss_data", "resstock_amy2018_release_1.1", "resstock_amy2018_release_1.1_processed_data", filename)

file_path = os.path.join(PROJECT_ROOT, relative_path)

print(f"Retrieved data for filename: {filename}")
print(f"Located at filepath: {file_path}")
print("\n")

# Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
columns_to_string = {11: str, 61: str, 121: str, 103: str, 128: str, 129: str}
df_euss_am_mp8 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
print(f"DATAFRAME SIZE before applying any filters: {df_euss_am_mp8.shape}")

# Filter for occupied homes
occupancy_filter = df_euss_am_mp8['in.vacancy_status'] == 'Occupied'
df_euss_am_mp8 = df_euss_am_mp8.loc[occupancy_filter]
print(f"DATAFRAME SIZE after filtering for 'Occupied' homes: {df_euss_am_mp8.shape}")

# Filter for allowed housing types
house_type_filter = df_euss_am_mp8['in.geometry_building_type_recs'].isin(ALLOWED_HOUSING_TYPES)
df_euss_am_mp8 = df_euss_am_mp8.loc[house_type_filter]
print(f"Allowed housing types: {ALLOWED_HOUSING_TYPES}")
print(f"DATAFRAME SIZE after filtering for allowed housing types: {df_euss_am_mp8.shape}")

# National Level 
if menu_state == 'N':
    print("You chose to analyze all of the United States.")
    input_state = 'National'

# Filter down to state or city
else:
    print(f"You chose to filter for: {input_state}")
    state_filter = df_euss_am_mp8['in.state'].eq(input_state)
    df_euss_am_mp8 = df_euss_am_mp8.loc[state_filter]

    # Filter for the entire selected state
    if menu_city == 'N':
        print(f"You chose to analyze all of state: {input_state}")
        
    # Filter to a city within the selected state
    else:
        print(f"You chose to filter for: {input_state}, {input_cityFilter}")
        city_filter = df_euss_am_mp8['in.city'].eq(f"{input_state}, {input_cityFilter}")
        df_euss_am_mp8 = df_euss_am_mp8.loc[city_filter]

# Display the filtered dataframe
# Display the filtered dataframe
print(f"DATAFRAME SIZE after applying geographic filter: {df_euss_am_mp8.shape}")
print(df_euss_am_mp8)

====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario Basic-BAU:
Basic Retrofit: Measure Package 8
BAU Costs
Current Electricity Grid
====================================================================================================================================================================

Retrieved data for filename: upgrade08_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\resstock_amy2018_release_1.1_processed_data\upgrade08_metadata_and_annual_results.csv


DATAFRAME SIZE before applying any filters: (548916, 347)
DATAFRAME SIZE after filtering for 'Occupied' homes: (482597, 347)
Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 347)
You chose to filter for: PA
You chose to analyze all of state: PA
DATAFRAME SIZE after applying geographic filter: (17990, 347)
         upgrade      weight  applicability  in.sqft  \
bldg_id
15             8  242.131013           True    333.0
79             8  242.131013           True   1220.0
119            8  242.131013           True   2152.0
122            8  242.131013           True   2176.0
150            8  242.131013           True   1690.0
...          ...         ...            ...      ...
549882         8  242.131013           True   1202.0
549915         8  242.131013           True   2176.0
549937         8  242.131013           True    885.0
549963         8  242.131013           True   1690.0
549989         8  242.131013           True   1220.0

                                            in.ahs_region  \
bldg_id
15       CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
79                               Non-CBSA Middle Atlantic
119      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
122      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
150                              Non-CBSA Middle Atlantic
...                                                   ...
549882                           Non-CBSA Middle Atlantic
549915                           Non-CBSA Middle Atlantic
549937                           Non-CBSA Middle Atlantic
549963                           Non-CBSA Middle Atlantic
549989                           Non-CBSA Middle Atlantic

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
15                                    4A
79                                    5A
119                                   4A
122                                   4A
150                                   5A
...                                  ...
549882                                5A
549915                                5A
549937                                5A
549963                                5A
549989                                5A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
15                                              4A                      Hour2
79                                              5A                     Hour10
119                                             4A                      Hour1
122                                             4A                     Hour18
150                                             5A                      Hour2
...                                            ...                        ...
549882                                          5A                      Hour5
549915                                          5A                      Hour0
549937                                          5A                     Hour20
549963                                          5A                     Hour13
549989                                          5A                     Hour22

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
15                 2                      Mixed-Humid  ...
79                 3                             Cold  ...
119                4                      Mixed-Humid  ...
122                4                      Mixed-Humid  ...
150                4                             Cold  ...
...              ...                              ...  ...
549882             2                             Cold  ...
549915             5                             Cold  ...
549937             4                             Cold  ...
549963             3                             Cold  ...
549989             3                             Cold  ...

        out.emissions_reduction.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
15                                             1463.385601
79                                            10413.652102
119                                            5063.088752
122                                           12066.712342
150                                            3103.153770
...                                                    ...
549882                                         5882.269769
549915                                         3949.186094
549937                                         5643.594000
549963                                         6479.951652
549989                                         5231.517125

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
15                                             1783.230817
79                                             8204.179627
119                                            4214.733128
122                                           10590.254662
150                                            7434.178003
...                                                    ...
549882                                         4814.108725
549915                                         9153.072186
549937                                         3941.494074
549963                                         4162.716516
549989                                         3713.809302

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                             1716.655251
79                                             8721.577475
119                                            4421.232869
122                                           10962.614536
150                                            6435.450158
...                                                    ...
549882                                         5058.857189
549915                                         7958.419199
549937                                         4289.405772
549963                                         4656.122049
549989                                         4068.275863

        out.emissions_reduction.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                             1792.641045
79                                             8005.156903
119                                            4103.394799
122                                           10472.994231
150                                            7914.527787
...                                                    ...
549882                                         4740.981471
549915                                         9734.504122
549937                                         3628.586099
549963                                         3803.239573
549989                                         3542.402188

                                     upgrade.clothes_dryer  \
bldg_id
15                                                     NaN
79       Electric, Premium, Heat Pump, Ventless, 100% U...
119      Electric, Premium, Heat Pump, Ventless, 100% U...
122      Electric, Premium, Heat Pump, Ventless, 100% U...
150      Electric, Premium, Heat Pump, Ventless, 80% Usage
...                                                    ...
549882   Electric, Premium, Heat Pump, Ventless, 120% U...
549915   Electric, Premium, Heat Pump, Ventless, 100% U...
549937   Electric, Premium, Heat Pump, Ventless, 120% U...
549963   Electric, Premium, Heat Pump, Ventless, 100% U...
549989   Electric, Premium, Heat Pump, Ventless, 100% U...

                   upgrade.cooking_range upgrade.hvac_cooling_efficiency  \
bldg_id
15       Electric, Induction, 100% Usage                       Heat Pump
79       Electric, Induction, 100% Usage                       Heat Pump
119      Electric, Induction, 100% Usage                       Heat Pump
122      Electric, Induction, 100% Usage                       Heat Pump
150       Electric, Induction, 80% Usage                       Heat Pump
...                                  ...                             ...
549882   Electric, Induction, 120% Usage                       Heat Pump
549915   Electric, Induction, 100% Usage                       Heat Pump
549937   Electric, Induction, 120% Usage                       Heat Pump
549963   Electric, Induction, 100% Usage                       Heat Pump
549989   Electric, Induction, 100% Usage                       Heat Pump

            upgrade.hvac_heating_efficiency upgrade.hvac_heating_type  \
bldg_id
15                   MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
79                   MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
119                  MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
122                  MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
150      MSHP, SEER 29.3, 14 HSPF, Max Load                       NaN
...                                     ...                       ...
549882   MSHP, SEER 29.3, 14 HSPF, Max Load                       NaN
549915               MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
549937               MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
549963               MSHP, SEER 24, 13 HSPF          Ducted Heat Pump
549989               MSHP, SEER 24, 13 HSPF          Ducted Heat Pump

              upgrade.water_heater_efficiency
bldg_id
15       Electric Heat Pump, 50 gal, 3.45 UEF
79       Electric Heat Pump, 50 gal, 3.45 UEF
119      Electric Heat Pump, 66 gal, 3.35 UEF
122      Electric Heat Pump, 66 gal, 3.35 UEF
150      Electric Heat Pump, 66 gal, 3.35 UEF
...                                       ...
549882   Electric Heat Pump, 50 gal, 3.45 UEF
549915   Electric Heat Pump, 80 gal, 3.45 UEF
549937   Electric Heat Pump, 66 gal, 3.35 UEF
549963   Electric Heat Pump, 50 gal, 3.45 UEF
549989   Electric Heat Pump, 50 gal, 3.45 UEF

[17990 rows x 347 columns]

# Project Future Energy Consumption

In [5]:
from cmu_tare_model.energy_consumption_and_metadata.process_euss_data import df_enduse_compare

print(F"""
====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE {menu_mp} (MP{menu_mp})
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp8.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied. 
      - df_euss_am_mp8_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp8_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.
      
Documentation for df_enduse_compare function:
{df_enduse_compare.__doc__}
----------------------------------------------------------------

RESULTING DATAFRAME:
""")

# df_enduse_compare(df_mp, category, df_baseline):
df_euss_am_mp8_home = df_enduse_compare(
    df_mp = df_euss_am_mp8,
    input_mp=input_mp,
    menu_mp=menu_mp,
    df_baseline = df_euss_am_baseline_home,
    df_cooking_range=df_euss_am_mp7,
    )

====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE 8 (MP8)
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp8.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied.
      - df_euss_am_mp8_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp8_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.

Documentation for df_enduse_compare function:
Creates a comparison DataFrame by merging multiple DataFrames based on measure packages.

    This function constructs a new DataFrame (df_compare) that includes columns
    from df_mp, df_cooking_range, and merges them with df_baseline to compare
    baseline vs. measure package outputs for heating, water heating, clothes drying,
    and cooking.

    Args:
        df_mp: The main DataFrame containing modeling parameters and outputs.
        input_mp: The input measure package ID (e.g., 'upgrade09', 'upgrade10').
        menu_mp: The menu measure package number.
        df_baseline: The baseline DataFrame to merge with df_compare.
        df_cooking_range: Additional DataFrame for cooking range parameters/outputs.

    Returns:
        A merged DataFrame (df_compare) that includes relevant columns for
        baseline and measure packages comparison.

----------------------------------------------------------------

RESULTING DATAFRAME:


Applying combined validation (data quality + retrofit status):
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
  mp8_heating_consumption: Masked 4141 values
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)
  mp8_waterHeating_consumption: Masked 735 values
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)
  mp8_clothesDrying_consumption: Masked 1752 values
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)
  mp8_cooking_consumption: Masked 9016 values

In [6]:
if print_debug:
    # Create a sample dataframe for the heating category
    df_sample_heating = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['heating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_heating', 'valid_fuel_heating', 'valid_tech_heating', 'include_heating', 'heating_consumption']
    )
    print(df_sample_heating)

    # Create a sample dataframe for the waterHeating category
    df_sample_waterHeating = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['waterHeating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_waterHeating', 'valid_fuel_waterHeating', 'valid_tech_waterHeating', 'include_waterHeating', 'waterHeating_consumption']
    )
    print(df_sample_waterHeating)

    # Create a sample dataframe for the clothesDrying category
    df_sample_clothesDrying = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['clothesDrying'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_clothesDrying', 'valid_fuel_clothesDrying', 'include_clothesDrying', 'clothesDrying_consumption']
    )
    print(df_sample_clothesDrying)

    # Create a sample dataframe for the cooking category
    df_sample_cooking = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', 'cooking_consumption']
    )
    print(df_sample_cooking)

# PUBLIC IMPACTS: Climate and Health Damages
## Scenarios: No IRA and IRA-Reference

In [7]:
from cmu_tare_model.public_impact.calculate_lifetime_climate_impacts_sensitivity import calculate_lifetime_climate_impacts
from cmu_tare_model.public_impact.calculate_lifetime_health_impacts_sensitivity import calculate_lifetime_health_impacts

print(f"""
====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================

""")

# Make copies from scenario consumption to keep df smaller
print("\n", "Creating dataframe to store marginal damages calculations ...")
# Climate damages: No IRA and IRA-Reference
df_mp8_noIRA_damages_climate = df_euss_am_mp8_home.copy()
df_mp8_IRA_damages_climate = df_euss_am_mp8_home.copy()

# Health damages: No IRA and IRA-Reference
df_mp8_noIRA_damages_health = df_euss_am_mp8_home.copy()
df_mp8_IRA_damages_health = df_euss_am_mp8_home.copy()

====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================



 Creating dataframe to store marginal damages calculations ...

In [8]:
# Health Impacts: Baseline Scenario
print(f"""
====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
{df_euss_am_baseline_home}
      
df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
{df_baseline_damages_health}

""")

if print_debug:
    # df_euss_am_baseline_home
    print(f"Shape of df_euss_am_baseline_home: {df_euss_am_baseline_home.shape}")

    # Print columns that contain the word "damages"
    damage_columns = [col for col in df_euss_am_baseline_home.columns if "damages" in col.lower()]
    print("\nColumns containing 'damages':")
    print(damage_columns)

    # df_baseline_damages_health
    print(f"Shape of df_baseline_damages_health: {df_baseline_damages_health.shape}")

    # Print columns that contain the word "damages"
    damage_columns = [col for col in df_baseline_damages_health.columns if "damages" in col.lower()]
    print("\nColumns containing 'damages':")
    print(damage_columns)

====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        baseline_cooking_lifetime_damages_health_inmap_acs  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 148.09
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                               50.48
549963                                                 NaN
549989                                               57.21

        baseline_cooking_lifetime_damages_health_inmap_h6c fuel_type_heating  \
bldg_id
15                                                     NaN       electricity
79                                                     NaN           fuelOil
119                                                 380.50        naturalGas
122                                                    NaN           fuelOil
150                                                    NaN       electricity
...                                                    ...               ...
549882                                                 NaN        naturalGas
549915                                                 NaN       electricity
549937                                              129.68        naturalGas
549963                                                 NaN        naturalGas
549989                                              146.99           fuelOil

        fuel_type_waterHeating fuel_type_clothesDrying  fuel_type_cooking  \
bldg_id
15                  naturalGas                     NaN        electricity
79                  naturalGas             electricity        electricity
119                 naturalGas              naturalGas         naturalGas
122                    fuelOil             electricity        electricity
150                electricity             electricity        electricity
...                        ...                     ...                ...
549882              naturalGas             electricity        electricity
549915             electricity             electricity        electricity
549937              naturalGas              naturalGas         naturalGas
549963              naturalGas             electricity        electricity
549989                 fuelOil             electricity            propane

         baseline_heating_lifetime_fuel_cost  \
bldg_id
15                                       NaN
79                                  51485.89
119                                  9692.04
122                                 56634.48
150                                 48835.85
...                                      ...
549882                                   NaN
549915                              52898.91
549937                               8456.00
549963                              17473.34
549989                              22285.90

        baseline_waterHeating_lifetime_fuel_cost  \
bldg_id
15                                       2470.92
79                                       1314.89
119                                      2299.55
122                                      2946.50
150                                      2764.45
...                                          ...
549882                                   2435.13
549915                                  10026.26
549937                                   5758.50
549963                                   1917.25
549989                                   4864.25

        baseline_clothesDrying_lifetime_fuel_cost  \
bldg_id
15                                            NaN
79                                         619.28
119                                        351.02
122                                        619.28
150                                        718.64
...                                           ...
549882                                     997.02
549915                                    1736.07
549937                                     982.27
549963                                     898.31
549989                                     898.31

        baseline_cooking_lifetime_fuel_cost
bldg_id
15                                      NaN
79                                      NaN
119                                  589.84
122                                     NaN
150                                     NaN
...                                     ...
549882                                  NaN
549915                                  NaN
549937                               802.29
549963                                  NaN
549989                              1691.55

[17990 rows x 126 columns]

df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
         include_all  include_heating  include_waterHeating  \
bldg_id
15             False            False                  True
79             False             True                  True
119             True             True                  True
122            False             True                  True
150            False             True                  True
...              ...              ...                   ...
549882         False            False                  True
549915         False             True                  True
549937          True             True                  True
549963         False             True                  True
549989          True             True                  True

         include_clothesDrying  include_cooking  valid_tech_heating  \
bldg_id
15                       False            False               False
79                        True            False                True
119                       True             True                True
122                       True            False                True
150                       True            False                True
...                        ...              ...                 ...
549882                    True            False               False
549915                    True            False                True
549937                    True             True                True
549963                    True            False                True
549989                    True             True                True

         valid_tech_waterHeating  valid_fuel_heating  valid_fuel_waterHeating  \
bldg_id
15                          True                True                     True
79                          True                True                     True
119                         True                True                     True
122                         True                True                     True
150                         True                True                     True
...                          ...                 ...                      ...
549882                      True                True                     True
549915                      True                True                     True
549937                      True                True                     True
549963                      True                True                     True
549989                      True                True                     True

         valid_fuel_clothesDrying  ...  \
bldg_id                            ...
15                          False  ...
79                           True  ...
119                          True  ...
122                          True  ...
150                          True  ...
...                           ...  ...
549882                       True  ...
549915                       True  ...
549937                       True  ...
549963                       True  ...
549989                       True  ...

         baseline_2038_cooking_damages_so2_inmap_h6c  \
bldg_id
15                                               NaN
79                                               NaN
119                                             0.92
122                                              NaN
150                                              NaN
...                                              ...
549882                                           NaN
549915                                           NaN
549937                                          0.63
549963                                           NaN
549989                                          0.82

         baseline_2038_cooking_damages_nox_inmap_h6c  \
bldg_id
15                                               NaN
79                                               NaN
119                                            17.35
122                                              NaN
150                                              NaN
...                                              ...
549882                                           NaN
549915                                           NaN
549937                                          7.15
549963                                           NaN
549989                                          8.32

         baseline_2038_cooking_damages_pm25_inmap_h6c  \
bldg_id
15                                                NaN
79                                                NaN
119                                              8.30
122                                               NaN
150                                               NaN
...                                               ...
549882                                            NaN
549915                                            NaN
549937                                           0.91
549963                                            NaN
549989                                           0.68

         baseline_2038_cooking_damages_health_inmap_h6c  \
bldg_id
15                                                  NaN
79                                                  NaN
119                                               26.56
122                                                 NaN
150                                                 NaN
...                                                 ...
549882                                              NaN
549915                                              NaN
549937                                             8.69
549963                                              NaN
549989                                             9.83

         baseline_cooking_lifetime_damages_health_ap2_acs  \
bldg_id
15                                                    NaN
79                                                    NaN
119                                                 37.49
122                                                   NaN
150                                                   NaN
...                                                   ...
549882                                                NaN
549915                                                NaN
549937                                              20.82
549963                                                NaN
549989                                              23.53

         baseline_cooking_lifetime_damages_health_ap2_h6c  \
bldg_id
15                                                    NaN
79                                                    NaN
119                                                 96.32
122                                                   NaN
150                                                   NaN
...                                                   ...
549882                                                NaN
549915                                                NaN
549937                                              53.48
549963                                                NaN
549989                                              60.44

         baseline_cooking_lifetime_damages_health_easiur_acs  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 130.47
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                               73.35
549963                                                 NaN
549989                                               59.17

         baseline_cooking_lifetime_damages_health_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 335.21
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              188.47
549963                                                 NaN
549989                                              152.01

         baseline_cooking_lifetime_damages_health_inmap_acs  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 148.09
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                               50.48
549963                                                 NaN
549989                                               57.21

         baseline_cooking_lifetime_damages_health_inmap_h6c
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 380.50
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              129.68
549963                                                 NaN
549989                                              146.99

[17990 rows x 1355 columns]

In [9]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp8_home, df_mp8_noIRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )

df_euss_am_mp8_home, df_mp8_noIRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp8_home, df_mp8_IRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )


df_euss_am_mp8_home, df_mp8_IRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
Post-Retrofit (MP8) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well. 
      
CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp8_noIRA_damages_climate
{df_mp8_noIRA_damages_climate}

Climate Damages (IRA): df_mp8_IRA_damages_climate
{df_mp8_IRA_damages_climate}

HEALTH DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Health Damages (No IRA): df_mp8_noIRA_damages_health
{df_mp8_noIRA_damages_health}

Health Damages (IRA): df_mp8_IRA_damages_health
{df_mp8_IRA_damages_health}

SUMMARY DATAFRAME FOR MP8: df_euss_am_mp8_home
{df_euss_am_mp8_home}
====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

====================================================================================================================================================================
Post-Retrofit (MP8) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well.

CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp8_noIRA_damages_climate
         include_all  include_heating  include_waterHeating  \
bldg_id
15             False            False                  True
79             False             True                  True
119             True             True                  True
122            False             True                  True
150            False             True                  True
...              ...              ...                   ...
549882         False            False                  True
549915         False             True                  True
549937          True             True                  True
549963         False             True                  True
549989          True             True                  True

         include_clothesDrying  include_cooking  valid_tech_heating  \
bldg_id
15                       False            False               False
79                        True            False                True
119                       True             True                True
122                       True            False                True
150                       True            False                True
...                        ...              ...                 ...
549882                    True            False               False
549915                    True            False                True
549937                    True             True                True
549963                    True            False                True
549989                    True             True                True

         valid_tech_waterHeating  valid_fuel_heating  valid_fuel_waterHeating  \
bldg_id
15                          True                True                     True
79                          True                True                     True
119                         True                True                     True
122                         True                True                     True
150                         True                True                     True
...                          ...                 ...                      ...
549882                      True                True                     True
549915                      True                True                     True
549937                      True                True                     True
549963                      True                True                     True
549989                      True                True                     True

         valid_fuel_clothesDrying  ...  \
bldg_id                            ...
15                          False  ...
79                           True  ...
119                          True  ...
122                          True  ...
150                          True  ...
...                           ...  ...
549882                       True  ...
549915                       True  ...
549937                       True  ...
549963                       True  ...
549989                       True  ...

         preIRA_mp8_cooking_avoided_damages_climate_lrmer_upper  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 166.95
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              120.55
549963                                                 NaN
549989                                              380.99

         preIRA_mp8_cooking_avoided_mt_co2e_lrmer  \
bldg_id
15                                            NaN
79                                            NaN
119                                          0.37
122                                           NaN
150                                           NaN
...                                           ...
549882                                        NaN
549915                                        NaN
549937                                       0.27
549963                                        NaN
549989                                       0.90

         preIRA_mp8_cooking_lifetime_mt_co2e_srmer  \
bldg_id
15                                             NaN
79                                             NaN
119                                           5.98
122                                            NaN
150                                            NaN
...                                            ...
549882                                         NaN
549915                                         NaN
549937                                        8.93
549963                                         NaN
549989                                        5.11

         preIRA_mp8_cooking_lifetime_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 440.52
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              658.13
549963                                                 NaN
549989                                              376.58

         preIRA_mp8_cooking_avoided_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                -168.60
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                             -284.18
549963                                                 NaN
549989                                             -101.83

         preIRA_mp8_cooking_lifetime_damages_climate_srmer_central  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                1565.05
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                             2338.49
549963                                                 NaN
549989                                             1337.88

         preIRA_mp8_cooking_avoided_damages_climate_srmer_central  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                -599.59
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                            -1010.75
549963                                                 NaN
549989                                             -362.41

         preIRA_mp8_cooking_lifetime_damages_climate_srmer_upper  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                2485.36
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                             3713.87
549963                                                 NaN
549989                                             2124.61

         preIRA_mp8_cooking_avoided_damages_climate_srmer_upper  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                -952.69
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                            -1606.04
549963                                                 NaN
549989                                             -576.04

         preIRA_mp8_cooking_avoided_mt_co2e_srmer
bldg_id
15                                            NaN
79                                            NaN
119                                         -2.30
122                                           NaN
150                                           NaN
...                                           ...
549882                                        NaN
549915                                        NaN
549937                                      -3.87
549963                                        NaN
549989                                      -1.39

[17990 rows x 515 columns]

Climate Damages (IRA): df_mp8_IRA_damages_climate
         include_all  include_heating  include_waterHeating  \
bldg_id
15             False            False                  True
79             False             True                  True
119             True             True                  True
122            False             True                  True
150            False             True                  True
...              ...              ...                   ...
549882         False            False                  True
549915         False             True                  True
549937          True             True                  True
549963         False             True                  True
549989          True             True                  True

         include_clothesDrying  include_cooking  valid_tech_heating  \
bldg_id
15                       False            False               False
79                        True            False                True
119                       True             True                True
122                       True            False                True
150                       True            False                True
...                        ...              ...                 ...
549882                    True            False               False
549915                    True            False                True
549937                    True             True                True
549963                    True            False                True
549989                    True             True                True

         valid_tech_waterHeating  valid_fuel_heating  valid_fuel_waterHeating  \
bldg_id
15                          True                True                     True
79                          True                True                     True
119                         True                True                     True
122                         True                True                     True
150                         True                True                     True
...                          ...                 ...                      ...
549882                      True                True                     True
549915                      True                True                     True
549937                      True                True                     True
549963                      True                True                     True
549989                      True                True                     True

         valid_fuel_clothesDrying  ...  \
bldg_id                            ...
15                          False  ...
79                           True  ...
119                          True  ...
122                          True  ...
150                          True  ...
...                           ...  ...
549882                       True  ...
549915                       True  ...
549937                       True  ...
549963                       True  ...
549989                       True  ...

         iraRef_mp8_cooking_avoided_damages_climate_lrmer_upper  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 390.79
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              342.11
549963                                                 NaN
549989                                              572.34

         iraRef_mp8_cooking_avoided_mt_co2e_lrmer  \
bldg_id
15                                            NaN
79                                            NaN
119                                          0.93
122                                           NaN
150                                           NaN
...                                           ...
549882                                        NaN
549915                                        NaN
549937                                       0.81
549963                                        NaN
549989                                       1.37

         iraRef_mp8_cooking_lifetime_mt_co2e_srmer  \
bldg_id
15                                             NaN
79                                             NaN
119                                           5.25
122                                            NaN
150                                            NaN
...                                            ...
549882                                         NaN
549915                                         NaN
549937                                        7.30
549963                                         NaN
549989                                        4.49

         iraRef_mp8_cooking_lifetime_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                 385.00
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                              533.74
549963                                                 NaN
549989                                              329.12

         iraRef_mp8_cooking_avoided_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                -113.08
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN
549915                                                 NaN
549937                                             -159.79
549963                                                 NaN
549989                                              -54.37

         iraRef_mp8_cooking_lifetime_damages_climate_srmer_central  \
bldg_id
15                                                     NaN
79                                                     NaN
119                                                1369.47
122                                                    NaN
150                                                    NaN
...                                                    ...
549882                                                 NaN

In [10]:
if print_debug:
   # Create a sample dataframe for the heating category
    df_sample_heating = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['heating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_heating', 'valid_fuel_heating', 'include_heating', 'heating_lifetime_damages']
    )
    print(df_sample_heating)

    # Create a sample dataframe for the waterHeating category
    df_sample_waterHeating = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['waterHeating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_waterHeating', 'valid_fuel_waterHeating', 'include_waterHeating', 'waterHeating_lifetime_damages']
    )
    print(df_sample_waterHeating)

    # Create a sample dataframe for the clothesDrying category
    df_sample_clothesDrying = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['clothesDrying'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_clothesDrying', 'valid_fuel_clothesDrying', 'include_clothesDrying', 'clothesDrying_lifetime_damages']
    )
    print(df_sample_clothesDrying)

    # Create a sample dataframe for the cooking category
    df_sample_cooking = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', 'cooking_lifetime_damages']
    )
    print(df_sample_cooking)

In [11]:
if print_debug:
    print("""
==================== SUMMARY DATAFRAME WITH LIFETIME DAMAGES ==========
""")
    # Create a sample dataframe for the heating category
    df_main_sample = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', 'cooking_lifetime_damages']
    )
    print(f"""
df_main_sample dataframe is created using df_euss_am_mp8_home:
-----------------------------------------------------------------------------

{df_main_sample}

-----------------------------------------------------------------------------
""")


    print("""
==================== CLIMATE IMPACTS WITH ANNUAL AND LIFETIME ==========
""")

    # Create a sample dataframe for the heating category
    df_detailed_climate_noIRA = create_sample_df(
        df=df_mp8_noIRA_damages_climate,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['preIRA'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', f'cooking_damages_health']
    )
    print(f"""
df_detailed_climate_noIRA dataframe is created using df_mp8_noIRA_damages_climate:
-----------------------------------------------------------------------------
          
{df_detailed_climate_noIRA}

-----------------------------------------------------------------------------
""")

    # Create a sample dataframe for the heating category
    df_detailed_climate_IRA = create_sample_df(
        df=df_mp8_IRA_damages_climate,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', f'cooking_damages_health']
    )
    print(f"""
df_detailed_climate_IRA dataframe is created using df_mp8_IRA_damages_climate:
-----------------------------------------------------------------------------
          
{df_detailed_climate_IRA}

-----------------------------------------------------------------------------
""")

    print("""
==================== HEALTH IMPACTS WITH ANNUAL AND LIFETIME ==========
""")
    # Create a sample dataframe for the heating category
    df_detailed_health_noIRA = create_sample_df(
        df=df_mp8_noIRA_damages_health,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['preIRA'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', f'cooking_damages_health']
    )
    print(f"""
df_detailed_health_noIRA dataframe is created using df_mp8_noIRA_damages_health:
-----------------------------------------------------------------------------
          
{df_detailed_health_noIRA}

-----------------------------------------------------------------------------
""")

    # Create a sample dataframe for the heating category
    df_detailed_health_IRA = create_sample_df(
        df=df_mp8_IRA_damages_health,
        include_groups=['base_equipment'],
        categories=['cooking'],
        scenarios=['iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', f'cooking_damages_health']
    )
    print(f"""
df_detailed_health_IRA dataframe is created using df_mp8_IRA_damages_health:
-----------------------------------------------------------------------------
          
{df_detailed_health_IRA}

-----------------------------------------------------------------------------
""")

# PRIVATE IMPACTS: FUEL COSTS
## Scenarios: No IRA and IRA-Reference

In [12]:
from cmu_tare_model.private_impact.calculate_lifetime_fuel_costs import calculate_lifetime_fuel_costs

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:
{calculate_lifetime_fuel_costs.__doc__}

====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference

""")

print("\n", "Creating dataframe to store annual fuel cost calculations ...")
# Annual fuel costs: No IRA and IRA-Reference
df_mp8_fuel_costs_noIRA = df_euss_am_mp8_home.copy()
df_mp8_fuel_costs_IRA = df_euss_am_mp8_home.copy()

====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:

    Calculate lifetime fuel costs for each equipment category.

    This function processes each equipment category over its lifetime, computing annual
    and lifetime fuel costs. Results are combined into two DataFrames:
    a main summary (df_main) and a detailed annual breakdown (df_detailed).

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    Args:
        df: Input DataFrame containing equipment consumption data, region info, etc.
        menu_mp: Measure package identifier (0 for baseline, nonzero for different scenarios).
        policy_scenario: Determines fuel price scenario inputs
            (e.g., 'No Inflation Reduction Act' or 'AEO2023 Reference Case').
        df_baseline_costs: Optional DataFrame with baseline costs for computing operational savings.
            Default is None.
        verbose: Whether to print detailed processing information. Default is True.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Main summary of lifetime fuel costs (rounded to 2 decimals).
            - df_detailed: Detailed annual and lifetime results (rounded to 2 decimals).

    Raises:
        RuntimeError: If processing fails at the category or year level.
        ValueError: If an invalid policy_scenario is provided.
        KeyError: If required columns are missing from the input DataFrame.


====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference



 Creating dataframe to store annual fuel cost calculations ...

In [13]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp8_home, df_mp8_noIRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )

print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp8_home, df_mp8_IRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp8_home,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )


print(f"""  
====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp8_noIRA_fuel_costs
{df_mp8_noIRA_fuel_costs}

FUEL COSTS (IRA): df_mp8_IRA_fuel_costs
{df_mp8_IRA_fuel_costs}

SUMMARY DATAFRAME FOR MP8: df_euss_am_mp8_home
{df_euss_am_mp8_home}

====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2036 for waterHeating
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2037 for clothesDrying
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2039 for cooking
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
Masking 1 columns for category 'waterHeating'
Masking 1 columns for category 'clothesDrying'
Masking 3 columns for category 'cooking'
WARNING: Replacing 4 existing columns. Function was called on data that already contains results.
Columns being replaced: ['baseline_heating_lifetime_fuel_cost', 'baseline_waterHeating_lifetime_fuel_cost', 'baseline_clothesDrying_lifetime_fuel_cost', 'baseline_cooking_lifetime_fuel_cost']

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
Masking 1 columns for category 'waterHeating'
Masking 1 columns for category 'clothesDrying'
Masking 48 columns for category 'cooking'

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2036 for waterHeating
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2037 for clothesDrying
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)
Calculating Fuel Costs from 2024 to 2039 for cooking
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
Masking 1 columns for category 'waterHeating'
Masking 1 columns for category 'clothesDrying'
Masking 3 columns for category 'cooking'
WARNING: Replacing 4 existing columns. Function was called on data that already contains results.
Columns being replaced: ['baseline_heating_lifetime_fuel_cost', 'baseline_waterHeating_lifetime_fuel_cost', 'baseline_clothesDrying_lifetime_fuel_cost', 'baseline_cooking_lifetime_fuel_cost']

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
Masking 1 columns for category 'waterHeating'
Masking 1 columns for category 'clothesDrying'
Masking 48 columns for category 'cooking'

====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp8_noIRA_fuel_costs
         include_all  include_heating  include_waterHeating  \
bldg_id
15             False            False                  True
79             False             True                  True
119             True             True                  True
122            False             True                  True
150            False             True                  True
...              ...              ...                   ...
549882         False            False                  True
549915         False             True                  True
549937          True             True                  True
549963         False             True                  True
549989          True             True                  True

         include_clothesDrying  include_cooking  valid_tech_heating  \
bldg_id
15                       False            False               False
79                        True            False                True
119                       True             True                True
122                       True            False                True
150                       True            False                True
...                        ...              ...                 ...
549882                    True            False               False
549915                    True            False                True
549937                    True             True                True
549963                    True            False                True
549989                    True             True                True

         valid_tech_waterHeating  valid_fuel_heating  valid_fuel_waterHeating  \
bldg_id
15                          True                True                     True
79                          True                True                     True
119                         True                True                     True
122                         True                True                     True
150                         True                True                     True
...                          ...                 ...                      ...
549882                      True                True                     True
549915                      True                True                     True
549937                      True                True                     True
549963                      True                True                     True
549989                      True                True                     True

         valid_fuel_clothesDrying  ...  baseline_2035_cooking_fuel_cost  \
bldg_id                            ...
15                          False  ...                              NaN
79                           True  ...                              NaN
119                          True  ...                            39.02
122                          True  ...                              NaN
150                          True  ...                              NaN
...                           ...  ...                              ...
549882                       True  ...                              NaN
549915                       True  ...                              NaN
549937                       True  ...                            53.07
549963                       True  ...                              NaN
549989                       True  ...                           115.40

         preIRA_mp8_2036_cooking_fuel_cost  baseline_2036_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  86.54                            38.84
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              117.60                            52.84
549963                                 NaN                              NaN
549989                               73.98                           116.58

         preIRA_mp8_2037_cooking_fuel_cost  baseline_2037_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  87.04                            39.25
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              118.27                            53.38
549963                                 NaN                              NaN
549989                               74.40                           117.97

         preIRA_mp8_2038_cooking_fuel_cost  baseline_2038_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  87.81                            39.49
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              119.32                            53.71
549963                                 NaN                              NaN
549989                               75.06                           119.31

         preIRA_mp8_cooking_lifetime_fuel_cost  \
bldg_id
15                                         NaN
79                                         NaN
119                                    1240.31
122                                        NaN
150                                        NaN
...                                        ...
549882                                     NaN
549915                                     NaN
549937                                 1685.42
549963                                     NaN
549989                                 1060.28

         preIRA_mp8_cooking_lifetime_savings_fuel_cost  \
bldg_id
15                                                 NaN
79                                                 NaN
119                                            -650.47
122                                                NaN
150                                                NaN
...                                                ...
549882                                             NaN
549915                                             NaN
549937                                         -883.13
549963                                             NaN
549989                                          631.27

         baseline_cooking_lifetime_fuel_cost
bldg_id
15                                       NaN
79                                       NaN
119                                   589.84
122                                      NaN
150                                      NaN
...                                      ...
549882                                   NaN
549915                                   NaN
549937                                802.29
549963                                   NaN
549989                               1691.55

[17990 rows x 133 columns]

FUEL COSTS (IRA): df_mp8_IRA_fuel_costs
         include_all  include_heating  include_waterHeating  \
bldg_id
15             False            False                  True
79             False             True                  True
119             True             True                  True
122            False             True                  True
150            False             True                  True
...              ...              ...                   ...
549882         False            False                  True
549915         False             True                  True
549937          True             True                  True
549963         False             True                  True
549989          True             True                  True

         include_clothesDrying  include_cooking  valid_tech_heating  \
bldg_id
15                       False            False               False
79                        True            False                True
119                       True             True                True
122                       True            False                True
150                       True            False                True
...                        ...              ...                 ...
549882                    True            False               False
549915                    True            False                True
549937                    True             True                True
549963                    True            False                True
549989                    True             True                True

         valid_tech_waterHeating  valid_fuel_heating  valid_fuel_waterHeating  \
bldg_id
15                          True                True                     True
79                          True                True                     True
119                         True                True                     True
122                         True                True                     True
150                         True                True                     True
...                          ...                 ...                      ...
549882                      True                True                     True
549915                      True                True                     True
549937                      True                True                     True
549963                      True                True                     True
549989                      True                True                     True

         valid_fuel_clothesDrying  ...  baseline_2035_cooking_fuel_cost  \
bldg_id                            ...
15                          False  ...                              NaN
79                           True  ...                              NaN
119                          True  ...                            39.02
122                          True  ...                              NaN
150                          True  ...                              NaN
...                           ...  ...                              ...
549882                       True  ...                              NaN
549915                       True  ...                              NaN
549937                       True  ...                            53.07
549963                       True  ...                              NaN
549989                       True  ...                           115.40

         iraRef_mp8_2036_cooking_fuel_cost  baseline_2036_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  84.01                            38.84
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              114.15                            52.84
549963                                 NaN                              NaN
549989                               71.81                           116.58

         iraRef_mp8_2037_cooking_fuel_cost  baseline_2037_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  84.44                            39.25
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              114.74                            53.38
549963                                 NaN                              NaN
549989                               72.18                           117.97

         iraRef_mp8_2038_cooking_fuel_cost  baseline_2038_cooking_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                     NaN                              NaN
119                                  85.44                            39.49
122                                    NaN                              NaN
150                                    NaN                              NaN
...                                    ...                              ...
549882                                 NaN                              NaN
549915                                 NaN                              NaN
549937                              116.10                            53.71
549963                                 NaN                              NaN
549989                               73.04                           119.31

         iraRef_mp8_cooking_lifetime_fuel_cost  \
bldg_id
15                                         NaN
79                                         NaN
119                                    1214.19
122                                        NaN
150                                        NaN
...                                        ...
549882                                     NaN
549915                                     NaN
549937                                 1649.94
549963                                     NaN
549989                                 1037.95

         iraRef_mp8_cooking_lifetime_savings_fuel_cost  \
bldg_id
15                                                 NaN

In [14]:
if print_debug:
    # Create a sample dataframe for the heating category
    df_main_sample = create_sample_df(
        df=df_euss_am_mp8_home,
        include_groups=['base_equipment', 'costs'],
        categories=['cooking'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', 'cooking_lifetime_fuel_cost']
    )
    print(f"""
df_main_sample dataframe is created using df_euss_am_mp8_home:
-----------------------------------------------------------------------------

{df_main_sample}

-----------------------------------------------------------------------------
""")

    # Create a sample dataframe for the heating category
    df_detailed_test = create_sample_df(
        df=df_mp8_IRA_fuel_costs,
        include_groups=['base_equipment', 'costs'],
        categories=['cooking'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', f'_fuel_cost']
    )
    print(f"""
df_detailed_test dataframe is created using df_mp8_IRA_fuel_costs:
-----------------------------------------------------------------------------
          
{df_detailed_test}

-----------------------------------------------------------------------------
""")

    # # Create a sample dataframe for the waterHeating category
    # df_sample_waterHeating = create_sample_df(
    #     df=df_euss_am_mp8_home,
    #     include_groups=['base_equipment', 'costs'],
    #     categories=['waterHeating'],
    #     scenarios=['preIRA', 'iraRef'],
    #     metrics=[],
    #     mp_number=menu_mp,
    #     regex_patterns=['upgrade_waterHeating', 'valid_fuel_waterHeating', 'include_waterHeating', 'waterHeating_lifetime_fuel_cost']
    # )
    # print(df_sample_waterHeating)

    # # Create a sample dataframe for the clothesDrying category
    # df_sample_clothesDrying = create_sample_df(
    #     df=df_euss_am_mp8_home,
    #     include_groups=['base_equipment', 'costs'],
    #     categories=['clothesDrying'],
    #     scenarios=['preIRA', 'iraRef'],
    #     metrics=[],
    #     mp_number=menu_mp,
    #     regex_patterns=['upgrade_clothesDrying', 'valid_fuel_clothesDrying', 'include_clothesDrying', 'clothesDrying_lifetime_fuel_cost']
    # )
    # print(df_sample_clothesDrying)

    # # Create a sample dataframe for the cooking category
    # df_sample_cooking = create_sample_df(
    #     df=df_euss_am_mp8_home,
    #     include_groups=['base_equipment', 'costs'],
    #     categories=['cooking'],
    #     scenarios=['preIRA', 'iraRef'],
    #     metrics=[],
    #     mp_number=menu_mp,
    #     regex_patterns=['upgrade_cooking', 'valid_fuel_cooking', 'include_cooking', 'cooking_lifetime_fuel_cost']
    # )
    # print(df_sample_cooking)

# PRIVATE IMPACTS: CAPITAL COSTS
## Scenarios: No IRA and IRA-Reference

In [15]:
from cmu_tare_model.utils.inflation_adjustment import *
from cmu_tare_model.private_impact.calculations.calculate_equipment_installation_costs import (
    obtain_heating_system_specs,
    calculate_heating_installation_premium,
    calculate_installation_cost
    )
from cmu_tare_model.private_impact.calculations.calculate_equipment_replacement_costs import (
    calculate_replacement_cost
)

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for obtain_heating_system_specs function (HVAC specific):
{obtain_heating_system_specs.__doc__}

Documentation for calculate_heating_installation_premium function (HVAC specific):
{calculate_heating_installation_premium.__doc__}

Documentation for calculate_installation_cost function:
{calculate_installation_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:
{calculate_replacement_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 4 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

""")

====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for obtain_heating_system_specs function (HVAC specific):

    Extract and process heating system specifications from input dataframe.

    Calculates total heating load and extracts efficiency metrics from raw data.

    Args:
        df (pd.DataFrame): Input dataframe containing heating system data

    Returns:
        pd.DataFrame: Updated dataframe with calculated heating system specs

    Raises:
        ValueError: If dataframe is missing required columns


Documentation for calculate_heating_installation_premium function (HVAC specific):

    Calculate premium costs for heating system installation based on existing infrastructure.

    Adds costs for homes without existing central AC or with boiler systems that
    need additional modifications for heat pump installation.

    Args:
        df (pd.DataFrame): Input dataframe containing heating system data
        menu_mp (int): Menu package identifier
        cpi_ratio_2023_2013 (float): Consumer price index ratio for adjusting 2013 costs to 2023

    Returns:
        pd.DataFrame: Updated dataframe with heating installation premium costs

    Raises:
        ValueError: If dataframe is missing required columns


Documentation for calculate_installation_cost function:

    Calculate installation costs for various end-uses based on technology types, efficiency, and cost data.

    This function applies a probabilistic approach by sampling from cost distributions defined
    by progressive (10th percentile), reference (50th percentile), and conservative (90th percentile)
    cost estimates for different technology and efficiency combinations. It also applies data validation
    to ensure only valid homes are included in calculations.

    Args:
        df: DataFrame containing data for different scenarios
        cost_dict: Dictionary mapping (technology, efficiency) tuples to cost components
        menu_mp: Menu option identifier (valid values: 7, 8, 9, 10)
        end_use: Type of end-use ('heating', 'waterHeating', 'clothesDrying', 'cooking')

    Returns:
        pd.DataFrame: Updated DataFrame with calculated installation costs

    Raises:
        ValueError: If menu_mp is not valid or if cost data is missing for any technology/efficiency combination
        RuntimeError: If an unexpected error occurs during calculation

    Notes:
        This function implements the validation framework:
        1. Uses initialize_validation_tracking() to determine valid homes
        2. Creates retrofit-only series with NaN for invalid homes
        3. Calculates values only for valid homes with identifiable technology
        4. Applies final verification masking


----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:

    Calculate replacement costs for various end-uses based on fuel types, costs, and efficiency.

    This function applies probabilistic cost calculation using normal distribution sampling
    from progressive, reference, and conservative cost estimates. It also applies data validation
    to ensure only valid homes are included in calculations.

    Args:
        df: DataFrame containing data for different scenarios.
        cost_dict: Dictionary with cost information for different technology and efficiency combinations.
            Expected format: {(tech, efficiency): {'unitCost_progressive': float, 'unitCost_reference': float, ...}}
        menu_mp: Menu option identifier (valid values: 7, 8, 9, 10).
        end_use: Type of end-use ('heating', 'waterHeating', 'clothesDrying', 'cooking').

    Returns:
        pd.DataFrame: Updated DataFrame with calculated replacement costs added as new columns.

    Raises:
        ValueError: If menu_mp is invalid or if cost data is missing for technology/efficiency combinations.
        RuntimeError: If an unexpected error occurs during calculation.

    Notes:
        This function implements the validation framework:
        1. Uses initialize_validation_tracking() to determine valid homes
        2. Creates retrofit-only series with NaN for invalid homes
        3. Calculates values only for valid homes with identifiable technology
        4. Applies final verification masking


----------------------------------------------------------------------------------------------------------------------
Step 4 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

In [16]:
# Collect Capital Cost Data for different End-uses
filename = "tare_retrofit_costs_cpi.xlsx"
relative_path = os.path.join("cmu_tare_model", "data", "retrofit_costs", filename)
file_path = os.path.join(PROJECT_ROOT, relative_path)

print(f"Retrieved data for filename: {filename}")
print(f"Located at filepath: {file_path}")
print("\n")

df_heating_retrofit_costs = pd.read_excel(io=file_path, sheet_name='heating_costs')
df_waterHeating_retrofit_costs = pd.read_excel(io=file_path, sheet_name='waterHeating_costs')
df_clothesDrying_retrofit_costs = pd.read_excel(io=file_path, sheet_name='clothesDrying_costs')
df_cooking_retrofit_costs = pd.read_excel(io=file_path, sheet_name='cooking_costs')
df_enclosure_retrofit_costs = pd.read_excel(io=file_path, sheet_name='enclosure_upgrade_costs')

Retrieved data for filename: tare_retrofit_costs_cpi.xlsx
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\retrofit_costs\tare_retrofit_costs_cpi.xlsx

### Space Heating and No Enclosure Upgrade

#### Space Heating Capital Costs

In [17]:
print("""
========================== Capital Costs: Space Heating ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...
""")

# Columns to update
cost_columns = [
    'unitCost_progressive', 'unitCost_reference', 'unitCost_conservative',
    'cost_per_kBtuh_progressive', 'cost_per_kBtuh_reference', 'cost_per_kBtuh_conservative',
    'otherCost_progressive', 'otherCost_reference', 'otherCost_conservative'
]

# Update each cost column by multiplying with cpi_ratio and cost_multiplier
for column in cost_columns:
    df_heating_retrofit_costs[column] = round((df_heating_retrofit_costs[column] * df_heating_retrofit_costs['cpi_ratio'] * df_heating_retrofit_costs['cost_multiplier']), 2)

# Creating a dictionary from the DataFrame
dict_heating_equipment_cost = df_heating_retrofit_costs.set_index(['technology', 'efficiency']).to_dict(orient='index')

# Call the function and obtain equipment specifications
print("Obtaining heating system specs ...")
df_euss_am_mp8_home = obtain_heating_system_specs(df=df_euss_am_mp8_home)

# calculate_installation_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Retrofit Upgrade: Heat Pump for Space Heating (No Enclosure Upgrade) ...")
df_euss_am_mp8_home = calculate_installation_cost(df=df_euss_am_mp8_home,
                                                  cost_dict=dict_heating_equipment_cost,
                                                  menu_mp=menu_mp,
                                                  end_use='heating')

# calculate_replacement_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...")
df_euss_am_mp8_home = calculate_replacement_cost(df=df_euss_am_mp8_home,
                                                 cost_dict=dict_heating_equipment_cost,
                                                 menu_mp=menu_mp,
                                                 end_use='heating')

# Call the function and calculate installation premium based on existing housing characteristics
# calculate_heating_installation_premium(df, menu_mp, cpi_ratio_2023_2013)
print("Calculating Space Heating Specific Premiums (Ex: Removing Hydronic Boiler) ...")
df_euss_am_mp8_home = calculate_heating_installation_premium(df=df_euss_am_mp8_home,
                                                             menu_mp=menu_mp,
                                                             cpi_ratio_2023_2013=cpi_ratio_2023_2013)

# Display the df
print(df_euss_am_mp8_home)

========================== Capital Costs: Space Heating ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...

Obtaining heating system specs ...
Calculating Cost of Retrofit Upgrade: Heat Pump for Space Heating (No Enclosure Upgrade) ...
Starting heating installation cost calculation with validation framework
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
Found 13849 valid homes out of 17990 for heating installation
After tech filtering: 13849 homes remain valid for heating installation

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...
Starting heating replacement cost calculation with validation framework
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
Found 13849 valid homes out of 17990 for heating replacement
After tech filtering: 13849 homes remain valid for heating replacement

Verifying masking for all calculated columns:
Masking 2 columns for category 'heating'
Calculating Space Heating Specific Premiums (Ex: Removing Hydronic Boiler) ...
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        iraRef_mp8_cooking_lifetime_savings_fuel_cost  \
bldg_id
15                                                NaN
79                                                NaN
119                                           -624.35
122                                               NaN
150                                               NaN
...                                               ...
549882                                            NaN
549915                                            NaN
549937                                        -847.65
549963                                            NaN
549989                                         653.60

        baseline_cooking_lifetime_fuel_cost total_heating_load_kBtuh  \
bldg_id
15                                      NaN                    40.28
79                                      NaN                   123.97
119                                  589.84                    93.27
122                                     NaN                   335.38
150                                     NaN                   114.81
...                                     ...                      ...
549882                                  NaN                   122.49
549915                                  NaN                   116.49
549937                               802.29                    58.90
549963                                  NaN                    98.06
549989                              1691.55                    41.04

        baseline_AFUE baseline_SEER  baseline_HSPF  ugrade_newInstall_HSPF  \
bldg_id
15                NaN          13.0            7.7                    13.0
79               80.0           NaN            NaN                    13.0
119              80.0           NaN            NaN                    13.0
122              92.5           NaN            NaN                    13.0
150             100.0           NaN            NaN                    14.0
...               ...           ...            ...                     ...
549882           68.0           NaN            NaN                    14.0
549915          100.0           NaN            NaN                    13.0
549937           92.5           NaN            NaN                    13.0
549963           80.0           NaN            NaN                    13.0
549989           80.0           NaN            NaN                    13.0

        mp8_heating_installationCost mp8_heating_replacementCost  \
bldg_id
15                               NaN                         NaN
79                          34036.98                     5994.95
119                         28913.55                     3745.62
122                         61066.77                     7073.14
150                         21333.99                     9601.33
...                              ...                         ...
549882                           NaN                         NaN
549915                      28044.73                     9711.21
549937                      16871.76                     3570.33
549963                      33869.61                     3770.05
549989                      20455.05                     5572.00

        mp8_heating_installation_premium
bldg_id
15                                   0.0
79                                   0.0
119                                  0.0
122                                  0.0
150                                  0.0
...                                  ...
549882                               0.0
549915                               0.0
549937                               0.0
549963                               0.0
549989                               0.0

[17990 rows x 395 columns]

In [51]:
df_euss_am_mp8_home

,square_footage,census_region,census_division,census_division_recs,building_america_climate_zone,reeds_balancing_area,gea_region,state,city,urbanicity,...,household_income,census_area_medianIncome,percent_AMI,income_level,lmi_or_mui,household_variable_discount_rate,mp8_heating_rebate_amount,mp8_waterHeating_rebate_amount,mp8_clothesDrying_rebate_amount,mp8_cooking_rebate_amount
bldg_id,,,,,,,,,,,,,,,,,,,,,
15,333.0,Northeast,Middle Atlantic,Middle Atlantic,Mixed-Humid,122,RFCEc,PA,Philadelphia,Urban,...,39052.35,58843.49,66.37,Low-Income,LMI,0.075753,NaN,1750.00,NaN,NaN
79,1220.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,122,RFCEc,PA,Not in a census Place,Suburban,...,38627.02,59989.82,64.39,Low-Income,LMI,0.077073,8000.0,1750.00,840.00,NaN
119,2152.0,Northeast,Middle Atlantic,Middle Atlantic,Mixed-Humid,122,RFCEc,PA,Not in a census Place,Suburban,...,114217.07,87416.17,130.66,Moderate-Income,LMI,0.032893,8000.0,1660.92,840.00,586.04
122,2176.0,Northeast,Middle Atlantic,Middle Atlantic,Mixed-Humid,122,RFCEc,PA,In another census Place,Suburban,...,29593.91,87416.17,33.85,Low-Income,LMI,0.097433,8000.0,1750.00,840.00,NaN
150,1690.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,122,RFCEc,PA,In another census Place,Rural,...,58985.88,63311.13,93.17,Moderate-Income,LMI,0.057887,8000.0,1212.63,840.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549882,1202.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,122,RFCEc,PA,Not in a census Place,Suburban,...,54733.52,58184.44,94.07,Moderate-Income,LMI,0.057287,NaN,1370.93,738.68,NaN
549915,2176.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,122,RFCEc,PA,Lancaster,Suburban,...,102170.22,74245.44,137.61,Moderate-Income,LMI,0.028260,8000.0,1750.00,840.00,NaN
549937,885.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,115,RFCWc,PA,In another census Place,Rural,...,84635.18,56766.37,149.09,Moderate-Income,LMI,0.020607,8000.0,1122.06,840.00,840.00
549963,1690.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,115,RFCWc,PA,In another census Place,Suburban,...,88794.04,74300.62,119.51,Moderate-Income,LMI,0.040327,8000.0,1610.15,840.00,NaN
549989,1220.0,Northeast,Middle Atlantic,Middle Atlantic,Cold,122,RFCEc,PA,Not in a census Place,Rural,...,83293.16,54719.44,152.22,Middle-to-Upper-Income,MUI,0.020000,0.0,0.00,0.00,0.00

In [57]:
if print_debug:
    # Create a sample dataframe for the heating category
    df_sample_heating = create_sample_df(
        df=df_euss_am_mp8_home_ap2,
        include_groups=['base_equipment'],
        categories=['heating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        # regex_patterns=['valid_fuel_heating', 'include_heating', 'baseline_AFUE', 'baseline_SEER', 'baseline_HSPF', 
        #                 'hvac_heating_efficiency', 'upgrade_hvac_', 'upgrade_heating','ugrade_newInstall_HSPF',
        #                 ]
        regex_patterns=['upgrade_heating', 'valid_fuel_heating', 'include_heating', 'heating_installation_cost',
                        'heating_replacement_cost', 'heating_total_capital_cost', 'heating_net_capital_cost',
                        'heating_private_npv'])
    print(df_sample_heating)

        base_heating_fuel                         heating_type  \
bldg_id
15            Electricity                     Electricity ASHP
79               Fuel Oil                Fuel Oil Fuel Furnace
119           Natural Gas             Natural Gas Fuel Furnace
122              Fuel Oil                Fuel Oil Fuel Furnace
150           Electricity                Electricity Baseboard
...                   ...                                  ...
549882        Natural Gas  Natural Gas Fuel Wall/Floor Furnace
549915        Electricity         Electricity Electric Furnace
549937        Natural Gas             Natural Gas Fuel Furnace
549963        Natural Gas             Natural Gas Fuel Furnace
549989           Fuel Oil                Fuel Oil Fuel Furnace

         base_electricity_heating_consumption  \
bldg_id
15                                        NaN
79                                       0.00
119                                      0.00
122                                      0.00
150                                  20677.34
...                                       ...
549882                                    NaN
549915                               22397.66
549937                                   0.00
549963                                   0.00
549989                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
15                                    NaN
79                               36921.09
119                                  0.00
122                              40613.20
150                                  0.00
...                                   ...
549882                                NaN
549915                               0.00
549937                               0.00
549963                               0.00
549989                           15981.46

         base_naturalGas_heating_consumption  \
bldg_id
15                                       NaN
79                                      0.00
119                                 17917.78
122                                     0.00
150                                     0.00
...                                      ...
549882                                   NaN
549915                                  0.00
549937                              15632.70
549963                              32303.17
549989                                  0.00

         base_propane_heating_consumption  valid_fuel_heating  \
bldg_id
15                                    NaN                True
79                                    0.0                True
119                                   0.0                True
122                                   0.0                True
150                                   0.0                True
...                                   ...                 ...
549882                                NaN                True
549915                                0.0                True
549937                                0.0                True
549963                                0.0                True
549989                                0.0                True

         include_heating                baseline_heating_type  \
bldg_id
15                 False                     Electricity ASHP
79                  True                Fuel Oil Fuel Furnace
119                 True             Natural Gas Fuel Furnace
122                 True                Fuel Oil Fuel Furnace
150                 True                Electricity Baseboard
...                  ...                                  ...
549882             False  Natural Gas Fuel Wall/Floor Furnace
549915              True         Electricity Electric Furnace
549937              True             Natural Gas Fuel Furnace
549963              True             Natural Gas Fuel Furnace
549989              True                Fuel Oil Fuel Furnace

                  hvac_heating_type_and_fuel  \
bldg_id
15                          Electricity ASHP
79                     Fuel Oil Fuel Furnace
119                 Natural Gas Fuel Furnace
122                    Fuel Oil Fuel Furnace
150                    Electricity Baseboard
...                                      ...
549882   Natural Gas Fuel Wall/Floor Furnace
549915          Electricity Electric Furnace
549937              Natural Gas Fuel Furnace
549963              Natural Gas Fuel Furnace
549989                 Fuel Oil Fuel Furnace

         preIRA_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                    -10660.00
119                                   -26828.60
122                                   -37766.61
150                                     6490.48
...                                         ...
549882                                      NaN
549915                                  5628.09
549937                                -16290.49
549963                                -30187.37
549989                                 -5407.59

         preIRA_mp8_heating_private_npv_moreWTP  \
bldg_id
15                                          NaN
79                                     -4665.05
119                                   -23082.98
122                                   -30693.47
150                                    16091.81
...                                         ...
549882                                      NaN
549915                                 15339.30
549937                                -12720.16
549963                                -26417.32
549989                                   164.41

         iraRef_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                     -2498.14
119                                   -18716.19
122                                   -29613.61
150                                    14600.32
...                                         ...
549882                                      NaN
549915                                 13826.61
549937                                 -8154.23
549963                                -21998.20
549989                                 -5317.92

         iraRef_mp8_heating_private_npv_moreWTP
bldg_id
15                                          NaN
79                                      3496.81
119                                   -14970.57
122                                   -22540.47
150                                    24201.65
...                                         ...
549882                                      NaN
549915                                 23537.82
549937                                 -4583.90
549963                                -18228.15
549989                                   254.08

[17990 rows x 14 columns]

### Water Heating

In [19]:
print("""
========================== Capital Costs: Water Heating ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...
""")

cost_columns = [
    'unitCost_progressive', 'unitCost_reference', 'unitCost_conservative',
    'cost_per_gallon_progressive', 'cost_per_gallon_reference', 'cost_per_gallon_conservative',
]

# Update each cost column by multiplying with cpi_ratio and cost_multiplier
for column in cost_columns:
    df_waterHeating_retrofit_costs[column] = round((df_waterHeating_retrofit_costs[column] * df_waterHeating_retrofit_costs['cpi_ratio'] * df_waterHeating_retrofit_costs['cost_multiplier']), 2)

# Creating a dictionary from the DataFrame
dict_waterHeating_equipment_cost = df_waterHeating_retrofit_costs.set_index(['technology', 'efficiency']).to_dict(orient='index')
# dict_waterHeating_equipment_cost

# calculate_installation_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Retrofit Upgrade: Electric Heat Pump Water Heater ...")
df_euss_am_mp8_home = calculate_installation_cost(df=df_euss_am_mp8_home,
                                                  cost_dict=dict_waterHeating_equipment_cost,
                                                  menu_mp=menu_mp,
                                                  end_use='waterHeating')

# calculate_replacement_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...")
df_euss_am_mp8_home = calculate_replacement_cost(df=df_euss_am_mp8_home,
                                                 cost_dict=dict_waterHeating_equipment_cost,
                                                 menu_mp=menu_mp,
                                                 end_use='waterHeating')

# Display the df
print(df_euss_am_mp8_home)

========================== Capital Costs: Water Heating ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...

Calculating Cost of Retrofit Upgrade: Electric Heat Pump Water Heater ...
Starting waterHeating installation cost calculation with validation framework
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)
Found 17255 valid homes out of 17990 for waterHeating installation
After tech filtering: 17255 homes remain valid for waterHeating installation

Verifying masking for all calculated columns:
Masking 1 columns for category 'waterHeating'
Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...
Starting waterHeating replacement cost calculation with validation framework
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)
Found 17255 valid homes out of 17990 for waterHeating replacement
After tech filtering: 17255 homes remain valid for waterHeating replacement

Verifying masking for all calculated columns:
Masking 2 columns for category 'waterHeating'
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ... total_heating_load_kBtuh  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...                    40.28
79         Not in a census Place   Suburban  ...                   123.97
119        Not in a census Place   Suburban  ...                    93.27
122      In another census Place   Suburban  ...                   335.38
150      In another census Place      Rural  ...                   114.81
...                          ...        ...  ...                      ...
549882     Not in a census Place   Suburban  ...                   122.49
549915                 Lancaster   Suburban  ...                   116.49
549937   In another census Place      Rural  ...                    58.90
549963   In another census Place   Suburban  ...                    98.06
549989     Not in a census Place      Rural  ...                    41.04

        baseline_AFUE baseline_SEER baseline_HSPF ugrade_newInstall_HSPF  \
bldg_id
15                NaN          13.0           7.7                   13.0
79               80.0           NaN           NaN                   13.0
119              80.0           NaN           NaN                   13.0
122              92.5           NaN           NaN                   13.0
150             100.0           NaN           NaN                   14.0
...               ...           ...           ...                    ...
549882           68.0           NaN           NaN                   14.0
549915          100.0           NaN           NaN                   13.0
549937           92.5           NaN           NaN                   13.0
549963           80.0           NaN           NaN                   13.0
549989           80.0           NaN           NaN                   13.0

         mp8_heating_installationCost  mp8_heating_replacementCost  \
bldg_id
15                                NaN                          NaN
79                           34036.98                      5994.95
119                          28913.55                      3745.62
122                          61066.77                      7073.14
150                          21333.99                      9601.33
...                               ...                          ...
549882                            NaN                          NaN
549915                       28044.73                      9711.21
549937                       16871.76                      3570.33
549963                       33869.61                      3770.05
549989                       20455.05                      5572.00

        mp8_heating_installation_premium mp8_waterHeating_installationCost  \
bldg_id
15                                   0.0                           2377.39
79                                   0.0                           3215.34
119                                  0.0                           3321.85
122                                  0.0                           2813.76
150                                  0.0                           2425.27
...                                  ...                               ...
549882                               0.0                           2741.87
549915                               0.0                           4739.66
549937                               0.0                           2244.12
549963                               0.0                           3220.30
549989                               0.0                           3045.09

        mp8_waterHeating_replacementCost
bldg_id
15                               1661.24
79                               1661.24
119                              1891.48
122                              2862.44
150                              1073.99
...                                  ...
549882                           1661.24
549915                           1138.11
549937                           1891.48
549963                           1661.24
549989                           2707.56

[17990 rows x 397 columns]

### Clothes Drying

In [20]:
print("""
========================== Capital Costs: Clothes Drying ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ... 
""")

# Columns to update
cost_columns = [
    'unitCost_progressive', 'unitCost_reference', 'unitCost_conservative',
]
 
# Update each cost column by multiplying with cpi_ratio and cost_multiplier
for column in cost_columns:
    df_clothesDrying_retrofit_costs[column] = round((df_clothesDrying_retrofit_costs[column] * df_clothesDrying_retrofit_costs['cpi_ratio'] * df_clothesDrying_retrofit_costs['cost_multiplier']), 2)

# Creating a dictionary from the DataFrame
dict_clothesDrying_equipment_cost = df_clothesDrying_retrofit_costs.set_index(['technology', 'efficiency']).to_dict(orient='index')
# dict_clothesDrying_equipment_cost

# calculate_installation_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Retrofit Upgrade: Ventless Heat Pump Clothes Dryer ...")
df_euss_am_mp8_home = calculate_installation_cost(df=df_euss_am_mp8_home,
                                                  cost_dict=dict_clothesDrying_equipment_cost,
                                                  menu_mp=menu_mp,
                                                  end_use='clothesDrying')


# calculate_replacement_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...")
df_euss_am_mp8_home = calculate_replacement_cost(df=df_euss_am_mp8_home,
                                                 cost_dict=dict_clothesDrying_equipment_cost,
                                                 menu_mp=menu_mp,
                                                 end_use='clothesDrying')

# Display the df
print(df_euss_am_mp8_home)

========================== Capital Costs: Clothes Drying ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...

Calculating Cost of Retrofit Upgrade: Ventless Heat Pump Clothes Dryer ...
Starting clothesDrying installation cost calculation with validation framework
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)
Found 16238 valid homes out of 17990 for clothesDrying installation
After tech filtering: 16238 homes remain valid for clothesDrying installation

Verifying masking for all calculated columns:
Masking 1 columns for category 'clothesDrying'
Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...
Starting clothesDrying replacement cost calculation with validation framework
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)
Found 16238 valid homes out of 17990 for clothesDrying replacement
After tech filtering: 16238 homes remain valid for clothesDrying replacement

Verifying masking for all calculated columns:
Masking 2 columns for category 'clothesDrying'
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ... baseline_SEER baseline_HSPF  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...          13.0           7.7
79         Not in a census Place   Suburban  ...           NaN           NaN
119        Not in a census Place   Suburban  ...           NaN           NaN
122      In another census Place   Suburban  ...           NaN           NaN
150      In another census Place      Rural  ...           NaN           NaN
...                          ...        ...  ...           ...           ...
549882     Not in a census Place   Suburban  ...           NaN           NaN
549915                 Lancaster   Suburban  ...           NaN           NaN
549937   In another census Place      Rural  ...           NaN           NaN
549963   In another census Place   Suburban  ...           NaN           NaN
549989     Not in a census Place      Rural  ...           NaN           NaN

        ugrade_newInstall_HSPF mp8_heating_installationCost  \
bldg_id
15                        13.0                          NaN
79                        13.0                     34036.98
119                       13.0                     28913.55
122                       13.0                     61066.77
150                       14.0                     21333.99
...                        ...                          ...
549882                    14.0                          NaN
549915                    13.0                     28044.73
549937                    13.0                     16871.76
549963                    13.0                     33869.61
549989                    13.0                     20455.05

        mp8_heating_replacementCost  mp8_heating_installation_premium  \
bldg_id
15                              NaN                               0.0
79                          5994.95                               0.0
119                         3745.62                               0.0
122                         7073.14                               0.0
150                         9601.33                               0.0
...                             ...                               ...
549882                          NaN                               0.0
549915                      9711.21                               0.0
549937                      3570.33                               0.0
549963                      3770.05                               0.0
549989                      5572.00                               0.0

         mp8_waterHeating_installationCost mp8_waterHeating_replacementCost  \
bldg_id
15                                 2377.39                          1661.24
79                                 3215.34                          1661.24
119                                3321.85                          1891.48
122                                2813.76                          2862.44
150                                2425.27                          1073.99
...                                    ...                              ...
549882                             2741.87                          1661.24
549915                             4739.66                          1138.11
549937                             2244.12                          1891.48
549963                             3220.30                          1661.24
549989                             3045.09                          2707.56

        mp8_clothesDrying_installationCost mp8_clothesDrying_replacementCost
bldg_id
15                                     NaN                               NaN
79                                 2453.54                            994.06
119                                2625.60                           1307.98
122                                2758.81                            994.06
150                                2796.83                            994.06
...                                    ...                               ...
549882                             1477.37                            994.06
549915                             2360.05                            994.06
549937                             2459.14                           1307.98
549963                             2141.62                            994.06
549989                             2596.08                            994.06

[17990 rows x 399 columns]

### Cooking

In [21]:
print("""
========================== Capital Costs: Cooking ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...      
""")

# Columns to update
cost_columns = [
    'unitCost_progressive', 'unitCost_reference', 'unitCost_conservative',
]
 
# Update each cost column by multiplying with cpi_ratio and cost_multiplier
for column in cost_columns:
    df_cooking_retrofit_costs[column] = round((df_cooking_retrofit_costs[column] * df_cooking_retrofit_costs['cpi_ratio'] * df_cooking_retrofit_costs['cost_multiplier']), 2)

# Creating a dictionary from the DataFrame
dict_cooking_equipment_cost = df_cooking_retrofit_costs.set_index(['technology', 'efficiency']).to_dict(orient='index')
# dict_cooking_equipment_cost

# calculate_installation_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Retrofit Upgrade: Electric Resistance Range ...")
df_euss_am_mp8_home = calculate_installation_cost(df=df_euss_am_mp8_home,
                                                  cost_dict=dict_cooking_equipment_cost,
                                                  menu_mp=menu_mp,
                                                  end_use='cooking')

# calculate_replacement_cost(df, cost_dict, menu_mp, end_use)
print("Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...")
df_euss_am_mp8_home = calculate_replacement_cost(df=df_euss_am_mp8_home,
                                                 cost_dict=dict_cooking_equipment_cost,
                                                 menu_mp=menu_mp,
                                                 end_use='cooking')

# Display the df
print(df_euss_am_mp8_home)

========================== Capital Costs: Cooking ==========================

Obtaining Capital Cost Data from Retrofit Cost Spreadsheet ...

Calculating Cost of Retrofit Upgrade: Electric Resistance Range ...
Starting cooking installation cost calculation with validation framework
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)
Found 8974 valid homes out of 17990 for cooking installation
After tech filtering: 8974 homes remain valid for cooking installation

Verifying masking for all calculated columns:
Masking 1 columns for category 'cooking'
Calculating Cost of Replacing Existing Equipment with Similar Model/Efficiency ...
Starting cooking replacement cost calculation with validation framework
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)
Found 8974 valid homes out of 17990 for cooking replacement
After tech filtering: 8974 homes remain valid for cooking replacement

Verifying masking for all calculated columns:
Masking 2 columns for category 'cooking'
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ... ugrade_newInstall_HSPF  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...                   13.0
79         Not in a census Place   Suburban  ...                   13.0
119        Not in a census Place   Suburban  ...                   13.0
122      In another census Place   Suburban  ...                   13.0
150      In another census Place      Rural  ...                   14.0
...                          ...        ...  ...                    ...
549882     Not in a census Place   Suburban  ...                   14.0
549915                 Lancaster   Suburban  ...                   13.0
549937   In another census Place      Rural  ...                   13.0
549963   In another census Place   Suburban  ...                   13.0
549989     Not in a census Place      Rural  ...                   13.0

        mp8_heating_installationCost mp8_heating_replacementCost  \
bldg_id
15                               NaN                         NaN
79                          34036.98                     5994.95
119                         28913.55                     3745.62
122                         61066.77                     7073.14
150                         21333.99                     9601.33
...                              ...                         ...
549882                           NaN                         NaN
549915                      28044.73                     9711.21
549937                      16871.76                     3570.33
549963                      33869.61                     3770.05
549989                      20455.05                     5572.00

        mp8_heating_installation_premium mp8_waterHeating_installationCost  \
bldg_id
15                                   0.0                           2377.39
79                                   0.0                           3215.34
119                                  0.0                           3321.85
122                                  0.0                           2813.76
150                                  0.0                           2425.27
...                                  ...                               ...
549882                               0.0                           2741.87
549915                               0.0                           4739.66
549937                               0.0                           2244.12
549963                               0.0                           3220.30
549989                               0.0                           3045.09

         mp8_waterHeating_replacementCost  mp8_clothesDrying_installationCost  \
bldg_id
15                                1661.24                                 NaN
79                                1661.24                             2453.54
119                               1891.48                             2625.60
122                               2862.44                             2758.81
150                               1073.99                             2796.83
...                                   ...                                 ...
549882                            1661.24                             1477.37
549915                            1138.11                             2360.05
549937                            1891.48                             2459.14
549963                            1661.24                             2141.62
549989                            2707.56                             2596.08

        mp8_clothesDrying_replacementCost mp8_cooking_installationCost  \
bldg_id
15                                    NaN                          NaN
79                                 994.06                          NaN
119                               1307.98                      1172.08
122                                994.06                          NaN
150                                994.06                          NaN
...                                   ...                          ...
549882                             994.06                          NaN
549915                             994.06                          NaN
549937                            1307.98                      1834.55
549963                             994.06                          NaN
549989                             994.06                      1433.35

        mp8_cooking_replacementCost
bldg_id
15                              NaN
79                              NaN
119                         1072.54
122                             NaN
150                             NaN
...                             ...
549882                          NaN
549915                          NaN
549937                      1072.54
549963                          NaN
549989                      1072.54

[17990 rows x 401 columns]

 ## Calculate Rebate Amounts (Applicable to IRA-Reference)

In [22]:
from cmu_tare_model.private_impact.data_processing.determine_rebate_eligibility_and_amount import calculate_percent_AMI, calculate_rebateIRA
from cmu_tare_model.utils.discounting import calculate_variable_discount_rate
print(f"""
====================================================================================================================================================================
CALCULATE HOUSEHOLD PERCENT AREA MEDIAN INCOME (%AMI) AND REBATE ELIGIBILITY/AMOUNTS
====================================================================================================================================================================
determine_rebate_eligibility_and_amount.py file contains the function definitions for calculating rebate amounts and determining household %AMI.
process_income_data_for_rebates.py file contains additional information on data sources and procedures used to process data for determine_rebate_eligibility_and_amount.py file.

Documentation for calculate_percent_AMI function:
{calculate_percent_AMI.__doc__}

Documentation for calculate_rebateIRA function:
{calculate_rebateIRA.__doc__}

Documentation for calculate_variable_discount_rate function:
{calculate_variable_discount_rate.__doc__}
-------------------------------------------------------

""")

# Determine Percent AMI and Rebate Amounts
# This needs to be done before running the calculate_percent_AMI function
df_euss_am_mp8_home = df_euss_am_mp8_home.copy()

# calculate_percent_AMI(df_results_IRA, df_county_medianIncome):
df_euss_am_mp8_home = calculate_percent_AMI(df_results_IRA=df_euss_am_mp8_home)

# calculate_variable_discount_rate(df):
df_euss_am_mp8_home = calculate_variable_discount_rate(df=df_euss_am_mp8_home)

print("Calculating rebate amounts for Space Heating ...")
df_euss_am_mp8_home = calculate_rebateIRA(df_results_IRA=df_euss_am_mp8_home,
                                          category="heating",
                                          menu_mp=menu_mp)

print("Calculating rebate amounts for Water Heating ...")
df_euss_am_mp8_home = calculate_rebateIRA(df_results_IRA=df_euss_am_mp8_home,
                                          category="waterHeating",
                                          menu_mp=menu_mp)

print("Calculating rebate amounts for Clothes Drying ...")
df_euss_am_mp8_home = calculate_rebateIRA(df_results_IRA=df_euss_am_mp8_home,
                                          category="clothesDrying",
                                          menu_mp=menu_mp)

print("Calculating rebate amounts for Cooking ...")
df_euss_am_mp8_home = calculate_rebateIRA(df_results_IRA=df_euss_am_mp8_home,
                                          category="cooking",
                                          menu_mp=menu_mp)

print(f"""
====================================================================================================================================================================
DATAFRAME: df_euss_am_mp8_home AFTER CALCULATING REBATE AMOUNTS
{df_euss_am_mp8_home}

====================================================================================================================================================================
""")

====================================================================================================================================================================
CALCULATE HOUSEHOLD PERCENT AREA MEDIAN INCOME (%AMI) AND REBATE ELIGIBILITY/AMOUNTS
====================================================================================================================================================================
determine_rebate_eligibility_and_amount.py file contains the function definitions for calculating rebate amounts and determining household %AMI.
process_income_data_for_rebates.py file contains additional information on data sources and procedures used to process data for determine_rebate_eligibility_and_amount.py file.

Documentation for calculate_percent_AMI function:

    Calculates the percentage of Area Median Income (AMI) and assigns income level designations.

    This function processes household income data, calculates the percentage relative to
    Area Median Income, and creates two categorical classifications:
    1. Detailed income level categories (Low, Moderate, Middle-to-Upper Income)
    2. Binary Low-to-Moderate Income (LMI) or Middle-to-Upper Income (MUI) classification for policy analysis

    Args:
        df_results_IRA: Input DataFrame containing income information with columns:
                       - 'income': Income data (ranges or values)
                       - Other demographic/geographic columns for median income lookup

    Returns:
        DataFrame: Modified DataFrame with additional columns:
                  - 'household_income': Calculated household income (float)
                  - 'census_area_medianIncome': Area median income (float)
                  - 'percent_AMI': Percentage of AMI (float)
                  - 'income_level': Detailed income category (str)
                  - 'lmi_or_mui': Binary Low-to-Moderate Income (LMI) or Middle-to-Upper Income (MUI) (str)

    Raises:
        ValueError: If an unexpected income format is encountered during processing


Documentation for calculate_rebateIRA function:

    Calculates rebate amounts for different end-uses based on income designation.

    This function applies the appropriate rebate percentage based on income designation
    and applies data validation to ensure only valid homes are considered for rebates.
    Rebates are calculated at different rates:
    - 100% coverage rate for low-income homes (up to maximum rebate amount)
    - 50% coverage rate for moderate-income homes (up to maximum rebate amount)
    - 0% coverage rate for middle-to-upper-income homes

    Args:
        df_results_IRA: DataFrame containing income designations and cost data
        category: Equipment category (e.g., 'heating', 'waterHeating')
        menu_mp: Measure package identifier

    Returns:
        Updated DataFrame with calculated rebate amounts

    Notes:
        This function implements the validation framework:
        1. Uses initialize_validation_tracking() to determine valid homes
        2. Creates retrofit-only series with NaN for invalid homes
        3. Calculates rebates only for valid homes
        4. Applies final verification masking


Documentation for calculate_variable_discount_rate function:

    Calculate household-specific discount rates based on AMI percentage.

    Variable discount rate is inversely proportional to AMI:
    - Values below 0% AMI get 12%, above 150% AMI get 2%.
    - At 0% AMI: 12% discount rate (highest, reflecting financial constraints)
    - At 150%+ AMI: 2% discount rate (lowest, same as public rate)
    - Linear interpolation between these bounds. Clamping behavior is built into np.interp.

    Args:
        df (pd.DataFrame): DataFrame containing 'percent_AMI' column with household AMI percentages.

    Returns:
        pd.DataFrame: DataFrame with additional column 'household_variable_discount_rate'.

    Raises:
        ValueError: If 'percent_AMI' column is missing from DataFrame.

    Example:
        >>> df = pd.DataFrame({'percent_AMI': [0, 75, 150, 200]})
        >>> result = calculate_variable_discount_rate(df)
        >>> result['household_variable_discount_rate'].tolist()
        [0.12, 0.07, 0.02, 0.02]  # Linear interpolation, capped at 150% AMI

-------------------------------------------------------


Calculating rebate amounts for Space Heating ...
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Calculating rebate amounts for Water Heating ...
Measure package calculation for waterHeating:
  - 17255 homes have valid data
  - 17872 homes will receive retrofits
  - 17255 homes have both valid data AND will receive retrofits
  - 735 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Calculating rebate amounts for Clothes Drying ...
Measure package calculation for clothesDrying:
  - 16238 homes have valid data
  - 16238 homes will receive retrofits
  - 16238 homes have both valid data AND will receive retrofits
  - 1752 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Calculating rebate amounts for Cooking ...
Measure package calculation for cooking:
  - 8974 homes have valid data
  - 8974 homes will receive retrofits
  - 8974 homes have both valid data AND will receive retrofits
  - 9016 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

====================================================================================================================================================================
DATAFRAME: df_euss_am_mp8_home AFTER CALCULATING REBATE AMOUNTS
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ... household_income  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...         39052.35
79         Not in a census Place   Suburban  ...         38627.02
119        Not in a census Place   Suburban  ...        114217.07
122      In another census Place   Suburban  ...         29593.91
150      In another census Place      Rural  ...         58985.88
...                          ...        ...  ...              ...
549882     Not in a census Place   Suburban  ...         54733.52
549915                 Lancaster   Suburban  ...        102170.22
549937   In another census Place      Rural  ...         84635.18
549963   In another census Place   Suburban  ...         88794.04
549989     Not in a census Place      Rural  ...         83293.16

        census_area_medianIncome percent_AMI            income_level  \
bldg_id
15                      58843.49       66.37              Low-Income
79                      59989.82       64.39              Low-Income
119                     87416.17      130.66         Moderate-Income
122                     87416.17       33.85              Low-Income
150                     63311.13       93.17         Moderate-Income
...                          ...         ...                     ...
549882                  58184.44       94.07         Moderate-Income
549915                  74245.44      137.61         Moderate-Income
549937                  56766.37      149.09         Moderate-Income
549963                  74300.62      119.51         Moderate-Income
549989                  54719.44      152.22  Middle-to-Upper-Income

        lmi_or_mui  household_variable_discount_rate  \
bldg_id
15             LMI                          0.075753
79             LMI                          0.077073
119            LMI                          0.032893
122            LMI                          0.097433
150            LMI                          0.057887
...            ...                               ...
549882         LMI                          0.057287
549915         LMI                          0.028260
549937         LMI                          0.020607
549963         LMI                          0.040327
549989         MUI                          0.020000

         mp8_heating_rebate_amount mp8_waterHeating_rebate_amount  \
bldg_id
15                             NaN                        1750.00
79                          8000.0                        1750.00
119                         8000.0                        1660.92
122                         8000.0                        1750.00
150                         8000.0                        1212.63
...                            ...                            ...
549882                         NaN                        1370.93
549915                      8000.0                        1750.00
549937                      8000.0                        1122.06
549963                      8000.0                        1610.15
549989                         0.0                           0.00

         mp8_clothesDrying_rebate_amount mp8_cooking_rebate_amount
bldg_id
15                                   NaN                       NaN
79                                840.00                       NaN
119                               840.00                    586.04
122                               840.00                       NaN
150                               840.00                       NaN
...                                  ...                       ...
549882                            738.68                       NaN
549915                            840.00                       NaN
549937                            840.00                    840.00
549963                            840.00                       NaN
549989                              0.00                      0.00

[17990 rows x 411 columns]

====================================================================================================================================================================

# SCENARIO ANALYSIS: 
## "No Inflation Reduction Act" and "AEO2023 Reference Case"
## Public Impact, Private Impact and Adoption Potential (Degree of Adoption Feasibility)

In [23]:
from cmu_tare_model.private_impact.calculate_lifetime_private_impact import calculate_private_npv
from cmu_tare_model.public_impact.calculate_lifetime_public_impact_sensitivity import calculate_public_npv
from cmu_tare_model.adoption_potential.determine_adoption_potential_sensitivity import *

print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS: OVERVIEW
====================================================================================================================================================================

-------------------------------------------------------
PUBLIC IMPACTS: CLIMATE AND HEALTH
-------------------------------------------------------
calculate_lifetime_public_impact.py file contains the definition for the calculate_public_npv function.
Additional information on emissions/damage factor lookups as well as marginal damages calculation methods can be found in the public_impact folder. 
      
Documentation for the calculate_public_NPV function:
{calculate_public_npv.__doc__} 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
PRIVATE IMPACTS: LIFETIME CAPITAL COSTS AND SAVINGS
--------------------------------------------------------
calculate_lifetime_private_impact.py file contains the definition for the calculate_private_npv function.
Additional information on fuel price lookups as well as capital costs calculation methods can be found in the private_impact folder.

Documentation for the calculate_private_npv function:
{calculate_private_npv.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
ADOPTION POTENTIAL
--------------------------------------------------------
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
Documentation for the adoption_decision function:
{adoption_decision.__doc__}

Documentation for the calculate_climate_only_adoption_robust function:
{calculate_climate_only_adoption_robust.__doc__}

Documentation for the calculate_health_only_adoption_robust function:
{calculate_health_only_adoption_robust.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

""")

====================================================================================================================================================================
SCENARIO ANALYSIS: OVERVIEW
====================================================================================================================================================================

-------------------------------------------------------
PUBLIC IMPACTS: CLIMATE AND HEALTH
-------------------------------------------------------
calculate_lifetime_public_impact.py file contains the definition for the calculate_public_npv function.
Additional information on emissions/damage factor lookups as well as marginal damages calculation methods can be found in the public_impact folder.

Documentation for the calculate_public_NPV function:

    Calculate the public Net Present Value (NPV) for specific categories of damages,
    considering different policy scenarios related to grid decarbonization.

    The function compares baseline damages with post-measure package (mp) damages
    to determine the avoided damages (benefits) from implementing retrofits.

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    The list-based collection approach stores yearly values in lists and sums them using pandas
    vectorized operations after all years have been processed. This approach prevents accumulation
    errors that can occur with incremental updates.

    Args:
        df (pd.DataFrame): Input DataFrame containing base data for calculations.
        df_baseline_climate (pd.DataFrame): DataFrame containing baseline climate damage projections.
        df_baseline_health (pd.DataFrame): DataFrame containing baseline health damage projections.
        df_mp_climate (pd.DataFrame): DataFrame containing post-retrofit climate damage projections.
        df_mp_health (pd.DataFrame): DataFrame containing post-retrofit health damage projections.
        menu_mp (int): Menu identifier used to construct column names for the measure package.
        policy_scenario (str): Policy scenario that determines electricity grid projections.
            Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        rcm_model (str): The Reduced Complexity Model used for health impact calculations.
        base_year (int, optional): The base year for discounting calculations. Default is 2024.
        discounting_method (str, optional): The method used for discounting. Default is 'public'.
        verbose (bool, optional): Whether to print detailed progress messages. Defaults to False.

    Returns:
        pd.DataFrame: DataFrame with additional columns containing the calculated public NPVs for each
        equipment category, damage type, and sensitivity analysis combination.

    Raises:
        ValueError: If input parameters are invalid or if required data columns are missing.
        RuntimeError: If processing fails at the category or combination level.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
PRIVATE IMPACTS: LIFETIME CAPITAL COSTS AND SAVINGS
--------------------------------------------------------
calculate_lifetime_private_impact.py file contains the definition for the calculate_private_npv function.
Additional information on fuel price lookups as well as capital costs calculation methods can be found in the private_impact folder.

Documentation for the calculate_private_npv function:

    Calculate the private net present value (NPV) for various equipment categories,
    considering different cost assumptions and potential IRA rebates.
    The function adjusts equipment costs for inflation and calculates NPV based on
    cost savings between baseline and retrofit scenarios.

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    Args:
        df (DataFrame): Input DataFrame with installation costs, fuel savings, and potential rebates.
        df_fuel_costs (DataFrame): DataFrame containing measure package fuel costs.
        df_baseline_costs (DataFrame): DataFrame containing baseline fuel costs.
        input_mp (str): Input policy_scenario for calculating costs.
        menu_mp (int): Measure package identifier.
        policy_scenario (str): Policy scenario that determines electricity grid projections.
                               Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        discounting_method (str): The method used for discounting. Default is 'private_fixed'.
            - 'private_fixed': 7% discount rate for all households
            - 'private_variable': Household-specific rate based on AMI (2% to 12%)
            Note: 'public' discounting is not typically used for private NPV calculations.
        base_year (int): The base year for discounting calculations. Default is 2024.
        verbose (bool): Whether to print detailed processing information. Default is True.

    Returns:
        DataFrame: The input DataFrame updated with calculated private NPV and adjusted equipment costs.

    Raises:
        ValueError: If an invalid policy_scenario or menu_mp is provided.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
ADOPTION POTENTIAL
--------------------------------------------------------
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

Documentation for the adoption_decision function:

    Updates DataFrame with adoption decisions and public impacts based on NPV analysis.

    Simplified output for nation-level analysis while maintaining full functionality.

    Args:
        df: DataFrame containing home equipment data.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario for electricity grid projections.
            Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        rcm_model: RCM model for health impact analysis ('ap2', 'easiur', 'inmap').
        cr_function: Concentration response function ('acs', 'h6c').
        verbose: Enable detailed output for debugging (default: False).

    Returns:
        DataFrame with adoption tier and public impact classifications.

    Raises:
        ValueError: If input parameters are invalid.
        KeyError: If required columns are missing.
        TypeError: If data type conversion fails.


Documentation for the calculate_climate_only_adoption_robust function:

    Climate-only adoption analysis with simplified output.

    Args:
        df: Input DataFrame.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario name.
        scc_assumptions: List of SCC assumptions to process.
        verbose: Enable detailed output.

    Returns:
        DataFrame with climate-only adoption analysis columns.


Documentation for the calculate_health_only_adoption_robust function:

    Health-only adoption analysis with simplified output.

    Args:
        df: Input DataFrame.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario name.
        rcm_model: RCM model name.
        cr_function: Concentration response function.
        verbose: Enable detailed output.

    Returns:
        DataFrame with health-only adoption analysis columns.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

## BASIC MEASURE PACKAGE (MP8): NO INFLATION REDUCTION ACT
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 8
- AEO2023 No Inflation Reduction Act:  HDD and Fuel Price Projections
- Cambium 2021 MidCase Scenario

In [24]:
# Measure Package 8
scenario_name = 'No Inflation Reduction Act'
cost_scenario = 'Fuel Costs: AEO2023 No Inflation Reduction Act'
grid_scenario = 'Electricity Grid: Cambium 2021 MidCase Scenario'

print(f"""
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

====================================================================================================================================================================
Scenario No Inflation Reduction Act:
Basic Retrofit: Measure Package 8
Fuel Costs: AEO2023 No Inflation Reduction Act
Electricity Grid: Cambium 2021 MidCase Scenario
====================================================================================================================================================================

In [25]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PUBLIC IMPACT 
====================================================================================================================================================================
Completed Steps:
1. Calculate the baseline marginal damages for climate and health-related emissions
2. Calculate the post-retrofit marginal damages for climate and health-related emissions

---------------------------------------------------------------------------------------------
Step 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)
---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# Create copies to prevent overwriting the original dataframe and compare the differences
df_euss_am_mp8_home_ap2 = df_euss_am_mp8_home.copy()
df_euss_am_mp8_home_easiur = df_euss_am_mp8_home.copy()
df_euss_am_mp8_home_inmap = df_euss_am_mp8_home.copy()

# ========================== AP2  ========================== 
df_euss_am_mp8_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp8_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_noIRA_damages_climate,
    df_mp_health=df_mp8_noIRA_damages_health,
    menu_mp="8",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp8_home_easiur = calculate_public_npv(
    df=df_euss_am_mp8_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_noIRA_damages_climate,
    df_mp_health=df_mp8_noIRA_damages_health,
    menu_mp="8",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp8_home_inmap = calculate_public_npv(
    df=df_euss_am_mp8_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_noIRA_damages_climate,
    df_mp_health=df_mp8_noIRA_damages_health,
    menu_mp="8",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PUBLIC NPV (NO IRA): df_euss_am_mp8_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp8_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp8_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp8_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PUBLIC IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate the baseline marginal damages for climate and health-related emissions
2. Calculate the post-retrofit marginal damages for climate and health-related emissions

---------------------------------------------------------------------------------------------
Step 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)
---------------------------------------------------------------------------------------------

RESULTS OUTPUT:

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PUBLIC NPV (NO IRA): df_euss_am_mp8_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        preIRA_mp8_clothesDrying_public_npv_central_ap2_h6c  \
bldg_id
15                                                     NaN
79                                                  262.15
119                                                   9.78
122                                                 295.27
150                                                 295.32
...                                                    ...
549882                                              466.75
549915                                              798.68
549937                                              235.36
549963                                              401.60
549989                                              399.86

        preIRA_mp8_clothesDrying_climate_npv_upper  \
bldg_id
15                                             NaN
79                                          314.41
119                                         229.76
122                                         314.41
150                                         365.15
...                                            ...
549882                                      506.33
549915                                      881.90
549937                                      577.42
549963                                      476.07
549989                                      456.24

        preIRA_mp8_clothesDrying_public_npv_upper_ap2_h6c  \
bldg_id
15                                                    NaN
79                                                 379.23
119                                                 94.59
122                                                412.35
150                                                431.28
...                                                   ...
549882                                             655.28
549915                                            1127.04
549937                                             449.16
549963                                             578.59
549989                                             569.73

        preIRA_mp8_cooking_climate_npv_lower  \
bldg_id
15                                       NaN
79                                       NaN
119                                    30.63
122                                      NaN
150                                      NaN
...                                      ...
549882                                   NaN
549915                                   NaN
549937                                 21.95
549963                                   NaN
549989                                 68.47

        preIRA_mp8_cooking_health_npv_ap2_h6c  \
bldg_id
15                                        NaN
79                                        NaN
119                                   -299.42
122                                       NaN
150                                       NaN
...                                       ...
549882                                    NaN
549915                                    NaN
549937                                -135.35
549963                                    NaN
549989                                -208.25

         preIRA_mp8_cooking_public_npv_lower_ap2_h6c  \
bldg_id
15                                               NaN
79                                               NaN
119                                          -268.79
122                                              NaN
150                                              NaN
...                                              ...
549882                                           NaN
549915                                           NaN
549937                                       -113.40
549963                                           NaN
549989                                       -139.78

         preIRA_mp8_cooking_climate_npv_central  \
bldg_id
15                                          NaN
79                                          NaN
119                                      106.37
122                                         NaN
150                                         NaN
...                                         ...
549882                                      NaN
549915                                      NaN
549937                                    76.59
549963                                      NaN
549989                                   241.05

        preIRA_mp8_cooking_public_npv_central_ap2_h6c  \
bldg_id
15                                                NaN
79                                                NaN
119                                           -193.05
122                                               NaN
150                                               NaN
...                                               ...
549882                                            NaN
549915                                            NaN
549937                                         -58.76
549963                                            NaN
549989                                          32.80

         preIRA_mp8_cooking_climate_npv_upper  \
bldg_id
15                                        NaN
79                                        NaN
119                                    166.96
122                                       NaN
150                                       NaN
...                                       ...
549882                                    NaN
549915                                    NaN
549937                                 120.54
549963                                    NaN
549989                                 380.96

        preIRA_mp8_cooking_public_npv_upper_ap2_h6c
bldg_id
15                                              NaN
79                                              NaN
119                                         -132.46
122                                             NaN
150                                             NaN
...                                             ...
549882                                          NaN
549915                                          NaN
549937                                       -14.81
549963                                          NaN
549989                                       172.71

[17990 rows x 467 columns]

-----------------------------------------------
EASIUR:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        preIRA_mp8_clothesDrying_public_npv_central_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                  278.92
119                                                 102.16
122                                                 309.99
150                                                 331.59
...                                                    ...
549882                                              489.97
549915                                              844.81
549937                                              315.24
549963                                              366.72
549989                                              392.31

        preIRA_mp8_clothesDrying_climate_npv_upper  \
bldg_id
15                                             NaN
79                                          314.41
119                                         229.76
122                                         314.41
150                                         365.15
...                                            ...
549882                                      506.33
549915                                      881.90
549937                                      577.42
549963                                      476.07
549989                                      456.24

        preIRA_mp8_clothesDrying_public_npv_upper_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                  396.00
119                                                 186.97
122                                                 427.07
150                                                 467.55
...                                                    ...
549882                                              678.50
549915                                             1173.17
549937                                              529.04
549963                                              543.71
549989                                              562.18

        preIRA_mp8_cooking_climate_npv_lower  \
bldg_id
15                                       NaN
79                                       NaN
119                                    30.63
122                                      NaN
150                                      NaN
...                                      ...
549882                                   NaN
549915                                   NaN
549937                                 21.95
549963                                   NaN
549989                                 68.47

        preIRA_mp8_cooking_health_npv_easiur_h6c  \
bldg_id
15                                           NaN
79                                           NaN
119                                      -152.59
122                                          NaN
150                                          NaN
...                                          ...
549882                                       NaN
549915                                       NaN
549937                                    -77.98

In [34]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PRIVATE IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs
2. Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
3. Calculate replacement cost (replacing existing piece of eqipment with similar technology)

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")


# ========================== AP2  ========================== 
df_euss_am_mp8_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp8_home_ap2,
    df_fuel_costs=df_mp8_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp8_home_easiur = calculate_private_npv(
    df=df_euss_am_mp8_home_easiur,
    df_fuel_costs=df_mp8_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp8_home_inmap = calculate_private_npv(
    df=df_euss_am_mp8_home_inmap,
    df_fuel_costs=df_mp8_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PRIVATE NPV (NO INFLATION REDUCTION ACT): df_euss_am_mp8_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp8_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp8_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp8_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PRIVATE IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs
2. Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
3. Calculate replacement cost (replacing existing piece of eqipment with similar technology)

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.

====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PRIVATE NPV (NO INFLATION REDUCTION ACT): df_euss_am_mp8_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        preIRA_mp8_waterHeating_private_npv_lessWTP  \
bldg_id
15                                         -1905.59
79                                         -2856.50
119                                        -2708.83
122                                        -1459.81
150                                        -1020.22
...                                             ...
549882                                     -2897.58
549915                                      1646.65
549937                                      -829.23
549963                                     -2676.94
549989                                       148.45

        preIRA_mp8_waterHeating_private_npv_moreWTP  \
bldg_id
15                                          -244.35
79                                         -1195.26
119                                         -817.35
122                                         1402.63
150                                           53.77
...                                             ...
549882                                     -1236.34
549915                                      2784.76
549937                                      1062.25
549963                                     -1015.70
549989                                      2856.01

        preIRA_mp8_clothesDrying_total_capitalCost  \
bldg_id
15                                             NaN
79                                         2453.54
119                                        2625.60
122                                        2758.81
150                                        2796.83
...                                            ...
549882                                     1477.37
549915                                     2360.05
549937                                     2459.14
549963                                     2141.62
549989                                     2596.08

        preIRA_mp8_clothesDrying_net_capitalCost  \
bldg_id
15                                           NaN
79                                       1459.48
119                                      1317.62
122                                      1764.75
150                                      1802.77
...                                          ...
549882                                    483.31
549915                                   1365.99
549937                                   1151.16
549963                                   1147.56
549989                                   1602.02

        preIRA_mp8_clothesDrying_private_npv_lessWTP  \
bldg_id
15                                               NaN
79                                          -2257.35
119                                         -2844.85
122                                         -2580.04
150                                         -2546.57
...                                              ...
549882                                      -1129.29
549915                                      -1652.69
549937                                      -3118.21
549963                                      -1799.03
549989                                      -2212.64

         preIRA_mp8_clothesDrying_private_npv_moreWTP  \
bldg_id
15                                                NaN
79                                           -1263.29
119                                          -1536.87
122                                          -1585.98
150                                          -1552.51
...                                               ...
549882                                        -135.23
549915                                        -658.63
549937                                       -1810.23
549963                                        -804.97
549989                                       -1218.58

         preIRA_mp8_cooking_total_capitalCost  \
bldg_id
15                                        NaN
79                                        NaN
119                                   1172.08
122                                       NaN
150                                       NaN
...                                       ...
549882                                    NaN
549915                                    NaN
549937                                1834.55
549963                                    NaN
549989                                1433.35

        preIRA_mp8_cooking_net_capitalCost  \
bldg_id
15                                     NaN
79                                     NaN
119                                  99.54
122                                    NaN
150                                    NaN
...                                    ...
549882                                 NaN
549915                                 NaN
549937                              762.01
549963                                 NaN
549989                              360.81

         preIRA_mp8_cooking_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                          NaN
119                                    -1689.48
122                                         NaN
150                                         NaN
...                                         ...
549882                                      NaN
549915                                      NaN
549937                                 -2597.33
549963                                      NaN
549989                                  -880.81

        preIRA_mp8_cooking_private_npv_moreWTP
bldg_id
15                                         NaN
79                                         NaN
119                                    -616.94
122                                        NaN
150                                        NaN
...                                        ...
549882                                     NaN
549915                                     NaN
549937                                -1524.79
549963                                     NaN
549989                                  191.73

[17990 rows x 772 columns]

-----------------------------------------------
EASIUR:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        preIRA_mp8_waterHeating_private_npv_lessWTP  \
bldg_id
15                                         -1905.59
79                                         -2856.50
119                                        -2708.83
122                                        -1459.81
150                                        -1020.22
...                                             ...
549882                                     -2897.58
549915                                      1646.65
549937                                      -829.23
549963                                     -2676.94
549989                                       148.45

        preIRA_mp8_waterHeating_private_npv_moreWTP  \
bldg_id
15                                          -244.35
79                                         -1195.26
119                                         -817.35
122                                         1402.63
150                                           53.77
...                                             ...
549882                                     -1236.34
549915                                      2784.76
549937                                      1062.25
549963                                     -1015.70
549989                                      2856.01

        preIRA_mp8_clothesDrying_total_capitalCost  \
bldg_id
15                                             NaN
79                                         2453.54
119                                        2625.60
122                                        2758.81
150                                        2796.83
...                                            ...
549882                                     1477.37
549915                                     2360.05
549937                                     2459.14
549963                                     2141.62
549989                                     2596.08

        preIRA_mp8_clothesDrying_net_capitalCost  \
bldg_id
15                                           NaN
79                                       1459.48
119                                      1317.62
122                                      1764.75
150                                      1802.77
...                                          ...
549882                                    483.31
549915                                   1365.99
549937                                   1151.16
549963                                   1147.56

In [27]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_ap2 = adoption_decision(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    )

df_euss_am_mp8_home_ap2 = adoption_decision(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_easiur = adoption_decision(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    )

df_euss_am_mp8_home_easiur = adoption_decision(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_inmap = adoption_decision(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    )

df_euss_am_mp8_home_inmap = adoption_decision(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER DETERMINING ADOPTION FEASIBILITY (NO INFLATION REDUCTION ACT): df_euss_am_mp8_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp8_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp8_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp8_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):

Processing AP2 model...
Fixed 12 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | ap2-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | ap2-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | ap2-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | ap2-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added
Processing EASIUR model...
Fixed 12 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | easiur-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | easiur-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | easiur-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | easiur-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added
Processing InMAP model...
Fixed 12 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | inmap-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | inmap-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | inmap-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | inmap-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added

====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER DETERMINING ADOPTION FEASIBILITY (NO INFLATION REDUCTION ACT): df_euss_am_mp8_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        preIRA_mp8_cooking_total_npv_climateOnly_central  \
bldg_id
15                                                   NaN
79                                                   NaN
119                                              -510.57
122                                                  NaN
150                                                  NaN
...                                                  ...
549882                                               NaN
549915                                               NaN
549937                                          -1448.20
549963                                               NaN
549989                                            432.78

        preIRA_mp8_cooking_total_npv_climateOnly_upper  \
bldg_id
15                                                 NaN
79                                                 NaN
119                                            -449.98
122                                                NaN
150                                                NaN
...                                                ...
549882                                             NaN
549915                                             NaN
549937                                        -1404.25
549963                                             NaN
549989                                          572.69

        preIRA_mp8_heating_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                  NaN
79                                             -4886.56
119                                           -23565.80
122                                           -30148.39
150                                            18908.10
...                                                 ...
549882                                              NaN
549915                                         19717.57
549937                                        -12906.93
549963                                        -26867.60
549989                                           134.05

        preIRA_mp8_waterHeating_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                 -387.26
79                                                -1235.57
119                                                -933.36
122                                                1426.04
150                                                 198.41
...                                                    ...
549882                                            -1458.10
549915                                             3657.05
549937                                              959.14
549963                                            -1066.67
549989                                             2819.77

        preIRA_mp8_clothesDrying_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                     NaN
79                                                -1238.06
119                                               -1589.47
122                                               -1547.86
150                                               -1526.77
...                                                    ...
549882                                              -77.26
549915                                             -563.21
549937                                            -1860.14
549963                                             -765.06
549989                                            -1174.42

         preIRA_mp8_cooking_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                   NaN
79                                                   NaN
119                                              -733.47
122                                                  NaN
150                                                  NaN
...                                                  ...
549882                                               NaN
549915                                               NaN
549937                                          -1577.47
549963                                               NaN
549989                                            110.69

         preIRA_mp8_heating_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                   NaN
79                                              -5234.32
119                                            -24323.54
122                                            -29293.10
150                                             23327.51
...                                                  ...
549882                                               NaN
549915                                          26588.33
549937                                         -13200.07
549963                                         -27574.29
549989                                             86.36

        preIRA_mp8_waterHeating_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                 -611.52
79                                                -1298.84
119                                               -1115.44
122                                                1462.74
150                                                 425.42
...                                                    ...
549882                                            -1806.13
549915                                             5025.95
549937                                              797.30
549963                                            -1146.66
549989                                             2762.90

         preIRA_mp8_clothesDrying_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                     NaN
79                                                -1198.47
119                                               -1672.04
122                                               -1488.04
150                                               -1486.38
...                                                    ...
549882                                               13.72
549915                                             -413.49
549937                                            -1938.49
549963                                             -702.45
549989                                            -1105.09

        preIRA_mp8_cooking_total_npv_healthOnly_ap2_h6c
bldg_id
15                                                  NaN
79                                                  NaN
119                                             -916.36
122                                                 NaN
150                                                 NaN
...                                                 ...

## BASIC MEASURE PACKAGE (MP8): AEO2023 REFERENCE CASE
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 8
- AEO2023 REFERENCE CASE: HDD and Fuel Price Projections
- Cambium 2023 MidCase Scenario

In [28]:
# Measure Package 8
scenario_name = 'Basic IRA-Reference'
cost_scenario = 'Fuel Costs: AEO2023 Reference Case'
grid_scenario = 'Electricity Grid: Cambium 2023 MidCase Scenario'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario Basic IRA-Reference:
Basic Retrofit: Measure Package 8
Fuel Costs: AEO2023 Reference Case
Electricity Grid: Cambium 2023 MidCase Scenario
====================================================================================================================================================================

In [29]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PUBLIC IMPACT 
====================================================================================================================================================================
STEP 1. Calculate the baseline marginal damages for climate and health-related emissions         [COMPLETED]
STEP 2. Calculate the post-retrofit marginal damages for climate and health-related emissions    [COMPLETED]
STEP 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)

---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# ========================== AP2  ========================== 
df_euss_am_mp8_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp8_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_IRA_damages_climate,
    df_mp_health=df_mp8_IRA_damages_health,
    menu_mp="8",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp8_home_easiur = calculate_public_npv(
    df=df_euss_am_mp8_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_IRA_damages_climate,
    df_mp_health=df_mp8_IRA_damages_health,
    menu_mp="8",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp8_home_inmap = calculate_public_npv(
    df=df_euss_am_mp8_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp8_IRA_damages_climate,
    df_mp_health=df_mp8_IRA_damages_health,
    menu_mp="8",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
=====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PUBLIC NPV (AEO2023 REFERENCE CASE): df_euss_am_mp8_home

-----------------------------------------------
AP2: 
-----------------------------------------------
      
{df_euss_am_mp8_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp8_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp8_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PUBLIC IMPACT
====================================================================================================================================================================
STEP 1. Calculate the baseline marginal damages for climate and health-related emissions         [COMPLETED]
STEP 2. Calculate the post-retrofit marginal damages for climate and health-related emissions    [COMPLETED]
STEP 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)

---------------------------------------------------------------------------------------------

RESULTS OUTPUT:

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

=====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER CALCULATING PUBLIC NPV (AEO2023 REFERENCE CASE): df_euss_am_mp8_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        iraRef_mp8_clothesDrying_public_npv_central_ap2_h6c  \
bldg_id
15                                                     NaN
79                                                  303.76
119                                                  89.78
122                                                 336.88
150                                                 343.57
...                                                    ...
549882                                              533.72
549915                                              915.26
549937                                              374.90
549963                                              439.22
549989                                              460.17

        iraRef_mp8_clothesDrying_climate_npv_upper  \
bldg_id
15                                             NaN
79                                          380.96
119                                         357.75
122                                         380.96
150                                         442.35
...                                            ...
549882                                      613.48
549915                                     1068.42
549937                                      799.95
549963                                      536.06
549989                                      552.77

        iraRef_mp8_clothesDrying_public_npv_upper_ap2_h6c  \
bldg_id
15                                                    NaN
79                                                 445.78
119                                                222.58
122                                                478.90
150                                                508.48
...                                                   ...
549882                                             762.43
549915                                            1313.56
549937                                             671.69
549963                                             638.58
549989                                             666.26

        iraRef_mp8_cooking_climate_npv_lower  \
bldg_id
15                                       NaN
79                                       NaN
119                                    69.50
122                                      NaN
150                                      NaN
...                                      ...
549882                                   NaN
549915                                   NaN
549937                                 61.03
549963                                   NaN
549989                                101.67

        iraRef_mp8_cooking_health_npv_ap2_h6c  \
bldg_id
15                                        NaN
79                                        NaN
119                                   -299.42
122                                       NaN
150                                       NaN
...                                       ...
549882                                    NaN
549915                                    NaN
549937                                -135.35
549963                                    NaN
549989                                -208.25

         iraRef_mp8_cooking_public_npv_lower_ap2_h6c  \
bldg_id
15                                               NaN
79                                               NaN
119                                          -229.92
122                                              NaN
150                                              NaN
...                                              ...
549882                                           NaN
549915                                           NaN
549937                                        -74.32
549963                                           NaN
549989                                       -106.58

         iraRef_mp8_cooking_climate_npv_central  \
bldg_id
15                                          NaN
79                                          NaN
119                                      246.33
122                                         NaN
150                                         NaN
...                                         ...
549882                                      NaN
549915                                      NaN
549937                                   215.90
549963                                      NaN
549989                                   360.67

        iraRef_mp8_cooking_public_npv_central_ap2_h6c  \
bldg_id
15                                                NaN
79                                                NaN
119                                            -53.09
122                                               NaN
150                                               NaN
...                                               ...
549882                                            NaN
549915                                            NaN
549937                                          80.55
549963                                            NaN
549989                                         152.42

         iraRef_mp8_cooking_climate_npv_upper  \
bldg_id
15                                        NaN
79                                        NaN
119                                    390.79
122                                       NaN
150                                       NaN
...                                       ...
549882                                    NaN
549915                                    NaN
549937                                 342.13
549963                                    NaN
549989                                 572.35

        iraRef_mp8_cooking_public_npv_upper_ap2_h6c
bldg_id
15                                              NaN
79                                              NaN
119                                           91.37
122                                             NaN
150                                             NaN
...                                             ...
549882                                          NaN
549915                                          NaN
549937                                       206.78
549963                                          NaN
549989                                       364.10

[17990 rows x 648 columns]

-----------------------------------------------
EASIUR:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        iraRef_mp8_clothesDrying_public_npv_central_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                  320.53
119                                                 182.16
122                                                 351.60
150                                                 379.84
...                                                    ...
549882                                              556.94
549915                                              961.39
549937                                              454.78
549963                                              404.34
549989                                              452.62

        iraRef_mp8_clothesDrying_climate_npv_upper  \
bldg_id
15                                             NaN
79                                          380.96
119                                         357.75
122                                         380.96
150                                         442.35
...                                            ...
549882                                      613.48
549915                                     1068.42
549937                                      799.95
549963                                      536.06
549989                                      552.77

        iraRef_mp8_clothesDrying_public_npv_upper_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                  462.55
119                                                 314.96
122                                                 493.62
150                                                 544.75
...                                                    ...
549882                                              785.65
549915                                             1359.69
549937                                              751.57
549963                                              603.70
549989                                              658.71

        iraRef_mp8_cooking_climate_npv_lower  \
bldg_id
15                                       NaN
79                                       NaN
119                                    69.50
122                                      NaN
150                                      NaN
...                                      ...
549882                                   NaN
549915                                   NaN
549937                                 61.03
549963                                   NaN
549989                                101.67

        iraRef_mp8_cooking_health_npv_easiur_h6c  \
bldg_id
15                                           NaN
79                                           NaN
119                                      -152.59
122                                          NaN
150                                          NaN
...                                          ...
549882                                       NaN
549915                                       NaN
549937                                    -77.98

In [63]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")


# ========================== AP2  ========================== 
df_euss_am_mp8_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp8_home_ap2,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    # discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp8_home_easiur = calculate_private_npv(
    df=df_euss_am_mp8_home_easiur,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    # discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp8_home_inmap = calculate_private_npv(
    df=df_euss_am_mp8_home_inmap,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    # discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )



# print(f"""  
# =====================================================================================================================================================================
# DATAFRAME FOR MP8 AFTER CALCULATING PRIVATE NPV (AEO2023 REFERENCE CASE): df_euss_am_mp8_home

# -----------------------------------------------
# AP2: 
# -----------------------------------------------
      
# {df_euss_am_mp8_home_ap2}

# -----------------------------------------------
# EASIUR:
# -----------------------------------------------

# {df_euss_am_mp8_home_easiur}

# -----------------------------------------------
# InMAP:
# -----------------------------------------------

# {df_euss_am_mp8_home_inmap}
      
# """)

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.

In [64]:
if print_debug:
    # Create a sample dataframe for the heating category
    df_sample_heating = create_sample_df(
        df=df_euss_am_mp8_home_ap2,
        include_groups=['base_equipment'],
        categories=['heating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        # regex_patterns=['valid_fuel_heating', 'include_heating', 'baseline_AFUE', 'baseline_SEER', 'baseline_HSPF', 
        #                 'hvac_heating_efficiency', 'upgrade_hvac_', 'upgrade_heating','ugrade_newInstall_HSPF',
        #                 ]
        regex_patterns=['upgrade_heating', 'valid_fuel_heating', 'include_heating', 'heating_installation_cost',
                        'heating_replacement_cost', 'heating_total_capital_cost', 'heating_net_capital_cost',
                        'variable', 'heating_private_npv'])
    print(df_sample_heating)

        base_heating_fuel                         heating_type  \
bldg_id
15            Electricity                     Electricity ASHP
79               Fuel Oil                Fuel Oil Fuel Furnace
119           Natural Gas             Natural Gas Fuel Furnace
122              Fuel Oil                Fuel Oil Fuel Furnace
150           Electricity                Electricity Baseboard
...                   ...                                  ...
549882        Natural Gas  Natural Gas Fuel Wall/Floor Furnace
549915        Electricity         Electricity Electric Furnace
549937        Natural Gas             Natural Gas Fuel Furnace
549963        Natural Gas             Natural Gas Fuel Furnace
549989           Fuel Oil                Fuel Oil Fuel Furnace

         base_electricity_heating_consumption  \
bldg_id
15                                        NaN
79                                       0.00
119                                      0.00
122                                      0.00
150                                  20677.34
...                                       ...
549882                                    NaN
549915                               22397.66
549937                                   0.00
549963                                   0.00
549989                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
15                                    NaN
79                               36921.09
119                                  0.00
122                              40613.20
150                                  0.00
...                                   ...
549882                                NaN
549915                               0.00
549937                               0.00
549963                               0.00
549989                           15981.46

         base_naturalGas_heating_consumption  \
bldg_id
15                                       NaN
79                                      0.00
119                                 17917.78
122                                     0.00
150                                     0.00
...                                      ...
549882                                   NaN
549915                                  0.00
549937                              15632.70
549963                              32303.17
549989                                  0.00

         base_propane_heating_consumption  valid_fuel_heating  \
bldg_id
15                                    NaN                True
79                                    0.0                True
119                                   0.0                True
122                                   0.0                True
150                                   0.0                True
...                                   ...                 ...
549882                                NaN                True
549915                                0.0                True
549937                                0.0                True
549963                                0.0                True
549989                                0.0                True

         include_heating                baseline_heating_type  \
bldg_id
15                 False                     Electricity ASHP
79                  True                Fuel Oil Fuel Furnace
119                 True             Natural Gas Fuel Furnace
122                 True                Fuel Oil Fuel Furnace
150                 True                Electricity Baseboard
...                  ...                                  ...
549882             False  Natural Gas Fuel Wall/Floor Furnace
549915              True         Electricity Electric Furnace
549937              True             Natural Gas Fuel Furnace
549963              True             Natural Gas Fuel Furnace
549989              True                Fuel Oil Fuel Furnace

                  hvac_heating_type_and_fuel  \
bldg_id
15                          Electricity ASHP
79                     Fuel Oil Fuel Furnace
119                 Natural Gas Fuel Furnace
122                    Fuel Oil Fuel Furnace
150                    Electricity Baseboard
...                                      ...
549882   Natural Gas Fuel Wall/Floor Furnace
549915          Electricity Electric Furnace
549937              Natural Gas Fuel Furnace
549963              Natural Gas Fuel Furnace
549989                 Fuel Oil Fuel Furnace

         household_variable_discount_rate  use_variable_discounting  \
bldg_id
15                               0.075753                     False
79                               0.077073                     False
119                              0.032893                     False
122                              0.097433                     False
150                              0.057887                     False
...                                   ...                       ...
549882                           0.057287                     False
549915                           0.028260                     False
549937                           0.020607                     False
549963                           0.040327                     False
549989                           0.020000                     False

         preIRA_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                    -10660.00
119                                   -26828.60
122                                   -37766.61
150                                     6490.48
...                                         ...
549882                                      NaN
549915                                  5628.09
549937                                -16290.49
549963                                -30187.37
549989                                 -5407.59

         preIRA_mp8_heating_private_npv_moreWTP  \
bldg_id
15                                          NaN
79                                     -4665.05
119                                   -23082.98
122                                   -30693.47
150                                    16091.81
...                                         ...
549882                                      NaN
549915                                 15339.30
549937                                -12720.16
549963                                -26417.32
549989                                   164.41

         iraRef_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                     -1627.99
119                                   -19100.16
122                                   -26215.16
150                                    12771.57
...                                         ...
549882                                      NaN
549915                                  6410.66
549937                                 -8287.65
549963                                -22542.56
549989                                 -9107.03

         iraRef_mp8_heating_private_npv_moreWTP
bldg_id
15                                          NaN
79                                      4366.96
119                                   -15354.54
122                                   -19142.02
150                                    22372.90
...                                         ...
549882                                      NaN
549915                                 16121.87
549937                                 -4717.32
549963                                -18772.51
549989                                 -3535.03

[17990 rows x 16 columns]

In [67]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")


# ========================== AP2  ========================== 
df_euss_am_mp8_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp8_home_ap2,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp8_home_easiur = calculate_private_npv(
    df=df_euss_am_mp8_home_easiur,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp8_home_inmap = calculate_private_npv(
    df=df_euss_am_mp8_home_inmap,
    df_fuel_costs=df_mp8_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    # discounting_method='private_fixed',
    discounting_method='private_variable',
    base_year=2024,
    verbose=False  # Add this parameter
    )



# print(f"""  
# =====================================================================================================================================================================
# DATAFRAME FOR MP8 AFTER CALCULATING PRIVATE NPV (AEO2023 REFERENCE CASE): df_euss_am_mp8_home

# -----------------------------------------------
# AP2: 
# -----------------------------------------------
      
# {df_euss_am_mp8_home_ap2}

# -----------------------------------------------
# EASIUR:
# -----------------------------------------------

# {df_euss_am_mp8_home_easiur}

# -----------------------------------------------
# InMAP:
# -----------------------------------------------

# {df_euss_am_mp8_home_inmap}
      
# """)

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for waterHeating...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for waterHeating with lifetime: 12 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for clothesDrying...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for clothesDrying with lifetime: 13 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Calculating costs for cooking...
          input_mp: upgrade08, menu_mp: 8, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for cooking with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp8_


Verifying masking for all calculated columns:
WARNING: Replacing 16 existing columns. Function was called on data that already contains results.

In [68]:
if print_debug:
    # Create a sample dataframe for the heating category
    df_sample_heating = create_sample_df(
        df=df_euss_am_mp8_home_ap2,
        include_groups=['base_equipment'],
        categories=['heating'],
        scenarios=['preIRA', 'iraRef'],
        metrics=[],
        mp_number=menu_mp,
        # regex_patterns=['valid_fuel_heating', 'include_heating', 'baseline_AFUE', 'baseline_SEER', 'baseline_HSPF', 
        #                 'hvac_heating_efficiency', 'upgrade_hvac_', 'upgrade_heating','ugrade_newInstall_HSPF',
        #                 ]
        regex_patterns=['upgrade_heating', 'valid_fuel_heating', 'include_heating', 'heating_installation_cost',
                        'heating_replacement_cost', 'heating_total_capital_cost', 'heating_net_capital_cost',
                        'variable', 'heating_private_npv'])
    print(df_sample_heating)

        base_heating_fuel                         heating_type  \
bldg_id
15            Electricity                     Electricity ASHP
79               Fuel Oil                Fuel Oil Fuel Furnace
119           Natural Gas             Natural Gas Fuel Furnace
122              Fuel Oil                Fuel Oil Fuel Furnace
150           Electricity                Electricity Baseboard
...                   ...                                  ...
549882        Natural Gas  Natural Gas Fuel Wall/Floor Furnace
549915        Electricity         Electricity Electric Furnace
549937        Natural Gas             Natural Gas Fuel Furnace
549963        Natural Gas             Natural Gas Fuel Furnace
549989           Fuel Oil                Fuel Oil Fuel Furnace

         base_electricity_heating_consumption  \
bldg_id
15                                        NaN
79                                       0.00
119                                      0.00
122                                      0.00
150                                  20677.34
...                                       ...
549882                                    NaN
549915                               22397.66
549937                                   0.00
549963                                   0.00
549989                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
15                                    NaN
79                               36921.09
119                                  0.00
122                              40613.20
150                                  0.00
...                                   ...
549882                                NaN
549915                               0.00
549937                               0.00
549963                               0.00
549989                           15981.46

         base_naturalGas_heating_consumption  \
bldg_id
15                                       NaN
79                                      0.00
119                                 17917.78
122                                     0.00
150                                     0.00
...                                      ...
549882                                   NaN
549915                                  0.00
549937                              15632.70
549963                              32303.17
549989                                  0.00

         base_propane_heating_consumption  valid_fuel_heating  \
bldg_id
15                                    NaN                True
79                                    0.0                True
119                                   0.0                True
122                                   0.0                True
150                                   0.0                True
...                                   ...                 ...
549882                                NaN                True
549915                                0.0                True
549937                                0.0                True
549963                                0.0                True
549989                                0.0                True

         include_heating                baseline_heating_type  \
bldg_id
15                 False                     Electricity ASHP
79                  True                Fuel Oil Fuel Furnace
119                 True             Natural Gas Fuel Furnace
122                 True                Fuel Oil Fuel Furnace
150                 True                Electricity Baseboard
...                  ...                                  ...
549882             False  Natural Gas Fuel Wall/Floor Furnace
549915              True         Electricity Electric Furnace
549937              True             Natural Gas Fuel Furnace
549963              True             Natural Gas Fuel Furnace
549989              True                Fuel Oil Fuel Furnace

                  hvac_heating_type_and_fuel  \
bldg_id
15                          Electricity ASHP
79                     Fuel Oil Fuel Furnace
119                 Natural Gas Fuel Furnace
122                    Fuel Oil Fuel Furnace
150                    Electricity Baseboard
...                                      ...
549882   Natural Gas Fuel Wall/Floor Furnace
549915          Electricity Electric Furnace
549937              Natural Gas Fuel Furnace
549963              Natural Gas Fuel Furnace
549989                 Fuel Oil Fuel Furnace

         household_variable_discount_rate  use_variable_discounting  \
bldg_id
15                               0.075753                      True
79                               0.077073                      True
119                              0.032893                      True
122                              0.097433                      True
150                              0.057887                      True
...                                   ...                       ...
549882                           0.057287                      True
549915                           0.028260                      True
549937                           0.020607                      True
549963                           0.040327                      True
549989                           0.020000                      True

         preIRA_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                    -10660.00
119                                   -26828.60
122                                   -37766.61
150                                     6490.48
...                                         ...
549882                                      NaN
549915                                  5628.09
549937                                -16290.49
549963                                -30187.37
549989                                 -5407.59

         preIRA_mp8_heating_private_npv_moreWTP  \
bldg_id
15                                          NaN
79                                     -4665.05
119                                   -23082.98
122                                   -30693.47
150                                    16091.81
...                                         ...
549882                                      NaN
549915                                 15339.30
549937                                -12720.16
549963                                -26417.32
549989                                   164.41

         iraRef_mp8_heating_private_npv_lessWTP  \
bldg_id
15                                          NaN
79                                     -2498.14
119                                   -18716.19
122                                   -29613.61
150                                    14600.32
...                                         ...
549882                                      NaN
549915                                 13826.61
549937                                 -8154.23
549963                                -21998.20
549989                                 -5317.92

         iraRef_mp8_heating_private_npv_moreWTP
bldg_id
15                                          NaN
79                                      3496.81
119                                   -14970.57
122                                   -22540.47
150                                    24201.65
...                                         ...
549882                                      NaN
549915                                 23537.82
549937                                 -4583.90
549963                                -18228.15
549989                                   254.08

[17990 rows x 16 columns]

In [31]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity_robust.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_ap2 = adoption_decision(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    )

df_euss_am_mp8_home_ap2 = adoption_decision(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_easiur = adoption_decision(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    )

df_euss_am_mp8_home_easiur = adoption_decision(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp8_home_inmap = adoption_decision(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    )

df_euss_am_mp8_home_inmap = adoption_decision(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    )

# Climate-only analysis (new)
df_euss_am_mp8_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False
    )

# Health-only analysis (new)
df_euss_am_mp8_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False
    )

df_euss_am_mp8_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp8_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER DETERMINING ADOPTION FEASIBILITY (AEO2023 REFERENCE CASE): df_euss_am_mp8_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------   
AP2: 
-----------------------------------------------
      
{df_euss_am_mp8_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp8_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp8_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity_robust.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

RESULTS OUTPUT (AEO2023 REFERENCE CASE):

Processing AP2 model...
Fixed 12 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | ap2-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | ap2-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | ap2-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | ap2-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added
Processing EASIUR model...
Fixed 12 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | easiur-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | easiur-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | easiur-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | easiur-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added
Processing InMAP model...
Fixed 12 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | inmap-acs

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | inmap-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 13,849/17,990 valid homes, 3 scenarios
  waterHeating: 17,255/17,990 valid homes, 3 scenarios
  clothesDrying: 16,238/17,990 valid homes, 3 scenarios
  cooking: 8,974/17,990 valid homes, 3 scenarios
  Total columns: 240
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 48 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | inmap-acs

Verifying masking for all calculated columns:
  Health-only: 8 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp8_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | inmap-h6c

Verifying masking for all calculated columns:
  Health-only: 8 columns added

====================================================================================================================================================================
DATAFRAME FOR MP8 AFTER DETERMINING ADOPTION FEASIBILITY (AEO2023 REFERENCE CASE): df_euss_am_mp8_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        iraRef_mp8_cooking_total_npv_climateOnly_central  \
bldg_id
15                                                   NaN
79                                                   NaN
119                                               235.02
122                                                  NaN
150                                                  NaN
...                                                  ...
549882                                               NaN
549915                                               NaN
549937                                           -439.34
549963                                               NaN
549989                                            571.09

        iraRef_mp8_cooking_total_npv_climateOnly_upper  \
bldg_id
15                                                 NaN
79                                                 NaN
119                                             379.48
122                                                NaN
150                                                NaN
...                                                ...
549882                                             NaN
549915                                             NaN
549937                                         -313.11
549963                                             NaN
549989                                          782.77

        iraRef_mp8_heating_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                  NaN
79                                              3275.30
119                                           -15453.39
122                                           -21995.39
150                                            27017.94
...                                                 ...
549882                                              NaN
549915                                         27916.09
549937                                         -4770.67
549963                                        -18678.43
549989                                           223.72

        iraRef_mp8_waterHeating_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                 1383.07
79                                                  523.36
119                                                 751.24
122                                                3184.09
150                                                1422.07
...                                                    ...
549882                                              -53.42
549915                                             5447.16
549937                                             2149.77
549963                                              561.37
549989                                             2841.42

        iraRef_mp8_clothesDrying_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                     NaN
79                                                 -394.46
119                                                -739.96
122                                                -704.73
150                                                -682.01
...                                                    ...
549882                                              668.04
549915                                              291.13
549937                                             -990.94
549963                                               81.73
549989                                            -1166.50

         iraRef_mp8_cooking_total_npv_healthOnly_ap2_acs  \
bldg_id
15                                                   NaN
79                                                   NaN
119                                              -127.84
122                                                  NaN
150                                                  NaN
...                                                  ...
549882                                               NaN
549915                                               NaN
549937                                           -707.92
549963                                               NaN
549989                                            129.38

         iraRef_mp8_heating_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                   NaN
79                                               2927.54
119                                            -16211.13
122                                            -21140.10
150                                             31437.35
...                                                  ...
549882                                               NaN
549915                                          34786.85
549937                                          -5063.81
549963                                         -19385.12
549989                                            176.03

        iraRef_mp8_waterHeating_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                 1158.81
79                                                  460.09
119                                                 569.16
122                                                3220.79
150                                                1649.08
...                                                    ...
549882                                             -401.45
549915                                             6816.06
549937                                             1987.93
549963                                              481.38
549989                                             2784.55

         iraRef_mp8_clothesDrying_total_npv_healthOnly_ap2_h6c  \
bldg_id
15                                                     NaN
79                                                 -354.87
119                                                -822.53
122                                                -644.91
150                                                -641.62
...                                                    ...
549882                                              759.02
549915                                              440.85
549937                                            -1069.29
549963                                              144.34
549989                                            -1097.17

        iraRef_mp8_cooking_total_npv_healthOnly_ap2_h6c
bldg_id
15                                                  NaN
79                                                  NaN
119                                             -310.73
122                                                 NaN
150                                                 NaN

In [32]:
# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp8_home_ap2 dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp8_home_ap2.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp8_home_easiur dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp8_home_easiur.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp8_home_inmap dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp8_home_inmap.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# Model Runtime

In [33]:
# Flag to prevent excessive output in other scenario files
individual_scenario_run = False

# Get the current datetime again
end_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

# Calculate the elapsed time
elapsed_time = datetime.strptime(end_time, "%Y-%m-%d_%H-%M-%S") - datetime.strptime(start_time, "%Y-%m-%d_%H-%M-%S")

# Format the elapsed time
elapsed_seconds = elapsed_time.total_seconds()
elapsed_minutes = int(elapsed_seconds // 60)
elapsed_seconds = int(elapsed_seconds % 60)

# Print the elapsed time
print(f"The code took {elapsed_minutes} minutes and {elapsed_seconds} seconds to execute.")

The code took 3 minutes and 17 seconds to execute.

In [40]:
# pd.set_option('display.max_columns', None)  # Show all columns when printing dataframes
pd.reset_option('display.max_columns')  # Reset to default behavior

In [37]:
df_euss_am_mp8_home_ap2

,square_footage,census_region,census_division,census_division_recs,building_america_climate_zone,reeds_balancing_area,gea_region,state,city,urbanicity,county,county_fips,puma,county_and_puma,weather_file_city,Longitude,Latitude,building_type,income,federal_poverty_level,occupancy,tenure,vacancy_status,base_heating_fuel,heating_type,hvac_cooling_type,vintage,base_heating_efficiency,base_electricity_heating_consumption,base_fuelOil_heating_consumption,base_naturalGas_heating_consumption,base_propane_heating_consumption,base_waterHeating_fuel,waterHeating_type,base_electricity_waterHeating_consumption,base_fuelOil_waterHeating_consumption,base_naturalGas_waterHeating_consumption,base_propane_waterHeating_consumption,base_clothesDrying_fuel,base_electricity_clothesDrying_consumption,base_naturalGas_clothesDrying_consumption,base_propane_clothesDrying_consumption,base_cooking_fuel,base_electricity_cooking_consumption,base_naturalGas_cooking_consumption,base_propane_cooking_consumption,baseline_heating_consumption,baseline_waterHeating_consumption,baseline_clothesDrying_consumption,baseline_cooking_consumption,include_all,valid_fuel_heating,valid_tech_heating,include_heating,valid_fuel_waterHeating,valid_tech_waterHeating,include_waterHeating,valid_fuel_clothesDrying,include_clothesDrying,valid_fuel_cooking,include_cooking,baseline_heating_lifetime_mt_co2e_lrmer,baseline_heating_lifetime_damages_climate_lrmer_lower,baseline_heating_lifetime_damages_climate_lrmer_central,baseline_heating_lifetime_damages_climate_lrmer_upper,baseline_heating_lifetime_mt_co2e_srmer,baseline_heating_lifetime_damages_climate_srmer_lower,baseline_heating_lifetime_damages_climate_srmer_central,baseline_heating_lifetime_damages_climate_srmer_upper,baseline_waterHeating_lifetime_mt_co2e_lrmer,baseline_waterHeating_lifetime_damages_climate_lrmer_lower,baseline_waterHeating_lifetime_damages_climate_lrmer_central,baseline_waterHeating_lifetime_damages_climate_lrmer_upper,baseline_waterHeating_lifetime_mt_co2e_srmer,baseline_waterHeating_lifetime_damages_climate_srmer_lower,baseline_waterHeating_lifetime_damages_climate_srmer_central,baseline_waterHeating_lifetime_damages_climate_srmer_upper,baseline_clothesDrying_lifetime_mt_co2e_lrmer,baseline_clothesDrying_lifetime_damages_climate_lrmer_lower,baseline_clothesDrying_lifetime_damages_climate_lrmer_central,baseline_clothesDrying_lifetime_damages_climate_lrmer_upper,baseline_clothesDrying_lifetime_mt_co2e_srmer,baseline_clothesDrying_lifetime_damages_climate_srmer_lower,baseline_clothesDrying_lifetime_damages_climate_srmer_central,baseline_clothesDrying_lifetime_damages_climate_srmer_upper,baseline_cooking_lifetime_mt_co2e_lrmer,baseline_cooking_lifetime_damages_climate_lrmer_lower,baseline_cooking_lifetime_damages_climate_lrmer_central,baseline_cooking_lifetime_damages_climate_lrmer_upper,baseline_cooking_lifetime_mt_co2e_srmer,baseline_cooking_lifetime_damages_climate_srmer_lower,baseline_cooking_lifetime_damages_climate_srmer_central,baseline_cooking_lifetime_damages_climate_srmer_upper,county_key,baseline_heating_lifetime_damages_health_ap2_acs,baseline_heating_lifetime_damages_health_ap2_h6c,baseline_heating_lifetime_damages_health_easiur_acs,baseline_heating_lifetime_damages_health_easiur_h6c,baseline_heating_lifetime_damages_health_inmap_acs,baseline_heating_lifetime_damages_health_inmap_h6c,baseline_waterHeating_lifetime_damages_health_ap2_acs,baseline_waterHeating_lifetime_damages_health_ap2_h6c,baseline_waterHeating_lifetime_damages_health_easiur_acs,baseline_waterHeating_lifetime_damages_health_easiur_h6c,baseline_waterHeating_lifetime_damages_health_inmap_acs,baseline_waterHeating_lifetime_damages_health_inmap_h6c,baseline_clothesDrying_lifetime_damages_health_ap2_acs,baseline_clothesDrying_lifetime_damages_health_ap2_h6c,baseline_clothesDrying_lifetime_damages_health_easiur_acs,baseline_clothesDrying_lifetime_damages_health_easiur_h6c,baseline_clothesDrying_lifetime_damages_health_inmap_acs,baseline_clothesDrying_lifetime_damages_health_inmap_h6c,baseline_cooking_lifetime_damages_health_ap2_acs,baseline_cooking_lifetime_damages_health_ap2_h6c,baseline_cooking_lifetime_damages_health_easiur_acs,baseline_cooking_lifetime_damages_health_easiur_h6c,baseline_cooking_lifetime_damages_health_inmap_acs,baseline_cooking_lifetime_damages_health_inmap_h6c,fuel_type_heating,fuel_type_waterHeating,fuel_type_clothesDrying,fuel_type_cooking,hvac_has_ducts,baseline_heating_type,hvac_heating_efficiency,hvac_heating_type_and_fuel,size_heat_pump_backup_primary_k_btu_h,size_heating_system_primary_k_btu_h,size_heating_system_secondary_k_btu_h,upgrade_hvac_heating_efficiency,water_heater_efficiency,water_heater_fuel,water_heater_in_unit,size_water_heater_gal,upgrade_water_heater_efficiency,clothes_dryer_in_unit,upgrade_clothes_dryer,cooking_range_in_unit,upgrade_cooking_range,mp8_heating_consumption,mp8_waterHeating_consumption,mp8_clothesDrying_consumption,mp8_cooking_consumption,preIRA_mp8_heating_lifetime_mt_co2e_lrmer,preIRA_mp8_heating_lifetime_damages_climate_lrmer_lower,preIRA_mp8_heating_avoided_damages_climate_lrmer_lower,preIRA_mp8_heating_lifetime_damages_climate_lrmer_central,preIRA_mp8_heating_avoided_damages_climate_lrmer_central,preIRA_mp8_heating_lifetime_damages_climate_lrmer_upper,preIRA_mp8_heating_avoided_damages_climate_lrmer_upper,preIRA_mp8_heating_avoided_mt_co2e_lrmer,preIRA_mp8_heating_lifetime_mt_co2e_srmer,preIRA_mp8_heating_lifetime_damages_climate_srmer_lower,preIRA_mp8_heating_avoided_damages_climate_srmer_lower,preIRA_mp8_heating_lifetime_damages_climate_srmer_central,preIRA_mp8_heating_avoided_damages_climate_srmer_central,preIRA_mp8_heating_lifetime_damages_climate_srmer_upper,preIRA_mp8_heating_avoided_damages_climate_srmer_upper,preIRA_mp8_heating_avoided_mt_co2e_srmer,preIRA_mp8_waterHeating_lifetime_mt_co2e_lrmer,preIRA_mp8_waterHeating_lifetime_damages_climate_lrmer_lower,preIRA_mp8_waterHeating_avoided_damages_climate_lrmer_lower,preIRA_mp8_waterHeating_lifetime_damages_climate_lrmer_central,preIRA_mp8_waterHeating_avoided_damages_climate_lrmer_central,preIRA_mp8_waterHeating_lifetime_damages_climate_lrmer_upper,preIRA_mp8_waterHeating_avoided_damages_climate_lrmer_upper,preIRA_mp8_waterHeating_avoided_mt_co2e_lrmer,preIRA_mp8_waterHeating_lifetime_mt_co2e_srmer,preIRA_mp8_waterHeating_lifetime_damages_climate_srmer_lower,preIRA_mp8_waterHeating_avoided_damages_climate_srmer_lower,preIRA_mp8_waterHeating_lifetime_damages_climate_srmer_central,preIRA_mp8_waterHeating_avoided_damages_climate_srmer_central,preIRA_mp8_waterHeating_lifetime_damages_climate_srmer_upper,preIRA_mp8_waterHeating_avoided_damages_climate_srmer_upper,preIRA_mp8_waterHeating_avoided_mt_co2e_srmer,preIRA_mp8_clothesDrying_lifetime_mt_co2e_lrmer,preIRA_mp8_clothesDrying_lifetime_damages_climate_lrmer_lower,preIRA_mp8_clothesDrying_avoided_damages_climate_lrmer_lower,preIRA_mp8_clothesDrying_lifetime_damages_climate_lrmer_central,preIRA_mp8_clothesDrying_avoided_damages_climate_lrmer_central,preIRA_mp8_clothesDrying_lifetime_damages_climate_lrmer_upper,preIRA_mp8_clothesDrying_avoided_damages_climate_lrmer_upper,preIRA_mp8_clothesDrying_avoided_mt_co2e_lrmer,preIRA_mp8_clothesDrying_lifetime_mt_co2e_srmer,preIRA_mp8_clothesDrying_lifetime_damages_climate_srmer_lower,preIRA_mp8_clothesDrying_avoided_damages_climate_srmer_lower,preIRA_mp8_clothesDrying_lifetime_damages_climate_srmer_central,preIRA_mp8_clothesDrying_avoided_damages_climate_srmer_central,preIRA_mp8_clothesDrying_lifetime_damages_climate_srmer_upper,preIRA_mp8_clothesDrying_avoided_damages_climate_srmer_upper,preIRA_mp8_clothesDrying_avoided_mt_co2e_srmer,preIRA_mp8_cooking_lifetime_mt_co2e_lrmer,preIRA_mp8_cooking_lifetime_damages_climate_lrmer_lower,preIRA_mp8_cooking_avoided_damages_climate_lrmer_lower,preIRA_mp8_cooking_lifetime_damages_climate_lrmer_central,preIRA_mp8_cooking_avoided_damages_climate_lrmer_central,preIRA_mp8_cooking_lifetime_damages_climate_lrmer_upper,preIRA_mp8_cooking_avoided_damages_climate_lrmer_upper,preIRA_mp8_cooking_avoided_mt_co2e_lrmer,preIRA_mp8_cooking_lifetime_mt_co2e_srmer,preIRA_mp8_cooking_lifetime_damages_climate_srmer_lower,preIRA_mp8_cooking_avoided_damages_climate_srmer_lower,preIRA_mp8_cooking_lifetime_damages_climate_srmer_central,preIRA_mp8_cooking_avoided_damages_climate_srmer_central,preIRA_mp8_cooking_lifetime_damages_climate_srmer_upper,preIRA_mp8_cooking_avoided_damages_climate_srmer_upper,preIRA_mp8_cooking_avoided_mt_co2e_srmer,preIRA_mp8_heating_lifetime_damages_health_ap2_acs,preIRA_mp8_heating_avoided_damages_health_ap2_acs,preIRA_mp8_heating_lifetime_damages_health_ap2_h6c,preIRA_mp8_heating_avoided_damages_health_ap2_h6c,preIRA_mp8_heating_lifetime_damages_health_easiur_acs,preIRA_mp8_heating_avoided_damages_health_easiur_acs,preIRA_mp8_heating_lifetime_damages_health_easiur_h6c,preIRA_mp8_heating_avoided_damages_health_easiur_h6c,preIRA_mp8_heating_lifetime_damages_health_inmap_acs,preIRA_mp8_heating_avoided_damages_health_inmap_acs,preIRA_mp8_heating_lifetime_damages_health_inmap_h6c,preIRA_mp8_heating_avoided_damages_health_inmap_h6c,preIRA_mp8_waterHeating_lifetime_damages_health_ap2_acs,preIRA_mp8_waterHeating_avoided_damages_health_ap2_acs,preIRA_mp8_waterHeating_lifetime_damages_health_ap2_h6c,preIRA_mp8_waterHeating_avoided_damages_health_ap2_h6c,preIRA_mp8_waterHeating_lifetime_damages_health_easiur_acs,preIRA_mp8_waterHeating_avoided_damages_health_easiur_acs,preIRA_mp8_waterHeating_lifetime_damages_health_easiur_h6c,preIRA_mp8_waterHeating_avoided_damages_health_easiur_h6c,preIRA_mp8_waterHeating_lifetime_damages_health_inmap_acs,preIRA_mp8_waterHeating_avoided_damages_health_inmap_acs,preIRA_mp8_waterHeating_lifetime_damages_health_inmap_h6c,preIRA_mp8_waterHeating_avoided_damages_health_inmap_h6c,preIRA_mp8_clothesDrying_lifetime_damages_health_ap2_acs,preIRA_mp8_clothesDrying_avoided_damages_health_ap2_acs,preIRA_mp8_clothesDrying_lifetime_damages_health_ap2_h6c,preIRA_mp8_clothesDrying_avoided_damages_health_ap2_h6c,preIRA_mp8_clothesDrying_lifetime_damages_health_easiur_acs,preIRA_mp8_clothesDrying_avoided_damages_health_easiur_acs,preIRA_mp8_clothesDrying_lifetime_damages_health_easiur_h6c,preIRA_mp8_clothesDrying_avoided_damages_health_easiur_h6c,preIRA_mp8_clothesDrying_lifetime_damages_health_inmap_acs,preIRA_mp8_clothesDrying_avoided_damages_health_inmap_acs,preIRA_mp8_clothesDrying_lifetime_damages_health_inmap_h6c,preIRA_mp8_clothesDrying_avoided_damages_health_inmap_h6c,preIRA_mp8_cooking_lifetime_damages_health_ap2_acs,preIRA_mp8_cooking_avoided_damages_health_ap2_acs,preIRA_mp8_cooking_lifetime_damages_health_ap2_h6c,preIRA_mp8_cooking_avoided_damages_health_ap2_h6c,preIRA_mp8_cooking_lifetime_damages_health_easiur_acs,preIRA_mp8_cooking_avoided_damages_health_easiur_acs,preIRA_mp8_cooking_lifetime_damages_health_easiur_h6c,preIRA_mp8_cooking_avoided_damages_health_easiur_h6c,preIRA_mp8_cooking_lifetime_damages_health_inmap_acs,preIRA_mp8_cooking_avoided_damages_health_inmap_acs,preIRA_mp8_cooking_lifetime_damages_health_inmap_h6c,preIRA_mp8_cooking_avoided_damages_health_inmap_h6c,iraRef_mp8_heating_lifetime_mt_co2e_lrmer,iraRef_mp8_heating_lifetime_damages_climate_lrmer_lower,iraRef_mp8_heating_avoided_damages_climate_lrmer_lower,iraRef_mp8_heating_lifetime_damages_climate_lrmer_central,iraRef_mp8_heating_avoided_damages_climate_lrmer_central,iraRef_mp8_heating_lifetime_damages_climate_lrmer_upper,iraRef_mp8_heating_avoided_damages_climate_lrmer_upper,iraRef_mp8_heating_avoided_mt_co2e_lrmer,iraRef_mp8_heating_lifetime_mt_co2e_srmer,iraRef_mp8_heating_lifetime_damages_climate_srmer_lower,iraRef_mp8_heating_avoided_damages_climate_srmer_lower,iraRef_mp8_heating_lifetime_damages_climate_srmer_central,iraRef_mp8_heating_avoided_damages_climate_srmer_central,iraRef_mp8_heating_lifetime_damages_climate_srmer_upper,iraRef_mp8_heating_avoided_damages_climate_srmer_upper,iraRef_mp8_heating_avoided_mt_co2e_srmer,iraRef_mp8_waterHeating_lifetime_mt_co2e_lrmer,iraRef_mp8_waterHeating_lifetime_damages_climate_lrmer_lower,iraRef_mp8_waterHeating_avoided_damages_climate_lrmer_lower,iraRef_mp8_waterHeating_lifetime_damages_climate_lrmer_central,iraRef_mp8_waterHeating_avoided_damages_climate_lrmer_central,iraRef_mp8_waterHeating_lifetime_damages_climate_lrmer_upper,iraRef_mp8_waterHeating_avoided_damages_climate_lrmer_upper,iraRef_mp8_waterHeating_avoided_mt_co2e_lrmer,iraRef_mp8_waterHeating_lifetime_mt_co2e_srmer,iraRef_mp8_waterHeating_lifetime_damages_climate_srmer_lower,iraRef_mp8_waterHeating_avoided_damages_climate_srmer_lower,iraRef_mp8_waterHeating_lifetime_damages_climate_srmer_central,iraRef_mp8_waterHeating_avoided_damages_climate_srmer_central,iraRef_mp8_waterHeating_lifetime_damages_climate_srmer_upper,iraRef_mp8_waterHeating_avoided_damages_climate_srmer_upper,iraRef_mp8_waterHeating_avoided_mt_co2e_srmer,iraRef_mp8_clothesDrying_lifetime_mt_co2e_lrmer,iraRef_mp8_clothesDrying_lifetime_damages_climate_lrmer_lower,iraRef_mp8_clothesDrying_avoided_damages_climate_lrmer_lower,iraRef_mp8_clothesDrying_lifetime_damages_climate_lrmer_central,iraRef_mp8_clothesDrying_avoided_damages_climate_lrmer_central,iraRef_mp8_clothesDrying_lifetime_damages_climate_lrmer_upper,iraRef_mp8_clothesDrying_avoided_damages_climate_lrmer_upper,iraRef_mp8_clothesDrying_avoided_mt_co2e_lrmer,iraRef_mp8_clothesDrying_lifetime_mt_co2e_srmer,iraRef_mp8_clothesDrying_lifetime_damages_climate_srmer_lower,iraRef_mp8_clothesDrying_avoided_damages_climate_srmer_lower,iraRef_mp8_clothesDrying_lifetime_damages_climate_srmer_central,iraRef_mp8_clothesDrying_avoided_damages_climate_srmer_central,iraRef_mp8_clothesDrying_lifetime_damages_climate_srmer_upper,iraRef_mp8_clothesDrying_avoided_damages_climate_srmer_upper,iraRef_mp8_clothesDrying_avoided_mt_co2e_srmer,iraRef_mp8_cooking_lifetime_mt_co2e_lrmer,iraRef_mp8_cooking_lifetime_damages_climate_lrmer_lower,iraRef_mp8_cooking_avoided_damages_climate_lrmer_lower,iraRef_mp8_cooking_lifetime_damages_climate_lrmer_central,iraRef_mp8_cooking_avoided_damages_climate_lrmer_central,iraRef_mp8_cooking_lifetime_damages_climate_lrmer_upper,iraRef_mp8_cooking_avoided_damages_climate_lrmer_upper,iraRef_mp8_cooking_avoided_mt_co2e_lrmer,iraRef_mp8_cooking_lifetime_mt_co2e_srmer,iraRef_mp8_cooking_lifetime_damages_climate_srmer_lower,iraRef_mp8_cooking_avoided_damages_climate_srmer_lower,iraRef_mp8_cooking_lifetime_damages_climate_srmer_central,iraRef_mp8_cooking_avoided_damages_climate_srmer_central,iraRef_mp8_cooking_lifetime_damages_climate_srmer_upper,iraRef_mp8_cooking_avoided_damages_climate_srmer_upper,iraRef_mp8_cooking_avoided_mt_co2e_srmer,iraRef_mp8_heating_lifetime_damages_health_ap2_acs,iraRef_mp8_heating_avoided_damages_health_ap2_acs,iraRef_mp8_heating_lifetime_damages_health_ap2_h6c,iraRef_mp8_heating_avoided_damages_health_ap2_h6c,iraRef_mp8_heating_lifetime_damages_health_easiur_acs,iraRef_mp8_heating_avoided_damages_health_easiur_acs,iraRef_mp8_heating_lifetime_damages_health_easiur_h6c,iraRef_mp8_heating_avoided_damages_health_easiur_h6c,iraRef_mp8_heating_lifetime_damages_health_inmap_acs,iraRef_mp8_heating_avoided_damages_health_inmap_acs,iraRef_mp8_heating_lifetime_damages_health_inmap_h6c,iraRef_mp8_heating_avoided_damages_health_inmap_h6c,iraRef_mp8_waterHeating_lifetime_damages_health_ap2_acs,iraRef_mp8_waterHeating_avoided_damages_health_ap2_acs,iraRef_mp8_waterHeating_lifetime_damages_health_ap2_h6c,iraRef_mp8_waterHeating_avoided_damages_health_ap2_h6c,iraRef_mp8_waterHeating_lifetime_damages_health_easiur_acs,iraRef_mp8_waterHeating_avoided_damages_health_easiur_acs,iraRef_mp8_waterHeating_lifetime_damages_health_easiur_h6c,iraRef_mp8_waterHeating_avoided_damages_health_easiur_h6c,iraRef_mp8_waterHeating_lifetime_damages_health_inmap_acs,iraRef_mp8_waterHeating_avoided_damages_health_inmap_acs,iraRef_mp8_waterHeating_lifetime_damages_health_inmap_h6c,iraRef_mp8_waterHeating_avoided_damages_health_inmap_h6c,iraRef_mp8_clothesDrying_lifetime_damages_health_ap2_acs,iraRef_mp8_clothesDrying_avoided_damages_health_ap2_acs,iraRef_mp8_clothesDrying_lifetime_damages_health_ap2_h6c,iraRef_mp8_clothesDrying_avoided_damages_health_ap2_h6c,iraRef_mp8_clothesDrying_lifetime_damages_health_easiur_acs,iraRef_mp8_clothesDrying_avoided_damages_health_easiur_acs,iraRef_mp8_clothesDrying_lifetime_damages_health_easiur_h6c,iraRef_mp8_clothesDrying_avoided_damages_health_easiur_h6c,iraRef_mp8_clothesDrying_lifetime_damages_health_inmap_acs,iraRef_mp8_clothesDrying_avoided_damages_health_inmap_acs,iraRef_mp8_clothesDrying_lifetime_damages_health_inmap_h6c,iraRef_mp8_clothesDrying_avoided_damages_health_inmap_h6c,iraRef_mp8_cooking_lifetime_damages_health_ap2_acs,iraRef_mp8_cooking_avoided_damages_health_ap2_acs,iraRef_mp8_cooking_lifetime_damages_health_ap2_h6c,iraRef_mp8_cooking_avoided_damages_health_ap2_h6c,iraRef_mp8_cooking_lifetime_damages_health_easiur_acs,iraRef_mp8_cooking_avoided_damages_health_easiur_acs,iraRef_mp8_cooking_lifetime_damages_health_easiur_h6c,iraRef_mp8_cooking_avoided_damages_health_easiur_h6c,iraRef_mp8_cooking_lifetime_damages_health_inmap_acs,iraRef_mp8_cooking_avoided_damages_health_inmap_acs,iraRef_mp8_cooking_lifetime_damages_health_inmap_h6c,iraRef_mp8_cooking_avoided_damages_health_inmap_h6c,preIRA_mp8_heating_lifetime_fuel_cost,preIRA_mp8_heating_lifetime_savings_fuel_cost,preIRA_mp8_waterHeating_lifetime_fuel_cost,preIRA_mp8_waterHeating_lifetime_savings_fuel_cost,preIRA_mp8_clothesDrying_lifetime_fuel_cost,preIRA_mp8_clothesDrying_lifetime_savings_fuel_cost,preIRA_mp8_cooking_lifetime_fuel_cost,preIRA_mp8_cooking_lifetime_savings_fuel_cost,iraRef_mp8_heating_lifetime_fuel_cost,iraRef_mp8_heating_lifetime_savings_fuel_cost,baseline_heating_lifetime_fuel_cost,iraRef_mp8_waterHeating_lifetime_fuel_cost,iraRef_mp8_waterHeating_lifetime_savings_fuel_cost,baseline_waterHeating_lifetime_fuel_cost,iraRef_mp8_clothesDrying_lifetime_fuel_cost,iraRef_mp8_clothesDrying_lifetime_savings_fuel_cost,baseline_clothesDrying_lifetime_fuel_cost,iraRef_mp8_cooking_lifetime_fuel_cost,iraRef_mp8_cooking_lifetime_savings_fuel_cost,baseline_cooking_lifetime_fuel_cost,total_heating_load_kBtuh,baseline_AFUE,baseline_SEER,baseline_HSPF,ugrade_newInstall_HSPF,mp8_heating_installationCost,mp8_heating_replacementCost,mp8_heating_installation_premium,mp8_waterHeating_installationCost,mp8_waterHeating_replacementCost,mp8_clothesDrying_installationCost,mp8_clothesDrying_replacementCost,mp8_cooking_installationCost,mp8_cooking_replacementCost,household_income,census_area_medianIncome,percent_AMI,income_level,lmi_or_mui,household_variable_discount_rate,mp8_heating_rebate_amount,mp8_waterHeating_rebate_amount,mp8_clothesDrying_rebate_amount,mp8_cooking_rebate_amount,preIRA_mp8_heating_climate_npv_lower,preIRA_mp8_heating_health_npv_ap2_acs,preIRA_mp8_heating_public_npv_lower_ap2_acs,preIRA_mp8_heating_climate_npv_central,preIRA_mp8_heating_public_npv_central_ap2_acs,preIRA_mp8_heating_climate_npv_upper,preIRA_mp8_heating_public_npv_upper_ap2_acs,preIRA_mp8_waterHeating_climate_npv_lower,preIRA_mp8_waterHeating_health_npv_ap2_acs,preIRA_mp8_waterHeating_public_npv_lower_ap2_acs,preIRA_mp8_waterHeating_climate_npv_central,preIRA_mp8_waterHeating_public_npv_central_ap2_acs,preIRA_mp8_waterHeating_climate_npv_upper,preIRA_mp8_waterHeating_public_npv_upper_ap2_acs,preIRA_mp8_clothesDrying_climate_npv_lower,preIRA_mp8_clothesDrying_health_npv_ap2_acs,preIRA_mp8_clothesDrying_public_npv_lower_ap2_acs,preIRA_mp8_clothesDrying_climate_npv_central,preIRA_mp8_clothesDrying_public_npv_central_ap2_acs,preIRA_mp8_clothesDrying_climate_npv_upper,preIRA_mp8_clothesDrying_public_npv_upper_ap2_acs,preIRA_mp8_cooking_climate_npv_lower,preIRA_mp8_cooking_health_npv_ap2_acs,preIRA_mp8_cooking_public_npv_lower_ap2_acs,preIRA_mp8_cooking_climate_npv_central,preIRA_mp8_cooking_public_npv_central_ap2_acs,preIRA_mp8_cooking_climate_npv_upper,preIRA_mp8_cooking_public_npv_uppe