In [1]:
# file_path = r'C:\Users\jorda\Desktop\Projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\upgrade03_metadata_and_annual_results.csv'

# # Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
# columns_to_string = {61: str, 113: str, 121: str}

# df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
# # df_euss_am_mp3 = pd.read_csv(file_path, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)

In [2]:
# df_euss_am_mp3

In [3]:
# df_euss_am_mp3['upgrade.hvac_cooling_efficiency'].value_counts()

In [4]:
# print(df_euss_am_mp3.columns.tolist())

# TARE Model: Space Conditioning Analysis for TRANE Technologies
## LOAD EUSS DATA: Annual Energy Consumption and Metadata

**Analysis Focus:** Space Heating and Cooling Equipment Only
- Heating: Furnaces, boilers, etc. --> ASHP
- Cooling: Air conditioning systems (central AC, room AC) --> ASHP
- Excluded: Water heating, clothes drying, cooking equipment

In [5]:
import os

# import from cmu-tare-model package
from config import PROJECT_ROOT

# Measure Package 0: Baseline
menu_mp = 0
input_mp = 'baseline'

print(f"PROJECT_ROOT (from config.py): {PROJECT_ROOT}")

# Construct the absolute path to the .py file
relative_path = os.path.join("cmu_tare_model", "model_scenarios", "trane_technologies", "tare_trane_baseline_v2_1.ipynb")
file_path = os.path.join(PROJECT_ROOT, relative_path)

# On Windows, to avoid any path-escape quirks, convert backslashes to forward slashes
file_path = file_path.replace("\\", "/")

print(f"Running file: {file_path}")

# %run magic command to run a .py file and import variables into the current IPython session
# # If your path has spaces, wrap it in quotes:
%run -i {file_path} # If your path has NO spaces, no quotes needed.

print("TARE Baseline Scenario for TRANE Technologies - Model Run Complete")
print("Analysis Focus: Space Conditioning (Heating + Cooling)")

# Flag to prevent excessive output in other scenario files
individual_scenario_run = True

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
PROJECT_ROOT (from config.py): c:\users\jorda\desktop\projects\cmu-tare-model
Running file: c:/users/jorda/desktop/projects/cmu-tare-model/cmu_tare_model/model_scenarios/trane_technologies/tare_trane_baseline_v2_1.ipynb

=========================================================================================================
Welcome to the Trade-off Analysis of residential Retrofits for energy Equity Tool (TARE Model)
Let's start by reading the data from the NREL EUSS Database.

Make sure that the zipped folders stay organized as they are once unzipped.
If changes are made to the file path, then the program will not run properly.
==========================================================================================================

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
Result outputs will be exported here: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\output_results



====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO (TRANE ANALYSIS): MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
Load data from the NREL EUSS Database for the baseline scenario and apply various filters.

DATA: NREL EUSS Database
HOUSING FILTERS: Occupied units for Single Family, Small Multi-Family, and Mobile Homes
GEOGRAPHIC FILTERS: National, State, or City
ANALYSIS FOCUS: Space Conditioning (Heating + Cooling Equipment Only)

Additional details data can be found in the official End-Use Load Profiles/Savings Shapes documentation.
Our methodology is detailed in the process_euss_data.py file and its associated imports.

RESULTS OUTPUT:

Retrieved data for filename: baseline_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\baseline_metadata_and_annual_results.csv

C:\Users\jorda\AppData\Local\Temp\ipykernel_33700\3577416974.py:33: DtypeWarning: Columns (113) have mixed types. Specify dtype option on import or set low_memory=False.
  df_euss_am_baseline = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id'

Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 259)
You chose to filter for: PA
Location ID is: PA

To accurately characterize load profile, it is recommended to select subsets of data with >= 1000 models (~240,000 representative dwelling units).

The following cities (number of models also shown) are available for this state:

in.city
Not in a census Place      7975
In another census Place    6648
PA, Philadelphia           1962
PA, Pittsburgh              412
PA, Erie                    146
PA, Allentown               136
PA, Reading                 110
PA, Scranton                109
PA, Bethlehem                98
PA, Harrisburg               74
PA, Altoona                  70
PA, Lancaster                69
PA, York                     64
PA, Levittown                61
PA, Wilkes-Barre             56
Name: count, dtype: int64
You chose to analyze all of state: PA
Location ID is: PA

====================================================================================================================================================================
DATAFRAME: df_euss_am_baseline

         upgrade      weight  applicability  in.sqft  \
bldg_id
15             0  242.131013           True    333.0
79             0  242.131013           True   1220.0
119            0  242.131013           True   2152.0
122            0  242.131013           True   2176.0
150            0  242.131013           True   1690.0
...          ...         ...            ...      ...
549882         0  242.131013           True   1202.0
549915         0  242.131013           True   2176.0
549937         0  242.131013           True    885.0
549963         0  242.131013           True   1690.0
549989         0  242.131013           True   1220.0

                                            in.ahs_region  \
bldg_id
15       CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
79                               Non-CBSA Middle Atlantic
119      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
122      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
150                              Non-CBSA Middle Atlantic
...                                                   ...
549882                           Non-CBSA Middle Atlantic
549915                           Non-CBSA Middle Atlantic
549937                           Non-CBSA Middle Atlantic
549963                           Non-CBSA Middle Atlantic
549989                           Non-CBSA Middle Atlantic

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
15                                    4A
79                                    5A
119                                   4A
122                                   4A
150                                   5A
...                                  ...
549882                                5A
549915                                5A
549937                                5A
549963                                5A
549989                                5A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
15                                              4A                      Hour2
79                                              5A                     Hour10
119                                             4A                      Hour1
122                                             4A                     Hour18
150                                             5A                      Hour2
...                                            ...                        ...
549882                                          5A                      Hour5
549915                                          5A                      Hour0
549937                                          5A                     Hour20
549963                                          5A                     Hour13
549989                                          5A                     Hour22

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
15                 2                      Mixed-Humid  ...
79                 3                             Cold  ...
119                4                      Mixed-Humid  ...
122                4                      Mixed-Humid  ...
150                4                             Cold  ...
...              ...                              ...  ...
549882             2                             Cold  ...
549915             5                             Cold  ...
549937             4                             Cold  ...
549963             3                             Cold  ...
549989             3                             Cold  ...

        out.emissions.natural_gas.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                             1176.320144
79                                              625.962460
119                                            5540.594966
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                         6675.629132
549915                                            0.000000
549937                                         7002.945922
549963                                         8277.210267
549989                                            0.000000

        out.emissions.propane.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                                0.000000
119                                               0.000000
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                          223.856453

        out.emissions.electricity.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                             3520.864715
79                                             3334.140695
119                                            4179.118870
122                                            3794.589113
150                                           11378.222173
...                                                    ...
549882                                         2916.093184
549915                                        16728.421288
549937                                         3823.559604
549963                                         3992.118611
549989                                         2136.040859

        out.emissions.fuel_oil.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                            11194.437431
119                                               0.000000
122                                           13038.928166
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                         6042.544365

        out.emissions.natural_gas.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                             1176.320144
79                                              625.962460
119                                            5540.594966
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                         6675.629132
549915                                            0.000000
549937                                         7002.945922
549963                                         8277.210267
549989                                            0.000000

        out.emissions.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                                0.000000
119                                               0.000000
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                          223.856453

        out.emissions.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
15                                             2676.537445
79                                            13266.125327
119                                            7380.371515
122                                           14675.825549
150                                            4530.910597
...                                                    ...
549882                                         7916.182492
549915                                         6870.847124
549937                                         8577.560537
549963                                         9951.214681
549989                                         7176.439561

        out.emissions.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
15                                             4531.425424
79                                            14949.893770
119                                            9495.197860
122                                           16590.276103
150                                           10702.844907
...                                                    ...
549882                                         9422.157695
549915                                        15814.400458
549937                                        10516.078249
549963                                        11921.778240
549989                                         8281.270372

        out.emissions.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                             4127.883797
79                                            14585.037676
119                                            9035.427108
122                                           16204.985672
150                                            9290.264827
...                                                    ...
549882                                         9095.470037
549915                                        13772.445542
549937                                        10222.759114
549963                                        11608.667963
549989                                         8040.946248

        out.emissions.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg
bldg_id
15                                             4697.184859
79                                            15154.540586
119                                            9719.713836
122                                           16833.517280
150                                           11378.222173
...                                                    ...
549882                                         9591.722316
549915                                        16728.421288
549937                                        10826.505527
549963                                        12269.328878
549989                                         8402.441677

[17990 rows x 259 columns]


====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO: MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
In addition to the housing type and occupancy filters, the data has been filtered for fuel and technology
Please see the energy_consumption_and_metadata folder for more details on data processing.

We employ the df_enduse_refactored function to process the data and create a new dataframe, which is part of the 5-step data validation process:
1. Mask Initialization with initialize_validation_tracking()
2. Series Initialization with create_retrofit_only_series()
3. Valid-Only Calculation for qualifying homes
4. Valid-Only Updates using list-based collection
5. Final Masking with apply_final_masking()

Documentation for df_enduse_refactored function:
Creates a standardized energy usage DataFrame and applies data quality filters.

    This function creates a new DataFrame with standardized column names and structure,
    calculates total consumption by fuel type, creates data quality flags for analysis,
    and sets invalid consumption values to NaN.

    Args:
        df_baseline: The baseline DataFrame containing raw EUSS/ResStock data.

    Returns:
        A standardized DataFrame with processed consumption data and data quality flags.

    Raises:
        ValueError: If required columns are missing from the input DataFrame.

----------------------------------------------------------------

RESULTS OUTPUT (BASELINE):

Processing column: in.clothes_dryer
Initial data types: object
Data types after processing: object
Processing column: in.cooking_range
Initial data types: object
Data types after processing: object
Calculated total heating consumption

Creating data quality flags for all categories

--- Processing heating ---
Values in base_heating_fuel (top 5):
base_heating_fuel
Natural Gas    9704
Electricity    3374
Fuel Oil       3302
Other Fuel      820
Propane         781
Name: count, dtype: int64
  heating: Found 829 homes (4.6%) with invalid fuel types
  Invalid fuel types (top 5):
base_heating_fuel
Other Fuel    820
Name: count, dtype: int64
Values in heating_type (top 5):
heating_type
Natural Gas Fuel Furnace               6269
Fuel Oil Fuel Furnace                  2113
Natural Gas Fuel Wall/Floor Furnace    1551
Natural Gas Fuel Boiler                1436
Electricity Baseboard                  1364
Name: count, dtype: int64
Allowed values for heating:
['Electricity Baseboard', 'Electricity Electric Boiler', 'Electricity Electric Furnace', 'Fuel Oil Fuel Boiler', 'Fuel Oil Fuel Furnace', 'Natural Gas Fuel Boiler', 'Natural Gas Fuel Furnace', 'Propane Fuel Boiler', 'Propane Fuel Furnace']
  heating: Found 4141 homes (23.0%) with invalid technology types
  Invalid technology types (top 5):
heating_type
Natural Gas Fuel Wall/Floor Furnace    1551
Electricity ASHP                        786
Natural Gas Shared Heating              448
Electricity Shared Heating              194
Propane Fuel Wall/Floor Furnace         148
Name: count, dtype: int64
  heating: Total 4141 homes (23.0%) excluded from analysis

Total 4141 homes (23.0%) excluded from all categories

Applying data validation (baseline only):
Baseline calculation for heating:
  - 13849 homes have valid data
  - 4141 homes have invalid data (values will be NaN)
  base_electricity_heating_consumption: Masked 4141 values
  base_naturalGas_heating_consumption: Masked 4141 values
  base_fuelOil_heating_consumption: Masked 4141 values
  base_propane_heating_consumption: Masked 4141 values
  baseline_heating_consumption: Masked 3312 values

====================================================================================================================================================================
DATAFRAME: df_euss_am_baseline_home

         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
15                                   NaN       Electricity    Heat Pump
79                                   0.0       Electricity      Room AC
119                                  0.0       Electricity   Central AC
122                                  0.0       Electricity   Central AC
150                                  0.0       Electricity      Room AC
...                                  ...               ...          ...
549882                               NaN       Electricity      Room AC
549915                               0.0       Electricity   Central AC
549937                               0.0       Electricity   Central AC
549963                               0.0       Electricity   Central AC
549989                               0.0       Electricity   Central AC

        base_cooling_efficiency base_electricity_cooling_consumption  \
bldg_id
15                    Heat Pump                          1811.765355
79             Room AC, EER 9.8                          2496.965516
119                  AC, SEER 8                          1759.012562
122                 AC, SEER 13                          3876.451043

## MEASURE PACKAGE 3 (MP3): Space Conditioning Analysis
### Metadata, Space Heating, and Cooling annual energy consumption data for Measure Package 3.

In [6]:
# # Print debugging information
# print_debug = False

# if print_debug:
#     from cmu_tare_model.utils.create_sample_df import create_sample_df

In [7]:
import pandas as pd
import os

In [8]:
# Measure Package 3
menu_mp = 3
input_mp = 'upgrade03'
scenario_name = 'Basic-BAU'
cost_scenario = 'BAU Costs'
grid_scenario = 'Current Electricity Grid'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

filename = "upgrade03_metadata_and_annual_results.csv"
relative_path = os.path.join("cmu_tare_model", "data", "euss_data", "resstock_amy2018_release_1.1", "national", 'csv', filename)

file_path = os.path.join(PROJECT_ROOT, relative_path)

print(f"Retrieved data for filename: {filename}")
print(f"Located at filepath: {file_path}")
print("\n")

# Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
columns_to_string = {11: str, 61: str, 121: str, 103: str, 128: str, 129: str}
df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
print(f"DATAFRAME SIZE before applying any filters: {df_euss_am_mp3.shape}")

# Filter for occupied homes
occupancy_filter = df_euss_am_mp3['in.vacancy_status'] == 'Occupied'
df_euss_am_mp3 = df_euss_am_mp3.loc[occupancy_filter]
print(f"DATAFRAME SIZE after filtering for 'Occupied' homes: {df_euss_am_mp3.shape}")

# Filter for allowed housing types
house_type_filter = df_euss_am_mp3['in.geometry_building_type_recs'].isin(ALLOWED_HOUSING_TYPES)
df_euss_am_mp3 = df_euss_am_mp3.loc[house_type_filter]
print(f"Allowed housing types: {ALLOWED_HOUSING_TYPES}")
print(f"DATAFRAME SIZE after filtering for allowed housing types: {df_euss_am_mp3.shape}")

# National Level 
if menu_state == 'N':
    print("You chose to analyze all of the United States.")
    input_state = 'National'

# Filter down to state or city
else:
    print(f"You chose to filter for: {input_state}")
    state_filter = df_euss_am_mp3['in.state'].eq(input_state)
    df_euss_am_mp3 = df_euss_am_mp3.loc[state_filter]

    # Filter for the entire selected state
    if menu_city == 'N':
        print(f"You chose to analyze all of state: {input_state}")
        
    # Filter to a city within the selected state
    else:
        print(f"You chose to filter for: {input_state}, {input_cityFilter}")
        city_filter = df_euss_am_mp3['in.city'].eq(f"{input_state}, {input_cityFilter}")
        df_euss_am_mp3 = df_euss_am_mp3.loc[city_filter]

# Display the filtered dataframe
# Display the filtered dataframe
print(f"DATAFRAME SIZE after applying geographic filter: {df_euss_am_mp3.shape}")
print(df_euss_am_mp3)

====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario Basic-BAU:
Basic Retrofit: Measure Package 3
BAU Costs
Current Electricity Grid
====================================================================================================================================================================

Retrieved data for filename: upgrade03_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\upgrade03_metadata_and_annual_results.csv

C:\Users\jorda\AppData\Local\Temp\ipykernel_33700\2869588233.py:30: DtypeWarning: Columns (113) have mixed types. Specify dtype option on import or set low_memory=False.
  df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)

DATAFRAME SIZE before applying any filters: (548916, 343)
DATAFRAME SIZE after filtering for 'Occupied' homes: (482597, 343)
Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 343)
You chose to filter for: PA
You chose to analyze all of state: PA
DATAFRAME SIZE after applying geographic filter: (17990, 343)
         upgrade      weight  applicability  in.sqft  \
bldg_id
15             3  242.131013           True    333.0
79             3  242.131013           True   1220.0
119            3  242.131013           True   2152.0
122            3  242.131013           True   2176.0
150            3  242.131013           True   1690.0
...          ...         ...            ...      ...
549882         3  242.131013           True   1202.0
549915         3  242.131013           True   2176.0
549937         3  242.131013           True    885.0
549963         3  242.131013           True   1690.0
549989         3  242.131013           True   1220.0

                                            in.ahs_region  \
bldg_id
15       CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
79                               Non-CBSA Middle Atlantic
119      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
122      CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
150                              Non-CBSA Middle Atlantic
...                                                   ...
549882                           Non-CBSA Middle Atlantic
549915                           Non-CBSA Middle Atlantic
549937                           Non-CBSA Middle Atlantic
549963                           Non-CBSA Middle Atlantic
549989                           Non-CBSA Middle Atlantic

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
15                                    4A
79                                    5A
119                                   4A
122                                   4A
150                                   5A
...                                  ...
549882                                5A
549915                                5A
549937                                5A
549963                                5A
549989                                5A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
15                                              4A                      Hour2
79                                              5A                     Hour10
119                                             4A                      Hour1
122                                             4A                     Hour18
150                                             5A                      Hour2
...                                            ...                        ...
549882                                          5A                      Hour5
549915                                          5A                      Hour0
549937                                          5A                     Hour20
549963                                          5A                     Hour13
549989                                          5A                     Hour22

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
15                 2                      Mixed-Humid  ...
79                 3                             Cold  ...
119                4                      Mixed-Humid  ...
122                4                      Mixed-Humid  ...
150                4                             Cold  ...
...              ...                              ...  ...
549882             2                             Cold  ...
549915             5                             Cold  ...
549937             4                             Cold  ...
549963             3                             Cold  ...
549989             3                             Cold  ...

        out.emissions_reduction.electricity.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                              296.179942
79                                            -7253.142938
119                                           -2387.169100
122                                           -6121.419088
150                                            6000.625626
...                                                    ...
549882                                        -2936.689906
549915                                         5299.364111
549937                                        -3729.565286
549963                                        -8258.842044
549989                                        -3479.128774

        out.emissions_reduction.fuel_oil.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                0.000000
79                                            11194.437431
119                                               0.000000
122                                           12313.868474
150                                               0.000000
...                                                    ...
549882                                            0.000000
549915                                            0.000000
549937                                            0.000000
549963                                            0.000000
549989                                         4845.319963

        out.emissions_reduction.natural_gas.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                               -0.000454
79                                               -0.472643
119                                            4085.115934
122                                               0.000000
150                                               0.000000
...                                                    ...
549882                                         5516.313713
549915                                            0.000000
549937                                         3563.914260
549963                                         7364.344736
549989                                            0.000000

        out.emissions_reduction.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                                     0.0
79                                                     0.0
119                                                    0.0
122                                                    0.0
150                                                    0.0
...                                                    ...
549882                                                 0.0
549915                                                 0.0
549937                                                 0.0
549963                                                 0.0
549989                                                 0.0

        out.emissions_reduction.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
15                                              128.915034
79                                             8421.069809
119                                            3222.822323
122                                            9859.088256
150                                            2314.341216
...                                                    ...
549882                                         4275.117613
549915                                         2102.820661
549937                                         2038.356567
549963                                         4029.211128
549989                                         3506.852793

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
15                                              284.539854
79                                             4344.938179
119                                            1831.842765
122                                            6477.476398
150                                            5625.258889
...                                                    ...
549882                                         2669.143436
549915                                         4942.660885
549937                                          123.119938
549963                                         -222.975576
549989                                         1571.796445

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
15                                              250.927753
79                                             5288.628487
119                                            2169.696506
122                                            7286.613519
150                                            4855.759845
...                                                    ...
549882                                         3030.162593
549915                                         4281.938281
549937                                          536.774407
549963                                          647.559354
549989                                         2023.116317

        out.emissions_reduction.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
15                                              296.179488
79                                             3940.821850
119                                            1697.946834
122                                            6192.449386
150                                            6000.625626
...                                                    ...
549882                                         2579.623807
549915                                         5299.364111
549937                                         -165.651026
549963                                         -894.497308
549989                                         1366.191189

        upgrade.hvac_cooling_efficiency    upgrade.hvac_heating_efficiency
bldg_id
15                            Heat Pump            ASHP, SEER 15, 9.0 HSPF
79                            Heat Pump            ASHP, SEER 15, 9.0 HSPF
119                           Heat Pump            ASHP, SEER 15, 9.0 HSPF
122                           Heat Pump            ASHP, SEER 15, 9.0 HSPF
150                           Heat Pump  MSHP, SEER 15, 9.0 HSPF, Max Load
...                                 ...                                ...
549882                        Heat Pump  MSHP, SEER 15, 9.0 HSPF, Max Load
549915                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549937                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549963                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549989                        Heat Pump            ASHP, SEER 15, 9.0 HSPF

[17990 rows x 343 columns]

In [9]:
# TRANE Analysis: No cooking data needed for space conditioning analysis
# Cooking equipment is excluded from this workflow
df_euss_am_mp7 = None  # Set to None for compatibility with legacy functions

# Project Future Energy Consumption

In [10]:
from cmu_tare_model.energy_consumption_and_metadata.process_euss_data import df_enduse_compare

print(F"""
====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE {menu_mp} (MP{menu_mp})
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp3.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied. 
      - df_euss_am_mp3_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp3_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.
      
Documentation for df_enduse_compare function:
{df_enduse_compare.__doc__}
----------------------------------------------------------------

RESULTING DATAFRAME:
""")

# df_enduse_compare(df_mp, category, df_baseline):
df_euss_am_mp3_home = df_enduse_compare(
    df_mp = df_euss_am_mp3,
    input_mp=input_mp,
    menu_mp=menu_mp,
    df_baseline = df_euss_am_baseline_home,
    df_cooking_range=df_euss_am_mp7,
    )

====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE 3 (MP3)
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp3.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied.
      - df_euss_am_mp3_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp3_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.

Documentation for df_enduse_compare function:
Creates a comparison DataFrame by merging multiple DataFrames based on measure packages.

    This function constructs a new DataFrame (df_compare) that includes columns
    from df_mp, df_cooking_range, and merges them with df_baseline to compare
    baseline vs. measure package outputs.

    Only includes columns for equipment categories present in EQUIPMENT_SPECS.

    Args:
        df_mp: The main DataFrame containing modeling parameters and outputs.
        input_mp: The input measure package ID (e.g., 'upgrade09', 'upgrade10').
        menu_mp: The menu measure package number.
        df_baseline: The baseline DataFrame to merge with df_compare.
        df_cooking_range: Additional DataFrame for cooking range parameters/outputs.

    Returns:
        A merged DataFrame (df_compare) that includes relevant columns for
        baseline and measure packages comparison.

----------------------------------------------------------------

RESULTING DATAFRAME:


Applying combined validation (data quality + retrofit status):
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)
  mp3_heating_consumption: Masked 4141 values

# PUBLIC IMPACTS: Climate and Health Damages
## Scenarios: No IRA and IRA-Reference

In [11]:
from cmu_tare_model.public_impact.calculate_lifetime_climate_impacts_sensitivity import calculate_lifetime_climate_impacts
from cmu_tare_model.public_impact.calculate_lifetime_health_impacts_sensitivity import calculate_lifetime_health_impacts

print(f"""
====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================

""")

# Make copies from scenario consumption to keep df smaller
print("\n", "Creating dataframe to store marginal damages calculations ...")
# Climate damages: No IRA and IRA-Reference
df_mp3_noIRA_damages_climate = df_euss_am_mp3_home.copy()
df_mp3_IRA_damages_climate = df_euss_am_mp3_home.copy()

# Health damages: No IRA and IRA-Reference
df_mp3_noIRA_damages_health = df_euss_am_mp3_home.copy()
df_mp3_IRA_damages_health = df_euss_am_mp3_home.copy()

====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================



 Creating dataframe to store marginal damages calculations ...

In [12]:
# Health Impacts: Baseline Scenario
print(f"""
====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
{df_euss_am_baseline_home}
      
df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
{df_baseline_damages_health}

""")

====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
         square_footage census_region  census_division census_division_recs  \
bldg_id
15                333.0     Northeast  Middle Atlantic      Middle Atlantic
79               1220.0     Northeast  Middle Atlantic      Middle Atlantic
119              2152.0     Northeast  Middle Atlantic      Middle Atlantic
122              2176.0     Northeast  Middle Atlantic      Middle Atlantic
150              1690.0     Northeast  Middle Atlantic      Middle Atlantic
...                 ...           ...              ...                  ...
549882           1202.0     Northeast  Middle Atlantic      Middle Atlantic
549915           2176.0     Northeast  Middle Atlantic      Middle Atlantic
549937            885.0     Northeast  Middle Atlantic      Middle Atlantic
549963           1690.0     Northeast  Middle Atlantic      Middle Atlantic
549989           1220.0     Northeast  Middle Atlantic      Middle Atlantic

        building_america_climate_zone  reeds_balancing_area gea_region state  \
bldg_id
15                        Mixed-Humid                   122      RFCEc    PA
79                               Cold                   122      RFCEc    PA
119                       Mixed-Humid                   122      RFCEc    PA
122                       Mixed-Humid                   122      RFCEc    PA
150                              Cold                   122      RFCEc    PA
...                               ...                   ...        ...   ...
549882                           Cold                   122      RFCEc    PA
549915                           Cold                   122      RFCEc    PA
549937                           Cold                   115      RFCWc    PA
549963                           Cold                   115      RFCWc    PA
549989                           Cold                   122      RFCEc    PA

                            city urbanicity  ...  \
bldg_id                                      ...
15                  Philadelphia      Urban  ...
79         Not in a census Place   Suburban  ...
119        Not in a census Place   Suburban  ...
122      In another census Place   Suburban  ...
150      In another census Place      Rural  ...
...                          ...        ...  ...
549882     Not in a census Place   Suburban  ...
549915                 Lancaster   Suburban  ...
549937   In another census Place      Rural  ...
549963   In another census Place   Suburban  ...
549989     Not in a census Place      Rural  ...

        baseline_heating_lifetime_damages_climate_srmer_upper   county_key  \
bldg_id
15                                                     NaN     (42101, PA)
79                                                63363.98     (42085, PA)
119                                               23121.05     (42045, PA)
122                                               69700.38     (42045, PA)
150                                               97912.17     (42119, PA)
...                                                    ...             ...
549882                                                 NaN     (42011, PA)
549915                                           106058.33     (42071, PA)
549937                                            20172.40     (42005, PA)
549963                                            41683.92     (42129, PA)
549989                                            27427.38     (42111, PA)

        baseline_heating_lifetime_damages_health_ap2_acs  \
bldg_id
15                                                   NaN
79                                               1087.28
119                                               438.35
122                                              2861.03
150                                              3887.41
...                                                  ...
549882                                               NaN
549915                                           6471.81
549937                                            168.62
549963                                            744.97
549989                                            530.04

        baseline_heating_lifetime_damages_health_ap2_h6c  \
bldg_id
15                                                   NaN
79                                               2793.39
119                                              1126.21
122                                              7350.73
150                                              9987.75
...                                                  ...
549882                                               NaN
549915                                          16627.89
549937                                            433.18
549963                                           1913.98
549989                                           1361.78

        baseline_heating_lifetime_damages_health_easiur_acs  \
bldg_id
15                                                     NaN
79                                                 3346.04
119                                                1984.53
122                                                8525.68
150                                                6065.71
...                                                    ...
549882                                                 NaN
549915                                             7761.62
549937                                              721.19
549963                                             1543.61
549989                                             1208.78

         baseline_heating_lifetime_damages_health_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                 8596.90
119                                                5098.84
122                                               21905.05
150                                               15584.52
...                                                    ...
549882                                                 NaN
549915                                            19941.84
549937                                             1852.93
549963                                             3965.93
549989                                             3105.68

         baseline_heating_lifetime_damages_health_inmap_acs  \
bldg_id
15                                                     NaN
79                                                 2601.41
119                                                2364.34
122                                               10769.96
150                                                9496.99
...                                                    ...
549882                                                 NaN
549915                                             8631.91
549937                                              471.58
549963                                             1463.42
549989                                              911.37

        baseline_heating_lifetime_damages_health_inmap_h6c fuel_type_heating  \
bldg_id
15                                                     NaN       electricity
79                                                 6683.68           fuelOil
119                                                6074.71        naturalGas
122                                               27671.34           fuelOil
150                                               24400.59       electricity
...                                                    ...               ...
549882                                                 NaN        naturalGas
549915                                            22177.89       electricity
549937                                             1211.59        naturalGas
549963                                             3759.89        naturalGas
549989                                             2341.54           fuelOil

        baseline_heating_lifetime_fuel_cost
bldg_id
15                                      NaN
79                                 51485.89
119                                 9692.04
122                                56634.48
150                                48835.85
...                                     ...
549882                                  NaN
549915                             52898.91
549937                              8456.00
549963                             17473.34
549989                             22285.90

[17990 rows x 57 columns]

df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
15             False            False               False                True
79              True             True                True                True
119             True             True                True                True
122             True             True                True                True
150             True             True                True                True
...              ...              ...                 ...                 ...
549882         False            False               False                True
549915          True             True                True                True
549937          True             True                True                True
549963          True             True                True                True
549989          True             True                True                True

         baseline_2024_heating_damages_so2_ap2_acs  \
bldg_id
15                                             NaN
79                                            4.05
119                                           1.40
122                                           7.91
150                                          87.65
...                                            ...
549882                                         NaN
549915                                      139.84
549937                                        0.65
549963                                        3.12
549989                                        2.19

         baseline_2024_heating_damages_nox_ap2_acs  \
bldg_id
15                                             NaN
79                                           27.97
119                                           5.40
122                                          17.25
150                                           5.62
...                                            ...
549882                                         NaN
549915                                       12.60
549937                                        5.74
549963                                       15.82
549989                                        9.67

         baseline_2024_heating_damages_pm25_ap2_acs  \
bldg_id
15                                              NaN
79                                            37.61
119                                           21.28
122                                          158.07
150                                           22.93
...                                             ...
549882                                          NaN
549915                                        45.29
549937                                         4.40
549963                                        28.78
549989                                        22.08

         baseline_2024_heating_damages_health_ap2_acs  \
bldg_id
15                                                NaN
79                                              69.64
119                                             28.07
122                                            183.24
150                                            116.20
...                                               ...
549882                                            NaN
549915                                         197.73
549937                                          10.80
549963                                          47.71
549989                                          33.95

         baseline_2024_heating_damages_so2_ap2_h6c  \
bldg_id
15                                             NaN
79                                           10.42
119                                           3.59
122                                          20.33
150                                         225.20
...                                            ...
549882                                         NaN
549915                                      359.29
549937                                        1.68
549963                                        8.01
549989                                        5.64

         baseline_2024_heating_damages_nox_ap2_h6c  ...  \
bldg_id                                             ...
15                                             NaN  ...
79                                           71.85  ...
119                                          13.86  ...
122                                          44.31  ...
150                                          14.43  ...
...                                            ...  ...
549882                                         NaN  ...
549915                                       32.36  ...
549937                                       14.75  ...
549963                                       40.63  ...
549989                                       24.84  ...

         baseline_2038_heating_damages_so2_inmap_h6c  \
bldg_id
15                                               NaN
79                                              8.85
119                                             3.08
122                                            17.45
150                                           769.97
...                                              ...
549882                                           NaN
549915                                        688.81
549937                                          1.49
549963                                          3.50
549989                                          4.50

         baseline_2038_heating_damages_nox_inmap_h6c  \
bldg_id
15                                               NaN
79                                            371.29
119                                           284.59
122                                           909.51
150                                           114.32
...                                              ...
549882                                           NaN
549915                                         95.83
549937                                         73.96
549963                                        221.19
549989                                        128.80

         baseline_2038_heating_damages_pm25_inmap_h6c  \
bldg_id
15                                                NaN
79                                              83.20
119                                            133.46
122                                            991.32
150                                            160.13
...                                               ...
549882                                            NaN
549915                                         171.86
549937                                           8.54
549963                                          35.95
549989                                          29.02

         baseline_2038_heating_damages_health_inmap_h6c  \
bldg_id
15                                                  NaN
79                                               463.34
119                                              421.12
122                                             1918.28
150                                             1044.43
...                                                 ...
549882                                              NaN
549915                                           956.50
549937                                            83.99
549963                                           260.65
549989                                           162.32

         baseline_heating_lifetime_damages_health_ap2_acs  \
bldg_id
15                                                    NaN
79                                                1087.28
119                                                438.35
122                                               2861.03
150                                               3887.41
...                                                   ...
549882                                                NaN
549915                                            6471.81
549937                                             168.62
549963                                             744.97
549989                                             530.04

         baseline_heating_lifetime_damages_health_ap2_h6c  \
bldg_id
15                                                    NaN
79                                                2793.39
119                                               1126.21
122                                               7350.73
150                                               9987.75
...                                                   ...
549882                                                NaN
549915                                           16627.89
549937                                             433.18
549963                                            1913.98
549989                                            1361.78

         baseline_heating_lifetime_damages_health_easiur_acs  \
bldg_id
15                                                     NaN
79                                                 3346.04
119                                                1984.53
122                                                8525.68
150                                                6065.71
...                                                    ...
549882                                                 NaN
549915                                             7761.62
549937                                              721.19
549963                                             1543.61
549989                                             1208.78

         baseline_heating_lifetime_damages_health_easiur_h6c  \
bldg_id
15                                                     NaN
79                                                 8596.90
119                                                5098.84
122                                               21905.05
150                                               15584.52
...                                                    ...
549882                                                 NaN
549915                                            19941.84
549937                                             1852.93
549963                                             3965.93
549989                                             3105.68

         baseline_heating_lifetime_damages_health_inmap_acs  \
bldg_id
15                                                     NaN
79                                                 2601.41
119                                                2364.34
122                                               10769.96
150                                                9496.99
...                                                    ...
549882                                                 NaN
549915                                             8631.91
549937                                              471.58
549963                                             1463.42
549989                                              911.37

         baseline_heating_lifetime_damages_health_inmap_h6c
bldg_id
15                                                     NaN

In [13]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp3_home, df_mp3_noIRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )

df_euss_am_mp3_home, df_mp3_noIRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp3_home, df_mp3_IRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )


df_euss_am_mp3_home, df_mp3_IRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
Post-Retrofit (mp3) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well. 
      
CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp3_noIRA_damages_climate
{df_mp3_noIRA_damages_climate}

Climate Damages (IRA): df_mp3_IRA_damages_climate
{df_mp3_IRA_damages_climate}

HEALTH DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Health Damages (No IRA): df_mp3_noIRA_damages_health
{df_mp3_noIRA_damages_health}

Health Damages (IRA): df_mp3_IRA_damages_health
{df_mp3_IRA_damages_health}

SUMMARY DATAFRAME FOR mp3: df_euss_am_mp3_home
{df_euss_am_mp3_home}
====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

====================================================================================================================================================================
Post-Retrofit (mp3) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well.

CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp3_noIRA_damages_climate
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
15             False            False               False                True
79              True             True                True                True
119             True             True                True                True
122             True             True                True                True
150             True             True                True                True
...              ...              ...                 ...                 ...
549882         False            False               False                True
549915          True             True                True                True
549937          True             True                True                True
549963          True             True                True                True
549989          True             True                True                True

         preIRA_mp3_2024_heating_mt_co2e_lrmer  \
bldg_id
15                                         NaN
79                                        4.60
119                                       2.51
122                                       7.40
150                                       3.63
...                                        ...
549882                                     NaN
549915                                    4.12
549937                                    2.23
549963                                    3.76
549989                                    1.38

         preIRA_mp3_2024_heating_damages_climate_lrmer_lower  \
bldg_id
15                                                     NaN
79                                                  298.15
119                                                 162.47
122                                                 479.10
150                                                 234.88
...                                                    ...
549882                                                 NaN
549915                                              266.65
549937                                              144.09
549963                                              243.41
549989                                               89.39

         preIRA_mp3_2024_heating_damages_climate_lrmer_central  \
bldg_id
15                                                     NaN
79                                                 1095.04
119                                                 596.72
122                                                1759.62
150                                                 862.63
...                                                    ...
549882                                                 NaN
549915                                              979.32
549937                                              529.20
549963                                              893.99
549989                                              328.32

         preIRA_mp3_2024_heating_damages_climate_lrmer_upper  \
bldg_id
15                                                     NaN
79                                                 1767.24
119                                                 963.02
122                                                2839.78
150                                                1392.17
...                                                    ...
549882                                                 NaN
549915                                             1580.48
549937                                              854.06
549963                                             1442.78
549989                                              529.87

         preIRA_mp3_2024_heating_mt_co2e_srmer  \
bldg_id
15                                         NaN
79                                        6.72
119                                       3.66
122                                      10.80
150                                       5.29
...                                        ...
549882                                     NaN
549915                                    6.01
549937                                    3.57
549963                                    6.04
549989                                    2.01

         preIRA_mp3_2024_heating_damages_climate_srmer_lower  ...  \
bldg_id                                                       ...
15                                                     NaN    ...
79                                                  435.03    ...
119                                                 237.06    ...
122                                                 699.05    ...
150                                                 342.70    ...
...                                                    ...    ...
549882                                                 NaN    ...
549915                                              389.06    ...
549937                                              231.42    ...
549963                                              390.94    ...
549989                                              130.43    ...

         preIRA_mp3_heating_avoided_damages_climate_lrmer_upper  \
bldg_id
15                                                     NaN
79                                                43740.99
119                                               12427.85
122                                               38168.12
150                                               35219.96
...                                                    ...
549882                                                 NaN
549915                                            37345.38
549937                                            10074.45
549963                                            24625.14
549989                                            21543.85

         preIRA_mp3_heating_avoided_mt_co2e_lrmer  \
bldg_id
15                                            NaN
79                                         104.64
119                                         29.63
122                                         91.02
150                                         85.30
...                                           ...
549882                                        NaN
549915                                      90.46
549937                                      24.12
549963                                      59.01
549989                                      51.62

         preIRA_mp3_heating_lifetime_mt_co2e_srmer  \
bldg_id
15                                             NaN
79                                           91.23
119                                          49.71
122                                         146.60
150                                          71.87
...                                            ...
549882                                         NaN
549915                                       81.59
549937                                       48.52
549963                                       81.97
549989                                       27.35

         preIRA_mp3_heating_lifetime_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                 6716.36
119                                                3659.96
122                                               10792.55
150                                                5290.92
...                                                    ...
549882                                                 NaN
549915                                             6006.59
549937                                             3570.34
549963                                             6031.49
549989                                             2013.76

         preIRA_mp3_heating_avoided_damages_climate_srmer_lower  \
bldg_id
15                                                     NaN
79                                                 4521.23
119                                                 440.56
122                                                1568.80
150                                               12054.74
...                                                    ...
549882                                                 NaN
549915                                            12782.20
549937                                                7.23
549963                                             1361.15
549989                                             2850.48

         preIRA_mp3_heating_lifetime_damages_climate_srmer_central  \
bldg_id
15                                                     NaN
79                                                23869.52
119                                               13007.27
122                                               38356.02
150                                               18803.60
...                                                    ...
549882                                                 NaN
549915                                            21347.04
549937                                            12690.34
549963                                            21438.19
549989                                             7156.76

         preIRA_mp3_heating_avoided_damages_climate_srmer_central  \
bldg_id
15                                                     NaN
79                                                16039.31
119                                                1555.17
122                                                5543.69
150                                               42841.76
...                                                    ...
549882                                                 NaN
549915                                            45427.14
549937                                               14.93
549963                                             4815.79
549989                                            10117.95

         preIRA_mp3_heating_lifetime_damages_climate_srmer_upper  \
bldg_id
15                                                     NaN
79                                                37912.28
119                                               20659.62
122                                               60921.38
150                                               29866.02
...                                                    ...
549882                                                 NaN
549915                                            33905.79
549937                                            20157.63
549963                                            34052.92
549989                                            11367.18

         preIRA_mp3_heating_avoided_damages_climate_srmer_upper  \
bldg_id
15                                                     NaN
79                                                25451.70
119                                                2461.43
122                                                8779.00
150                                               68046.15
...                                                    ...
549882                                                 NaN
549915                                            72152.54
549937                                               14.77
549963                                             7631.00
549989                                            16060.20

         preIRA_mp3_heating_avoided_mt_co2e_srmer
bldg_id
15                                            NaN
79                                          60.94
119                                          5.82
122                                         20.79
150                                        163.74
...                                           ...
549882                                        NaN
549915                                     173.62
549937                                      -0.07
549963                                      18.14
549989                                      38.52

[17990 rows x 140 columns]

Climate Damages (IRA): df_mp3_IRA_damages_climate
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
15             False            False               False                True
79              True             True                True                True
119             True             True                True                True
122             True             True                True                True
150             True             True                True                True
...              ...              ...                 ...                 ...
549882         False            False               False                True
549915          True             True                True                True
549937          True             True                True                True
549963          True             True                True                True
549989          True             True                True                True

         iraRef_mp3_2024_heating_mt_co2e_lrmer  \
bldg_id
15                                         NaN
79                                        3.27
119                                       1.78
122                                       5.26
150                                       2.58
...                                        ...
549882                                     NaN
549915                                    2.93
549937                                    1.70
549963                                    2.88
549989                                    0.98

         iraRef_mp3_2024_heating_damages_climate_lrmer_lower  \
bldg_id
15                                                     NaN
79                                                  212.00
119                                                 115.53
122                                                 340.67
150                                                 167.01
...                                                    ...
549882                                                 NaN
549915                                              189.60
549937                                              110.35
549963                                              186.42
549989                                               63.56

         iraRef_mp3_2024_heating_damages_climate_lrmer_central  \
bldg_id
15                                                     NaN
79                                                  778.62
119                                                 424.30
122                                                1251.17
150                                                 613.37
...                                                    ...
549882                                                 NaN
549915                                              696.34
549937                                              405.29
549963                                              684.67
549989                                              233.45

         iraRef_mp3_2024_heating_damages_climate_lrmer_upper  \
bldg_id
15                                                     NaN
79                                                 1256.59
119                                                 684.75
122                                                2019.22
150                                                 989.90
...                                                    ...
549882                                                 NaN
549915                                             1123.79
549937                                              654.09
549963                                             1104.97
549989                                              376.76

         iraRef_mp3_2024_heating_mt_co2e_srmer  \
bldg_id
15                                         NaN
79                                        6.73
119                                       3.67
122                                      10.82
150                                       5.30
...                                        ...
549882                                     NaN
549915                                    6.02
549937                                    3.48
549963                                    5.87
549989                                    2.02

         iraRef_mp3_2024_heating_damages_climate_srmer_lower  ...  \
bldg_id                                                       ...
15                                                     NaN    ...
79                                                  436.00    ...
119                                                 237.59    ...
122                                                 700.61    ...
150                                                 343.46    ...
...                                                    ...    ...

# PRIVATE IMPACTS: FUEL COSTS
## Scenarios: No IRA and IRA-Reference

In [14]:
from cmu_tare_model.private_impact.calculate_lifetime_fuel_costs import calculate_lifetime_fuel_costs

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:
{calculate_lifetime_fuel_costs.__doc__}

====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference

""")

print("\n", "Creating dataframe to store annual fuel cost calculations ...")
# Annual fuel costs: No IRA and IRA-Reference
df_mp3_fuel_costs_noIRA = df_euss_am_mp3_home.copy()
df_mp3_fuel_costs_IRA = df_euss_am_mp3_home.copy()

====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:

    Calculate lifetime fuel costs for each equipment category.

    This function processes each equipment category over its lifetime, computing annual
    and lifetime fuel costs. Results are combined into two DataFrames:
    a main summary (df_main) and a detailed annual breakdown (df_detailed).

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    Args:
        df: Input DataFrame containing equipment consumption data, region info, etc.
        menu_mp: Measure package identifier (0 for baseline, nonzero for different scenarios).
        policy_scenario: Determines fuel price scenario inputs
            (e.g., 'No Inflation Reduction Act' or 'AEO2023 Reference Case').
        df_baseline_costs: Optional DataFrame with baseline costs for computing operational savings.
            Default is None.
        verbose: Whether to print detailed processing information. Default is True.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Main summary of lifetime fuel costs (rounded to 2 decimals).
            - df_detailed: Detailed annual and lifetime results (rounded to 2 decimals).

    Raises:
        RuntimeError: If processing fails at the category or year level.
        ValueError: If an invalid policy_scenario is provided.
        KeyError: If required columns are missing from the input DataFrame.


====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference



 Creating dataframe to store annual fuel cost calculations ...

In [15]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp3_home, df_mp3_noIRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )

print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp3_home, df_mp3_IRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )


print(f"""  
====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp3_noIRA_fuel_costs
{df_mp3_noIRA_fuel_costs}

FUEL COSTS (IRA): df_mp3_IRA_fuel_costs
{df_mp3_IRA_fuel_costs}

SUMMARY DATAFRAME FOR mp3: df_euss_am_mp3_home
{df_euss_am_mp3_home}

====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 3 columns for category 'heating'
Dropping 1 overlapping columns from original DataFrame.

Verifying masking for all calculated columns:
Masking 48 columns for category 'heating'

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 3 columns for category 'heating'
Dropping 1 overlapping columns from original DataFrame.

Verifying masking for all calculated columns:
Masking 48 columns for category 'heating'

====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp3_noIRA_fuel_costs
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
15             False            False               False                True
79              True             True                True                True
119             True             True                True                True
122             True             True                True                True
150             True             True                True                True
...              ...              ...                 ...                 ...
549882         False            False               False                True
549915          True             True                True                True
549937          True             True                True                True
549963          True             True                True                True
549989          True             True                True                True

         preIRA_mp3_2024_heating_fuel_cost  baseline_2024_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1239.47                          3819.58
119                                 675.42                           731.14
122                                1991.70                          4201.54
150                                 976.41                          3201.04
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1108.48                          3467.36
549937                              599.20                           637.89
549963                             1012.25                          1318.13
549989                              371.63                          1653.32

         preIRA_mp3_2025_heating_fuel_cost  baseline_2025_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1238.91                          3591.62
119                                 675.12                           691.86
122                                1990.80                          3950.78
150                                 975.97                          3199.60
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1107.98                          3465.80
549937                              598.93                           603.63
549963                             1011.79                          1247.32
549989                              371.46                          1554.65

         preIRA_mp3_2026_heating_fuel_cost  baseline_2026_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1226.95                          3512.33
119                                 668.61                           661.81
122                                1971.59                          3863.56
150                                 966.55                          3168.72
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1097.29                          3432.36
549937                              593.15                           577.41
549963                             1002.03                          1193.15
549989                              367.88                          1520.33

         ...  baseline_2035_heating_fuel_cost  \
bldg_id  ...
15       ...                              NaN
79       ...                          3363.08
119      ...                           629.88
122      ...                          3699.39
150      ...                          3353.88
...      ...                              ...
549882   ...                              NaN
549915   ...                          3632.92
549937   ...                           549.55
549963   ...                          1135.58
549989   ...                          1455.72

         preIRA_mp3_2036_heating_fuel_cost  baseline_2036_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1291.97                          3365.74
119                                 704.04                           624.40
122                                2076.08                          3702.31
150                                1017.77                          3336.65
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1155.44                          3614.25
549937                              624.59                           544.77
549963                             1055.13                          1125.70
549989                              387.37                          1456.87

         preIRA_mp3_2037_heating_fuel_cost  baseline_2037_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1293.71                          3361.04
119                                 704.98                           628.12
122                                2078.86                          3697.14
150                                1019.14                          3341.13
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1156.99                          3619.10
549937                              625.43                           548.02
549963                             1056.55                          1132.41
549989                              387.89                          1454.84

         preIRA_mp3_2038_heating_fuel_cost  baseline_2038_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1299.46                          3355.30
119                                 708.12                           629.29
122                                2088.11                          3690.83
150                                1023.67                          3355.99
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1162.14                          3635.20
549937                              628.21                           549.04
549963                             1061.25                          1134.52
549989                              389.62                          1452.36

         preIRA_mp3_heating_lifetime_fuel_cost  \
bldg_id
15                                         NaN
79                                    18909.58
119                                   10304.44
122                                   30385.87
150                                   14896.33
...                                        ...
549882                                     NaN
549915                                16911.26
549937                                 9141.58
549963                                15443.16
549989                                 5669.63

         preIRA_mp3_heating_lifetime_savings_fuel_cost  \
bldg_id
15                                                 NaN
79                                            32576.31
119                                            -612.40
122                                           26248.61
150                                           33939.52
...                                                ...
549882                                             NaN
549915                                        35987.65
549937                                         -685.58
549963                                         2030.18
549989                                        16616.27

         baseline_heating_lifetime_fuel_cost
bldg_id
15                                       NaN
79                                  51485.89
119                                  9692.04
122                                 56634.48
150                                 48835.85
...                                      ...
549882                                   NaN
549915                              52898.91
549937                               8456.00
549963                              17473.34
549989                              22285.90

[17990 rows x 37 columns]

FUEL COSTS (IRA): df_mp3_IRA_fuel_costs
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
15             False            False               False                True
79              True             True                True                True
119             True             True                True                True
122             True             True                True                True
150             True             True                True                True
...              ...              ...                 ...                 ...
549882         False            False               False                True
549915          True             True                True                True
549937          True             True                True                True
549963          True             True                True                True
549989          True             True                True                True

         iraRef_mp3_2024_heating_fuel_cost  baseline_2024_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1249.74                          3819.58
119                                 681.02                           731.14
122                                2008.21                          4201.54
150                                 984.50                          3201.04
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1117.67                          3467.36
549937                              604.17                           637.89
549963                             1020.64                          1318.13
549989                              374.71                          1653.32

         iraRef_mp3_2025_heating_fuel_cost  baseline_2025_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1232.84                          3591.62
119                                 671.81                           691.86
122                                1981.06                          3950.78
150                                 971.19                          3199.60
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1102.56                          3465.80
549937                              596.00                           603.63
549963                             1006.84                          1247.32
549989                              369.64                          1554.65

         iraRef_mp3_2026_heating_fuel_cost  baseline_2026_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1213.42                          3512.33
119                                 661.23                           661.81
122                                1949.85                          3863.56
150                                 955.89                          3168.72
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1085.19                          3432.36
549937                              586.61                           577.41
549963                              990.98                          1193.15
549989                              363.82                          1520.33

         ...  baseline_2035_heating_fuel_cost  \
bldg_id  ...
15       ...                              NaN
79       ...                          3363.08
119      ...                           629.88
122      ...                          3699.39
150      ...                          3353.88
...      ...                              ...
549882   ...                              NaN
549915   ...                          3632.92
549937   ...                           549.55
549963   ...                          1135.58
549989   ...                          1455.72

         iraRef_mp3_2036_heating_fuel_cost  baseline_2036_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1254.09                          3365.74
119                                 683.40                           624.40
122                                2015.21                          3702.31
150                                 987.93                          3336.65
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1121.56                          3614.25
549937                              606.27                           544.77
549963                             1024.20                          1125.70
549989                              376.01                          1456.87

         iraRef_mp3_2037_heating_fuel_cost  baseline_2037_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1255.11                          3361.04
119                                 683.95                           628.12
122                                2016.85                          3697.14
150                                 988.74                          3341.13
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1122.48                          3619.10
549937                              606.77                           548.02
549963                             1025.03                          1132.41
549989                              376.32                          1454.84

         iraRef_mp3_2038_heating_fuel_cost  baseline_2038_heating_fuel_cost  \
bldg_id
15                                     NaN                              NaN
79                                 1264.43                          3355.30
119                                 689.03                           629.29
122                                2031.82                          3690.83
150                                 996.08                          3355.99
...                                    ...                              ...
549882                                 NaN                              NaN
549915                             1130.81                          3635.20
549937                              611.27                           549.04
549963                             1032.64                          1134.52
549989                              379.11                          1452.36

         iraRef_mp3_heating_lifetime_fuel_cost  \
bldg_id
15                                         NaN
79                                    18514.72
119                                   10089.26
122                                   29751.37
150                                   14585.27
...                                        ...
549882                                     NaN
549915                                16558.12
549937                                 8950.69
549963                                15120.68
549989                                 5551.24

         iraRef_mp3_heating_lifetime_savings_fuel_cost  \
bldg_id
15                                                 NaN
79                                            32971.17
119                                            -397.22
122                                           26883.11
150                                           34250.58
...                                                ...
549882                                             NaN
549915                                        36340.79
549937                                         -494.69
549963                                         2352.66
549989                                        16734.66

         baseline_heating_lifetime_fuel_cost
bldg_id
15                                       NaN
79                                  51485.89
119                                  9692.04
122                                 56634.48
150                                 48835.85
...                                      ...
549882                                   NaN
549915                              52898.91

# PRIVATE IMPACTS: CAPITAL COSTS
## Scenarios: No IRA and IRA-Reference

In [16]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
from cmu_tare_model.utils.remdb_v4_installed_cost_utils import load_remdb_v4_data, add_remdb_upgrade_metrics, add_remdb_replacement_metrics
from cmu_tare_model.private_impact.calculations.calculate_equipment_installation_costs import (
    calculate_upgrade_installed_cost
    )
from cmu_tare_model.private_impact.calculations.calculate_equipment_replacement_costs import (
    calculate_replacement_installed_cost
)

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Load REMDB v4 Data and prepare for regression cost calculations
----------------------------------------------------------------------------------------------------------------------
Documentation for load_remdb_v4_data function:
{load_remdb_v4_data.__doc__}

Documentation for add_remdb_upgrade_metrics function:
{add_remdb_upgrade_metrics.__doc__}

Documentation for add_remdb_replacement_metrics function:
{add_remdb_replacement_metrics.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_upgrade_installed_cost function:
{calculate_upgrade_installed_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:
{calculate_replacement_installed_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 5 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

""")

====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Load REMDB v4 Data and prepare for regression cost calculations
----------------------------------------------------------------------------------------------------------------------
Documentation for load_remdb_v4_data function:
Load REMDB v4 retrofit cost data.

    Args:
        data_dir: Optional custom directory path.
        filename: CSV filename.

    Returns:
        DataFrame indexed by row_id with cost regression parameters.


Documentation for add_remdb_upgrade_metrics function:

    Prepare UPGRADE cost metrics from BASELINE equipment for REMDB v4 calculations.

    This function performs ALL preparation steps:
    1. Assigns row_id based on equipment type
    2. Maps REMDB coefficients and unit specifications
    3. Extracts metrics from EUSS data with correct unit conversions
    4. Fills missing values from REMDB bounds
    5. Separates columns into main (summary) and detailed (all intermediates) DataFrames

    Args:
        df: DataFrame with baseline equipment specifications.
        remdb_v4_costs: REMDB v4 cost database (indexed by row_id).
        end_use: Equipment category ('heating', 'cooling').
        percentile: Cost percentile ('low', 'mid', 'high').
        df_detailed: Optional detailed DataFrame to append new columns.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Updated DataFrame with summary columns only.
            - df_detailed_out: Updated detailed DataFrame with all calculation columns.


Documentation for add_remdb_replacement_metrics function:

    Prepare REPLACEMENT cost metrics from BASELINE equipment for REMDB v4 calculations.

    This function performs ALL preparation steps:
    1. Assigns row_id based on equipment type
    2. Maps REMDB coefficients and unit specifications
    3. Extracts metrics from EUSS data with correct unit conversions
    4. Fills missing values from REMDB bounds
    5. Separates columns into main (summary) and detailed (all intermediates) DataFrames

    Args:
        df: DataFrame with baseline equipment specifications.
        remdb_v4_costs: REMDB v4 cost database (indexed by row_id).
        end_use: Equipment category ('heating', 'cooling').
        percentile: Cost percentile ('low', 'mid', 'high').
        df_detailed: Optional detailed DataFrame to append new columns.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Updated DataFrame with summary columns only.
            - df_detailed_out: Updated detailed DataFrame with all calculation columns.


----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_upgrade_installed_cost function:

    Calculate UPGRADE installed costs using REMDB v4 regression formula.

    PREREQUISITE: Call add_remdb_upgrade_metrics() first to do the following:
    - Extract metrics (capacity, efficiency)
    - Assign row_id (technology mapping)
    - Map REMDB parameters (coefficients, multiplier)

    Then use this function to calculate installed costs:
    - Calculate costs (regression formula)
    - Uses the validation framework to ensure only valid homes receive cost calculations.

    Args:
        df: DataFrame with prepared metrics.
        df_detailed: Detailed DataFrame with regression parameters.
        menu_mp: Measure package number.
        end_use: Equipment category.
        percentile: Cost percentile.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_copy: Updated DataFrame with new cost column.
            - df_detailed_out: Updated detailed DataFrame with new cost column.


----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:

    Calculate REPLACEMENT installed costs using REMDB v4 regression formula.

    PREREQUISITE: Call add_remdb_replacement_metrics() first to do the following:
    - Extract metrics (capacity, efficiency)
    - Assign row_id (technology mapping)
    - Map REMDB parameters (coefficients, multiplier)

    Then use this function to calculate installed costs:
    - Calculate costs (regression formula)
    - Uses the validation framework to ensure only valid homes receive cost calculations.

    SPECIAL CASE - COOLING: Creates temporary include_cooling flag for validation,
    then removes it to prevent downstream interference.

    Args:
        df: DataFrame with prepared metrics.
        df_detailed: Detailed DataFrame with regression parameters.
        menu_mp: Measure package number.
        end_use: Equipment category.
        percentile: Cost percentile.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_copy: Updated DataFrame with new cost column.
            - df_detailed_out: Updated detailed DataFrame with new cost column.


----------------------------------------------------------------------------------------------------------------------
Step 5 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

In [17]:
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows')

In [18]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
REMDB_v4_PATH = os.path.join(PROJECT_ROOT, 'cmu_tare_model', 'data', 'retrofit_costs')

df_tare_remdb_v4_costs = load_remdb_v4_data(
    data_dir=REMDB_v4_PATH,
    filename="remdb_v4_tare_retrofit_costs.csv")

print(f"""
Final cleaned dataframe for retrofit capital costs:
{df_tare_remdb_v4_costs}

--------------------------------------------------""")

Final cleaned dataframe for retrofit capital costs:
                                                    Unnamed: 0  tare_category  \
row_id
air_conditioner_centrally_ducted                             0        cooling
air_conditioner_room_ac_window_or_through_wall               1        cooling
air_sealing_lt40pct_reduction                                2      enclosure
air_sealing_gt40pct_reduction                                3      enclosure
air_source_heat_pump_centrally_ducted                        4        heating
air_source_heat_pump_centrally_ducted_with_new_...           5        heating
air_source_heat_pump_non_ducted_single_zone                  6        heating
air_source_heat_pump_non_ducted_multi_zone                   7        heating
boiler_gas_non_condensing                                    9        heating
boiler_gas_condensing                                       10        heating
boiler_oil                                                  11        heating
clothes_dryer_electric                                      12  clothesDrying
clothes_dryer_heat_pump                                     13  clothesDrying
clothes_dryer_gas                                           14  clothesDrying
cooking_range_electric                                      22        cooking
cooking_range_induction                                     23        cooking
cooking_range_gas                                           24        cooking
duct_duct_insulation                                        44      enclosure
duct_duct_sealing                                           45      enclosure
electric_baseboard_default                                  46        heating
furnaces_gas_furnace                                        71        heating
unfinished_attic_ceiling_batt                               96      enclosure
unfinished_attic_ceiling_loose_fill                         97      enclosure
unfinished_attic_ceiling_spray_foam_closed_cell             98      enclosure
unfinished_attic_ceiling_spray_foam_open_cell               99      enclosure
water_heater_electric_instantaneous                        116   waterHeating
water_heater_electric_storage                              117   waterHeating
water_heater_hp_tank                                       118   waterHeating
water_heater_hp_tank_w_gas_capping                         119   waterHeating
water_heater_hp_tank_w_gas_capping_and_240v_wiring         120   waterHeating
water_heater_gas_inst                                      121   waterHeating
water_heater_gas_storage                                   122   waterHeating

                                                                     component  \
row_id
air_conditioner_centrally_ducted                               Air Conditioner
air_conditioner_room_ac_window_or_through_wall                 Air Conditioner
air_sealing_lt40pct_reduction                                      Air Sealing
air_sealing_gt40pct_reduction                                      Air Sealing
air_source_heat_pump_centrally_ducted                     Air Source Heat Pump
air_source_heat_pump_centrally_ducted_with_new_...        Air Source Heat Pump
air_source_heat_pump_non_ducted_single_zone               Air Source Heat Pump
air_source_heat_pump_non_ducted_multi_zone                Air Source Heat Pump
boiler_gas_non_condensing                                               Boiler
boiler_gas_condensing                                                   Boiler
boiler_oil                                                              Boiler
clothes_dryer_electric                                           Clothes Dryer
clothes_dryer_heat_pump                                          Clothes Dryer
clothes_dryer_gas                                                Clothes Dryer
cooking_range_electric                                           Cooking Range
cooking_range_induction                                          Cooking Range
cooking_range_gas                                                Cooking Range
duct_duct_insulation                                                      Duct
duct_duct_sealing                                                        Duct
electric_baseboard_default                                  Electric Baseboard
furnaces_gas_furnace                                                  Furnaces
unfinished_attic_ceiling_batt                       Unfinished Attic (Ceiling)
unfinished_attic_ceiling_loose_fill                 Unfinished Attic (Ceiling)
unfinished_attic_ceiling_spray_foam_closed_cell     Unfinished Attic (Ceiling)
unfinished_attic_ceiling_spray_foam_open_cell       Unfinished Attic (Ceiling)
water_heater_electric_instantaneous                               Water Heater
water_heater_electric_storage                                     Water Heater
water_heater_hp_tank                                              Water Heater
water_heater_hp_tank_w_gas_capping                                Water Heater
water_heater_hp_tank_w_gas_capping_and_240v_wiring                Water Heater
water_heater_gas_inst                                             Water Heater
water_heater_gas_storage                                          Water Heater

                                                                                     class  \
row_id
air_conditioner_centrally_ducted                                          Centrally ducted
air_conditioner_room_ac_window_or_through_wall            Room AC (window or through-wall)
air_sealing_lt40pct_reduction                                               <40% Reduction
air_sealing_gt40pct_reduction                                               >40% Reduction
air_source_heat_pump_centrally_ducted                                     Centrally ducted
air_source_heat_pump_centrally_ducted_with_new_...      Centrally ducted, with new circuit
air_source_heat_pump_non_ducted_single_zone                        Non-ducted, single-zone
air_source_heat_pump_non_ducted_multi_zone                          Non-ducted, multi-zone
boiler_gas_non_condensing                                             Gas (Non-Condensing)
boiler_gas_condensing                                                     Gas (Condensing)
boiler_oil                                                                             Oil
clothes_dryer_electric                                                            Electric
clothes_dryer_heat_pump                                                          Heat Pump
clothes_dryer_gas                                                                      Gas
cooking_range_electric                                                            Electric
cooking_range_induction                                                          Induction
cooking_range_gas                                                                      Gas
duct_duct_insulation                                                       Duct Insulation
duct_duct_sealing                                                             Duct Sealing
electric_baseboard_default                                                             NaN
furnaces_gas_furnace                                                           Gas Furnace
unfinished_attic_ceiling_batt                                                         Batt
unfinished_attic_ceiling_loose_fill                                             Loose Fill
unfinished_attic_ceiling_spray_foam_closed_cell                   Spray Foam (Closed Cell)
unfinished_attic_ceiling_spray_foam_open_cell                       Spray Foam (Open Cell)
water_heater_electric_instantaneous                                 Electric Instantaneous
water_heater_electric_storage                                             Electric Storage
water_heater_hp_tank                                                               HP Tank
water_heater_hp_tank_w_gas_capping                                  HP Tank w/ Gas Capping
water_heater_hp_tank_w_gas_capping_and_240v_wiring  HP Tank w/ Gas Capping and 240V Wiring
water_heater_gas_inst                                                             Gas Inst
water_heater_gas_storage                                                       Gas Storage

                                                   output_units  \
row_id
air_conditioner_centrally_ducted                          2023$
air_conditioner_room_ac_window_or_through_wall            2023$
air_sealing_lt40pct_reduction                        2023$/sqft
air_sealing_gt40pct_reduction                        2023$/sqft
air_source_heat_pump_centrally_ducted                     2023$
air_source_heat_pump_centrally_ducted_with_new_...        2023$
air_source_heat_pump_non_ducted_single_zone               2023$
air_source_heat_pump_non_ducted_multi_zone                2023$
boiler_gas_non_condensing                                 2023$
boiler_gas_condensing                                     2023$
boiler_oil                                                2023$
clothes_dryer_electric                                    2023$
clothes_dryer_heat_pump                                   2023$
clothes_dryer_gas                                         2023$
cooking_range_electric                                    2023$
cooking_range_induction                                   2023$
cooking_range_gas                                         2023$
duct_duct_insulation                                 2023$/sqft
duct_duct_sealing                                    2023$/sqft
electric_baseboard_default                                2023$
furnaces_gas_furnace                                      2023$
unfinished_attic_ceiling_batt                        2023$/sqft
unfinished_attic_ceiling_loose_fill                  2023$/sqft
unfinished_attic_ceiling_spray_foam_closed_cell      2023$/sqft
unfinished_attic_ceiling_spray_foam_open_cell        2023$/sqft
water_heater_electric_instantaneous                       2023$
water_heater_electric_storage                             2023$
water_heater_hp_tank                                      2023$
water_heater_hp_tank_w_gas_capping                        2023$
water_heater_hp_tank_w_gas_capping_and_240v_wiring        2023$
water_heater_gas_inst                                     2023$
water_heater_gas_storage                                  2023$

                                                           pm1_metric  \
row_id
air_conditioner_centrally_ducted                     Cooling Capacity
air_conditioner_room_ac_window_or_through_wall               Capacity
air_sealing_lt40pct_reduction                       Leakage Reduction
air_sealing_gt40pct_reduction                       Leakage Reduction
air_source_heat_pump_centrally_ducted                Cooling Capacity
air_source_heat_pump_centrally_ducted_with_new_...   Cooling Capacity
air_source_heat_pump_non_ducted_single_zone          Cooling Capacity
air_source_heat_pump_non_ducted_multi_zone           Cooling Capacity
boiler_gas_non_condensing                            Heating Capacity
boiler_gas_condensing                                Heating Capacity
boiler_oil                                           Heating Capacity
clothes_dryer_electric                                         Volume
clothes_dryer_heat_pump                                        Volume
clothes_dryer_gas                                              Volume
cooking_range_electric                                         Volume
cooking_range_induction                                        Volume
cooking_range_gas                                              Volume
duct_duct_insulation                                          R-value
duct_duct_sealing                                   Leakage Reduction
electric_baseboard_default                                   Capacity
furnaces_gas_furnace                                 Heating Capacity
unfinished_attic_ceiling_batt                                 R-value
unfinished_attic_ceiling_loose_fill                           R-value
unfinished_attic_ceiling_spray_foam_closed_cell               R-value
unfinished_attic_ceiling_spray_foam_open_cell                 R-value
water_heater_electric_instantaneous                               UEF
water_heater_electric_storage                                     UEF
water_heater_hp_tank                                              UEF
water_heater_hp_tank_w_gas_capping                                UEF
water_heater_hp_tank_w_gas_capping_and_240v_wiring                UEF
water_heater_gas_inst                                             UEF
water_heater_gas_storage                                          UEF

                                                        pm1_unit  \
row_id
air_conditioner_centrally_ducted                            Tons
air_conditioner_room_ac_window_or_through_wall              Tons
air_sealing_lt40pct_reduction                            Percent
air_sealing_gt40pct_reduction                            Percent
air_source_heat_pump_centrally_ducted                       Tons
air_source_heat_pump_centrally_ducted_with_new_...          Tons
air_source_heat_pump_non_ducted_single_zone                 Tons
air_source_heat_pump_non_ducted_multi_zone                  Tons
boiler_gas_non_condensing                                 BTU/hr
boiler_gas_condensing                                     BTU/hr
boiler_oil                                                BTU/hr
clothes_dryer_electric                                  Cubic ft
clothes_dryer_heat_pump                                 Cubic ft
clothes_dryer_gas                                       Cubic ft
cooking_range_electric                                  Cubic ft
cooking_range_induction                                 Cubic ft
cooking_range_gas                                       Cubic ft
duct_duct_insulation                                ft2·°F·h/BTU
duct_duct_sealing                                        Percent
electric_baseboard_default                                BTU/Hr
furnaces_gas_furnace                                      BTU/Hr
unfinished_attic_ceiling_batt                       ft2·°F·h/BTU
unfinished_attic_ceiling_loose_fill                 ft2·°F·h/BTU
unfinished_attic_ceiling_spray_foam_closed_cell     ft2·°F·h/BTU
unfinished_attic_ceiling_spray_foam_open_cell       ft2·°F·h/BTU
water_heater_electric_instantaneous                     Unitless
water_heater_electric_storage                           Unitless
water_heater_hp_tank                                    Unitless
water_heater_hp_tank_w_gas_capping                      Unitless
water_heater_hp_tank_w_gas_capping_and_240v_wiring      Unitless
water_heater_gas_inst                                   Unitless
water_heater_gas_storage                                Unitless

                                                    pm1_coef_low  \
row_id
air_conditioner_centrally_ducted                      196.966095
air_conditioner_room_ac_window_or_through_wall        350.160000
air_sealing_lt40pct_reduction                           0.480450
air_sealing_gt40pct_reduction                           0.107294
air_source_heat_pump_centrally_ducted                 639.168000
air_source_heat_pump_centrally_ducted_with_new_...    639.168000
air_source_heat_pump_non_ducted_single_zone          1878.048000
air_source_heat_pump_non_ducted_multi_zone           1878.048000
boiler_gas_non_condensing                               0.013611
boiler_gas_condensing                                   0.020390
boiler_oil                                              0.013617
clothes_dryer_electric                                 37.500000
clothes_dryer_heat_pump                                45.900353
clothes_dryer_gas                                      71.678322
cooking_range_electric                                 27.703333
cooking_range_induction                              1048.888889
cooking_range_gas                                     111.854839
duct_duct_insulation                                    0.250999
duct_duct_sealing                                       0.151667
electric_baseboard_default                              0.034056
furnaces_gas_furnace                                    0.004744
unfinished_attic_ceiling_batt                           0.031667
unfinished_attic_ceiling_loose_fill                     0.008696
unfinished_attic_ceiling_spray_foam_closed_cell         0.209286
unfinished_attic_ceiling_spray_foam_open_cell           0.146427
water_heater_electric_instantaneous                   250.000019
water_heater_electric_storage                         571.423485
water_heater_hp_tank                                  102.325583
water_heater_hp_tank_w_gas_capping                    102.325583
water_heater_hp_tank_w_gas_capping_and_240v_wiring    102.325583
water_heater_gas_inst                                4192.333369
water_heater_gas_storage                             5190.140327

                                                    pm1_coef_mid  \
row_id
air_conditioner_centrally_ducted                      328.276825
air_conditioner_room_ac_window_or_through_wall        364.332000
air_sealing_lt40pct_reduction                           0.894236
air_sealing_gt40pct_reduction                           0.867979
air_source_heat_pump_centrally_ducted                1065.280000
air_source_heat_pump_centrally_ducted_with_new_...   1065.280000
air_source_heat_pump_non_ducted_single_zone          3130.080000
air_source_heat_pump_non_ducted_multi_zone           3130.080000
boiler_gas_non_condensing                               0.017470
boiler_gas_condensing                                   0.030098
boiler_oil                                              0.018460
clothes_dryer_electric                                -42.857155
clothes_dryer_heat_pump                                34.365975
clothes_dryer_gas                                     170.121951
cooking_range_electric                                127.969233
cooking_range_induction                                49.000000
cooking_range_gas                                     674.418603
duct_duct_insulation                                    0.163885
duct_duct_sealing                                       0.298588
electric_baseboard_default                              0.056760
furnaces_gas_furnace                                    0.006450
unfinished_attic_ceiling_batt                           0.043000
unfinished_attic_ceiling_loose_fill                     0.017857
unfinished_attic_ceiling_spray_foam_closed_cell         0.301055
unfinished_attic_ceiling_spray_foam_open_cell           0.273450
water_heater_electric_instantaneous                   353.549649
water_heater_electric_storage                       10549.499565
water_heater_hp_tank                                  248.326452
water_heater_hp_tank_w_gas_capping                    248.326452
water_heater_hp_tank_w_gas_capping_and_240v_wiring    248.326452
water_heater_gas_inst                                3885.583326
water_heater_gas_storage                             8799.424875

                                                    pm1_coef_high  \
row_id
air_conditioner_centrally_ducted                       459.587555
air_conditioner_room_ac_window_or_through_wall         311.640000
air_sealing_lt40pct_reduction                            1.333659
air_sealing_gt40pct_reduction                            0.785978
air_source_heat_pump_centrally_ducted                 1491.392000
air_source_heat_pump_centrally_ducted_with_new_...    1491.392000
air_source_heat_pump_non_ducted_single_zone           4382.112000
air_source_heat_pump_non_ducted_multi_zone            4382.112000
boiler_gas_non_condensing                                0.020046
boiler_gas_condensing                                    0.027623
boiler_oil                                               0.020154

### Space Heating and No Enclosure Upgrade

#### Space Heating Capital Costs

In [19]:
# Configuration
# menu_mp = 3
percentile = 'mid'

# Initialize detailed DataFrame as None (created on first call)
df_detailed_mp3_installed_costs = None

# Heating upgrade
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_upgrade_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_upgrade_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

# Heating replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

Preparing heating UPGRADE metrics (REMDB v4)
  Filled 6 missing euss_heating_upgrade_pm2 from REMDB bounds

  WARNING: 7,324 homes have out-of-bounds capacity (method=keep_as_is)
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 3,413 below; range 0.395 to 1.49917
      - 619 above; range 5.00167 to 34.245
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 1.5 to 5)
      - 40 below; range 0.701667 to 1.49667
      - 3,252 above; range 5.00333 to 50.1025

  WARNING: 4,885 homes have out-of-bounds efficiency (method=keep_as_is)
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 16 to 23)
      - 4,885 below; range 15 to 15
  Valid metrics after bounds checking: 17,990 pm1, 17,990 pm2

Calculating heating upgrade costs (REMDB v4)
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 13,849 homes (mean: $17,481.02)


Preparing heating REPLACEMENT metrics (REMDB v4)
  Warning: 829 homes with unknown row_id
  Filled 829 missing euss_heating_replacement_pm1 from REMDB bounds
  Filled 508 missing euss_heating_replacement_pm2 from REMDB bounds

  WARNING: 7,329 homes have out-of-bounds capacity (method=keep_as_is)
    • furnaces_gas_furnace (bounds: 30000 to 156250)
      - 6,660 below; range 4740 to 29990
      - 375 above; range 156260 to 601230
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 254 below; range 0.424167 to 1.49333
      - 39 above; range 5.03917 to 13.1167
    • electric_baseboard_default (bounds: 1194.2 to 416000)
      - 1 above; range 456510 to 456510

  WARNING: 3,398 homes have out-of-bounds efficiency (method=keep_as_is)
    • furnaces_gas_furnace (bounds: 0.8 to 0.97)
      - 2,775 below; range 0.6 to 0.76
    • air_source_heat_pump_centrally_ducted (bounds: 13.8 to 24)
      - 623 below; range 10 to 13
  Valid metrics after bounds checking: 17,161 pm1, 17,990 pm2

Calculating heating replacement costs (REMDB v4)
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 13,849 homes (mean: $3,408.64)

### Air Conditioning - ONLY CALCULATE REPLACEMENT COSTS
### (Create new column and add to heating replacement cost)

UPDATE: 
- Updated to handle different enduses based on EQUIPMENT_SPECS.
- Rest of codebase updated so only initial columns created for cooling and replacement cost calculations performed
- This allows for a scenario where only heating is replaced AND one where heating and cooling systems are both replace with HP
- Resolves the excessive data columns and double counting with $8000 rebate. No longer need CDD projections.

In [20]:
# Cooling replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='cooling',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='cooling',
    percentile=percentile
)

Preparing cooling REPLACEMENT metrics (REMDB v4)
  Warning: 2,515 homes with unknown row_id
  Filled 2,515 missing euss_cooling_replacement_pm1 from REMDB bounds
  Filled 6,357 missing euss_cooling_replacement_pm2 from REMDB bounds

  WARNING: 7,329 homes have out-of-bounds capacity (method=keep_as_is)
    • air_conditioner_room_ac_window_or_through_wall (bounds: 0.416667 to 2.33333)
      - 1 below; range 0.395 to 0.395
      - 4,202 above; range 2.33333 to 50.1025
    • air_conditioner_centrally_ducted (bounds: 1.5 to 5)
      - 2,392 below; range 0.423333 to 1.49917
      - 426 above; range 5.00167 to 34.245
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 269 below; range 0 to 1.49333
      - 39 above; range 5.03917 to 13.1167

  WARNING: 2,185 homes have out-of-bounds efficiency (method=keep_as_is)
    • air_conditioner_centrally_ducted (bounds: 13 to 24)
      - 2,185 below; range 8 to 10
  Valid metrics after bounds checking: 15,475 pm1, 17,990 pm2

Calculating cooling replacement costs (REMDB v4)
  Created temporary include_cooling flag for metadata calculation
Measure package calculation for cooling:
  - 15475 homes have valid data
  - 17990 homes will receive retrofits
  - 15475 homes have both valid data AND will receive retrofits
  - 2515 homes excluded (values will be NaN)
  Initialized all_columns_to_mask['cooling'] for metadata tracking

Verifying masking for all calculated columns:
Masking 1 columns for category 'cooling'
  Removed temporary include_cooling flag
  Calculated costs for 15,475 homes (mean: $3,945.73)

In [21]:
# Combined cost (in notebook)
heating_replacement_col = f'mp{menu_mp}_heating_replacement_installed_cost_{percentile}'
cooling_replacement_col = f'mp{menu_mp}_cooling_replacement_installed_cost_{percentile}'
combined_col = f'mp{menu_mp}_heating_and_cooling_replacement_installed_cost_{percentile}'

df_euss_am_mp3_home[combined_col] = (
    df_euss_am_mp3_home[heating_replacement_col] + 
    df_euss_am_mp3_home[cooling_replacement_col]
)

df_detailed_mp3_installed_costs[combined_col] = (
    df_detailed_mp3_installed_costs[heating_replacement_col] + 
    df_detailed_mp3_installed_costs[cooling_replacement_col]
)

In [22]:
df_detailed_mp3_installed_costs

,row_id_heating_upgrade,heating_upgrade_pm1_metric,heating_upgrade_pm1_unit,heating_upgrade_pm1_lower_bound,heating_upgrade_pm1_upper_bound,euss_heating_upgrade_pm1,heating_upgrade_pm1_coef_mid,heating_upgrade_pm2_metric,heating_upgrade_pm2_unit,heating_upgrade_pm2_lower_bound,heating_upgrade_pm2_upper_bound,euss_heating_upgrade_pm2,heating_upgrade_pm2_coef_mid,heating_upgrade_intercept_mid,heating_upgrade_multiplier_retrofit,heating_upgrade_adder_retrofit,mp3_heating_upgrade_installed_cost_mid,row_id_heating_replacement,heating_replacement_pm1_metric,heating_replacement_pm1_unit,heating_replacement_pm1_lower_bound,heating_replacement_pm1_upper_bound,euss_heating_replacement_pm1,heating_replacement_pm1_coef_mid,heating_replacement_pm2_metric,heating_replacement_pm2_unit,heating_replacement_pm2_lower_bound,heating_replacement_pm2_upper_bound,euss_heating_replacement_pm2,heating_replacement_pm2_coef_mid,heating_replacement_intercept_mid,heating_replacement_multiplier_retrofit,heating_replacement_adder_retrofit,mp3_heating_replacement_installed_cost_mid,row_id_cooling_replacement,cooling_replacement_pm1_metric,cooling_replacement_pm1_unit,cooling_replacement_pm1_lower_bound,cooling_replacement_pm1_upper_bound,euss_cooling_replacement_pm1,cooling_replacement_pm1_coef_mid,cooling_replacement_pm2_metric,cooling_replacement_pm2_unit,cooling_replacement_pm2_lower_bound,cooling_replacement_pm2_upper_bound,euss_cooling_replacement_pm2,cooling_replacement_pm2_coef_mid,cooling_replacement_intercept_mid,cooling_replacement_multiplier_retrofit,cooling_replacement_adder_retrofit,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
bldg_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
15,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,1.572500,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,NaN,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,1.5725,1065.28000,SEER1,Unitless,13.8,24.00,13.000,594.740000,-2291.000000,1.5,-1384.000,NaN,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,1.572500,1065.280000,SEER1,Unitless,13.8,24.0,18.9,594.740000,-2291.000000,1.5,-1384.000000,14553.11,NaN
79,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.019167,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13385.54,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,36230.0000,0.00645,AFUE,Unitless,0.8,0.97,0.800,4325.000025,-2780.000019,1.0,2217.753,3131.44,air_conditioner_room_ac_window_or_through_wall,Capacity,Tons,0.416667,2.333333,3.019167,364.332000,CEER,Unitless,9.4,15.0,12.2,6.069364,13.277460,1.0,352.607677,1539.91,4671.35
119,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.702500,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,12879.53,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,32430.0000,0.00645,AFUE,Unitless,0.8,0.97,0.800,4325.000025,-2780.000019,1.0,2217.753,3106.93,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.702500,328.276825,SEER1,Unitless,13.0,24.0,8.0,594.740000,-5888.936117,1.5,0.000000,0.00,3106.93
122,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,13.465833,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,30078.47,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,161590.0000,0.00645,AFUE,Unitless,0.8,0.97,0.925,4325.000025,-2780.000019,1.0,2217.753,4480.63,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,13.465833,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,9394.81,13875.44
150,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,7.772500,3130.08,SEER1,Unitless,16.0,23.0,15.0,160.413333,-1343.333333,1.5,0.0,38087.12,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,93270.0000,0.05676,NaN,NaN,0.0,0.00,0.000,0.000000,0.000000,1.5,0.000,7941.05,air_conditioner_room_ac_window_or_through_wall,Capacity,Tons,0.416667,2.333333,7.772500,364.332000,CEER,Unitless,9.4,15.0,12.2,6.069364,13.277460,1.0,352.607677,3271.70,11212.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549882,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,7.541667,3130.08,SEER1,Unitless,16.0,23.0,15.0,160.413333,-1343.333333,1.5,0.0,NaN,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,90500.0000,0.00645,AFUE,Unitless,0.8,0.97,0.680,4325.000025,-2780.000019,1.0,2217.753,NaN,air_conditioner_room_ac_window_or_through_wall,Capacity,Tons,0.416667,2.333333,7.541667,364.332000,CEER,Unitless,9.4,15.0,12.2,6.069364,13.277460,1.0,352.607677,3187.60,NaN
549915,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.196667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13669.17,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,38360.0000,0.05676,NaN,NaN,0.0,0.00,0.000,0.000000,0.000000,1.5,0.000,3265.99,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.196667,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,4338.11,7604.10
549937,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,1.452500,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,10882.13,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,17430.0000,0.00645,AFUE,Unitless,0.8,0.97,0.925,4325.000025,-2780.000019,1.0,2217.753,3550.80,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,1.452500,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,5263.48,8814.28
549963,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.116667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,11943.41,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,25400.0000,0.00645,AFUE,Unitless,0.8,0.97,0.800,4325.000025,-2780.000019,1.0,2217.753,3061.58,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.116667,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,3806.30,6867.88
549989,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,0.825833,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,9880.77,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,9910.0000,0.00645,AFUE,Unitless,0.8,0.97,0.800,4325.000025,-2780.000019,1.0,2217.753,2961.67,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,0.825833,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,3170.68,6132.35

In [23]:
installed_cost_cols = [col for col in df_detailed_mp3_installed_costs.columns if 'installed_cost' in col]
print(installed_cost_cols)

['mp3_heating_upgrade_installed_cost_mid', 'mp3_heating_replacement_installed_cost_mid', 'mp3_cooling_replacement_installed_cost_mid', 'mp3_heating_and_cooling_replacement_installed_cost_mid']

In [24]:
df_installed_cost_only = df_detailed_mp3_installed_costs[installed_cost_cols]
df_installed_cost_only.describe()

,mp3_heating_upgrade_installed_cost_mid,mp3_heating_replacement_installed_cost_mid,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
count,13849.000000,13849.000000,15475.000000,11958.000000
mean,17481.020722,3408.644742,3945.732580,6621.356634
std,13665.512625,1578.053412,3346.408514,2491.252557
min,6528.090000,534.680000,0.000000,688.790000
25%,11153.780000,3011.080000,1697.990000,4724.780000
50%,12481.380000,3117.890000,3503.060000,6599.600000
75%,15521.420000,3550.430000,4828.040000,7920.565000
max,202424.150000,38867.460000,32999.760000,40322.570000

## OLDER METHODS USING MASKING (Before Dec 16 Code)

In [25]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
from cmu_tare_model.utils.remdb_v4_installed_cost_utils_16Dec2025 import load_remdb_v4_data, add_remdb_upgrade_metrics, add_remdb_replacement_metrics
from cmu_tare_model.private_impact.calculations.calculate_equipment_installation_costs import (
    calculate_upgrade_installed_cost
    )
from cmu_tare_model.private_impact.calculations.calculate_equipment_replacement_costs import (
    calculate_replacement_installed_cost
)

### Space Heating and No Enclosure Upgrade

#### Space Heating Capital Costs

In [26]:
# Configuration
# menu_mp = 3
percentile = 'mid'

# Initialize detailed DataFrame as None (created on first call)
df_detailed_mp3_installed_costs = None

# Heating upgrade
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_upgrade_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_upgrade_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

# Heating replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

Preparing heating UPGRADE metrics (REMDB v4)
  Filled 6 missing euss_heating_upgrade_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 7,324 homes → masked to NaN
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 3,413 below bound
      - 619 above bound
      - Problematic range: 0.40 to 34.24
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 1.50 to 5.00)
      - 40 below bound
      - 3,252 above bound
      - Problematic range: 0.70 to 50.10

  WARNING: Out-of-bounds efficiency: 4,885 homes → masked to NaN
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 16.00 to 23.00)
      - 4,885 below bound
      - Problematic range: 15.00 to 15.00
  Valid metrics after bounds checking: 10,666 pm1, 13,105 pm2

Calculating heating upgrade costs (REMDB v4)
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 7,648 homes (mean: $12,664.40)


Preparing heating REPLACEMENT metrics (REMDB v4)
  Warning: 829 homes with unknown row_id
  Filled 829 missing euss_heating_replacement_pm1 from REMDB bounds
  Filled 508 missing euss_heating_replacement_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 7,329 homes → masked to NaN
    • furnaces_gas_furnace (bounds: 30000.00 to 156250.00)
      - 6,660 below bound
      - 375 above bound
      - Problematic range: 4740.00 to 601230.00
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 254 below bound
      - 39 above bound
      - Problematic range: 0.42 to 13.12
    • electric_baseboard_default (bounds: 1194.20 to 416000.00)
      - 1 above bound
      - Problematic range: 456510.00 to 456510.00

  WARNING: Out-of-bounds efficiency: 3,398 homes → masked to NaN
    • furnaces_gas_furnace (bounds: 0.80 to 0.97)
      - 2,775 below bound
      - Problematic range: 0.60 to 0.76
    • air_source_heat_pump_centrally_ducted (bounds: 13.80 to 24.00)
      - 623 below bound
      - Problematic range: 10.00 to 13.00
  Valid metrics after bounds checking: 9,832 pm1, 14,592 pm2

Calculating heating replacement costs (REMDB v4)
Measure package calculation for heating:
  - 13849 homes have valid data
  - 17984 homes will receive retrofits
  - 13849 homes have both valid data AND will receive retrofits
  - 4141 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 7,090 homes (mean: $3,637.56)

### Air Conditioning - ONLY CALCULATE REPLACEMENT COSTS
### (Create new column and add to heating replacement cost)

UPDATE: 
- Updated to handle different enduses based on EQUIPMENT_SPECS.
- Rest of codebase updated so only initial columns created for cooling and replacement cost calculations performed
- This allows for a scenario where only heating is replaced AND one where heating and cooling systems are both replace with HP
- Resolves the excessive data columns and double counting with $8000 rebate. No longer need CDD projections.

In [27]:
# Cooling replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='cooling',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='cooling',
    percentile=percentile
)

Preparing cooling REPLACEMENT metrics (REMDB v4)
  Warning: 2,515 homes with unknown row_id
  Filled 2,515 missing euss_cooling_replacement_pm1 from REMDB bounds
  Filled 6,357 missing euss_cooling_replacement_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 7,329 homes → masked to NaN
    • air_conditioner_room_ac_window_or_through_wall (bounds: 0.42 to 2.33)
      - 1 below bound
      - 4,202 above bound
      - Problematic range: 0.40 to 50.10
    • air_conditioner_centrally_ducted (bounds: 1.50 to 5.00)
      - 2,392 below bound
      - 426 above bound
      - Problematic range: 0.42 to 34.24
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 269 below bound
      - 39 above bound
      - Problematic range: 0.00 to 13.12

  WARNING: Out-of-bounds efficiency: 2,185 homes → masked to NaN
    • air_conditioner_centrally_ducted (bounds: 13.00 to 24.00)
      - 2,185 below bound
      - Problematic range: 8.00 to 10.00
  Valid metrics after bounds checking: 8,146 pm1, 15,805 pm2

Calculating cooling replacement costs (REMDB v4)
  Created temporary include_cooling flag for metadata calculation
Measure package calculation for cooling:
  - 15475 homes have valid data
  - 17990 homes will receive retrofits
  - 15475 homes have both valid data AND will receive retrofits
  - 2515 homes excluded (values will be NaN)
  Initialized all_columns_to_mask['cooling'] for metadata tracking

Verifying masking for all calculated columns:
Masking 1 columns for category 'cooling'
  Removed temporary include_cooling flag
  Calculated costs for 6,590 homes (mean: $4,846.47)

In [28]:
# Cooling replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='cooling',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='cooling',
    percentile=percentile
)

Preparing cooling REPLACEMENT metrics (REMDB v4)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# Combined cost (in notebook)
heating_replacement_col = f'mp{menu_mp}_heating_replacement_installed_cost_{percentile}'
cooling_replacement_col = f'mp{menu_mp}_cooling_replacement_installed_cost_{percentile}'
combined_col = f'mp{menu_mp}_heating_and_cooling_replacement_installed_cost_{percentile}'

df_euss_am_mp3_home[combined_col] = (
    df_euss_am_mp3_home[heating_replacement_col] + 
    df_euss_am_mp3_home[cooling_replacement_col]
)

df_detailed_mp3_installed_costs[combined_col] = (
    df_detailed_mp3_installed_costs[heating_replacement_col] + 
    df_detailed_mp3_installed_costs[cooling_replacement_col]
)

In [ ]:
df_detailed_mp3_installed_costs

In [ ]:
installed_cost_cols = [col for col in df_detailed_mp3_installed_costs.columns if 'installed_cost' in col]
print(installed_cost_cols)

In [ ]:
df_installed_cost_only = df_detailed_mp3_installed_costs[installed_cost_cols]
df_installed_cost_only.describe()

 ## Calculate Rebate Amounts (Applicable to IRA-Reference)
 ## SIMPLIFY THIS TO USE THE INCOME COLUMN DIRECTLY - NO NEED TO SAMPLE FROM DISTRIBUTION
 ## UPDATE TERMINOLOGY TO SPECIFY ASHP NOT SPACE HEATING BECAUSE WE NOW INCLUDE AC

In [ ]:
from cmu_tare_model.private_impact.data_processing.determine_rebate_eligibility_and_amount import calculate_percent_AMI, calculate_rebateIRA

print(f"""
====================================================================================================================================================================
CALCULATE HOUSEHOLD PERCENT AREA MEDIAN INCOME (%AMI) AND REBATE ELIGIBILITY/AMOUNTS
====================================================================================================================================================================
determine_rebate_eligibility_and_amount.py file contains the function definitions for calculating rebate amounts and determining household %AMI.
process_income_data_for_rebates.py file contains additional information on data sources and procedures used to process data for determine_rebate_eligibility_and_amount.py file.

Documentation for calculate_percent_AMI function:
{calculate_percent_AMI.__doc__}

Documentation for calculate_rebateIRA function:
{calculate_rebateIRA.__doc__}
-------------------------------------------------------

""")

# Determine Percent AMI and Rebate Amounts
# This needs to be done before running the calculate_percent_AMI function
df_euss_am_mp3_home = df_euss_am_mp3_home.copy()

# calculate_percent_AMI(df_results_IRA, df_county_medianIncome):
df_euss_am_mp3_home = calculate_percent_AMI(df_results_IRA=df_euss_am_mp3_home)

print("Calculating rebate amounts for Heating ...")
df_euss_am_mp3_home = calculate_rebateIRA(df=df_euss_am_mp3_home,
                                          category="heating",
                                          menu_mp=menu_mp,
                                          percentile='mid')

# print("Calculating rebate amounts for Cooling ...")
# df_euss_am_mp3_home = calculate_rebateIRA(df=df_euss_am_mp3_home,
#                                           category="cooling",
#                                           menu_mp=menu_mp,
#                                           percentile='mid')


print(f"""
====================================================================================================================================================================
DATAFRAME: df_euss_am_mp3_home AFTER CALCULATING REBATE AMOUNTS
{df_euss_am_mp3_home}

====================================================================================================================================================================
""")

# SCENARIO ANALYSIS: 
## "No Inflation Reduction Act" and "AEO2023 Reference Case"
## Public Impact, Private Impact and Adoption Potential (Degree of Adoption Feasibility)

In [ ]:
from cmu_tare_model.private_impact.calculate_lifetime_private_impact import calculate_private_npv
from cmu_tare_model.public_impact.calculate_lifetime_public_impact_sensitivity import calculate_public_npv
from cmu_tare_model.adoption_potential.determine_adoption_potential_sensitivity import *

print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS: OVERVIEW
====================================================================================================================================================================

-------------------------------------------------------
PUBLIC IMPACTS: CLIMATE AND HEALTH
-------------------------------------------------------
calculate_lifetime_public_impact.py file contains the definition for the calculate_public_npv function.
Additional information on emissions/damage factor lookups as well as marginal damages calculation methods can be found in the public_impact folder. 
      
Documentation for the calculate_public_NPV function:
{calculate_public_npv.__doc__} 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
PRIVATE IMPACTS: LIFETIME CAPITAL COSTS AND SAVINGS
--------------------------------------------------------
calculate_lifetime_private_impact.py file contains the definition for the calculate_private_npv function.
Additional information on fuel price lookups as well as capital costs calculation methods can be found in the private_impact folder.

Documentation for the calculate_private_npv function:
{calculate_private_npv.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
ADOPTION POTENTIAL
--------------------------------------------------------
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
Documentation for the adoption_decision function:
{adoption_decision.__doc__}

Documentation for the calculate_climate_only_adoption_robust function:
{calculate_climate_only_adoption_robust.__doc__}

Documentation for the calculate_health_only_adoption_robust function:
{calculate_health_only_adoption_robust.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

""")

## BASIC MEASURE PACKAGE (mp3): NO INFLATION REDUCTION ACT
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 3
- AEO2023 No Inflation Reduction Act:  HDD and Fuel Price Projections
- Cambium 2021 MidCase Scenario

In [ ]:
# Measure Package 3
scenario_name = 'No Inflation Reduction Act'
cost_scenario = 'Fuel Costs: AEO2023 No Inflation Reduction Act'
grid_scenario = 'Electricity Grid: Cambium 2021 MidCase Scenario'

print(f"""
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

In [ ]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PUBLIC IMPACT 
====================================================================================================================================================================
Completed Steps:
1. Calculate the baseline marginal damages for climate and health-related emissions
2. Calculate the post-retrofit marginal damages for climate and health-related emissions

---------------------------------------------------------------------------------------------
Step 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)
---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# Create copies to prevent overwriting the original dataframe and compare the differences
df_euss_am_mp3_home_ap2 = df_euss_am_mp3_home.copy()
df_euss_am_mp3_home_easiur = df_euss_am_mp3_home.copy()
df_euss_am_mp3_home_inmap = df_euss_am_mp3_home.copy()

# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp3_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_public_npv(
    df=df_euss_am_mp3_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_public_npv(
    df=df_euss_am_mp3_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (NO IRA): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PRIVATE IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs
2. Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
3. Calculate replacement cost (replacing existing piece of eqipment with similar technology)

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")


# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp3_home_ap2,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_private_npv(
    df=df_euss_am_mp3_home_easiur,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_private_npv(
    df=df_euss_am_mp3_home_inmap,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    percentile='mid'
    )

df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
print(df_euss_am_mp3_home_easiur.columns.tolist())

## BASIC MEASURE PACKAGE (mp3): AEO2023 REFERENCE CASE
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 3
- AEO2023 REFERENCE CASE: HDD and Fuel Price Projections
- Cambium 2023 MidCase Scenario

In [ ]:
# Measure Package 3
scenario_name = 'Basic IRA-Reference'
cost_scenario = 'Fuel Costs: AEO2023 Reference Case'
grid_scenario = 'Electricity Grid: Cambium 2023 MidCase Scenario'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

In [ ]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PUBLIC IMPACT 
====================================================================================================================================================================
STEP 1. Calculate the baseline marginal damages for climate and health-related emissions         [COMPLETED]
STEP 2. Calculate the post-retrofit marginal damages for climate and health-related emissions    [COMPLETED]
STEP 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)

---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp3_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_public_npv(
    df=df_euss_am_mp3_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_public_npv(
    df=df_euss_am_mp3_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")


# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp3_home_ap2,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_private_npv(
    df=df_euss_am_mp3_home_easiur,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_private_npv(
    df=df_euss_am_mp3_home_inmap,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )



print(f"""  
=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity_robust.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (AEO2023 REFERENCE CASE): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------   
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

In [ ]:
# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_ap2 dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_ap2.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_easiur dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_easiur.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_inmap dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_inmap.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# Model Runtime

In [ ]:
# Flag to prevent excessive output in other scenario files
individual_scenario_run = False

# Get the current datetime again
end_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

# Calculate the elapsed time
elapsed_time = datetime.strptime(end_time, "%Y-%m-%d_%H-%M-%S") - datetime.strptime(start_time, "%Y-%m-%d_%H-%M-%S")

# Format the elapsed time
elapsed_seconds = elapsed_time.total_seconds()
elapsed_minutes = int(elapsed_seconds // 60)
elapsed_seconds = int(elapsed_seconds % 60)

# Print the elapsed time
print(f"The code took {elapsed_minutes} minutes and {elapsed_seconds} seconds to execute.")