In [1]:
# file_path = r'C:\Users\jorda\Desktop\Projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\upgrade03_metadata_and_annual_results.csv'

# # Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
# columns_to_string = {61: str, 113: str, 121: str}

# df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
# # df_euss_am_mp3 = pd.read_csv(file_path, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)

In [2]:
# df_euss_am_mp3

In [3]:
# df_euss_am_mp3['upgrade.hvac_cooling_efficiency'].value_counts()

In [4]:
# print(df_euss_am_mp3.columns.tolist())

# TARE Model: Space Conditioning Analysis for TRANE Technologies
## LOAD EUSS DATA: Annual Energy Consumption and Metadata

**Analysis Focus:** Space Heating and Cooling Equipment Only
- Heating: Furnaces, boilers, etc. --> ASHP
- Cooling: Air conditioning systems (central AC, room AC) --> ASHP
- Excluded: Water heating, clothes drying, cooking equipment

In [5]:
import os

# import from cmu-tare-model package
from config import PROJECT_ROOT

# Measure Package 0: Baseline
menu_mp = 0
input_mp = 'baseline'

print(f"PROJECT_ROOT (from config.py): {PROJECT_ROOT}")

# Construct the absolute path to the .py file
relative_path = os.path.join("cmu_tare_model", "model_scenarios", "trane_technologies", "tare_trane_baseline_v2_1.ipynb")
file_path = os.path.join(PROJECT_ROOT, relative_path)

# On Windows, to avoid any path-escape quirks, convert backslashes to forward slashes
file_path = file_path.replace("\\", "/")

print(f"Running file: {file_path}")

# %run magic command to run a .py file and import variables into the current IPython session
# # If your path has spaces, wrap it in quotes:
%run -i {file_path} # If your path has NO spaces, no quotes needed.

print("TARE Baseline Scenario for TRANE Technologies - Model Run Complete")
print("Analysis Focus: Space Conditioning (Heating + Cooling)")

# Flag to prevent excessive output in other scenario files
individual_scenario_run = True

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
PROJECT_ROOT (from config.py): c:\users\jorda\desktop\projects\cmu-tare-model
Running file: c:/users/jorda/desktop/projects/cmu-tare-model/cmu_tare_model/model_scenarios/trane_technologies/tare_trane_baseline_v2_1.ipynb

=========================================================================================================
Welcome to the Trade-off Analysis of residential Retrofits for energy Equity Tool (TARE Model)
Let's start by reading the data from the NREL EUSS Database.

Make sure that the zipped folders stay organized as they are once unzipped.
If changes are made to the file path, then the program will not run properly.
==========================================================================================================

Project root directory: c:\users\jorda\desktop\projects\cmu-tare-model
Result outputs will be exported here: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\output_results



====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO (TRANE ANALYSIS): MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
Load data from the NREL EUSS Database for the baseline scenario and apply various filters.

DATA: NREL EUSS Database
HOUSING FILTERS: Occupied units for Single Family, Small Multi-Family, and Mobile Homes
GEOGRAPHIC FILTERS: National, State, or City
ANALYSIS FOCUS: Space Conditioning (Heating + Cooling Equipment Only)

Additional details data can be found in the official End-Use Load Profiles/Savings Shapes documentation.
Our methodology is detailed in the process_euss_data.py file and its associated imports.

RESULTS OUTPUT:

Retrieved data for filename: baseline_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\baseline_metadata_and_annual_results.csv

C:\Users\jorda\AppData\Local\Temp\ipykernel_14944\3577416974.py:33: DtypeWarning: Columns (113) have mixed types. Specify dtype option on import or set low_memory=False.
  df_euss_am_baseline = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id'

Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 259)
You chose to analyze all of the United States.

====================================================================================================================================================================
DATAFRAME: df_euss_am_baseline

         upgrade      weight  applicability  in.sqft  \
bldg_id
1              0  242.131013           True   1690.0
2              0  242.131013           True   1690.0
5              0  242.131013           True   2176.0
6              0  242.131013           True   1690.0
8              0  242.131013           True   1220.0
...          ...         ...            ...      ...
549995         0  242.131013           True   1220.0
549996         0  242.131013           True    853.0
549997         0  242.131013           True   1623.0
549998         0  242.131013           True   1690.0
549999         0  242.131013           True   2176.0

                                            in.ahs_region  \
bldg_id
1                                 Non-CBSA South Atlantic
2                                       Non-CBSA Mountain
5                             Non-CBSA West North Central
6          CBSA Miami-Fort Lauderdale-West Palm Beach, FL
8                             Non-CBSA West North Central
...                                                   ...
549995                        Non-CBSA West South Central
549996   CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
549997         CBSA New York-Newark-Jersey City, NY-NJ-PA
549998            CBSA Los Angeles-Long Beach-Anaheim, CA
549999                        Non-CBSA East South Central

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
1                                     4A
2                                     6B
5                                     4A
6                                     2A
8                                     5A
...                                  ...
549995                                2A
549996                                4A
549997                                5A
549998                                3B
549999                                3A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
1                                               4A                     Hour22
2                                               6B                     Hour22
5                                               4A                     Hour19
6                              2A - FL, GA, AL, MS                      Hour7
8                                               5A                      Hour4
...                                            ...                        ...
549995                                 2A - TX, LA                     Hour17
549996                                          4A                      Hour0
549997                                          5A                      Hour8
549998                                          3B                      Hour3
549999                                          3A                     Hour17

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
1                  3                      Mixed-Humid  ...
2                  3                             Cold  ...
5                  3                      Mixed-Humid  ...
6                  3                        Hot-Humid  ...
8                  2                             Cold  ...
...              ...                              ...  ...
549995             3                        Hot-Humid  ...
549996             2                      Mixed-Humid  ...
549997             3                             Cold  ...
549998             2                          Hot-Dry  ...
549999             5                        Hot-Humid  ...

        out.emissions.natural_gas.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
1                                                 0.000000
2                                             11698.051968
5                                              1120.975525
6                                                 0.000000
8                                              7039.287743
...                                                    ...
549995                                            0.000000
549996                                            0.000000
549997                                         5806.032685
549998                                         2227.263275
549999                                            0.000000

        out.emissions.propane.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
1                                              4545.057690
2                                                 0.000000
5                                                 0.000000
6                                                 0.000000
8                                                 0.000000
...                                                    ...
549995                                          401.108104
549996                                          152.954976
549997                                            0.000000
549998                                            0.000000
549999                                          713.835096

        out.emissions.electricity.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                              3821.031734
2                                              1484.025414
5                                             10726.472987
6                                              4534.191431
8                                              2283.155834
...                                                    ...
549995                                         8876.118664
549996                                         5018.503798
549997                                         2528.881335
549998                                         1903.402858
549999                                         4908.129352

        out.emissions.fuel_oil.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                                      0.0
2                                                      0.0
5                                                      0.0
6                                                      0.0
8                                                      0.0
...                                                    ...
549995                                                 0.0
549996                                                 0.0
549997                                                 0.0
549998                                                 0.0
549999                                                 0.0

        out.emissions.natural_gas.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                                 0.000000
2                                             11698.051968
5                                              1120.975525
6                                                 0.000000
8                                              7039.287743
...                                                    ...
549995                                            0.000000
549996                                            0.000000
549997                                         5806.032685
549998                                         2227.263275
549999                                            0.000000

        out.emissions.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                              4545.057690
2                                                 0.000000
5                                                 0.000000
6                                                 0.000000
8                                                 0.000000
...                                                    ...
549995                                          401.108104
549996                                          152.954976
549997                                            0.000000
549998                                            0.000000
549999                                          713.835096

        out.emissions.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
1                                              6305.129895
2                                             12644.960060
5                                              6125.036034
6                                              1802.311180
8                                              8392.180510
...                                                    ...
549995                                         4901.746854
549996                                         2173.658182
549997                                         6901.983972
549998                                         4236.552736
549999                                         2540.236113

        out.emissions.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
1                                              7225.786328
2                                             12496.100116
5                                              9884.570622
6                                              3171.276993
8                                              7986.184041
...                                                    ...
549995                                         6716.204784
549996                                         4889.406873
549997                                         8227.778224
549998                                         3243.038028
549999                                         4020.170124

        out.emissions.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
1                                              7133.629513
2                                             12444.101647
5                                              9125.980474
6                                              2401.704014
8                                              8034.931160
...                                                    ...
549995                                         6298.994605
549996                                         4257.138572
549997                                         7944.079330
549998                                         3098.643247
549999                                         3733.931567

        out.emissions.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg
bldg_id
1                                              8366.089424
2                                             13182.077382
5                                             11847.448512
6                                              4534.191431
8                                              9322.443577
...                                                    ...
549995                                         9277.226768
549996                                         5171.458773
549997                                         8334.914020
549998                                         4130.666133
549999                                         5621.964447

[396252 rows x 259 columns]


====================================================================================================================================================================
LOAD EUSS DATA FOR BASELINE SCENARIO: MEASURE PACKAGE 0 (MP0)
====================================================================================================================================================================
In addition to the housing type and occupancy filters, the data has been filtered for fuel and technology
Please see the energy_consumption_and_metadata folder for more details on data processing.

We employ the df_enduse_refactored function to process the data and create a new dataframe, which is part of the 5-step data validation process:
1. Mask Initialization with initialize_validation_tracking()
2. Series Initialization with create_retrofit_only_series()
3. Valid-Only Calculation for qualifying homes
4. Valid-Only Updates using list-based collection
5. Final Masking with apply_final_masking()

Documentation for df_enduse_refactored function:
Creates a standardized energy usage DataFrame and applies data quality filters.

    This function creates a new DataFrame with standardized column names and structure,
    calculates total consumption by fuel type, creates data quality flags for analysis,
    and sets invalid consumption values to NaN.

    Args:
        df_baseline: The baseline DataFrame containing raw EUSS/ResStock data.

    Returns:
        A standardized DataFrame with processed consumption data and data quality flags.

    Raises:
        ValueError: If required columns are missing from the input DataFrame.

----------------------------------------------------------------

RESULTS OUTPUT (BASELINE):

Processing column: in.clothes_dryer
Initial data types: object
Data types after processing: object
Processing column: in.cooking_range
Initial data types: object
Data types after processing: object
Calculated total heating consumption

Creating data quality flags for all categories

--- Processing heating ---
Values in base_heating_fuel (top 5):
base_heating_fuel
Natural Gas    206940
Electricity    137402
Propane         20625
Fuel Oil        19836
Other Fuel      10308
Name: count, dtype: int64
  heating: Found 11449 homes (2.9%) with invalid fuel types
  Invalid fuel types (top 5):
base_heating_fuel
Other Fuel    10308
Name: count, dtype: int64
Values in heating_type (top 5):
heating_type
Natural Gas Fuel Furnace               148721
Electricity Electric Furnace            64671
Electricity ASHP                        40131
Electricity Baseboard                   28852
Natural Gas Fuel Wall/Floor Furnace     27144
Name: count, dtype: int64
Allowed values for heating:
['Electricity Baseboard', 'Electricity Electric Boiler', 'Electricity Electric Furnace', 'Fuel Oil Fuel Boiler', 'Fuel Oil Fuel Furnace', 'Natural Gas Fuel Boiler', 'Natural Gas Fuel Furnace', 'Propane Fuel Boiler', 'Propane Fuel Furnace']
  heating: Found 92736 homes (23.4%) with invalid technology types
  Invalid technology types (top 5):
heating_type
Electricity ASHP                       40131
Natural Gas Fuel Wall/Floor Furnace    27144
Natural Gas Shared Heating              5614
Propane Fuel Wall/Floor Furnace         4006
Electricity Shared Heating              2670
Name: count, dtype: int64
  heating: Total 92736 homes (23.4%) excluded from analysis

Total 92736 homes (23.4%) excluded from all categories

Applying data validation (baseline only):
Baseline calculation for heating:
  - 303516 homes have valid data
  - 92736 homes have invalid data (values will be NaN)
  base_electricity_heating_consumption: Masked 92736 values
  base_naturalGas_heating_consumption: Masked 92736 values
  base_fuelOil_heating_consumption: Masked 92736 values
  base_propane_heating_consumption: Masked 92736 values
  baseline_heating_consumption: Masked 81171 values

====================================================================================================================================================================
DATAFRAME: df_euss_am_baseline_home

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity  ... base_propane_heating_consumption base_cooling_fuel  \
bldg_id             ...
1            Rural  ...                     16516.313221       Electricity
2            Rural  ...                         0.000000       Electricity
5            Rural  ...                         0.000000       Electricity
6         Suburban  ...                              NaN       Electricity
8            Rural  ...                         0.000000       Electricity
...            ...  ...                              ...               ...
549995       Rural  ...                         0.000000       Electricity
549996    Suburban  ...                              NaN       Electricity
549997    Suburban  ...                         0.000000       Electricity
549998    Suburban  ...                         0.000000       Electricity
549999       Rural  ...                      2593.972041       Electricity

        cooling_type base_cooling_efficiency  \
bldg_id
1         Central AC             AC, SEER 15
2                NaN                     NaN
5         Central AC             AC, SEER 13
6                NaN                     NaN
8         Central AC             AC, SEER 13
...              ...                     ...
549995    Central AC             AC, SEER 13
549996           NaN                     NaN
549997       Room AC       Room AC, EER 12.0
549998    Central AC             AC, SEER 15
549999    Central AC             AC, SEER 15

        base_electricity_cooling_consumption  baseline_heating_consumption  \
bldg_id
1                                2085.786805                  16516.313221
2                                   0.000000                  46812.828153
5                                4124.389168                  15824.372425
6                                   0.000000                           NaN
8                                3135.567378                  27903.003504
...                                      ...                           ...
549995                           6632.198314                    462.759220
549996                              0.000000                           NaN

## MEASURE PACKAGE 3 (MP3): Space Conditioning Analysis
### Metadata, Space Heating, and Cooling annual energy consumption data for Measure Package 3.

In [6]:
# # Print debugging information
# print_debug = False

# if print_debug:
#     from cmu_tare_model.utils.create_sample_df import create_sample_df

In [7]:
import pandas as pd
import os

In [8]:
# Measure Package 3
menu_mp = 3
input_mp = 'upgrade03'
scenario_name = 'Basic-BAU'
cost_scenario = 'BAU Costs'
grid_scenario = 'Current Electricity Grid'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

filename = "upgrade03_metadata_and_annual_results.csv"
relative_path = os.path.join("cmu_tare_model", "data", "euss_data", "resstock_amy2018_release_1.1", "national", 'csv', filename)

file_path = os.path.join(PROJECT_ROOT, relative_path)

print(f"Retrieved data for filename: {filename}")
print(f"Located at filepath: {file_path}")
print("\n")

# Fix DtypeWarning error in columns 'in.neighbors' and 'in.geometry_stories_low_rise'
columns_to_string = {11: str, 61: str, 121: str, 103: str, 128: str, 129: str}
df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)
print(f"DATAFRAME SIZE before applying any filters: {df_euss_am_mp3.shape}")

# Filter for occupied homes
occupancy_filter = df_euss_am_mp3['in.vacancy_status'] == 'Occupied'
df_euss_am_mp3 = df_euss_am_mp3.loc[occupancy_filter]
print(f"DATAFRAME SIZE after filtering for 'Occupied' homes: {df_euss_am_mp3.shape}")

# Filter for allowed housing types
house_type_filter = df_euss_am_mp3['in.geometry_building_type_recs'].isin(ALLOWED_HOUSING_TYPES)
df_euss_am_mp3 = df_euss_am_mp3.loc[house_type_filter]
print(f"Allowed housing types: {ALLOWED_HOUSING_TYPES}")
print(f"DATAFRAME SIZE after filtering for allowed housing types: {df_euss_am_mp3.shape}")

# National Level 
if menu_state == 'N':
    print("You chose to analyze all of the United States.")
    input_state = 'National'

# Filter down to state or city
else:
    print(f"You chose to filter for: {input_state}")
    state_filter = df_euss_am_mp3['in.state'].eq(input_state)
    df_euss_am_mp3 = df_euss_am_mp3.loc[state_filter]

    # Filter for the entire selected state
    if menu_city == 'N':
        print(f"You chose to analyze all of state: {input_state}")
        
    # Filter to a city within the selected state
    else:
        print(f"You chose to filter for: {input_state}, {input_cityFilter}")
        city_filter = df_euss_am_mp3['in.city'].eq(f"{input_state}, {input_cityFilter}")
        df_euss_am_mp3 = df_euss_am_mp3.loc[city_filter]

# Display the filtered dataframe
# Display the filtered dataframe
print(f"DATAFRAME SIZE after applying geographic filter: {df_euss_am_mp3.shape}")
print(df_euss_am_mp3)

====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario Basic-BAU:
Basic Retrofit: Measure Package 3
BAU Costs
Current Electricity Grid
====================================================================================================================================================================

Retrieved data for filename: upgrade03_metadata_and_annual_results.csv
Located at filepath: c:\users\jorda\desktop\projects\cmu-tare-model\cmu_tare_model\data\euss_data\resstock_amy2018_release_1.1\national\csv\upgrade03_metadata_and_annual_results.csv

C:\Users\jorda\AppData\Local\Temp\ipykernel_14944\2869588233.py:30: DtypeWarning: Columns (113) have mixed types. Specify dtype option on import or set low_memory=False.
  df_euss_am_mp3 = pd.read_csv(file_path, dtype=columns_to_string, index_col="bldg_id") # UPDATE: Set index to 'bldg_id' (unique identifier)

DATAFRAME SIZE before applying any filters: (548916, 343)
DATAFRAME SIZE after filtering for 'Occupied' homes: (482597, 343)
Allowed housing types: ['Single-Family Attached', 'Single-Family Detached', 'Mobile Home', 'Multi-Family with 2 - 4 Units']
DATAFRAME SIZE after filtering for allowed housing types: (396252, 343)
You chose to analyze all of the United States.
DATAFRAME SIZE after applying geographic filter: (396252, 343)
         upgrade      weight  applicability  in.sqft  \
bldg_id
1              3  242.131013           True   1690.0
2              3  242.131013           True   1690.0
5              3  242.131013           True   2176.0
6              3  242.131013           True   1690.0
8              3  242.131013           True   1220.0
...          ...         ...            ...      ...
549995         3  242.131013           True   1220.0
549996         3  242.131013           True    853.0
549997         3  242.131013           True   1623.0
549998         3  242.131013           True   1690.0
549999         3  242.131013           True   2176.0

                                            in.ahs_region  \
bldg_id
1                                 Non-CBSA South Atlantic
2                                       Non-CBSA Mountain
5                             Non-CBSA West North Central
6          CBSA Miami-Fort Lauderdale-West Palm Beach, FL
8                             Non-CBSA West North Central
...                                                   ...
549995                        Non-CBSA West South Central
549996   CBSA Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
549997         CBSA New York-Newark-Jersey City, NY-NJ-PA
549998            CBSA Los Angeles-Long Beach-Anaheim, CA
549999                        Non-CBSA East South Central

        in.ashrae_iecc_climate_zone_2004  \
bldg_id
1                                     4A
2                                     6B
5                                     4A
6                                     2A
8                                     5A
...                                  ...
549995                                2A
549996                                4A
549997                                5A
549998                                3B
549999                                3A

        in.ashrae_iecc_climate_zone_2004_2_a_split in.bathroom_spot_vent_hour  \
bldg_id
1                                               4A                     Hour22
2                                               6B                     Hour22
5                                               4A                     Hour19
6                              2A - FL, GA, AL, MS                      Hour7
8                                               5A                      Hour4
...                                            ...                        ...
549995                                 2A - TX, LA                     Hour17
549996                                          4A                      Hour0
549997                                          5A                      Hour8
549998                                          3B                      Hour3
549999                                          3A                     Hour17

         in.bedrooms in.building_america_climate_zone  ...  \
bldg_id                                                ...
1                  3                      Mixed-Humid  ...
2                  3                             Cold  ...
5                  3                      Mixed-Humid  ...
6                  3                        Hot-Humid  ...
8                  2                             Cold  ...
...              ...                              ...  ...
549995             3                        Hot-Humid  ...
549996             2                      Mixed-Humid  ...
549997             3                             Cold  ...
549998             2                          Hot-Dry  ...
549999             5                        Hot-Humid  ...

        out.emissions_reduction.electricity.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                             -2219.034655
2                                             -5389.159524
5                                              3342.531700
6                                             -1852.573751
8                                             -3205.759993
...                                                    ...
549995                                          373.783700
549996                                         2229.294915
549997                                        -3826.182729
549998                                            8.017245
549999                                        -1066.378425

        out.emissions_reduction.fuel_oil.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                                      0.0
2                                                      0.0
5                                                      0.0
6                                                      0.0
8                                                      0.0
...                                                    ...
549995                                                 0.0
549996                                                 0.0
549997                                                 0.0
549998                                                 0.0
549999                                                 0.0

        out.emissions_reduction.natural_gas.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                                 0.000000
2                                             10664.268690
5                                                -0.100698
6                                                 0.000000
8                                              6363.614734
...                                                    ...
549995                                            0.000000
549996                                            0.000000
549997                                         4269.542962
549998                                            0.025401
549999                                            0.000000

        out.emissions_reduction.propane.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                              4545.057690
2                                                 0.000000
5                                                 0.000000
6                                                 0.000000
8                                                 0.000000
...                                                    ...
549995                                            0.000000
549996                                            0.000000
549997                                            0.000000
549998                                            0.000000
549999                                          713.835096

        out.emissions_reduction.all_fuels.lrmer_95_decarb_by_2035_15_2025_start.co2e_kg  \
bldg_id
1                                              3555.470184
2                                              7100.866990
5                                              1540.725368
6                                              -741.350009
8                                              4617.934108
...                                                    ...
549995                                          190.813156
549996                                          835.244083
549997                                         2679.204115
549998                                            8.500321
549999                                          314.716448

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_15_2025_start.co2e_kg  \
bldg_id
1                                              2881.908195
2                                              7520.515228
5                                              2708.817800
6                                             -1253.501607
8                                              5020.915548
...                                                    ...
549995                                          273.318433
549996                                         2063.194832
549997                                          550.989992
549998                                            4.050126
549999                                            2.604074

        out.emissions_reduction.all_fuels.lrmer_low_re_cost_25_2025_start.co2e_kg  \
bldg_id
1                                              3022.220644
2                                              7805.105431
5                                              2437.843986
6                                              -964.456220
8                                              5100.237060
...                                                    ...
549995                                          254.896232
549996                                         1760.701338
549997                                         1045.159828
549998                                            3.572494
549999                                           50.270735

        out.emissions_reduction.all_fuels.lrmer_mid_case_15_2025_start.co2e_kg  \
bldg_id
1                                              2326.023034
2                                              5275.109166
5                                              3342.431002
6                                             -1852.573751
8                                              3157.854742
...                                                    ...
549995                                          373.783700
549996                                         2229.294915
549997                                          443.360233
549998                                            8.042646
549999                                         -352.543330

        upgrade.hvac_cooling_efficiency    upgrade.hvac_heating_efficiency
bldg_id
1                             Heat Pump            ASHP, SEER 15, 9.0 HSPF
2                             Heat Pump            ASHP, SEER 15, 9.0 HSPF
5                             Heat Pump            ASHP, SEER 15, 9.0 HSPF
6                             Heat Pump  MSHP, SEER 15, 9.0 HSPF, Max Load
8                             Heat Pump            ASHP, SEER 15, 9.0 HSPF
...                                 ...                                ...
549995                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549996                        Heat Pump  MSHP, SEER 15, 9.0 HSPF, Max Load
549997                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549998                        Heat Pump            ASHP, SEER 15, 9.0 HSPF
549999                        Heat Pump            ASHP, SEER 15, 9.0 HSPF

[396252 rows x 343 columns]

In [9]:
# TRANE Analysis: No cooking data needed for space conditioning analysis
# Cooking equipment is excluded from this workflow
df_euss_am_mp7 = None  # Set to None for compatibility with legacy functions

# Project Future Energy Consumption

In [10]:
from cmu_tare_model.energy_consumption_and_metadata.process_euss_data import df_enduse_compare

print(F"""
====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE {menu_mp} (MP{menu_mp})
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp3.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied. 
      - df_euss_am_mp3_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp3_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.
      
Documentation for df_enduse_compare function:
{df_enduse_compare.__doc__}
----------------------------------------------------------------

RESULTING DATAFRAME:
""")

# df_enduse_compare(df_mp, category, df_baseline):
df_euss_am_mp3_home = df_enduse_compare(
    df_mp = df_euss_am_mp3,
    input_mp=input_mp,
    menu_mp=menu_mp,
    df_baseline = df_euss_am_baseline_home,
    df_cooking_range=df_euss_am_mp7,
    )

====================================================================================================================================================================
LOAD EUSS DATA FOR MEASURE PACKAGE 3 (MP3)
====================================================================================================================================================================
You'll notice that the number of rows differs from df_euss_am_mp7 and df_euss_am_mp3.
      - df_euss_am_baseline_home has fewer rows (representative dwelling units) because a tech filter was applied.
      - df_euss_am_mp3_home will have the same number of rows as df_euss_am_baseline_home after df_enduse_compare function is run.
      - df_enduse_compare function performs an inner merge on the two dataframes, keeping only the rows that are present in both dataframes.
====================================================================================================================================================================
df_euss_am_mp3_home will be created by running the df_enduse_compare function (contains post-retrofit consumption data for the entire home in 2024).
process_euss_data.py file contains the function definition.

Documentation for df_enduse_compare function:
Creates a comparison DataFrame by merging multiple DataFrames based on measure packages.

    This function constructs a new DataFrame (df_compare) that includes columns
    from df_mp, df_cooking_range, and merges them with df_baseline to compare
    baseline vs. measure package outputs.

    Only includes columns for equipment categories present in EQUIPMENT_SPECS.

    Args:
        df_mp: The main DataFrame containing modeling parameters and outputs.
        input_mp: The input measure package ID (e.g., 'upgrade09', 'upgrade10').
        menu_mp: The menu measure package number.
        df_baseline: The baseline DataFrame to merge with df_compare.
        df_cooking_range: Additional DataFrame for cooking range parameters/outputs.

    Returns:
        A merged DataFrame (df_compare) that includes relevant columns for
        baseline and measure packages comparison.

----------------------------------------------------------------

RESULTING DATAFRAME:


Applying combined validation (data quality + retrofit status):
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)
  mp3_heating_consumption: Masked 92736 values

# PUBLIC IMPACTS: Climate and Health Damages
## Scenarios: No IRA and IRA-Reference

In [11]:
from cmu_tare_model.public_impact.calculate_lifetime_climate_impacts_sensitivity import calculate_lifetime_climate_impacts
from cmu_tare_model.public_impact.calculate_lifetime_health_impacts_sensitivity import calculate_lifetime_health_impacts

print(f"""
====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================

""")

# Make copies from scenario consumption to keep df smaller
print("\n", "Creating dataframe to store marginal damages calculations ...")
# Climate damages: No IRA and IRA-Reference
df_mp3_noIRA_damages_climate = df_euss_am_mp3_home.copy()
df_mp3_IRA_damages_climate = df_euss_am_mp3_home.copy()

# Health damages: No IRA and IRA-Reference
df_mp3_noIRA_damages_health = df_euss_am_mp3_home.copy()
df_mp3_IRA_damages_health = df_euss_am_mp3_home.copy()

====================================================================================================================================================================
PUBLIC IMPACTS: DAMAGES FROM CLIMATE AND HEALTH-RELATED EMISSIONS
====================================================================================================================================================================



 Creating dataframe to store marginal damages calculations ...

In [12]:
# Health Impacts: Baseline Scenario
print(f"""
====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
{df_euss_am_baseline_home}
      
df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
{df_baseline_damages_health}

""")

====================================================================================================================================================================
df_euss_am_baseline_home: DataFrame containing the baseline scenario data
         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity  ... baseline_heating_lifetime_damages_climate_srmer_upper  \
bldg_id             ...
1            Rural  ...                                           25057.25
2            Rural  ...                                           63173.17
5            Rural  ...                                           85660.16
6         Suburban  ...                                                NaN
8            Rural  ...                                           36557.99
...            ...  ...                                                ...
549995       Rural  ...                                            1961.40
549996    Suburban  ...                                                NaN
549997    Suburban  ...                                           24244.24
549998    Suburban  ...                                               0.00
549999       Rural  ...                                            3964.24

          county_key baseline_heating_lifetime_damages_health_ap2_acs  \
bldg_id
1        (51033, VA)                                           171.01
2        (56025, WY)                                           971.09
5        (29169, MO)                                          4538.27
6        (12099, FL)                                              NaN
8        (31147, NE)                                           608.00
...              ...                                              ...
549995   (48489, TX)                                            21.47
549996   (34015, NJ)                                              NaN
549997   (34003, NJ)                                          1296.75
549998   (06037, CA)                                             0.00
549999   (01091, AL)                                            27.34

        baseline_heating_lifetime_damages_health_ap2_h6c  \
bldg_id
1                                                 439.31
2                                                2494.88
5                                               11659.98
6                                                    NaN
8                                                1562.05
...                                                  ...
549995                                             55.16
549996                                               NaN
549997                                           3331.71
549998                                              0.00
549999                                             70.23

        baseline_heating_lifetime_damages_health_easiur_acs  \
bldg_id
1                                                   988.07
2                                                   225.12
5                                                  4509.28
6                                                      NaN
8                                                   690.54
...                                                    ...
549995                                               35.32
549996                                                 NaN
549997                                             3529.21
549998                                                0.00
549999                                               49.01

         baseline_heating_lifetime_damages_health_easiur_h6c  \
bldg_id
1                                                  2538.58
2                                                   578.24
5                                                 11585.48
6                                                      NaN
8                                                  1774.14
...                                                    ...
549995                                               90.74
549996                                                 NaN
549997                                             9067.62
549998                                                0.00
549999                                              125.92

         baseline_heating_lifetime_damages_health_inmap_acs  \
bldg_id
1                                                   359.14
2                                                   974.82
5                                                  4799.76
6                                                      NaN
8                                                   979.22
...                                                    ...
549995                                               15.58
549996                                                 NaN
549997                                             3928.70
549998                                                0.00
549999                                               83.11

        baseline_heating_lifetime_damages_health_inmap_h6c fuel_type_heating  \
bldg_id
1                                                   922.65           propane
2                                                  2504.46        naturalGas
5                                                 12331.82       electricity
6                                                      NaN               NaN
8                                                  2515.84        naturalGas
...                                                    ...               ...
549995                                               40.03       electricity
549996                                                 NaN       electricity
549997                                            10094.06        naturalGas
549998                                                0.00       electricity
549999                                              213.53           propane

        baseline_heating_lifetime_fuel_cost
bldg_id
1                                  30295.50
2                                  27681.40
5                                  25606.73
6                                       NaN
8                                  13497.28
...                                     ...
549995                               814.63
549996                                  NaN
549997                              8523.47
549998                                 0.00
549999                                 0.00

[396252 rows x 57 columns]

df_baseline_damages_health: DataFrame containing the baseline scenario data with health damages
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
1               True             True                True                True
2               True             True                True                True
5               True             True                True                True
6              False            False               False               False
8               True             True                True                True
...              ...              ...                 ...                 ...
549995          True             True                True                True
549996         False            False               False                True
549997          True             True                True                True
549998          True             True                True                True
549999          True             True                True                True

         baseline_2024_heating_damages_so2_ap2_acs  \
bldg_id
1                                             0.21
2                                             0.79
5                                           560.32
6                                              NaN
8                                             0.22
...                                            ...
549995                                        4.66
549996                                         NaN
549997                                        4.05
549998                                        0.00
549999                                        0.01

         baseline_2024_heating_damages_nox_ap2_acs  \
bldg_id
1                                             6.57
2                                            58.20
5                                            78.77
6                                              NaN
8                                            35.73
...                                            ...
549995                                        1.35
549996                                         NaN
549997                                       -2.95
549998                                        0.00
549999                                        1.56

         baseline_2024_heating_damages_pm25_ap2_acs  \
bldg_id
1                                              4.39
2                                              2.54
5                                             13.60
6                                               NaN
8                                              2.24
...                                             ...
549995                                         0.43
549996                                          NaN
549997                                        81.94
549998                                         0.00
549999                                         0.17

         baseline_2024_heating_damages_health_ap2_acs  \
bldg_id
1                                               11.17
2                                               61.53
5                                              652.69
6                                                 NaN
8                                               38.20
...                                               ...
549995                                           6.44
549996                                            NaN
549997                                          83.05
549998                                           0.00
549999                                           1.75

         baseline_2024_heating_damages_so2_ap2_h6c  \
bldg_id
1                                             0.54
2                                             2.04
5                                          1439.60
6                                              NaN
8                                             0.56
...                                            ...
549995                                       11.98
549996                                         NaN
549997                                       10.42
549998                                        0.00
549999                                        0.04

         baseline_2024_heating_damages_nox_ap2_h6c  ...  \
bldg_id                                             ...
1                                            16.87  ...
2                                           149.52  ...
5                                           202.37  ...
6                                              NaN  ...
8                                            91.80  ...
...                                            ...  ...
549995                                        3.47  ...
549996                                         NaN  ...
549997                                       -7.58  ...
549998                                        0.00  ...
549999                                        4.01  ...

         baseline_2038_heating_damages_so2_inmap_h6c  \
bldg_id
1                                               0.29
2                                               1.22
5                                             329.88
6                                                NaN
8                                               1.56
...                                              ...
549995                                          0.39
549996                                           NaN
549997                                          8.00
549998                                          0.00
549999                                          0.05

         baseline_2038_heating_damages_nox_inmap_h6c  \
bldg_id
1                                              50.30
2                                             165.95
5                                              75.95
6                                                NaN
8                                             167.91
...                                              ...
549995                                          0.12
549996                                           NaN
549997                                        402.75
549998                                          0.00
549999                                         14.15

         baseline_2038_heating_damages_pm25_inmap_h6c  \
bldg_id
1                                               12.08
2                                                8.26
5                                               10.89
6                                                 NaN
8                                                8.20
...                                               ...
549995                                           0.02
549996                                            NaN
549997                                         289.01
549998                                           0.00
549999                                           0.63

         baseline_2038_heating_damages_health_inmap_h6c  \
bldg_id
1                                                 62.67
2                                                175.43
5                                                416.72
6                                                   NaN
8                                                177.67
...                                                 ...
549995                                             0.53
549996                                              NaN
549997                                           699.76
549998                                             0.00
549999                                            14.82

         baseline_heating_lifetime_damages_health_ap2_acs  \
bldg_id
1                                                  171.01
2                                                  971.09
5                                                 4538.27
6                                                     NaN
8                                                  608.00
...                                                   ...
549995                                              21.47
549996                                                NaN
549997                                            1296.75
549998                                               0.00
549999                                              27.34

         baseline_heating_lifetime_damages_health_ap2_h6c  \
bldg_id
1                                                  439.31
2                                                 2494.88
5                                                11659.98
6                                                     NaN
8                                                 1562.05
...                                                   ...
549995                                              55.16
549996                                                NaN
549997                                            3331.71
549998                                               0.00
549999                                              70.23

         baseline_heating_lifetime_damages_health_easiur_acs  \
bldg_id
1                                                   988.07
2                                                   225.12
5                                                  4509.28
6                                                      NaN
8                                                   690.54
...                                                    ...
549995                                               35.32
549996                                                 NaN
549997                                             3529.21
549998                                                0.00
549999                                               49.01

         baseline_heating_lifetime_damages_health_easiur_h6c  \
bldg_id
1                                                  2538.58
2                                                   578.24
5                                                 11585.48
6                                                      NaN
8                                                  1774.14
...                                                    ...
549995                                               90.74
549996                                                 NaN
549997                                             9067.62
549998                                                0.00
549999                                              125.92

         baseline_heating_lifetime_damages_health_inmap_acs  \
bldg_id
1                                                   359.14
2                                                   974.82
5                                                  4799.76
6                                                      NaN
8                                                   979.22
...                                                    ...
549995                                               15.58
549996                                                 NaN
549997                                             3928.70
549998                                                0.00
549999                                               83.11

         baseline_heating_lifetime_damages_health_inmap_h6c
bldg_id
1                                                   922.65

In [13]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp3_home, df_mp3_noIRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )

df_euss_am_mp3_home, df_mp3_noIRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='No Inflation Reduction Act', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp3_home, df_mp3_IRA_damages_climate = calculate_lifetime_climate_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_climate,
    verbose=False  # Add this parameter
    )


df_euss_am_mp3_home, df_mp3_IRA_damages_health = calculate_lifetime_health_impacts(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp, 
    policy_scenario='AEO2023 Reference Case', 
    df_baseline_damages=df_baseline_damages_health,
    debug=False,
    verbose=False  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
Post-Retrofit (mp3) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well. 
      
CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp3_noIRA_damages_climate
{df_mp3_noIRA_damages_climate}

Climate Damages (IRA): df_mp3_IRA_damages_climate
{df_mp3_IRA_damages_climate}

HEALTH DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Health Damages (No IRA): df_mp3_noIRA_damages_health
{df_mp3_noIRA_damages_health}

Health Damages (IRA): df_mp3_IRA_damages_health
{df_mp3_IRA_damages_health}

SUMMARY DATAFRAME FOR mp3: df_euss_am_mp3_home
{df_euss_am_mp3_home}
====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

Verifying masking for all calculated columns:

====================================================================================================================================================================
Post-Retrofit (mp3) Marginal Damages: WHOLE-HOME
Scenario: No Inflation Reduction Act and AEO2023 Reference Case
====================================================================================================================================================================
calculate_emissions_damages.py file contains the definition for the calculate_marginal_damages function.
Additional information on emissions and damage factor lookups can be found in the calculate_emissions_damages.py file as well.

CLIMATE DAMAGES: No IRA and IRA-Reference
--------------------------------------------------------
Climate Damages (No IRA): df_mp3_noIRA_damages_climate
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
1               True             True                True                True
2               True             True                True                True
5               True             True                True                True
6              False            False               False               False
8               True             True                True                True
...              ...              ...                 ...                 ...
549995          True             True                True                True
549996         False            False               False                True
549997          True             True                True                True
549998          True             True                True                True
549999          True             True                True                True

         preIRA_mp3_2024_heating_mt_co2e_lrmer  \
bldg_id
1                                         2.92
2                                         4.33
5                                         3.24
6                                          NaN
8                                         3.70
...                                        ...
549995                                    0.09
549996                                     NaN
549997                                    2.81
549998                                    0.00
549999                                    0.36

         preIRA_mp3_2024_heating_damages_climate_lrmer_lower  \
bldg_id
1                                                   189.39
2                                                   280.13
5                                                   209.97
6                                                      NaN
8                                                   239.71
...                                                    ...
549995                                                5.63
549996                                                 NaN
549997                                              181.79
549998                                                0.21
549999                                               23.59

         preIRA_mp3_2024_heating_damages_climate_lrmer_central  \
bldg_id
1                                                   695.56
2                                                  1028.82
5                                                   771.18
6                                                      NaN
8                                                   880.40
...                                                    ...
549995                                               20.66
549996                                                 NaN
549997                                              667.67
549998                                                0.77
549999                                               86.65

         preIRA_mp3_2024_heating_damages_climate_lrmer_upper  \
bldg_id
1                                                  1122.54
2                                                  1660.38
5                                                  1244.57
6                                                      NaN
8                                                  1420.85
...                                                    ...
549995                                               33.34
549996                                                 NaN
549997                                             1077.52
549998                                                1.24
549999                                              139.84

         preIRA_mp3_2024_heating_mt_co2e_srmer  \
bldg_id
1                                         4.16
2                                         8.12
5                                         5.03
6                                          NaN
8                                         6.04
...                                        ...
549995                                    0.14
549996                                     NaN
549997                                    4.10
549998                                    0.01
549999                                    0.49

         preIRA_mp3_2024_heating_damages_climate_srmer_lower  ...  \
bldg_id                                                       ...
1                                                   269.33    ...
2                                                   526.03    ...
5                                                   325.78    ...
6                                                      NaN    ...
8                                                   391.05    ...
...                                                    ...    ...
549995                                                8.91    ...
549996                                                 NaN    ...
549997                                              265.25    ...
549998                                                0.59    ...
549999                                               31.65    ...

         preIRA_mp3_heating_avoided_damages_climate_lrmer_upper  \
bldg_id
1                                                 13739.74
2                                                 46972.00
5                                                 23897.39
6                                                      NaN
8                                                 23566.69
...                                                    ...
549995                                              530.21
549996                                                 NaN
549997                                            12279.68
549998                                              -12.65
549999                                             2347.97

         preIRA_mp3_heating_avoided_mt_co2e_lrmer  \
bldg_id
1                                           32.75
2                                          112.43
5                                           57.84
6                                             NaN
8                                           56.03
...                                           ...
549995                                       1.29
549996                                        NaN
549997                                      29.24
549998                                      -0.03
549999                                       5.62

         preIRA_mp3_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                            57.14
2                                           109.94
5                                            71.46
6                                              NaN
8                                            81.69
...                                            ...
549995                                        1.94
549996                                         NaN
549997                                       55.62
549998                                        0.13
549999                                        6.99

         preIRA_mp3_heating_lifetime_damages_climate_srmer_lower  \
bldg_id
1                                                  4204.07
2                                                  8088.54
5                                                  5273.16
6                                                      NaN
8                                                  6019.70
...                                                    ...
549995                                              142.67
549996                                                 NaN
549997                                             4095.11
549998                                                9.26
549999                                              515.10

         preIRA_mp3_heating_avoided_damages_climate_srmer_lower  \
bldg_id
1                                                   238.34
2                                                  3117.18
5                                                  9914.57
6                                                      NaN
8                                                   465.90
...                                                    ...
549995                                              204.97
549996                                                 NaN
549997                                              204.60
549998                                               -9.26
549999                                              187.98

         preIRA_mp3_heating_lifetime_damages_climate_srmer_central  \
bldg_id
1                                                 14942.82
2                                                 28751.00
5                                                 18730.26
6                                                      NaN
8                                                 21388.94
...                                                    ...
549995                                              506.86
549996                                                 NaN
549997                                            14553.76
549998                                               32.92
549999                                             1830.01

         preIRA_mp3_heating_avoided_damages_climate_srmer_central  \
bldg_id
1                                                   837.28
2                                                 11040.05
5                                                 35216.55
6                                                      NaN
8                                                  1639.05
...                                                    ...
549995                                              728.23
549996                                                 NaN
549997                                              716.10
549998                                              -32.92
549999                                              666.83

         preIRA_mp3_heating_lifetime_damages_climate_srmer_upper  \
bldg_id
1                                                 23735.57
2                                                 45669.22
5                                                 29741.09
6                                                      NaN
8                                                 33968.39
...                                                    ...
549995                                              804.93
549996                                                 NaN
549997                                            23115.93
549998                                               52.28
549999                                             2906.14

         preIRA_mp3_heating_avoided_damages_climate_srmer_upper  \
bldg_id
1                                                  1321.68
2                                                 17503.95
5                                                 55919.07
6                                                      NaN
8                                                  2589.60
...                                                    ...
549995                                             1156.47
549996                                                 NaN
549997                                             1128.31
549998                                              -52.28
549999                                             1058.10

         preIRA_mp3_heating_avoided_mt_co2e_srmer
bldg_id
1                                            3.07
2                                           41.73
5                                          134.36
6                                             NaN
8                                            6.06
...                                           ...
549995                                       2.78
549996                                        NaN
549997                                       2.60
549998                                      -0.13
549999                                       2.53

[396252 rows x 140 columns]

Climate Damages (IRA): df_mp3_IRA_damages_climate
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
1               True             True                True                True
2               True             True                True                True
5               True             True                True                True
6              False            False               False               False
8               True             True                True                True
...              ...              ...                 ...                 ...
549995          True             True                True                True
549996         False            False               False                True
549997          True             True                True                True
549998          True             True                True                True
549999          True             True                True                True

         iraRef_mp3_2024_heating_mt_co2e_lrmer  \
bldg_id
1                                         1.71
2                                         3.66
5                                         2.31
6                                          NaN
8                                         1.90
...                                        ...
549995                                    0.05
549996                                     NaN
549997                                    2.00
549998                                    0.00
549999                                    0.21

         iraRef_mp3_2024_heating_damages_climate_lrmer_lower  \
bldg_id
1                                                   110.66
2                                                   237.10
5                                                   149.26
6                                                      NaN
8                                                   123.01
...                                                    ...
549995                                                3.37
549996                                                 NaN
549997                                              129.26
549998                                                0.16
549999                                               13.29

         iraRef_mp3_2024_heating_damages_climate_lrmer_central  \
bldg_id
1                                                   406.44
2                                                   870.82
5                                                   548.18
6                                                      NaN
8                                                   451.79
...                                                    ...
549995                                               12.37
549996                                                 NaN
549997                                              474.74
549998                                                0.57
549999                                               48.80

         iraRef_mp3_2024_heating_damages_climate_lrmer_upper  \
bldg_id
1                                                   655.94
2                                                  1405.38
5                                                   884.68
6                                                      NaN
8                                                   729.12
...                                                    ...
549995                                               19.96
549996                                                 NaN
549997                                              766.17
549998                                                0.92
549999                                               78.76

         iraRef_mp3_2024_heating_mt_co2e_srmer  \
bldg_id
1                                         3.93
2                                         8.16
5                                         5.08
6                                          NaN
8                                         5.86
...                                        ...
549995                                    0.12
549996                                     NaN
549997                                    4.11
549998                                    0.01
549999                                    0.48

         iraRef_mp3_2024_heating_damages_climate_srmer_lower  ...  \
bldg_id                                                       ...
1                                                   254.39    ...
2                                                   528.26    ...
5                                                   328.77    ...
6                                                      NaN    ...
8                                                   379.68    ...
...                                                    ...    ...

# PRIVATE IMPACTS: FUEL COSTS
## Scenarios: No IRA and IRA-Reference

In [14]:
from cmu_tare_model.private_impact.calculate_lifetime_fuel_costs import calculate_lifetime_fuel_costs

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:
{calculate_lifetime_fuel_costs.__doc__}

====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference

""")

print("\n", "Creating dataframe to store annual fuel cost calculations ...")
# Annual fuel costs: No IRA and IRA-Reference
df_mp3_fuel_costs_noIRA = df_euss_am_mp3_home.copy()
df_mp3_fuel_costs_IRA = df_euss_am_mp3_home.copy()

====================================================================================================================================================================
PRIVATE IMPACTS: OVERVIEW
====================================================================================================================================================================
Step 1: Calculate annual operating (fuel) costs
Step 2: Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
Step 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)

----------------------------------------------------------------------------------------------------------------------
Step 1: Calculate annual operating (fuel) costs
----------------------------------------------------------------------------------------------------------------------

Documentation for calculate_lifetime_fuel_costs function:

    Calculate lifetime fuel costs for each equipment category.

    This function processes each equipment category over its lifetime, computing annual
    and lifetime fuel costs. Results are combined into two DataFrames:
    a main summary (df_main) and a detailed annual breakdown (df_detailed).

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    Args:
        df: Input DataFrame containing equipment consumption data, region info, etc.
        menu_mp: Measure package identifier (0 for baseline, nonzero for different scenarios).
        policy_scenario: Determines fuel price scenario inputs
            (e.g., 'No Inflation Reduction Act' or 'AEO2023 Reference Case').
        df_baseline_costs: Optional DataFrame with baseline costs for computing operational savings.
            Default is None.
        verbose: Whether to print detailed processing information. Default is True.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Main summary of lifetime fuel costs (rounded to 2 decimals).
            - df_detailed: Detailed annual and lifetime results (rounded to 2 decimals).

    Raises:
        RuntimeError: If processing fails at the category or year level.
        ValueError: If an invalid policy_scenario is provided.
        KeyError: If required columns are missing from the input DataFrame.


====================================================================================================================================================================
FUEL COSTS RESULTS: No IRA and IRA-Reference



 Creating dataframe to store annual fuel cost calculations ...

In [15]:
print("""
==================== SCENARIO: No Inflation Reduction Act ==========
""")
df_euss_am_mp3_home, df_mp3_noIRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )

print("""
==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========
""")
df_euss_am_mp3_home, df_mp3_IRA_fuel_costs = calculate_lifetime_fuel_costs(
    df=df_euss_am_mp3_home,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    df_baseline_costs=df_baseline_fuel_costs  # Add this line
    )


print(f"""  
====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp3_noIRA_fuel_costs
{df_mp3_noIRA_fuel_costs}

FUEL COSTS (IRA): df_mp3_IRA_fuel_costs
{df_mp3_IRA_fuel_costs}

SUMMARY DATAFRAME FOR mp3: df_euss_am_mp3_home
{df_euss_am_mp3_home}

====================================================================================================================================================================
""")

==================== SCENARIO: No Inflation Reduction Act ==========

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 3 columns for category 'heating'
Dropping 1 overlapping columns from original DataFrame.

Verifying masking for all calculated columns:
Masking 48 columns for category 'heating'

==================== SCENARIO: Inflation Reduction Act (AEO2023 Reference Case) ==========

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Calculating Fuel Costs from 2024 to 2039 for heating
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:

Verifying masking for all calculated columns:
Masking 3 columns for category 'heating'
Dropping 1 overlapping columns from original DataFrame.

Verifying masking for all calculated columns:
Masking 48 columns for category 'heating'

====================================================================================================================================================================
Creating Dataframes for Lifetime Fuel Costs ...

FUEL COSTS (No IRA): df_mp3_noIRA_fuel_costs
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
1               True             True                True                True
2               True             True                True                True
5               True             True                True                True
6              False            False               False               False
8               True             True                True                True
...              ...              ...                 ...                 ...
549995          True             True                True                True
549996         False            False               False                True
549997          True             True                True                True
549998          True             True                True                True
549999          True             True                True                True

         preIRA_mp3_2024_heating_fuel_cost  baseline_2024_heating_fuel_cost  \
bldg_id
1                                   568.81                          2217.48
2                                   979.00                          1812.04
5                                   598.83                          1724.75
6                                      NaN                              NaN
8                                   680.08                           946.63
...                                    ...                              ...
549995                               22.86                            55.70
549996                                 NaN                              NaN
549997                              793.66                           642.98
549998                                2.62                             0.00
549999                               69.80                             0.00

         preIRA_mp3_2025_heating_fuel_cost  baseline_2025_heating_fuel_cost  \
bldg_id
1                                   554.69                          2126.82
2                                   958.19                          1758.41
5                                   593.77                          1710.18
6                                      NaN                              NaN
8                                   674.33                           898.21
...                                    ...                              ...
549995                               22.52                            54.88
549996                                 NaN                              NaN
549997                              793.30                           608.44
549998                                2.37                             0.00
549999                               67.27                             0.00

         preIRA_mp3_2026_heating_fuel_cost  baseline_2026_heating_fuel_cost  \
bldg_id
1                                   545.88                          2046.51
2                                   946.48                          1741.56
5                                   590.01                          1699.35
6                                      NaN                              NaN
8                                   670.06                           869.58
...                                    ...                              ...
549995                               22.10                            53.85
549996                                 NaN                              NaN
549997                              785.64                           582.02
549998                                2.34                             0.00
549999                               66.62                             0.00

         ...  baseline_2035_heating_fuel_cost  \
bldg_id  ...
1        ...                          2009.08
2        ...                          1899.54
5        ...                          1711.88
6        ...                              NaN
8        ...                           915.09
...      ...                              ...
549995   ...                            53.63
549996   ...                              NaN
549997   ...                           553.93
549998   ...                             0.00
549999   ...                             0.00

         preIRA_mp3_2036_heating_fuel_cost  baseline_2036_heating_fuel_cost  \
bldg_id
1                                   517.48                          2013.92
2                                   991.94                          1898.82
5                                   592.98                          1707.91
6                                      NaN                              NaN
8                                   673.44                           915.03
...                                    ...                              ...
549995                               22.31                            54.36
549996                                 NaN                              NaN
549997                              827.28                           549.11
549998                                2.50                             0.00
549999                               65.68                             0.00

         preIRA_mp3_2037_heating_fuel_cost  baseline_2037_heating_fuel_cost  \
bldg_id
1                                   512.66                          2023.11
2                                   997.56                          1911.28
5                                   589.02                          1696.50
6                                      NaN                              NaN
8                                   668.94                           922.86
...                                    ...                              ...
549995                               22.12                            53.90
549996                                 NaN                              NaN
549997                              828.39                           552.39
549998                                2.53                             0.00
549999                               65.70                             0.00

         preIRA_mp3_2038_heating_fuel_cost  baseline_2038_heating_fuel_cost  \
bldg_id
1                                   509.36                          2030.99
2                                  1000.19                          1917.35
5                                   587.72                          1692.75
6                                      NaN                              NaN
8                                   667.46                           927.88
...                                    ...                              ...
549995                               22.19                            54.08
549996                                 NaN                              NaN
549997                              832.07                           553.42
549998                                2.58                             0.00
549999                               65.54                             0.00

         preIRA_mp3_heating_lifetime_fuel_cost  \
bldg_id
1                                      7999.42
2                                     14570.29
5                                      8890.62
6                                          NaN
8                                     10096.86
...                                        ...
549995                                  334.31
549996                                     NaN
549997                                12108.23
549998                                   36.76
549999                                  999.90

         preIRA_mp3_heating_lifetime_savings_fuel_cost  \
bldg_id
1                                             22296.08
2                                             13111.11
5                                             16716.11
6                                                  NaN
8                                              3400.42
...                                                ...
549995                                          480.32
549996                                             NaN
549997                                        -3584.76
549998                                          -36.76
549999                                         -999.90

         baseline_heating_lifetime_fuel_cost
bldg_id
1                                   30295.50
2                                   27681.40
5                                   25606.73
6                                        NaN
8                                   13497.28
...                                      ...
549995                                814.63
549996                                   NaN
549997                               8523.47
549998                                  0.00
549999                                  0.00

[396252 rows x 37 columns]

FUEL COSTS (IRA): df_mp3_IRA_fuel_costs
         include_all  include_heating  valid_tech_heating  valid_fuel_heating  \
bldg_id
1               True             True                True                True
2               True             True                True                True
5               True             True                True                True
6              False            False               False               False
8               True             True                True                True
...              ...              ...                 ...                 ...
549995          True             True                True                True
549996         False            False               False                True
549997          True             True                True                True
549998          True             True                True                True
549999          True             True                True                True

         iraRef_mp3_2024_heating_fuel_cost  baseline_2024_heating_fuel_cost  \
bldg_id
1                                   568.56                          2217.48
2                                   977.99                          1812.04
5                                   595.29                          1724.75
6                                      NaN                              NaN
8                                   676.06                           946.63
...                                    ...                              ...
549995                               23.13                            55.70
549996                                 NaN                              NaN
549997                              800.24                           642.98
549998                                2.64                             0.00
549999                               69.87                             0.00

         iraRef_mp3_2025_heating_fuel_cost  baseline_2025_heating_fuel_cost  \
bldg_id
1                                   553.39                          2126.82
2                                   955.82                          1758.41
5                                   590.64                          1710.18
6                                      NaN                              NaN
8                                   670.77                           898.21
...                                    ...                              ...
549995                               22.50                            54.88
549996                                 NaN                              NaN
549997                              789.42                           608.44
549998                                2.38                             0.00
549999                               67.40                             0.00

         iraRef_mp3_2026_heating_fuel_cost  baseline_2026_heating_fuel_cost  \
bldg_id
1                                   538.40                          2046.51
2                                   941.08                          1741.56
5                                   581.69                          1699.35
6                                      NaN                              NaN
8                                   660.61                           869.58
...                                    ...                              ...
549995                               21.79                            53.85
549996                                 NaN                              NaN
549997                              776.98                           582.02
549998                                2.35                             0.00
549999                               65.25                             0.00

         ...  baseline_2035_heating_fuel_cost  \
bldg_id  ...
1        ...                          2009.08
2        ...                          1899.54
5        ...                          1711.88
6        ...                              NaN
8        ...                           915.09
...      ...                              ...
549995   ...                            53.63
549996   ...                              NaN
549997   ...                           553.93
549998   ...                             0.00
549999   ...                             0.00

         iraRef_mp3_2036_heating_fuel_cost  baseline_2036_heating_fuel_cost  \
bldg_id
1                                   497.77                          2013.92
2                                   943.37                          1898.82
5                                   557.98                          1707.91
6                                      NaN                              NaN
8                                   633.69                           915.03
...                                    ...                              ...
549995                               21.33                            54.36
549996                                 NaN                              NaN
549997                              803.02                           549.11
549998                                2.53                             0.00
549999                               63.61                             0.00

         iraRef_mp3_2037_heating_fuel_cost  baseline_2037_heating_fuel_cost  \
bldg_id
1                                   500.72                          2023.11
2                                   955.30                          1911.28
5                                   558.67                          1696.50
6                                      NaN                              NaN
8                                   634.47                           922.86
...                                    ...                              ...
549995                               21.25                            53.90
549996                                 NaN                              NaN
549997                              803.68                           552.39
549998                                2.54                             0.00
549999                               63.96                             0.00

         iraRef_mp3_2038_heating_fuel_cost  baseline_2038_heating_fuel_cost  \
bldg_id
1                                   505.25                          2030.99
2                                   972.85                          1917.35
5                                   560.54                          1692.75
6                                      NaN                              NaN
8                                   636.59                           927.88
...                                    ...                              ...
549995                               21.21                            54.08
549996                                 NaN                              NaN
549997                              809.64                           553.42
549998                                2.56                             0.00
549999                               64.34                             0.00

         iraRef_mp3_heating_lifetime_fuel_cost  \
bldg_id
1                                      7690.95
2                                     14093.93
5                                      8566.22
6                                          NaN
8                                      9728.45
...                                        ...
549995                                  320.35
549996                                     NaN
549997                                11855.39
549998                                   36.65
549999                                  958.12

         iraRef_mp3_heating_lifetime_savings_fuel_cost  \
bldg_id
1                                             22604.55
2                                             13587.47
5                                             17040.51
6                                                  NaN
8                                              3768.83
...                                                ...
549995                                          494.28
549996                                             NaN
549997                                        -3331.92
549998                                          -36.65
549999                                         -958.12

         baseline_heating_lifetime_fuel_cost
bldg_id
1                                   30295.50
2                                   27681.40
5                                   25606.73
6                                        NaN
8                                   13497.28
...                                      ...
549995                                814.63

# PRIVATE IMPACTS: CAPITAL COSTS
## Scenarios: No IRA and IRA-Reference

In [16]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
from cmu_tare_model.utils.remdb_v4_installed_cost_utils import load_remdb_v4_data, add_remdb_upgrade_metrics, add_remdb_replacement_metrics
from cmu_tare_model.private_impact.calculations.calculate_equipment_installation_costs import (
    calculate_upgrade_installed_cost
    )
from cmu_tare_model.private_impact.calculations.calculate_equipment_replacement_costs import (
    calculate_replacement_installed_cost
)

print(f"""
====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Load REMDB v4 Data and prepare for regression cost calculations
----------------------------------------------------------------------------------------------------------------------
Documentation for load_remdb_v4_data function:
{load_remdb_v4_data.__doc__}

Documentation for add_remdb_upgrade_metrics function:
{add_remdb_upgrade_metrics.__doc__}

Documentation for add_remdb_replacement_metrics function:
{add_remdb_replacement_metrics.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_upgrade_installed_cost function:
{calculate_upgrade_installed_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:
{calculate_replacement_installed_cost.__doc__}

----------------------------------------------------------------------------------------------------------------------
Step 5 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

""")

====================================================================================================================================================================
PRIVATE IMPACTS: NET CAPITAL COSTS AND TOTAL CAPITAL COSTS
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs

----------------------------------------------------------------------------------------------------------------------
Step 2: Load REMDB v4 Data and prepare for regression cost calculations
----------------------------------------------------------------------------------------------------------------------
Documentation for load_remdb_v4_data function:
Load REMDB v4 retrofit cost data.

    Args:
        data_dir: Optional custom directory path.
        filename: CSV filename.

    Returns:
        DataFrame indexed by row_id with cost regression parameters.


Documentation for add_remdb_upgrade_metrics function:

    Prepare UPGRADE cost metrics from BASELINE equipment for REMDB v4 calculations.

    This function performs ALL preparation steps:
    1. Assigns row_id based on equipment type
    2. Maps REMDB coefficients and unit specifications
    3. Extracts metrics from EUSS data with correct unit conversions
    4. Fills missing values from REMDB bounds
    5. Separates columns into main (summary) and detailed (all intermediates) DataFrames

    Args:
        df: DataFrame with baseline equipment specifications.
        remdb_v4_costs: REMDB v4 cost database (indexed by row_id).
        end_use: Equipment category ('heating', 'cooling').
        percentile: Cost percentile ('low', 'mid', 'high').
        df_detailed: Optional detailed DataFrame to append new columns.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Updated DataFrame with summary columns only.
            - df_detailed_out: Updated detailed DataFrame with all calculation columns.


Documentation for add_remdb_replacement_metrics function:

    Prepare REPLACEMENT cost metrics from BASELINE equipment for REMDB v4 calculations.

    This function performs ALL preparation steps:
    1. Assigns row_id based on equipment type
    2. Maps REMDB coefficients and unit specifications
    3. Extracts metrics from EUSS data with correct unit conversions
    4. Fills missing values from REMDB bounds
    5. Separates columns into main (summary) and detailed (all intermediates) DataFrames

    Args:
        df: DataFrame with baseline equipment specifications.
        remdb_v4_costs: REMDB v4 cost database (indexed by row_id).
        end_use: Equipment category ('heating', 'cooling').
        percentile: Cost percentile ('low', 'mid', 'high').
        df_detailed: Optional detailed DataFrame to append new columns.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_main: Updated DataFrame with summary columns only.
            - df_detailed_out: Updated detailed DataFrame with all calculation columns.


----------------------------------------------------------------------------------------------------------------------
Step 3: Calculate equipment capital costs (For space heating, include ductwork)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_upgrade_installed_cost function:

    Calculate UPGRADE installed costs using REMDB v4 regression formula.

    PREREQUISITE: Call add_remdb_upgrade_metrics() first to do the following:
    - Extract metrics (capacity, efficiency)
    - Assign row_id (technology mapping)
    - Map REMDB parameters (coefficients, multiplier)

    Then use this function to calculate installed costs:
    - Calculate costs (regression formula)
    - Uses the validation framework to ensure only valid homes receive cost calculations.

    Args:
        df: DataFrame with prepared metrics.
        df_detailed: Detailed DataFrame with regression parameters.
        menu_mp: Measure package number.
        end_use: Equipment category.
        percentile: Cost percentile.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_copy: Updated DataFrame with new cost column.
            - df_detailed_out: Updated detailed DataFrame with new cost column.


----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate replacement cost (replacing existing piece of eqipment with similar technology)
----------------------------------------------------------------------------------------------------------------------
Documentation for calculate_replacement_cost function:

    Calculate REPLACEMENT installed costs using REMDB v4 regression formula.

    PREREQUISITE: Call add_remdb_replacement_metrics() first to do the following:
    - Extract metrics (capacity, efficiency)
    - Assign row_id (technology mapping)
    - Map REMDB parameters (coefficients, multiplier)

    Then use this function to calculate installed costs:
    - Calculate costs (regression formula)
    - Uses the validation framework to ensure only valid homes receive cost calculations.

    SPECIAL CASE - COOLING: Creates temporary include_cooling flag for validation,
    then removes it to prevent downstream interference.

    Args:
        df: DataFrame with prepared metrics.
        df_detailed: Detailed DataFrame with regression parameters.
        menu_mp: Measure package number.
        end_use: Equipment category.
        percentile: Cost percentile.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]:
            - df_copy: Updated DataFrame with new cost column.
            - df_detailed_out: Updated detailed DataFrame with new cost column.


----------------------------------------------------------------------------------------------------------------------
Step 5 (MP9 AND MP10 SPACE HEATING ONLY): Calculate Enclosure Upgrade Costs
----------------------------------------------------------------------------------------------------------------------
FOR MODERATE (MP9) AND ADVANCED (MP10) ONLY:
calculate_enclosure_upgrade_costs.py file contains the definition for the calculate_enclosure_upgrade_costs function.

====================================================================================================================================================================
LIFETIME CAPITAL COSTS RESULTS: No IRA and IRA-Reference (Rebates)

In [17]:
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows')

In [18]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
REMDB_v4_PATH = os.path.join(PROJECT_ROOT, 'cmu_tare_model', 'data', 'retrofit_costs')

df_tare_remdb_v4_costs = load_remdb_v4_data(
    data_dir=REMDB_v4_PATH,
    filename="remdb_v4_tare_retrofit_costs.csv")

print(f"""
Final cleaned dataframe for retrofit capital costs:
{df_tare_remdb_v4_costs}

--------------------------------------------------""")

Final cleaned dataframe for retrofit capital costs:
                                                    Unnamed: 0  tare_category  \
row_id
air_conditioner_centrally_ducted                             0        cooling
air_conditioner_room_ac_window_or_through_wall               1        cooling
air_sealing_lt40pct_reduction                                2      enclosure
air_sealing_gt40pct_reduction                                3      enclosure
air_source_heat_pump_centrally_ducted                        4        heating
air_source_heat_pump_centrally_ducted_with_new_...           5        heating
air_source_heat_pump_non_ducted_single_zone                  6        heating
air_source_heat_pump_non_ducted_multi_zone                   7        heating
boiler_gas_non_condensing                                    9        heating
boiler_gas_condensing                                       10        heating
boiler_oil                                                  11        heating
clothes_dryer_electric                                      12  clothesDrying
clothes_dryer_heat_pump                                     13  clothesDrying
clothes_dryer_gas                                           14  clothesDrying
cooking_range_electric                                      22        cooking
cooking_range_induction                                     23        cooking
cooking_range_gas                                           24        cooking
duct_duct_insulation                                        44      enclosure
duct_duct_sealing                                           45      enclosure
electric_baseboard_default                                  46        heating
furnaces_gas_furnace                                        71        heating
unfinished_attic_ceiling_batt                               96      enclosure
unfinished_attic_ceiling_loose_fill                         97      enclosure
unfinished_attic_ceiling_spray_foam_closed_cell             98      enclosure
unfinished_attic_ceiling_spray_foam_open_cell               99      enclosure
water_heater_electric_instantaneous                        116   waterHeating
water_heater_electric_storage                              117   waterHeating
water_heater_hp_tank                                       118   waterHeating
water_heater_hp_tank_w_gas_capping                         119   waterHeating
water_heater_hp_tank_w_gas_capping_and_240v_wiring         120   waterHeating
water_heater_gas_inst                                      121   waterHeating
water_heater_gas_storage                                   122   waterHeating

                                                                     component  \
row_id
air_conditioner_centrally_ducted                               Air Conditioner
air_conditioner_room_ac_window_or_through_wall                 Air Conditioner
air_sealing_lt40pct_reduction                                      Air Sealing
air_sealing_gt40pct_reduction                                      Air Sealing
air_source_heat_pump_centrally_ducted                     Air Source Heat Pump
air_source_heat_pump_centrally_ducted_with_new_...        Air Source Heat Pump
air_source_heat_pump_non_ducted_single_zone               Air Source Heat Pump
air_source_heat_pump_non_ducted_multi_zone                Air Source Heat Pump
boiler_gas_non_condensing                                               Boiler
boiler_gas_condensing                                                   Boiler
boiler_oil                                                              Boiler
clothes_dryer_electric                                           Clothes Dryer
clothes_dryer_heat_pump                                          Clothes Dryer
clothes_dryer_gas                                                Clothes Dryer
cooking_range_electric                                           Cooking Range
cooking_range_induction                                          Cooking Range
cooking_range_gas                                                Cooking Range
duct_duct_insulation                                                      Duct
duct_duct_sealing                                                        Duct
electric_baseboard_default                                  Electric Baseboard
furnaces_gas_furnace                                                  Furnaces
unfinished_attic_ceiling_batt                       Unfinished Attic (Ceiling)
unfinished_attic_ceiling_loose_fill                 Unfinished Attic (Ceiling)
unfinished_attic_ceiling_spray_foam_closed_cell     Unfinished Attic (Ceiling)
unfinished_attic_ceiling_spray_foam_open_cell       Unfinished Attic (Ceiling)
water_heater_electric_instantaneous                               Water Heater
water_heater_electric_storage                                     Water Heater
water_heater_hp_tank                                              Water Heater
water_heater_hp_tank_w_gas_capping                                Water Heater
water_heater_hp_tank_w_gas_capping_and_240v_wiring                Water Heater
water_heater_gas_inst                                             Water Heater
water_heater_gas_storage                                          Water Heater

                                                                                     class  \
row_id
air_conditioner_centrally_ducted                                          Centrally ducted
air_conditioner_room_ac_window_or_through_wall            Room AC (window or through-wall)
air_sealing_lt40pct_reduction                                               <40% Reduction
air_sealing_gt40pct_reduction                                               >40% Reduction
air_source_heat_pump_centrally_ducted                                     Centrally ducted
air_source_heat_pump_centrally_ducted_with_new_...      Centrally ducted, with new circuit
air_source_heat_pump_non_ducted_single_zone                        Non-ducted, single-zone
air_source_heat_pump_non_ducted_multi_zone                          Non-ducted, multi-zone
boiler_gas_non_condensing                                             Gas (Non-Condensing)
boiler_gas_condensing                                                     Gas (Condensing)
boiler_oil                                                                             Oil
clothes_dryer_electric                                                            Electric
clothes_dryer_heat_pump                                                          Heat Pump
clothes_dryer_gas                                                                      Gas
cooking_range_electric                                                            Electric
cooking_range_induction                                                          Induction
cooking_range_gas                                                                      Gas
duct_duct_insulation                                                       Duct Insulation
duct_duct_sealing                                                             Duct Sealing
electric_baseboard_default                                                             NaN
furnaces_gas_furnace                                                           Gas Furnace
unfinished_attic_ceiling_batt                                                         Batt
unfinished_attic_ceiling_loose_fill                                             Loose Fill
unfinished_attic_ceiling_spray_foam_closed_cell                   Spray Foam (Closed Cell)
unfinished_attic_ceiling_spray_foam_open_cell                       Spray Foam (Open Cell)
water_heater_electric_instantaneous                                 Electric Instantaneous
water_heater_electric_storage                                             Electric Storage
water_heater_hp_tank                                                               HP Tank
water_heater_hp_tank_w_gas_capping                                  HP Tank w/ Gas Capping
water_heater_hp_tank_w_gas_capping_and_240v_wiring  HP Tank w/ Gas Capping and 240V Wiring
water_heater_gas_inst                                                             Gas Inst
water_heater_gas_storage                                                       Gas Storage

                                                   output_units  \
row_id
air_conditioner_centrally_ducted                          2023$
air_conditioner_room_ac_window_or_through_wall            2023$
air_sealing_lt40pct_reduction                        2023$/sqft
air_sealing_gt40pct_reduction                        2023$/sqft
air_source_heat_pump_centrally_ducted                     2023$
air_source_heat_pump_centrally_ducted_with_new_...        2023$
air_source_heat_pump_non_ducted_single_zone               2023$
air_source_heat_pump_non_ducted_multi_zone                2023$
boiler_gas_non_condensing                                 2023$
boiler_gas_condensing                                     2023$
boiler_oil                                                2023$
clothes_dryer_electric                                    2023$
clothes_dryer_heat_pump                                   2023$
clothes_dryer_gas                                         2023$
cooking_range_electric                                    2023$
cooking_range_induction                                   2023$
cooking_range_gas                                         2023$
duct_duct_insulation                                 2023$/sqft
duct_duct_sealing                                    2023$/sqft
electric_baseboard_default                                2023$
furnaces_gas_furnace                                      2023$
unfinished_attic_ceiling_batt                        2023$/sqft
unfinished_attic_ceiling_loose_fill                  2023$/sqft
unfinished_attic_ceiling_spray_foam_closed_cell      2023$/sqft
unfinished_attic_ceiling_spray_foam_open_cell        2023$/sqft
water_heater_electric_instantaneous                       2023$
water_heater_electric_storage                             2023$
water_heater_hp_tank                                      2023$
water_heater_hp_tank_w_gas_capping                        2023$
water_heater_hp_tank_w_gas_capping_and_240v_wiring        2023$
water_heater_gas_inst                                     2023$
water_heater_gas_storage                                  2023$

                                                           pm1_metric  \
row_id
air_conditioner_centrally_ducted                     Cooling Capacity
air_conditioner_room_ac_window_or_through_wall               Capacity
air_sealing_lt40pct_reduction                       Leakage Reduction
air_sealing_gt40pct_reduction                       Leakage Reduction
air_source_heat_pump_centrally_ducted                Cooling Capacity
air_source_heat_pump_centrally_ducted_with_new_...   Cooling Capacity
air_source_heat_pump_non_ducted_single_zone          Cooling Capacity
air_source_heat_pump_non_ducted_multi_zone           Cooling Capacity
boiler_gas_non_condensing                            Heating Capacity
boiler_gas_condensing                                Heating Capacity
boiler_oil                                           Heating Capacity
clothes_dryer_electric                                         Volume
clothes_dryer_heat_pump                                        Volume
clothes_dryer_gas                                              Volume
cooking_range_electric                                         Volume
cooking_range_induction                                        Volume
cooking_range_gas                                              Volume
duct_duct_insulation                                          R-value
duct_duct_sealing                                   Leakage Reduction
electric_baseboard_default                                   Capacity
furnaces_gas_furnace                                 Heating Capacity
unfinished_attic_ceiling_batt                                 R-value
unfinished_attic_ceiling_loose_fill                           R-value
unfinished_attic_ceiling_spray_foam_closed_cell               R-value
unfinished_attic_ceiling_spray_foam_open_cell                 R-value
water_heater_electric_instantaneous                               UEF
water_heater_electric_storage                                     UEF
water_heater_hp_tank                                              UEF
water_heater_hp_tank_w_gas_capping                                UEF
water_heater_hp_tank_w_gas_capping_and_240v_wiring                UEF
water_heater_gas_inst                                             UEF
water_heater_gas_storage                                          UEF

                                                        pm1_unit  \
row_id
air_conditioner_centrally_ducted                            Tons
air_conditioner_room_ac_window_or_through_wall              Tons
air_sealing_lt40pct_reduction                            Percent
air_sealing_gt40pct_reduction                            Percent
air_source_heat_pump_centrally_ducted                       Tons
air_source_heat_pump_centrally_ducted_with_new_...          Tons
air_source_heat_pump_non_ducted_single_zone                 Tons
air_source_heat_pump_non_ducted_multi_zone                  Tons
boiler_gas_non_condensing                                 BTU/hr
boiler_gas_condensing                                     BTU/hr
boiler_oil                                                BTU/hr
clothes_dryer_electric                                  Cubic ft
clothes_dryer_heat_pump                                 Cubic ft
clothes_dryer_gas                                       Cubic ft
cooking_range_electric                                  Cubic ft
cooking_range_induction                                 Cubic ft
cooking_range_gas                                       Cubic ft
duct_duct_insulation                                ft2·°F·h/BTU
duct_duct_sealing                                        Percent
electric_baseboard_default                                BTU/Hr
furnaces_gas_furnace                                      BTU/Hr
unfinished_attic_ceiling_batt                       ft2·°F·h/BTU
unfinished_attic_ceiling_loose_fill                 ft2·°F·h/BTU
unfinished_attic_ceiling_spray_foam_closed_cell     ft2·°F·h/BTU
unfinished_attic_ceiling_spray_foam_open_cell       ft2·°F·h/BTU
water_heater_electric_instantaneous                     Unitless
water_heater_electric_storage                           Unitless
water_heater_hp_tank                                    Unitless
water_heater_hp_tank_w_gas_capping                      Unitless
water_heater_hp_tank_w_gas_capping_and_240v_wiring      Unitless
water_heater_gas_inst                                   Unitless
water_heater_gas_storage                                Unitless

                                                    pm1_coef_low  \
row_id
air_conditioner_centrally_ducted                      196.966095
air_conditioner_room_ac_window_or_through_wall        350.160000
air_sealing_lt40pct_reduction                           0.480450
air_sealing_gt40pct_reduction                           0.107294
air_source_heat_pump_centrally_ducted                 639.168000
air_source_heat_pump_centrally_ducted_with_new_...    639.168000
air_source_heat_pump_non_ducted_single_zone          1878.048000
air_source_heat_pump_non_ducted_multi_zone           1878.048000
boiler_gas_non_condensing                               0.013611
boiler_gas_condensing                                   0.020390
boiler_oil                                              0.013617
clothes_dryer_electric                                 37.500000
clothes_dryer_heat_pump                                45.900353
clothes_dryer_gas                                      71.678322
cooking_range_electric                                 27.703333
cooking_range_induction                              1048.888889
cooking_range_gas                                     111.854839
duct_duct_insulation                                    0.250999
duct_duct_sealing                                       0.151667
electric_baseboard_default                              0.034056
furnaces_gas_furnace                                    0.004744
unfinished_attic_ceiling_batt                           0.031667
unfinished_attic_ceiling_loose_fill                     0.008696
unfinished_attic_ceiling_spray_foam_closed_cell         0.209286
unfinished_attic_ceiling_spray_foam_open_cell           0.146427
water_heater_electric_instantaneous                   250.000019
water_heater_electric_storage                         571.423485
water_heater_hp_tank                                  102.325583
water_heater_hp_tank_w_gas_capping                    102.325583
water_heater_hp_tank_w_gas_capping_and_240v_wiring    102.325583
water_heater_gas_inst                                4192.333369
water_heater_gas_storage                             5190.140327

                                                    pm1_coef_mid  \
row_id
air_conditioner_centrally_ducted                      328.276825
air_conditioner_room_ac_window_or_through_wall        364.332000
air_sealing_lt40pct_reduction                           0.894236
air_sealing_gt40pct_reduction                           0.867979
air_source_heat_pump_centrally_ducted                1065.280000
air_source_heat_pump_centrally_ducted_with_new_...   1065.280000
air_source_heat_pump_non_ducted_single_zone          3130.080000
air_source_heat_pump_non_ducted_multi_zone           3130.080000
boiler_gas_non_condensing                               0.017470
boiler_gas_condensing                                   0.030098
boiler_oil                                              0.018460
clothes_dryer_electric                                -42.857155
clothes_dryer_heat_pump                                34.365975
clothes_dryer_gas                                     170.121951
cooking_range_electric                                127.969233
cooking_range_induction                                49.000000
cooking_range_gas                                     674.418603
duct_duct_insulation                                    0.163885
duct_duct_sealing                                       0.298588
electric_baseboard_default                              0.056760
furnaces_gas_furnace                                    0.006450
unfinished_attic_ceiling_batt                           0.043000
unfinished_attic_ceiling_loose_fill                     0.017857
unfinished_attic_ceiling_spray_foam_closed_cell         0.301055
unfinished_attic_ceiling_spray_foam_open_cell           0.273450
water_heater_electric_instantaneous                   353.549649
water_heater_electric_storage                       10549.499565
water_heater_hp_tank                                  248.326452
water_heater_hp_tank_w_gas_capping                    248.326452
water_heater_hp_tank_w_gas_capping_and_240v_wiring    248.326452
water_heater_gas_inst                                3885.583326
water_heater_gas_storage                             8799.424875

                                                    pm1_coef_high  \
row_id
air_conditioner_centrally_ducted                       459.587555
air_conditioner_room_ac_window_or_through_wall         311.640000
air_sealing_lt40pct_reduction                            1.333659
air_sealing_gt40pct_reduction                            0.785978
air_source_heat_pump_centrally_ducted                 1491.392000
air_source_heat_pump_centrally_ducted_with_new_...    1491.392000
air_source_heat_pump_non_ducted_single_zone           4382.112000
air_source_heat_pump_non_ducted_multi_zone            4382.112000
boiler_gas_non_condensing                                0.020046
boiler_gas_condensing                                    0.027623
boiler_oil                                               0.020154

### Space Heating and No Enclosure Upgrade

#### Space Heating Capital Costs

In [19]:
# Configuration
# menu_mp = 3
percentile = 'mid'

# Initialize detailed DataFrame as None (created on first call)
df_detailed_mp3_installed_costs = None

# Heating upgrade
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_upgrade_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_upgrade_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

# Heating replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

Preparing heating UPGRADE metrics (REMDB v4)
  Filled 130 missing euss_heating_upgrade_pm2 from REMDB bounds

  WARNING: 140,726 homes have out-of-bounds capacity (method=keep_as_is)
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 48,721 below; range 0.270833 to 1.49917
      - 43,547 above; range 5.00083 to 64.0775
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 1.5 to 5)
      - 4,086 below; range 0.255 to 1.49917
      - 44,372 above; range 5.00083 to 326.303

  WARNING: 80,094 homes have out-of-bounds efficiency (method=keep_as_is)
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 16 to 23)
      - 80,094 below; range 15 to 15
  Valid metrics after bounds checking: 396,252 pm1, 396,252 pm2

Calculating heating upgrade costs (REMDB v4)
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 303,516 homes (mean: $17,087.14)


Preparing heating REPLACEMENT metrics (REMDB v4)
  Warning: 11,449 homes with unknown row_id
  Filled 11,449 missing euss_heating_replacement_pm1 from REMDB bounds
  Filled 6,144 missing euss_heating_replacement_pm2 from REMDB bounds

  WARNING: 121,357 homes have out-of-bounds capacity (method=keep_as_is)
    • furnaces_gas_furnace (bounds: 30000 to 156250)
      - 101,588 below; range 3250 to 29990
      - 8,362 above; range 156260 to 3.88804e+06
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 4,310 below; range 0.321667 to 1.49917
      - 6,874 above; range 5.00083 to 44.1058
    • electric_baseboard_default (bounds: 1194.2 to 416000)
      - 223 above; range 417070 to 3.91564e+06

  WARNING: 84,264 homes have out-of-bounds efficiency (method=keep_as_is)
    • furnaces_gas_furnace (bounds: 0.8 to 0.97)
      - 51,701 below; range 0.6 to 0.76
    • air_source_heat_pump_centrally_ducted (bounds: 13.8 to 24)
      - 32,563 below; range 10 to 13
  Valid metrics after bounds checking: 384,803 pm1, 396,252 pm2

Calculating heating replacement costs (REMDB v4)
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 303,516 homes (mean: $3,616.93)

### Air Conditioning - ONLY CALCULATE REPLACEMENT COSTS
### (Create new column and add to heating replacement cost)

UPDATE: 
- Updated to handle different enduses based on EQUIPMENT_SPECS.
- Rest of codebase updated so only initial columns created for cooling and replacement cost calculations performed
- This allows for a scenario where only heating is replaced AND one where heating and cooling systems are both replace with HP
- Resolves the excessive data columns and double counting with $8000 rebate. No longer need CDD projections.

In [20]:
# Cooling replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='cooling',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs,
    out_of_bound_method='keep_as_is',
    bounds_verbose=True,
    max_groups_to_print=25
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='cooling',
    percentile=percentile
)

Preparing cooling REPLACEMENT metrics (REMDB v4)
  Warning: 62,104 homes with unknown row_id
  Filled 62,104 missing euss_cooling_replacement_pm1 from REMDB bounds
  Filled 119,562 missing euss_cooling_replacement_pm2 from REMDB bounds

  WARNING: 134,509 homes have out-of-bounds capacity (method=keep_as_is)
    • air_conditioner_centrally_ducted (bounds: 1.5 to 5)
      - 31,734 below; range 0.270833 to 1.49917
      - 32,074 above; range 5.00083 to 64.0775
    • air_conditioner_room_ac_window_or_through_wall (bounds: 0.416667 to 2.33333)
      - 10 below; range 0.3375 to 0.4125
      - 59,290 above; range 2.33333 to 253.559
    • air_source_heat_pump_centrally_ducted (bounds: 1.5 to 5)
      - 4,521 below; range 0 to 1.49917
      - 6,880 above; range 5.00083 to 44.1058

  WARNING: 47,783 homes have out-of-bounds efficiency (method=keep_as_is)
    • air_conditioner_centrally_ducted (bounds: 13 to 24)
      - 47,783 below; range 8 to 10
  Valid metrics after bounds checking: 334,148 pm1, 396,252 pm2

Calculating cooling replacement costs (REMDB v4)
  Created temporary include_cooling flag for metadata calculation
Measure package calculation for cooling:
  - 334148 homes have valid data
  - 396252 homes will receive retrofits
  - 334148 homes have both valid data AND will receive retrofits
  - 62104 homes excluded (values will be NaN)
  Initialized all_columns_to_mask['cooling'] for metadata tracking

Verifying masking for all calculated columns:
Masking 1 columns for category 'cooling'
  Removed temporary include_cooling flag
  Calculated costs for 334,148 homes (mean: $5,481.26)

In [21]:
# Combined cost (in notebook)
heating_replacement_col = f'mp{menu_mp}_heating_replacement_installed_cost_{percentile}'
cooling_replacement_col = f'mp{menu_mp}_cooling_replacement_installed_cost_{percentile}'
combined_col = f'mp{menu_mp}_heating_and_cooling_replacement_installed_cost_{percentile}'

df_euss_am_mp3_home[combined_col] = (
    df_euss_am_mp3_home[heating_replacement_col] + 
    df_euss_am_mp3_home[cooling_replacement_col]
)

df_detailed_mp3_installed_costs[combined_col] = (
    df_detailed_mp3_installed_costs[heating_replacement_col] + 
    df_detailed_mp3_installed_costs[cooling_replacement_col]
)

In [22]:
df_detailed_mp3_installed_costs

,row_id_heating_upgrade,heating_upgrade_pm1_metric,heating_upgrade_pm1_unit,heating_upgrade_pm1_lower_bound,heating_upgrade_pm1_upper_bound,euss_heating_upgrade_pm1,heating_upgrade_pm1_coef_mid,heating_upgrade_pm2_metric,heating_upgrade_pm2_unit,heating_upgrade_pm2_lower_bound,heating_upgrade_pm2_upper_bound,euss_heating_upgrade_pm2,heating_upgrade_pm2_coef_mid,heating_upgrade_intercept_mid,heating_upgrade_multiplier_retrofit,heating_upgrade_adder_retrofit,mp3_heating_upgrade_installed_cost_mid,row_id_heating_replacement,heating_replacement_pm1_metric,heating_replacement_pm1_unit,heating_replacement_pm1_lower_bound,heating_replacement_pm1_upper_bound,euss_heating_replacement_pm1,heating_replacement_pm1_coef_mid,heating_replacement_pm2_metric,heating_replacement_pm2_unit,heating_replacement_pm2_lower_bound,heating_replacement_pm2_upper_bound,euss_heating_replacement_pm2,heating_replacement_pm2_coef_mid,heating_replacement_intercept_mid,heating_replacement_multiplier_retrofit,heating_replacement_adder_retrofit,mp3_heating_replacement_installed_cost_mid,row_id_cooling_replacement,cooling_replacement_pm1_metric,cooling_replacement_pm1_unit,cooling_replacement_pm1_lower_bound,cooling_replacement_pm1_upper_bound,euss_cooling_replacement_pm1,cooling_replacement_pm1_coef_mid,cooling_replacement_pm2_metric,cooling_replacement_pm2_unit,cooling_replacement_pm2_lower_bound,cooling_replacement_pm2_upper_bound,euss_cooling_replacement_pm2,cooling_replacement_pm2_coef_mid,cooling_replacement_intercept_mid,cooling_replacement_multiplier_retrofit,cooling_replacement_adder_retrofit,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
bldg_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,4.383333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,15565.37,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,52600.0,0.00645,AFUE,Unitless,0.8,0.97,0.76,4325.000025,-2780.000019,1.0,2217.753,3064.02,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,4.383333,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6706.67,9770.69
2,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.848333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13112.56,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,34180.0,0.00645,AFUE,Unitless,0.8,0.97,0.80,4325.000025,-2780.000019,1.0,2217.753,3118.21,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.296667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13828.96,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,39560.0,0.05676,NaN,NaN,0.0,0.00,0.00,0.000000,0.000000,1.5,0.000,3368.16,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.296667,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,4387.35,7755.51
6,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,2.190000,3130.08,SEER1,Unitless,16.0,23.0,15.0,160.413333,-1343.333333,1.5,0.0,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.483333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,14127.24,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,41800.0,0.00645,AFUE,Unitless,0.8,0.97,0.76,4325.000025,-2780.000019,1.0,2217.753,2994.36,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.483333,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,4479.27,7473.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549995,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.115000,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,11940.75,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,25380.0,0.05676,NaN,NaN,0.0,0.00,0.00,0.000000,0.000000,1.5,0.000,2160.86,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.115000,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,3805.48,5966.34
549996,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,3.015833,3130.08,SEER1,Unitless,16.0,23.0,15.0,160.413333,-1343.333333,1.5,0.0,NaN,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,36190.0,0.05676,NaN,NaN,0.0,0.00,0.00,0.000000,0.000000,1.5,0.000,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
549997,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,1.946667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,11671.77,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,23360.0,0.00645,AFUE,Unitless,0.8,0.97,0.80,4325.000025,-2780.000019,1.0,2217.753,3048.43,air_conditioner_room_ac_window_or_through_wall,Capacity,Tons,0.416667,2.333333,1.946667,364.332000,CEER,Unitless,9.4,15.0,12.2,6.069364,13.277460,1.0,352.607677,1149.16,4197.59
549998,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.976667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13317.63,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,35720.0,0.05676,NaN,NaN,0.0,0.00,0.00,0.000000,0.000000,1.5,0.000,3041.22,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.976667,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6014.00,9055.22
549999,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.281667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13804.99,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,39380.0,0.00645,AFUE,Unitless,0.8,0.97,0.76,4325.000025,-2780.000019,1.0,2217.753,2978.75,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.281667,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6164.19,9142.94

In [23]:
installed_cost_cols = [col for col in df_detailed_mp3_installed_costs.columns if 'installed_cost' in col]
print(installed_cost_cols)

['mp3_heating_upgrade_installed_cost_mid', 'mp3_heating_replacement_installed_cost_mid', 'mp3_cooling_replacement_installed_cost_mid', 'mp3_heating_and_cooling_replacement_installed_cost_mid']

In [24]:
df_installed_cost_only = df_detailed_mp3_installed_costs[installed_cost_cols]
df_installed_cost_only.describe()

,mp3_heating_upgrade_installed_cost_mid,mp3_heating_replacement_installed_cost_mid,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
count,3.035160e+05,303516.000000,334148.000000,256016.000000
mean,1.708714e+04,3616.929741,5481.256099,7411.555527
std,1.632207e+04,2498.016757,5103.079631,3474.777074
min,2.791560e+03,260.530000,0.000000,444.430000
25%,1.163981e+04,3017.720000,2271.560000,5323.065000
50%,1.330697e+04,3182.130000,4106.270000,7138.360000
75%,1.616325e+04,3644.000000,5860.940000,8719.590000
max,1.533628e+06,333379.310000,92819.650000,312443.970000

## OLDER METHODS USING MASKING (Before Dec 16 Code)

In [25]:
# Added the load_remdb_v4_data function for data validation, error handling, DRY, reusability and maintainability
from cmu_tare_model.utils.remdb_v4_installed_cost_utils_16Dec2025 import load_remdb_v4_data, add_remdb_upgrade_metrics, add_remdb_replacement_metrics
from cmu_tare_model.private_impact.calculations.calculate_equipment_installation_costs import (
    calculate_upgrade_installed_cost
    )
from cmu_tare_model.private_impact.calculations.calculate_equipment_replacement_costs import (
    calculate_replacement_installed_cost
)

### Space Heating and No Enclosure Upgrade

#### Space Heating Capital Costs

In [26]:
# Configuration
# menu_mp = 3
percentile = 'mid'

# Initialize detailed DataFrame as None (created on first call)
df_detailed_mp3_installed_costs = None

# Heating upgrade
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_upgrade_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_upgrade_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

# Heating replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='heating',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='heating',
    percentile=percentile
)

Preparing heating UPGRADE metrics (REMDB v4)
  Filled 130 missing euss_heating_upgrade_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 140,726 homes → masked to NaN
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 48,721 below bound
      - 43,547 above bound
      - Problematic range: 0.27 to 64.08
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 1.50 to 5.00)
      - 4,086 below bound
      - 44,372 above bound
      - Problematic range: 0.26 to 326.30

  WARNING: Out-of-bounds efficiency: 80,094 homes → masked to NaN
    • air_source_heat_pump_non_ducted_multi_zone (bounds: 16.00 to 23.00)
      - 80,094 below bound
      - Problematic range: 15.00 to 15.00
  Valid metrics after bounds checking: 255,526 pm1, 316,158 pm2

Calculating heating upgrade costs (REMDB v4)
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 181,168 homes (mean: $13,187.20)


Preparing heating REPLACEMENT metrics (REMDB v4)
  Warning: 11,449 homes with unknown row_id
  Filled 11,449 missing euss_heating_replacement_pm1 from REMDB bounds
  Filled 6,144 missing euss_heating_replacement_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 121,357 homes → masked to NaN
    • furnaces_gas_furnace (bounds: 30000.00 to 156250.00)
      - 101,588 below bound
      - 8,362 above bound
      - Problematic range: 3250.00 to 3888040.00
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 4,310 below bound
      - 6,874 above bound
      - Problematic range: 0.32 to 44.11
    • electric_baseboard_default (bounds: 1194.20 to 416000.00)
      - 223 above bound
      - Problematic range: 417070.00 to 3915640.00

  WARNING: Out-of-bounds efficiency: 84,264 homes → masked to NaN
    • furnaces_gas_furnace (bounds: 0.80 to 0.97)
      - 51,701 below bound
      - Problematic range: 0.60 to 0.76
    • air_source_heat_pump_centrally_ducted (bounds: 13.80 to 24.00)
      - 32,563 below bound
      - Problematic range: 10.00 to 13.00
  Valid metrics after bounds checking: 263,446 pm1, 311,988 pm2

Calculating heating replacement costs (REMDB v4)
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated costs for 195,817 homes (mean: $3,793.86)

### Air Conditioning - ONLY CALCULATE REPLACEMENT COSTS
### (Create new column and add to heating replacement cost)

UPDATE: 
- Updated to handle different enduses based on EQUIPMENT_SPECS.
- Rest of codebase updated so only initial columns created for cooling and replacement cost calculations performed
- This allows for a scenario where only heating is replaced AND one where heating and cooling systems are both replace with HP
- Resolves the excessive data columns and double counting with $8000 rebate. No longer need CDD projections.

In [27]:
# Cooling replacement
# Step 1: Extract upgrade metrics FIRST
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = add_remdb_replacement_metrics(
    df=df_euss_am_mp3_home,
    remdb_v4_costs=df_tare_remdb_v4_costs,
    end_use='cooling',
    percentile=percentile,
    df_detailed=df_detailed_mp3_installed_costs
)

# Step 2: Then calculate costs
df_euss_am_mp3_home, df_detailed_mp3_installed_costs = calculate_replacement_installed_cost(
    df=df_euss_am_mp3_home,
    df_detailed=df_detailed_mp3_installed_costs,
    menu_mp=menu_mp,
    end_use='cooling',
    percentile=percentile
)

Preparing cooling REPLACEMENT metrics (REMDB v4)
  Warning: 62,104 homes with unknown row_id
  Filled 62,104 missing euss_cooling_replacement_pm1 from REMDB bounds
  Filled 119,562 missing euss_cooling_replacement_pm2 from REMDB bounds

  WARNING: Out-of-bounds capacity: 134,509 homes → masked to NaN
    • air_conditioner_centrally_ducted (bounds: 1.50 to 5.00)
      - 31,734 below bound
      - 32,074 above bound
      - Problematic range: 0.27 to 64.08
    • air_conditioner_room_ac_window_or_through_wall (bounds: 0.42 to 2.33)
      - 10 below bound
      - 59,290 above bound
      - Problematic range: 0.34 to 253.56
    • air_source_heat_pump_centrally_ducted (bounds: 1.50 to 5.00)
      - 4,521 below bound
      - 6,880 above bound
      - Problematic range: 0.00 to 44.11

  WARNING: Out-of-bounds efficiency: 47,783 homes → masked to NaN
    • air_conditioner_centrally_ducted (bounds: 13.00 to 24.00)
      - 47,783 below bound
      - Problematic range: 8.00 to 10.00
  Valid metrics after bounds checking: 199,639 pm1, 348,469 pm2

Calculating cooling replacement costs (REMDB v4)
  Created temporary include_cooling flag for metadata calculation
Measure package calculation for cooling:
  - 334148 homes have valid data
  - 396252 homes will receive retrofits
  - 334148 homes have both valid data AND will receive retrofits
  - 62104 homes excluded (values will be NaN)
  Initialized all_columns_to_mask['cooling'] for metadata tracking

Verifying masking for all calculated columns:
Masking 1 columns for category 'cooling'
  Removed temporary include_cooling flag
  Calculated costs for 166,103 homes (mean: $6,515.14)

In [28]:
# Combined cost (in notebook)
heating_replacement_col = f'mp{menu_mp}_heating_replacement_installed_cost_{percentile}'
cooling_replacement_col = f'mp{menu_mp}_cooling_replacement_installed_cost_{percentile}'
combined_col = f'mp{menu_mp}_heating_and_cooling_replacement_installed_cost_{percentile}'

df_euss_am_mp3_home[combined_col] = (
    df_euss_am_mp3_home[heating_replacement_col] + 
    df_euss_am_mp3_home[cooling_replacement_col]
)

df_detailed_mp3_installed_costs[combined_col] = (
    df_detailed_mp3_installed_costs[heating_replacement_col] + 
    df_detailed_mp3_installed_costs[cooling_replacement_col]
)

In [29]:
df_detailed_mp3_installed_costs

,row_id_heating_upgrade,heating_upgrade_pm1_metric,heating_upgrade_pm1_unit,heating_upgrade_pm1_lower_bound,heating_upgrade_pm1_upper_bound,euss_heating_upgrade_pm1,heating_upgrade_pm1_coef_mid,heating_upgrade_pm2_metric,heating_upgrade_pm2_unit,heating_upgrade_pm2_lower_bound,heating_upgrade_pm2_upper_bound,euss_heating_upgrade_pm2,heating_upgrade_pm2_coef_mid,heating_upgrade_intercept_mid,heating_upgrade_multiplier_retrofit,heating_upgrade_adder_retrofit,mp3_heating_upgrade_installed_cost_mid,row_id_heating_replacement,heating_replacement_pm1_metric,heating_replacement_pm1_unit,heating_replacement_pm1_lower_bound,heating_replacement_pm1_upper_bound,euss_heating_replacement_pm1,heating_replacement_pm1_coef_mid,heating_replacement_pm2_metric,heating_replacement_pm2_unit,heating_replacement_pm2_lower_bound,heating_replacement_pm2_upper_bound,euss_heating_replacement_pm2,heating_replacement_pm2_coef_mid,heating_replacement_intercept_mid,heating_replacement_multiplier_retrofit,heating_replacement_adder_retrofit,mp3_heating_replacement_installed_cost_mid,row_id_cooling_replacement,cooling_replacement_pm1_metric,cooling_replacement_pm1_unit,cooling_replacement_pm1_lower_bound,cooling_replacement_pm1_upper_bound,euss_cooling_replacement_pm1,cooling_replacement_pm1_coef_mid,cooling_replacement_pm2_metric,cooling_replacement_pm2_unit,cooling_replacement_pm2_lower_bound,cooling_replacement_pm2_upper_bound,euss_cooling_replacement_pm2,cooling_replacement_pm2_coef_mid,cooling_replacement_intercept_mid,cooling_replacement_multiplier_retrofit,cooling_replacement_adder_retrofit,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
bldg_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,4.383333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,15565.37,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,52600.0,0.00645,AFUE,Unitless,0.8,0.97,NaN,4325.000025,-2780.000019,1.0,2217.753,NaN,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,4.383333,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6706.67,NaN
2,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.848333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13112.56,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,34180.0,0.00645,AFUE,Unitless,0.8,0.97,0.8,4325.000025,-2780.000019,1.0,2217.753,3118.21,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.296667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13828.96,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,39560.0,0.05676,NaN,NaN,0.0,0.00,0.0,0.000000,0.000000,1.5,0.000,3368.16,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.296667,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,4387.35,7755.51
6,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,2.190000,3130.08,SEER1,Unitless,16.0,23.0,NaN,160.413333,-1343.333333,1.5,0.0,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.483333,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,14127.24,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,41800.0,0.00645,AFUE,Unitless,0.8,0.97,NaN,4325.000025,-2780.000019,1.0,2217.753,NaN,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.483333,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,4479.27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549995,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.115000,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,11940.75,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,25380.0,0.05676,NaN,NaN,0.0,0.00,0.0,0.000000,0.000000,1.5,0.000,2160.86,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.115000,328.276825,SEER1,Unitless,13.0,24.0,13.0,594.740000,-5888.936117,1.5,0.000000,3805.48,5966.34
549996,air_source_heat_pump_non_ducted_multi_zone,Cooling Capacity,Tons,1.5,5.0,3.015833,3130.08,SEER1,Unitless,16.0,23.0,NaN,160.413333,-1343.333333,1.5,0.0,NaN,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,36190.0,0.05676,NaN,NaN,0.0,0.00,0.0,0.000000,0.000000,1.5,0.000,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
549997,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,1.946667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,11671.77,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,NaN,0.00645,AFUE,Unitless,0.8,0.97,0.8,4325.000025,-2780.000019,1.0,2217.753,NaN,air_conditioner_room_ac_window_or_through_wall,Capacity,Tons,0.416667,2.333333,1.946667,364.332000,CEER,Unitless,9.4,15.0,12.2,6.069364,13.277460,1.0,352.607677,1149.16,NaN
549998,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,2.976667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13317.63,electric_baseboard_default,Capacity,BTU/Hr,1194.2,416000.0,35720.0,0.05676,NaN,NaN,0.0,0.00,0.0,0.000000,0.000000,1.5,0.000,3041.22,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,2.976667,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6014.00,9055.22
549999,air_source_heat_pump_centrally_ducted,Cooling Capacity,Tons,1.5,5.0,3.281667,1065.28,SEER1,Unitless,13.8,24.0,15.0,594.740000,-2291.000000,1.5,-1384.0,13804.99,furnaces_gas_furnace,Heating Capacity,BTU/Hr,30000.0,156250.0,39380.0,0.00645,AFUE,Unitless,0.8,0.97,NaN,4325.000025,-2780.000019,1.0,2217.753,NaN,air_conditioner_centrally_ducted,Cooling Capacity,Tons,1.500000,5.000000,3.281667,328.276825,SEER1,Unitless,13.0,24.0,15.0,594.740000,-5888.936117,1.5,0.000000,6164.19,NaN

In [30]:
installed_cost_cols = [col for col in df_detailed_mp3_installed_costs.columns if 'installed_cost' in col]
print(installed_cost_cols)

['mp3_heating_upgrade_installed_cost_mid', 'mp3_heating_replacement_installed_cost_mid', 'mp3_cooling_replacement_installed_cost_mid', 'mp3_heating_and_cooling_replacement_installed_cost_mid']

In [31]:
df_installed_cost_only = df_detailed_mp3_installed_costs[installed_cost_cols]
df_installed_cost_only.describe()

,mp3_heating_upgrade_installed_cost_mid,mp3_heating_replacement_installed_cost_mid,mp3_cooling_replacement_installed_cost_mid,mp3_heating_and_cooling_replacement_installed_cost_mid
count,181168.000000,195817.000000,166103.000000,78854.000000
mean,13187.199527,3793.862115,6515.138886,7968.317934
std,1465.744503,2256.520652,5031.242536,1701.480483
min,10958.030000,260.530000,592.950000,1038.230000
25%,11962.060000,3111.250000,3881.400000,7259.640000
50%,12972.740000,3301.390000,4654.080000,7971.400000
75%,14257.730000,3799.140000,6223.280000,9096.570000
max,16550.750000,35416.720000,20029.980000,14944.630000

 ## Calculate Rebate Amounts (Applicable to IRA-Reference)
 ## SIMPLIFY THIS TO USE THE INCOME COLUMN DIRECTLY - NO NEED TO SAMPLE FROM DISTRIBUTION
 ## UPDATE TERMINOLOGY TO SPECIFY ASHP NOT SPACE HEATING BECAUSE WE NOW INCLUDE AC

In [32]:
from cmu_tare_model.private_impact.data_processing.determine_rebate_eligibility_and_amount import calculate_percent_AMI, calculate_rebateIRA

print(f"""
====================================================================================================================================================================
CALCULATE HOUSEHOLD PERCENT AREA MEDIAN INCOME (%AMI) AND REBATE ELIGIBILITY/AMOUNTS
====================================================================================================================================================================
determine_rebate_eligibility_and_amount.py file contains the function definitions for calculating rebate amounts and determining household %AMI.
process_income_data_for_rebates.py file contains additional information on data sources and procedures used to process data for determine_rebate_eligibility_and_amount.py file.

Documentation for calculate_percent_AMI function:
{calculate_percent_AMI.__doc__}

Documentation for calculate_rebateIRA function:
{calculate_rebateIRA.__doc__}
-------------------------------------------------------

""")

# Determine Percent AMI and Rebate Amounts
# This needs to be done before running the calculate_percent_AMI function
df_euss_am_mp3_home = df_euss_am_mp3_home.copy()

# calculate_percent_AMI(df_results_IRA, df_county_medianIncome):
df_euss_am_mp3_home = calculate_percent_AMI(df_results_IRA=df_euss_am_mp3_home)

print("Calculating rebate amounts for Heating ...")
df_euss_am_mp3_home = calculate_rebateIRA(df=df_euss_am_mp3_home,
                                          category="heating",
                                          menu_mp=menu_mp,
                                          percentile='mid')

# print("Calculating rebate amounts for Cooling ...")
# df_euss_am_mp3_home = calculate_rebateIRA(df=df_euss_am_mp3_home,
#                                           category="cooling",
#                                           menu_mp=menu_mp,
#                                           percentile='mid')


print(f"""
====================================================================================================================================================================
DATAFRAME: df_euss_am_mp3_home AFTER CALCULATING REBATE AMOUNTS
{df_euss_am_mp3_home}

====================================================================================================================================================================
""")

====================================================================================================================================================================
CALCULATE HOUSEHOLD PERCENT AREA MEDIAN INCOME (%AMI) AND REBATE ELIGIBILITY/AMOUNTS
====================================================================================================================================================================
determine_rebate_eligibility_and_amount.py file contains the function definitions for calculating rebate amounts and determining household %AMI.
process_income_data_for_rebates.py file contains additional information on data sources and procedures used to process data for determine_rebate_eligibility_and_amount.py file.

Documentation for calculate_percent_AMI function:

    Calculates the percentage of Area Median Income (AMI) and assigns income level designations.

    This function processes household income data, calculates the percentage relative to
    Area Median Income, and creates two categorical classifications:
    1. Detailed income level categories (Low, Moderate, Middle-to-Upper Income)
    2. Binary Low-to-Moderate Income (LMI) or Middle-to-Upper Income (MUI) classification for policy analysis

    Args:
        df_results_IRA: Input DataFrame containing income information with columns:
                       - 'income': Income data (ranges or values)
                       - Other demographic/geographic columns for median income lookup

    Returns:
        DataFrame: Modified DataFrame with additional columns:
                  - 'household_income': Calculated household income (float)
                  - 'census_area_medianIncome': Area median income (float)
                  - 'percent_AMI': Percentage of AMI (float)
                  - 'income_level': Detailed income category (str)
                  - 'lmi_or_mui': Binary Low-to-Moderate Income (LMI) or Middle-to-Upper Income (MUI) (str)

    Raises:
        ValueError: If an unexpected income format is encountered during processing


Documentation for calculate_rebateIRA function:

    Calculate IRA rebate amounts based on income level and equipment costs.

    PREREQUISITE: Call calculate_upgrade_installed_cost() first to create the required
    mp{menu_mp}_{category}_upgrade_installed_cost_{percentile} columns.

    Applies income-based rebate rates:
    - Low-Income (≤80% AMI): 100% of cost up to max rebate
    - Moderate-Income (>80-150% AMI): 50% of cost up to max rebate
    - Middle-to-Upper Income (>150% AMI): $0 rebate

    Uses the 5-step validation framework to ensure only valid homes receive rebates.

    Args:
        df: DataFrame with income data and upgrade costs.
        category: Equipment category (e.g., 'heating', 'cooling', 'waterHeating').
        menu_mp: Measure package number.
        percentile: Cost percentile ('low', 'mid', 'high').

    Returns:
        DataFrame with mp{menu_mp}_{category}_rebate_amount_{percentile} column.

    Raises:
        ValueError: If invalid menu_mp, category, or percentile provided.
        KeyError: If required columns are missing.

-------------------------------------------------------


Calculating rebate amounts for Heating ...

Calculating heating rebates (Menu MP3, mid percentile)
Measure package calculation for heating:
  - 303516 homes have valid data
  - 396122 homes will receive retrofits
  - 303516 homes have both valid data AND will receive retrofits
  - 92736 homes excluded (values will be NaN)

Verifying masking for all calculated columns:
Masking 1 columns for category 'heating'
  Calculated rebates for 212,161 homes
  Mean rebate: $4,669.49
  Total rebates: $990,684,249.21


====================================================================================================================================================================
DATAFRAME: df_euss_am_mp3_home AFTER CALCULATING REBATE AMOUNTS
         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True
...                               ...          ...                 ...
549995                         462.76         True                True
549996                            NaN        False                True
549997                       18788.20         True                True
549998                            NaN         True                True
549999                        2593.97         True                True

         valid_tech_heating  include_heating  \
bldg_id
1                      True             True
2                      True             True
5                      True             True
6                     False            False
8                      True             True
...                     ...              ...
549995                 True             True
549996                False            False
549997                 True             True
549998                 True             True
549999                 True             True

         baseline_heating_lifetime_mt_co2e_lrmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                          88.60
6                                            NaN
8                                          87.75
...                                          ...
549995                                      2.19
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_lrmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                  6463.66
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              158.40
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_lrmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 23022.55
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                              565.04
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_lrmer_upper  \
bldg_id
1                                                 25057.25
2                                                 63173.17
5                                                 36607.44
6                                                      NaN
8                                                 36557.99
...                                                    ...
549995                                              899.25
549996                                                 NaN
549997                                            24244.24
549998                                                0.00
549999                                             3964.24

         baseline_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                         205.82
6                                            NaN
8                                          87.75
...                                          ...
549995                                      4.72
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_srmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                 15187.73
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              347.64
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_srmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 53946.81
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                             1235.09
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84


# SCENARIO ANALYSIS: 
## "No Inflation Reduction Act" and "AEO2023 Reference Case"
## Public Impact, Private Impact and Adoption Potential (Degree of Adoption Feasibility)

In [33]:
from cmu_tare_model.private_impact.calculate_lifetime_private_impact import calculate_private_npv
from cmu_tare_model.public_impact.calculate_lifetime_public_impact_sensitivity import calculate_public_npv
from cmu_tare_model.adoption_potential.determine_adoption_potential_sensitivity import *

print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS: OVERVIEW
====================================================================================================================================================================

-------------------------------------------------------
PUBLIC IMPACTS: CLIMATE AND HEALTH
-------------------------------------------------------
calculate_lifetime_public_impact.py file contains the definition for the calculate_public_npv function.
Additional information on emissions/damage factor lookups as well as marginal damages calculation methods can be found in the public_impact folder. 
      
Documentation for the calculate_public_NPV function:
{calculate_public_npv.__doc__} 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
PRIVATE IMPACTS: LIFETIME CAPITAL COSTS AND SAVINGS
--------------------------------------------------------
calculate_lifetime_private_impact.py file contains the definition for the calculate_private_npv function.
Additional information on fuel price lookups as well as capital costs calculation methods can be found in the private_impact folder.

Documentation for the calculate_private_npv function:
{calculate_private_npv.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
ADOPTION POTENTIAL
--------------------------------------------------------
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
Documentation for the adoption_decision function:
{adoption_decision.__doc__}

Documentation for the calculate_climate_only_adoption_robust function:
{calculate_climate_only_adoption_robust.__doc__}

Documentation for the calculate_health_only_adoption_robust function:
{calculate_health_only_adoption_robust.__doc__}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

""")

====================================================================================================================================================================
SCENARIO ANALYSIS: OVERVIEW
====================================================================================================================================================================

-------------------------------------------------------
PUBLIC IMPACTS: CLIMATE AND HEALTH
-------------------------------------------------------
calculate_lifetime_public_impact.py file contains the definition for the calculate_public_npv function.
Additional information on emissions/damage factor lookups as well as marginal damages calculation methods can be found in the public_impact folder.

Documentation for the calculate_public_NPV function:

    Calculate the public Net Present Value (NPV) for specific categories of damages,
    considering different policy scenarios related to grid decarbonization.

    The function compares baseline damages with post-measure package (mp) damages
    to determine the avoided damages (benefits) from implementing retrofits.

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    The list-based collection approach stores yearly values in lists and sums them using pandas
    vectorized operations after all years have been processed. This approach prevents accumulation
    errors that can occur with incremental updates.

    Args:
        df (pd.DataFrame): Input DataFrame containing base data for calculations.
        df_baseline_climate (pd.DataFrame): DataFrame containing baseline climate damage projections.
        df_baseline_health (pd.DataFrame): DataFrame containing baseline health damage projections.
        df_mp_climate (pd.DataFrame): DataFrame containing post-retrofit climate damage projections.
        df_mp_health (pd.DataFrame): DataFrame containing post-retrofit health damage projections.
        menu_mp (int): Menu identifier used to construct column names for the measure package.
        policy_scenario (str): Policy scenario that determines electricity grid projections.
            Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        rcm_model (str): The Reduced Complexity Model used for health impact calculations.
        base_year (int, optional): The base year for discounting calculations. Default is 2024.
        discounting_method (str, optional): The method used for discounting. Default is 'public'.
        verbose (bool, optional): Whether to print detailed progress messages. Defaults to False.

    Returns:
        pd.DataFrame: DataFrame with additional columns containing the calculated public NPVs for each
        equipment category, damage type, and sensitivity analysis combination.

    Raises:
        ValueError: If input parameters are invalid or if required data columns are missing.
        RuntimeError: If processing fails at the category or combination level.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
PRIVATE IMPACTS: LIFETIME CAPITAL COSTS AND SAVINGS
--------------------------------------------------------
calculate_lifetime_private_impact.py file contains the definition for the calculate_private_npv function.
Additional information on fuel price lookups as well as capital costs calculation methods can be found in the private_impact folder.

Documentation for the calculate_private_npv function:

    Calculate the private net present value (NPV) for various equipment categories,
    considering different cost assumptions and potential IRA rebates.
    The function adjusts equipment costs for inflation and calculates NPV based on
    cost savings between baseline and retrofit scenarios.

    This function follows the five-step validation framework:
    1. Mask Initialization: Identifies valid homes using inclusion flags and retrofit status
    2. Series Initialization: Creates result series with zeros for valid homes, NaN for others
    3. Valid-Only Calculation: Performs calculations only for valid homes
    4. Valid-Only Updates: Uses list-based collection of yearly values instead of incremental updates
    5. Final Masking: Applies consistent masking to all result columns

    Args:
        df (DataFrame): Input DataFrame with installation costs, fuel savings, and potential rebates.
        df_fuel_costs (DataFrame): DataFrame containing measure package fuel costs.
        df_baseline_costs (DataFrame): DataFrame containing baseline fuel costs.
        input_mp (str): Input policy_scenario for calculating costs.
        menu_mp (int): Measure package identifier.
        policy_scenario (str): Policy scenario that determines electricity grid projections.
                               Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        discounting_method (str): The method used for discounting. Default is 'private_fixed'.
        base_year (int): The base year for discounting calculations. Default is 2024.
        verbose (bool): Whether to print detailed processing information. Default is True.
        percentile (str): The percentile to use for cost calculations. Default is 'mid'.

    Returns:
        DataFrame: The input DataFrame updated with calculated private NPV and adjusted equipment costs.

    Raises:
        ValueError: If an invalid policy_scenario or menu_mp is provided.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
ADOPTION POTENTIAL
--------------------------------------------------------
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

Documentation for the adoption_decision function:

    Updates DataFrame with adoption decisions and public impacts based on NPV analysis.

    Simplified output for nation-level analysis while maintaining full functionality.

    Args:
        df: DataFrame containing home equipment data.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario for electricity grid projections.
            Accepted values: 'No Inflation Reduction Act', 'AEO2023 Reference Case'.
        rcm_model: RCM model for health impact analysis ('ap2', 'easiur', 'inmap').
        cr_function: Concentration response function ('acs', 'h6c').
        verbose: Enable detailed output for debugging (default: False).
        percentile: Percentile to use for cost calculations (default is 'mid').

    Returns:
        DataFrame with adoption tier and public impact classifications.

    Raises:
        ValueError: If input parameters are invalid.
        KeyError: If required columns are missing.
        TypeError: If data type conversion fails.


Documentation for the calculate_climate_only_adoption_robust function:

    Climate-only adoption analysis with simplified output.

    Args:
        df: Input DataFrame.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario name.
        scc_assumptions: List of SCC assumptions to process.
        verbose: Enable detailed output.
        percentile: Percentile to use for cost calculations (default is 'mid').

    Returns:
        DataFrame with climate-only adoption analysis columns.


Documentation for the calculate_health_only_adoption_robust function:

    Health-only adoption analysis with simplified output.

    Args:
        df: Input DataFrame.
        menu_mp: Measure package identifier.
        policy_scenario: Policy scenario name.
        rcm_model: RCM model name.
        cr_function: Concentration response function.
        verbose: Enable detailed output.
        percentile: Percentile to use for cost calculations (default is 'mid').

    Returns:
        DataFrame with health-only adoption analysis columns.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

## BASIC MEASURE PACKAGE (mp3): NO INFLATION REDUCTION ACT
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 3
- AEO2023 No Inflation Reduction Act:  HDD and Fuel Price Projections
- Cambium 2021 MidCase Scenario

In [34]:
# Measure Package 3
scenario_name = 'No Inflation Reduction Act'
cost_scenario = 'Fuel Costs: AEO2023 No Inflation Reduction Act'
grid_scenario = 'Electricity Grid: Cambium 2021 MidCase Scenario'

print(f"""
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

====================================================================================================================================================================
Scenario No Inflation Reduction Act:
Basic Retrofit: Measure Package 3
Fuel Costs: AEO2023 No Inflation Reduction Act
Electricity Grid: Cambium 2021 MidCase Scenario
====================================================================================================================================================================

In [35]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PUBLIC IMPACT 
====================================================================================================================================================================
Completed Steps:
1. Calculate the baseline marginal damages for climate and health-related emissions
2. Calculate the post-retrofit marginal damages for climate and health-related emissions

---------------------------------------------------------------------------------------------
Step 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)
---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# Create copies to prevent overwriting the original dataframe and compare the differences
df_euss_am_mp3_home_ap2 = df_euss_am_mp3_home.copy()
df_euss_am_mp3_home_easiur = df_euss_am_mp3_home.copy()
df_euss_am_mp3_home_inmap = df_euss_am_mp3_home.copy()

# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp3_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_public_npv(
    df=df_euss_am_mp3_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_public_npv(
    df=df_euss_am_mp3_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_noIRA_damages_climate,
    df_mp_health=df_mp3_noIRA_damages_health,
    menu_mp="3",
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (NO IRA): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PUBLIC IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate the baseline marginal damages for climate and health-related emissions
2. Calculate the post-retrofit marginal damages for climate and health-related emissions

---------------------------------------------------------------------------------------------
Step 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)
---------------------------------------------------------------------------------------------

RESULTS OUTPUT:

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Verifying masking for all calculated columns:

====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (NO IRA): df_euss_am_mp3_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True
...                               ...          ...                 ...
549995                         462.76         True                True
549996                            NaN        False                True
549997                       18788.20         True                True
549998                            NaN         True                True
549999                        2593.97         True                True

         valid_tech_heating  include_heating  \
bldg_id
1                      True             True
2                      True             True
5                      True             True
6                     False            False
8                      True             True
...                     ...              ...
549995                 True             True
549996                False            False
549997                 True             True
549998                 True             True
549999                 True             True

         baseline_heating_lifetime_mt_co2e_lrmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                          88.60
6                                            NaN
8                                          87.75
...                                          ...
549995                                      2.19
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_lrmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                  6463.66
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              158.40
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_lrmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 23022.55
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                              565.04
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_lrmer_upper  \
bldg_id
1                                                 25057.25
2                                                 63173.17
5                                                 36607.44
6                                                      NaN
8                                                 36557.99
...                                                    ...
549995                                              899.25
549996                                                 NaN
549997                                            24244.24
549998                                                0.00
549999                                             3964.24

         baseline_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                         205.82
6                                            NaN
8                                          87.75
...                                          ...
549995                                      4.72
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52


In [36]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PRIVATE IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs
2. Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
3. Calculate replacement cost (replacing existing piece of eqipment with similar technology)

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")


# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp3_home_ap2,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_private_npv(
    df=df_euss_am_mp3_home_easiur,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_private_npv(
    df=df_euss_am_mp3_home_inmap,
    df_fuel_costs=df_mp3_noIRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='No Inflation Reduction Act',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )


print(f"""  
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): PRIVATE IMPACT
====================================================================================================================================================================
Completed Steps:
1. Calculate annual operating (fuel) costs
2. Calculate equipment capital costs (For space heating, include ductwork and weatherization (MP9 and MP10))
3. Calculate replacement cost (replacing existing piece of eqipment with similar technology)

----------------------------------------------------------------------------------------------------------------------
Step 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):

-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp3_


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp3_


Verifying masking for all calculated columns:
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: No Inflation Reduction Act
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: No Inflation Reduction Act --> scenario_prefix: preIRA_mp3_


Verifying masking for all calculated columns:

====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True
...                               ...          ...                 ...
549995                         462.76         True                True
549996                            NaN        False                True
549997                       18788.20         True                True
549998                            NaN         True                True
549999                        2593.97         True                True

         valid_tech_heating  include_heating  \
bldg_id
1                      True             True
2                      True             True
5                      True             True
6                     False            False
8                      True             True
...                     ...              ...
549995                 True             True
549996                False            False
549997                 True             True
549998                 True             True
549999                 True             True

         baseline_heating_lifetime_mt_co2e_lrmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                          88.60
6                                            NaN
8                                          87.75
...                                          ...
549995                                      2.19
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_lrmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                  6463.66
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              158.40
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_lrmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 23022.55
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                              565.04
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_lrmer_upper  \
bldg_id
1                                                 25057.25
2                                                 63173.17
5                                                 36607.44
6                                                      NaN
8                                                 36557.99
...                                                    ...
549995                                              899.25
549996                                                 NaN
549997                                            24244.24
549998                                                0.00
549999                                             3964.24

         baseline_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                         205.82
6                                            NaN
8                                          87.75
...                                          ...
549995                                      4.72
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_srmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                 15187.73
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              347.64
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_srmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 53946.81
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                             1235.09
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_srmer_upper   county_key  \
bldg_id
1                                                 25057.25      (51033, VA)
2                                                 63173.17      (56025, WY)
5                                                 85660.16      (29169, MO)
6                                                      NaN      (12099, FL)

In [37]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (NO INFLATION REDUCTION ACT):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    percentile='mid'
    )

df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='No Inflation Reduction Act',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2: 
-----------------------------------------------

{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (NO INFLATION REDUCTION ACT): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

RESULTS OUTPUT (NO INFLATION REDUCTION ACT):

Processing AP2 model...
Fixed 24 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | ap2-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | ap2-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | ap2-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | ap2-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added
Processing EASIUR model...
Fixed 24 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | easiur-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | easiur-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | easiur-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | easiur-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added
Processing InMAP model...
Fixed 24 duplicate columns
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | inmap-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Adoption Analysis: No Inflation Reduction Act | inmap-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Climate-only Analysis: No Inflation Reduction Act

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | inmap-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: No Inflation Reduction Act --
              scenario_prefix: f'preIRA_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_preIRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_preIRA'


Health-only Analysis: No Inflation Reduction Act | inmap-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added

====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (NO INFLATION REDUCTION ACT): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True

In [38]:
print(df_euss_am_mp3_home_easiur.columns.tolist())

['square_footage', 'census_region', 'census_division', 'census_division_recs', 'building_america_climate_zone', 'reeds_balancing_area', 'gea_region', 'state', 'city', 'urbanicity', 'county', 'county_fips', 'puma', 'county_and_puma', 'weather_file_city', 'Longitude', 'Latitude', 'building_type', 'income', 'federal_poverty_level', 'occupancy', 'tenure', 'vacancy_status', 'vintage', 'base_heating_fuel', 'heating_type', 'base_heating_efficiency', 'base_electricity_heating_consumption', 'base_fuelOil_heating_consumption', 'base_naturalGas_heating_consumption', 'base_propane_heating_consumption', 'base_cooling_fuel', 'cooling_type', 'base_cooling_efficiency', 'base_electricity_cooling_consumption', 'baseline_heating_consumption', 'include_all', 'valid_fuel_heating', 'valid_tech_heating', 'include_heating', 'baseline_heating_lifetime_mt_co2e_lrmer', 'baseline_heating_lifetime_damages_climate_lrmer_lower', 'baseline_heating_lifetime_damages_climate_lrmer_central', 'baseline_heating_lifetime_damages_climate_lrmer_upper', 'baseline_heating_lifetime_mt_co2e_srmer', 'baseline_heating_lifetime_damages_climate_srmer_lower', 'baseline_heating_lifetime_damages_climate_srmer_central', 'baseline_heating_lifetime_damages_climate_srmer_upper', 'county_key', 'baseline_heating_lifetime_damages_health_ap2_acs', 'baseline_heating_lifetime_damages_health_ap2_h6c', 'baseline_heating_lifetime_damages_health_easiur_acs', 'baseline_heating_lifetime_damages_health_easiur_h6c', 'baseline_heating_lifetime_damages_health_inmap_acs', 'baseline_heating_lifetime_damages_health_inmap_h6c', 'fuel_type_heating', 'hvac_has_ducts', 'hvac_heating_type_and_fuel', 'hvac_heating_efficiency', 'size_heating_system_primary_k_btu_h', 'upgrade_hvac_heating_efficiency', 'hvac_cooling_type', 'hvac_cooling_efficiency', 'size_cooling_system_primary_k_btu_h', 'upgrade_hvac_cooling_efficiency', 'mp3_heating_consumption', 'preIRA_mp3_heating_lifetime_mt_co2e_lrmer', 'preIRA_mp3_heating_lifetime_damages_climate_lrmer_lower', 'preIRA_mp3_heating_avoided_damages_climate_lrmer_lower', 'preIRA_mp3_heating_lifetime_damages_climate_lrmer_central', 'preIRA_mp3_heating_avoided_damages_climate_lrmer_central', 'preIRA_mp3_heating_lifetime_damages_climate_lrmer_upper', 'preIRA_mp3_heating_avoided_damages_climate_lrmer_upper', 'preIRA_mp3_heating_avoided_mt_co2e_lrmer', 'preIRA_mp3_heating_lifetime_mt_co2e_srmer', 'preIRA_mp3_heating_lifetime_damages_climate_srmer_lower', 'preIRA_mp3_heating_avoided_damages_climate_srmer_lower', 'preIRA_mp3_heating_lifetime_damages_climate_srmer_central', 'preIRA_mp3_heating_avoided_damages_climate_srmer_central', 'preIRA_mp3_heating_lifetime_damages_climate_srmer_upper', 'preIRA_mp3_heating_avoided_damages_climate_srmer_upper', 'preIRA_mp3_heating_avoided_mt_co2e_srmer', 'preIRA_mp3_heating_lifetime_damages_health_ap2_acs', 'preIRA_mp3_heating_avoided_damages_health_ap2_acs', 'preIRA_mp3_heating_lifetime_damages_health_ap2_h6c', 'preIRA_mp3_heating_avoided_damages_health_ap2_h6c', 'preIRA_mp3_heating_lifetime_damages_health_easiur_acs', 'preIRA_mp3_heating_avoided_damages_health_easiur_acs', 'preIRA_mp3_heating_lifetime_damages_health_easiur_h6c', 'preIRA_mp3_heating_avoided_damages_health_easiur_h6c', 'preIRA_mp3_heating_lifetime_damages_health_inmap_acs', 'preIRA_mp3_heating_avoided_damages_health_inmap_acs', 'preIRA_mp3_heating_lifetime_damages_health_inmap_h6c', 'preIRA_mp3_heating_avoided_damages_health_inmap_h6c', 'iraRef_mp3_heating_lifetime_mt_co2e_lrmer', 'iraRef_mp3_heating_lifetime_damages_climate_lrmer_lower', 'iraRef_mp3_heating_avoided_damages_climate_lrmer_lower', 'iraRef_mp3_heating_lifetime_damages_climate_lrmer_central', 'iraRef_mp3_heating_avoided_damages_climate_lrmer_central', 'iraRef_mp3_heating_lifetime_damages_climate_lrmer_upper', 'iraRef_mp3_heating_avoided_damages_climate_lrmer_upper', 'iraRef_mp3_heating_avoided_mt_co2e_lrmer', 'iraRef_mp3_heating_lifetime_mt_co2e_srmer', 'iraRef_mp3_heating_lifetime_damages_climate_srmer_lower', 'iraRef_mp3_heating_avoided_damages_climate_srmer_lower', 'iraRef_mp3_heating_lifetime_damages_climate_srmer_central', 'iraRef_mp3_heating_avoided_damages_climate_srmer_central', 'iraRef_mp3_heating_lifetime_damages_climate_srmer_upper', 'iraRef_mp3_heating_avoided_damages_climate_srmer_upper', 'iraRef_mp3_heating_avoided_mt_co2e_srmer', 'iraRef_mp3_heating_lifetime_damages_health_ap2_acs', 'iraRef_mp3_heating_avoided_damages_health_ap2_acs', 'iraRef_mp3_heating_lifetime_damages_health_ap2_h6c', 'iraRef_mp3_heating_avoided_damages_health_ap2_h6c', 'iraRef_mp3_heating_lifetime_damages_health_easiur_acs', 'iraRef_mp3_heating_avoided_damages_health_easiur_acs', 'iraRef_mp3_heating_lifetime_damages_health_easiur_h6c', 'iraRef_mp3_heating_avoided_damages_health_easiur_h6c', 'iraRef_mp3_heating_lifetime_damages_health_inmap_acs', 'iraRef_mp3_heating_avoided_damages_health_inmap_acs', 'iraRef_mp3_heating_lifetime_damages_health_inmap_h6c', 'iraRef_mp3_heating_avoided_damages_health_inmap_h6c', 'preIRA_mp3_heating_lifetime_fuel_cost', 'preIRA_mp3_heating_lifetime_savings_fuel_cost', 'iraRef_mp3_heating_lifetime_fuel_cost', 'iraRef_mp3_heating_lifetime_savings_fuel_cost', 'baseline_heating_lifetime_fuel_cost', 'row_id_heating_upgrade', 'heating_upgrade_pm1_lower_bound', 'heating_upgrade_pm1_upper_bound', 'euss_heating_upgrade_pm1', 'heating_upgrade_pm2_lower_bound', 'heating_upgrade_pm2_upper_bound', 'euss_heating_upgrade_pm2', 'row_id_heating_replacement', 'heating_replacement_pm1_lower_bound', 'heating_replacement_pm1_upper_bound', 'euss_heating_replacement_pm1', 'heating_replacement_pm2_lower_bound', 'heating_replacement_pm2_upper_bound', 'euss_heating_replacement_pm2', 'row_id_cooling_replacement', 'cooling_replacement_pm1_lower_bound', 'cooling_replacement_pm1_upper_bound', 'euss_cooling_replacement_pm1', 'cooling_replacement_pm2_lower_bound', 'cooling_replacement_pm2_upper_bound', 'euss_cooling_replacement_pm2', 'mp3_heating_and_cooling_replacement_installed_cost_mid', 'mp3_heating_upgrade_installed_cost_mid', 'mp3_heating_replacement_installed_cost_mid', 'mp3_cooling_replacement_installed_cost_mid', 'household_income', 'census_area_medianIncome', 'percent_AMI', 'income_level', 'lmi_or_mui', 'mp3_heating_rebate_amount_mid', 'preIRA_mp3_heating_climate_npv_lower', 'preIRA_mp3_heating_health_npv_easiur_acs', 'preIRA_mp3_heating_public_npv_lower_easiur_acs', 'preIRA_mp3_heating_climate_npv_central', 'preIRA_mp3_heating_public_npv_central_easiur_acs', 'preIRA_mp3_heating_climate_npv_upper', 'preIRA_mp3_heating_public_npv_upper_easiur_acs', 'preIRA_mp3_heating_health_npv_easiur_h6c', 'preIRA_mp3_heating_public_npv_lower_easiur_h6c', 'preIRA_mp3_heating_public_npv_central_easiur_h6c', 'preIRA_mp3_heating_public_npv_upper_easiur_h6c', 'preIRA_mp3_heating_total_capital_cost_mid', 'preIRA_mp3_heating_net_capital_cost_mid', 'preIRA_mp3_heating_private_npv_lessWTP_mid', 'preIRA_mp3_heating_private_npv_moreWTP_mid', 'preIRA_mp3_heating_benefit_lower_easiur_acs', 'preIRA_mp3_heating_total_npv_lower_easiur_acs_mid', 'preIRA_mp3_heating_adoption_lower_easiur_acs_mid', 'preIRA_mp3_heating_impact_lower_easiur_acs', 'preIRA_mp3_heating_benefit_central_easiur_acs', 'preIRA_mp3_heating_total_npv_central_easiur_acs_mid', 'preIRA_mp3_heating_adoption_central_easiur_acs_mid', 'preIRA_mp3_heating_impact_central_easiur_acs', 'preIRA_mp3_heating_benefit_upper_easiur_acs', 'preIRA_mp3_heating_total_npv_upper_easiur_acs_mid', 'preIRA_mp3_heating_adoption_upper_easiur_acs_mid', 'preIRA_mp3_heating_impact_upper_easiur_acs', 'preIRA_mp3_heating_benefit_lower_easiur_h6c', 'preIRA_mp3_heating_total_npv_lower_easiur_h6c_mid', 'preIRA_mp3_heating_adoption_lower_easiur_h6c_mid', 'preIRA_mp3_heating_impact_lower_easiur_h6c', 'preIRA_mp3_heating_benefit_central_easiur_h6c', 'preIRA_mp3_heating_total_npv_central_easiur_h6c_mid', 'preIRA_mp3_heating_adoption_central_easiur_h6c_mid', 'preIRA_mp3_heating_impact_central_easiur_h6c', 'preIRA_mp3_heating_health_sensitivity', 'preIRA_mp3_heating_benefit_upper_easiur_h6c', 'preIRA_mp3_heating_total_npv_upper_easiur_h6c_mid', 'preIRA_mp3_heating_adoption_upper_easiur_h6c_mid', 'preIRA_mp3_heating_impact_upper_easiur_h6c', 'preIRA_mp3_heating_total_npv_climateOnly_lower_mid', 'preIRA_mp3_heating_total_npv_climateOnly_central_mid', 'preIRA_mp3_heating_total_npv_climateOnly_upper_mid', 'preIRA_mp3_heating_total_npv_healthOnly_easiur_acs_mid', 'preIRA_mp3_heating_total_npv_healthOnly_easiur_h6c_mid']

## BASIC MEASURE PACKAGE (mp3): AEO2023 REFERENCE CASE
## Assumptions
- NREL End-Use Savings Shapes Database: Measure Package 3
- AEO2023 REFERENCE CASE: HDD and Fuel Price Projections
- Cambium 2023 MidCase Scenario

In [39]:
# Measure Package 3
scenario_name = 'Basic IRA-Reference'
cost_scenario = 'Fuel Costs: AEO2023 Reference Case'
grid_scenario = 'Electricity Grid: Cambium 2023 MidCase Scenario'

print(f"""
====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario {scenario_name}:
Basic Retrofit: Measure Package {menu_mp}
{cost_scenario}
{grid_scenario}
====================================================================================================================================================================
""")

====================================================================================================================================================================
MODEL SCENARIO
====================================================================================================================================================================
Scenario Basic IRA-Reference:
Basic Retrofit: Measure Package 3
Fuel Costs: AEO2023 Reference Case
Electricity Grid: Cambium 2023 MidCase Scenario
====================================================================================================================================================================

In [40]:
print(f"""  
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PUBLIC IMPACT 
====================================================================================================================================================================
STEP 1. Calculate the baseline marginal damages for climate and health-related emissions         [COMPLETED]
STEP 2. Calculate the post-retrofit marginal damages for climate and health-related emissions    [COMPLETED]
STEP 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)

---------------------------------------------------------------------------------------------

RESULTS OUTPUT:
""")

# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_public_npv(
    df=df_euss_am_mp3_home_ap2,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    base_year=2024,
    discounting_method='public'
)

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_public_npv(
    df=df_euss_am_mp3_home_easiur,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    base_year=2024,
    discounting_method='public'
)

# ========================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_public_npv(
    df=df_euss_am_mp3_home_inmap,
    df_baseline_climate=df_baseline_damages_climate,
    df_baseline_health=df_baseline_damages_health,
    df_mp_climate=df_mp3_IRA_damages_climate,
    df_mp_health=df_mp3_IRA_damages_health,
    menu_mp="3",
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    base_year=2024,
    discounting_method='public'
)

print(f"""  
=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PUBLIC IMPACT
====================================================================================================================================================================
STEP 1. Calculate the baseline marginal damages for climate and health-related emissions         [COMPLETED]
STEP 2. Calculate the post-retrofit marginal damages for climate and health-related emissions    [COMPLETED]
STEP 3: Discount climate and health impacts and calculate lifetime public impacts (public NPV)

---------------------------------------------------------------------------------------------

RESULTS OUTPUT:

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

Baseline Climate DataFrame: ✓ Valid
Baseline Health DataFrame: ✓ Valid
Retrofit Climate DataFrame: ✓ Valid
Retrofit Health DataFrame: ✓ Valid
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Verifying masking for all calculated columns:

=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PUBLIC NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True
...                               ...          ...                 ...
549995                         462.76         True                True
549996                            NaN        False                True
549997                       18788.20         True                True
549998                            NaN         True                True
549999                        2593.97         True                True

         valid_tech_heating  include_heating  \
bldg_id
1                      True             True
2                      True             True
5                      True             True
6                     False            False
8                      True             True
...                     ...              ...
549995                 True             True
549996                False            False
549997                 True             True
549998                 True             True
549999                 True             True

         baseline_heating_lifetime_mt_co2e_lrmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                          88.60
6                                            NaN
8                                          87.75
...                                          ...
549995                                      2.19
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_lrmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                  6463.66
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              158.40
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_lrmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 23022.55
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                              565.04
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_lrmer_upper  \
bldg_id
1                                                 25057.25
2                                                 63173.17
5                                                 36607.44
6                                                      NaN
8                                                 36557.99
...                                                    ...
549995                                              899.25
549996                                                 NaN
549997                                            24244.24
549998                                                0.00
549999                                             3964.24

         baseline_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                         205.82
6                                            NaN
8                                          87.75
...                                          ...
549995                                      4.72
549996                                       NaN
549997                                     58.22
549998                                      0.00

In [41]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")


# ========================== AP2  ========================== 
df_euss_am_mp3_home_ap2 = calculate_private_npv(
    df=df_euss_am_mp3_home_ap2,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
df_euss_am_mp3_home_easiur = calculate_private_npv(
    df=df_euss_am_mp3_home_easiur,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
df_euss_am_mp3_home_inmap = calculate_private_npv(
    df=df_euss_am_mp3_home_inmap,
    df_fuel_costs=df_mp3_IRA_fuel_costs,
    df_baseline_costs=df_baseline_fuel_costs,
    menu_mp=menu_mp,
    input_mp=input_mp,
    policy_scenario='AEO2023 Reference Case',
    discounting_method='private_fixed',
    base_year=2024,
    verbose=False,
    percentile='mid'  # Add this parameter
    )



print(f"""  
=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): PRIVATE IMPACT
====================================================================================================================================================================
STEP 1: Calculate annual operating (fuel) costs                                                          [COMPLETED]
STEP 2: Calculate equipment capital costs (HEATING: include ductwork and weatherization (MP9 and MP10))  [COMPLETED]
STEP 3: Calculate replacement cost (replacing existing piece of eqipment with similar technology)        [COMPLETED]
STEP 4: Calculate net equipment capital costs and private NPV (less WTP and more WTP)
----------------------------------------------------------------------------------------------------------------------

RESULTS OUTPUT (AEO2023 REFERENCE CASE):

-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp3_


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp3_


Verifying masking for all calculated columns:
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Calculating costs for heating...
          input_mp: upgrade03, menu_mp: 3, policy_scenario: AEO2023 Reference Case
Calculating Private NPV for heating with lifetime: 15 years
          policy_scenario: AEO2023 Reference Case --> scenario_prefix: iraRef_mp3_


Verifying masking for all calculated columns:

=====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER CALCULATING PRIVATE NPV (AEO2023 REFERENCE CASE): df_euss_am_mp3_home

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False
8                            27903.00         True                True
...                               ...          ...                 ...
549995                         462.76         True                True
549996                            NaN        False                True
549997                       18788.20         True                True
549998                            NaN         True                True
549999                        2593.97         True                True

         valid_tech_heating  include_heating  \
bldg_id
1                      True             True
2                      True             True
5                      True             True
6                     False            False
8                      True             True
...                     ...              ...
549995                 True             True
549996                False            False
549997                 True             True
549998                 True             True
549999                 True             True

         baseline_heating_lifetime_mt_co2e_lrmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                          88.60
6                                            NaN
8                                          87.75
...                                          ...
549995                                      2.19
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_lrmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                  6463.66
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              158.40
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_lrmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 23022.55
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                              565.04
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_lrmer_upper  \
bldg_id
1                                                 25057.25
2                                                 63173.17
5                                                 36607.44
6                                                      NaN
8                                                 36557.99
...                                                    ...
549995                                              899.25
549996                                                 NaN
549997                                            24244.24
549998                                                0.00
549999                                             3964.24

         baseline_heating_lifetime_mt_co2e_srmer  \
bldg_id
1                                          60.21
2                                         151.67
5                                         205.82
6                                            NaN
8                                          87.75
...                                          ...
549995                                      4.72
549996                                       NaN
549997                                     58.22
549998                                      0.00
549999                                      9.52

         baseline_heating_lifetime_damages_climate_srmer_lower  \
bldg_id
1                                                  4442.41
2                                                 11205.72
5                                                 15187.73
6                                                      NaN
8                                                  6485.60
...                                                    ...
549995                                              347.64
549996                                                 NaN
549997                                             4299.71
549998                                                0.00
549999                                              703.08

         baseline_heating_lifetime_damages_climate_srmer_central  \
bldg_id
1                                                 15780.10
2                                                 39791.05
5                                                 53946.81
6                                                      NaN
8                                                 23027.99
...                                                    ...
549995                                             1235.09
549996                                                 NaN
549997                                            15269.86
549998                                                0.00
549999                                             2496.84

         baseline_heating_lifetime_damages_climate_srmer_upper   county_key  \
bldg_id
1                                                 25057.25      (51033, VA)
2                                                 63173.17      (56025, WY)
5                                                 85660.16      (29169, MO)
6                                                      NaN      (12099, FL)
8                                                 36557.99      (31147, NE)

In [42]:
print(f"""
====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity_robust.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)
      
RESULTS OUTPUT (AEO2023 REFERENCE CASE):
""")

# ========================== AP2  ========================== 
print("Processing AP2 model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = adoption_decision(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_ap2 = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_ap2,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='ap2',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== EASIUR ========================== 
print("Processing EASIUR model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = adoption_decision(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_easiur = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_easiur,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='easiur',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# ====================== InMAP ========================== 
print("Processing InMAP model...")

# Combined climate + health analysis (existing)
df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = adoption_decision(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    percentile='mid'  # Add this parameter
    )

# Climate-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_climate_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

# Health-only analysis (new)
df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='acs',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

df_euss_am_mp3_home_inmap = calculate_health_only_adoption_robust(
    df=df_euss_am_mp3_home_inmap,
    menu_mp=menu_mp,
    policy_scenario='AEO2023 Reference Case',
    rcm_model='inmap',
    cr_function='h6c',
    verbose=False,
    percentile='mid'  # Add this parameter
    )

print(f"""
====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (AEO2023 REFERENCE CASE): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------   
AP2: 
-----------------------------------------------
      
{df_euss_am_mp3_home_ap2}

-----------------------------------------------
EASIUR:
-----------------------------------------------

{df_euss_am_mp3_home_easiur}

-----------------------------------------------
InMAP:
-----------------------------------------------

{df_euss_am_mp3_home_inmap}
      
""")

====================================================================================================================================================================
SCENARIO ANALYSIS (AEO2023 REFERENCE CASE): ADOPTION POTENTIAL
====================================================================================================================================================================
determine_adoption_potential_sensitivity_robust.py file contains the definitions for:
- adoption_decision function (combined climate + health analysis)
- calculate_climate_only_adoption_robust function (climate-only analysis)
- calculate_health_only_adoption_robust function (health-only analysis)

RESULTS OUTPUT (AEO2023 REFERENCE CASE):

Processing AP2 model...
Fixed 3 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | ap2-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | ap2-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | ap2-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | ap2-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added
Processing EASIUR model...
Fixed 3 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | easiur-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | easiur-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | easiur-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | easiur-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added
Processing InMAP model...
Fixed 3 duplicate columns
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | inmap-acs

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Adoption Analysis: AEO2023 Reference Case | inmap-h6c

Verifying masking for all calculated columns:

Summary:
  heating: 303,516/396,252 valid homes, 3 scenarios
  Total columns: 60
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Climate-only Analysis: AEO2023 Reference Case

Verifying masking for all calculated columns:
  Climate-only: 12 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | inmap-acs

Verifying masking for all calculated columns:
  Health-only: 2 columns added
-- Scenario: Inflation Reduction Act (IRA) Reference --
              scenario_prefix: 'iraRef_mp3_', cambium_scenario: 'MidCase', lookup_emissions_fossil_fuel: 'lookup_emissions_fossil_fuel',
              lookup_emissions_electricity_climate: 'lookup_emissions_electricity_climate_IRA', lookup_emissions_electricity_health: 'lookup_emissions_electricity_health', lookup_fuel_prices: 'lookup_fuel_prices_iraRef'


Health-only Analysis: AEO2023 Reference Case | inmap-h6c

Verifying masking for all calculated columns:
  Health-only: 2 columns added

====================================================================================================================================================================
DATAFRAME FOR mp3 AFTER DETERMINING ADOPTION FEASIBILITY (AEO2023 REFERENCE CASE): df_euss_am_mp3_home
Includes: Combined (Climate + Health), Climate-Only, and Health-Only Adoption Analysis

-----------------------------------------------
AP2:
-----------------------------------------------

         square_footage census_region     census_division  \
bldg_id
1                1690.0         South      South Atlantic
2                1690.0          West            Mountain
5                2176.0       Midwest  West North Central
6                1690.0         South      South Atlantic
8                1220.0       Midwest  West North Central
...                 ...           ...                 ...
549995           1220.0         South  West South Central
549996            853.0     Northeast     Middle Atlantic
549997           1623.0     Northeast     Middle Atlantic
549998           1690.0          West             Pacific
549999           2176.0         South  East South Central

        census_division_recs building_america_climate_zone  \
bldg_id
1             South Atlantic                   Mixed-Humid
2             Mountain North                          Cold
5         West North Central                   Mixed-Humid
6             South Atlantic                     Hot-Humid
8         West North Central                          Cold
...                      ...                           ...
549995    West South Central                     Hot-Humid
549996       Middle Atlantic                   Mixed-Humid
549997       Middle Atlantic                          Cold
549998               Pacific                       Hot-Dry
549999    East South Central                     Hot-Humid

         reeds_balancing_area gea_region state                     city  \
bldg_id
1                          99      SRVCc    VA  In another census Place
2                          24      RMPAc    WY    Not in a census Place
5                          73      SRMWc    MO    Not in a census Place
6                         102      FRCCc    FL  In another census Place
8                          41      MROWc    NE  In another census Place
...                       ...        ...   ...                      ...
549995                     65      ERCTc    TX  In another census Place
549996                    126      RFCEc    NJ    Not in a census Place
549997                    126      RFCEc    NJ  In another census Place
549998                     10      CAMXc    CA                Inglewood
549999                     89      SRSOc    AL  In another census Place

        urbanicity    county county_fips       puma      county_and_puma  \
bldg_id
1            Rural  G5100330       51033  G51051120  G5100330, G51051120
2            Rural  G5600250       56025  G56000400  G5600250, G56000400
5            Rural  G2901690       29169  G29001400  G2901690, G29001400
6         Suburban  G1200990       12099  G12009902  G1200990, G12009902
8            Rural  G3101470       31147  G31000600  G3101470, G31000600
...            ...       ...         ...        ...                  ...
549995       Rural  G4804890       48489  G48006900  G4804890, G48006900
549996    Suburban  G3400150       34015  G34002201  G3400150, G34002201
549997    Suburban  G3400030       34003  G34000303  G3400030, G34000303
549998    Suburban  G0600370       06037  G06003749  G0600370, G06003749
549999       Rural  G0100910       01091  G01001700  G0100910, G01001700

           weather_file_city  Longitude  Latitude  \
bldg_id
1                    Shannon     -77.44     38.27
2        Casper Natrona Coun    -106.47     42.90
5             Lee C Fine Mem     -92.55     38.10
6         West Palm Beach In     -80.10     26.69
8         Falls City Brenner     -95.59     40.08
...                      ...        ...       ...
549995           Valley Intl     -97.65     26.23
549996     Philadelphia Intl     -75.23     39.87
549997             Teterboro     -74.06     40.85
549998   La Usc Downtown Cam    -118.30     34.03
549999           Centreville     -87.25     32.90

                         building_type    income federal_poverty_level  \
bldg_id
1               Single-Family Detached   64999.5              300-400%
2               Single-Family Detached  109999.5                 400%+
5               Single-Family Detached  109999.5                 400%+
6               Single-Family Detached   37499.5              200-300%
8               Single-Family Detached   27499.5              200-300%
...                                ...       ...                   ...
549995          Single-Family Detached   37499.5              100-150%
549996   Multi-Family with 2 - 4 Units    9999.0                0-100%
549997   Multi-Family with 2 - 4 Units  149999.5                 400%+
549998          Single-Family Detached   22499.5              100-150%
549999          Single-Family Detached   54999.5              300-400%

        occupancy  tenure vacancy_status vintage base_heating_fuel  \
bldg_id
1               2   Owner       Occupied   2000s           Propane
2               2   Owner       Occupied   1950s       Natural Gas
5               3   Owner       Occupied   2000s       Electricity
6               2   Owner       Occupied   1960s               NaN
8               1   Owner       Occupied   1940s       Natural Gas
...           ...     ...            ...     ...               ...
549995          5  Renter       Occupied   2000s       Electricity
549996          1  Renter       Occupied   <1940       Electricity
549997          5  Renter       Occupied   1960s       Natural Gas
549998          3  Renter       Occupied   1960s       Electricity
549999          2   Owner       Occupied   1990s           Propane

                         heating_type              base_heating_efficiency  \
bldg_id
1                Propane Fuel Furnace               Fuel Furnace, 76% AFUE
2            Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
5        Electricity Electric Furnace          Electric Furnace, 100% AFUE
6                                 NaN                                  NaN
8            Natural Gas Fuel Furnace               Fuel Furnace, 76% AFUE
...                               ...                                  ...
549995   Electricity Electric Furnace          Electric Furnace, 100% AFUE
549996     Electricity Shared Heating                       Shared Heating
549997       Natural Gas Fuel Furnace               Fuel Furnace, 80% AFUE
549998          Electricity Baseboard  Electric Baseboard, 100% Efficiency
549999           Propane Fuel Furnace               Fuel Furnace, 76% AFUE

         base_electricity_heating_consumption  \
bldg_id
1                                        0.00
2                                        0.00
5                                    15824.37
6                                         NaN
8                                        0.00
...                                       ...
549995                                 462.76
549996                                    NaN
549997                                   0.00
549998                                   0.00
549999                                   0.00

         base_fuelOil_heating_consumption  \
bldg_id
1                                     0.0
2                                     0.0
5                                     0.0
6                                     NaN
8                                     0.0
...                                   ...
549995                                0.0
549996                                NaN
549997                                0.0
549998                                0.0
549999                                0.0

         base_naturalGas_heating_consumption  \
bldg_id
1                                       0.00
2                                   46812.83
5                                       0.00
6                                        NaN
8                                   27903.00
...                                      ...
549995                                  0.00
549996                                   NaN
549997                              18788.20
549998                                  0.00
549999                                  0.00

         base_propane_heating_consumption base_cooling_fuel cooling_type  \
bldg_id
1                                16516.31       Electricity   Central AC
2                                    0.00       Electricity          NaN
5                                    0.00       Electricity   Central AC
6                                     NaN       Electricity          NaN
8                                    0.00       Electricity   Central AC
...                                   ...               ...          ...
549995                               0.00       Electricity   Central AC
549996                                NaN       Electricity          NaN
549997                               0.00       Electricity      Room AC
549998                               0.00       Electricity   Central AC
549999                            2593.97       Electricity   Central AC

        base_cooling_efficiency  base_electricity_cooling_consumption  \
bldg_id
1                   AC, SEER 15                               2085.79
2                           NaN                                  0.00
5                   AC, SEER 13                               4124.39
6                           NaN                                  0.00
8                   AC, SEER 13                               3135.57
...                         ...                                   ...
549995              AC, SEER 13                               6632.20
549996                      NaN                                  0.00
549997        Room AC, EER 12.0                               1645.89
549998              AC, SEER 15                               3666.61
549999              AC, SEER 15                               2897.01

         baseline_heating_consumption  include_all  valid_fuel_heating  \
bldg_id
1                            16516.31         True                True
2                            46812.83         True                True
5                            15824.37         True                True
6                                 NaN        False               False

In [43]:
# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_ap2 dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_ap2.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_easiur dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_easiur.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# print(f"""
# =======================================================================================================================================================
# Columns in the df_euss_am_mp3_home_inmap dataframe:
# =======================================================================================================================================================
# {df_euss_am_mp3_home_inmap.columns.to_list()}""")  # Ensure the columns are loaded correctly for the next steps

# Model Runtime

In [44]:
# Flag to prevent excessive output in other scenario files
individual_scenario_run = False

# Get the current datetime again
end_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

# Calculate the elapsed time
elapsed_time = datetime.strptime(end_time, "%Y-%m-%d_%H-%M-%S") - datetime.strptime(start_time, "%Y-%m-%d_%H-%M-%S")

# Format the elapsed time
elapsed_seconds = elapsed_time.total_seconds()
elapsed_minutes = int(elapsed_seconds // 60)
elapsed_seconds = int(elapsed_seconds % 60)

# Print the elapsed time
print(f"The code took {elapsed_minutes} minutes and {elapsed_seconds} seconds to execute.")

The code took 11 minutes and 5 seconds to execute.